---
permalink: a1k/bootmedia-replace-requirements-bmr.html
sidebar: sidebar
keywords: a1k, replace the boot media
summary: Before replacing the boot media in your AFF A1K system, ensure you meet the necessary requirements for a successful replacement.
---
= Requirements for automated boot media recovery - AFF A1K
:icons: font
:imagesdir: ../media/

[.lead]
Before replacing the boot media in your AFF A1K system, ensure you meet the necessary requirements for a successful replacement. This includes verifying that you have the correct replacement boot media, confirming that there are no defective cluster ports on the controller, and determining whether Onboard Key Manager (OKM) or External Key Manager (EKM) is enabled.

Your storage system must be running ONTAP 9.17.1RC or later to use the automated boot recovery procedure. If your storage system is running an earlier version of ONTAP, use the link:bootmedia-replace-workflow.html[manual boot recovery procedure].

include::../_include/bootmedia_replace_requirements_bmr.adoc[]

.What's next

After you've reviewed the boot media requirements, you link:bootmedia-shutdown-bmr.html[shut down the controller].
