---
permalink: a1k/bootmedia-recovery-image-boot-bmr.html
sidebar: sidebar
keywords: a1k, boot the recovery image
summary: You can restore image on the boot media from the partner controller through the automated boot recovery process.  
---
= Restore the boot image automatically from the partner node  - AFF A1K
:icons: font
:imagesdir: ../media/

[.lead]
After installing the new boot media device in your AFF A1K system, you can start the automated boot media recovery process to restore the configuration from the partner node.

During the recovery process, the system checks whether encryption is enabled and determines the type of key encryption in use. If key encryption is enabled, the system guides you through the appropriate steps to restore it. 

Your storage system must be running ONTAP 9.17.1RC or later to use the automated boot recovery procedure. If your storage system is running an earlier version of ONTAP, use the link:bootmedia-replace-workflow.html[manual boot recovery procedure].

include::../_include/bmr_single_node_boot_recovery.adoc[]

.What's next

After you've restored the ONTAP image and the node is up and serving data, you link:bootmedia-complete-rma-bmr.html[return the failed part to NetApp].

