---
permalink: a1k/install-hardware.html
sidebar: sidebar
keywords: aff a1k, install hardware, telco rack
summary: Install your storage system in cabinet or telco rack.
---
= Install the hardware - AFF A1K
:icons: font
:imagesdir: ../media/

[.lead]
The following instructions describe how to install the hardware in an empty cabinet or telco rack. Skip this step if your cabinet is pre-populated.

.Before you begin
* You should review the https://library.netapp.com/ecm/ecm_download_file/ECMP12475945[Safety Notices] document, and understand the precautions for moving and installing hardware.

* You should have the instructions packaged with the rail kit.

* You should be aware of the safety concerns associated with the weight of the platform and shelf.

.Steps

. Install the rail kits for the platform and shelves, as needed, using the instructions included with the kits.

. Install and secure your platform in the cabinet or telco rack:

.. Position the platform onto the rails in the middle of the cabinet or telco rack, and then support the platform from the bottom and slide it into place.

.. Secure the platform to the cabinet or telco rack using the included mounting screws.

+
. Install the shelf or shelves:
+

.. Position the back of the shelf onto the rails, and then support the shelf from the bottom and slide it into the cabinet or telco rack.
+
If you are installing multiple shelves, place the first shelf directly above the controllers. Place the second shelf directly under the controllers. Repeat this pattern for any additional drive shelves.

.. Secure the shelf to the cabinet or telco rack using the included mounting screws.
+
. Attach the cable management devices to the rear of the platform.
+
image::../media/drw_affa1k_install_cable_mgmt_ieops-1697.svg[]

. Attach the bezel to the front of the platform.

