---
permalink: a1k/install-hardware.html
sidebar: sidebar
keywords: aff a1k, install hardware, rack
summary: Install your storage system in cabinet or rack.
---
= Rack the hardware - AFF A1K
:icons: font
:imagesdir: ../media/

[.lead]
The following instructions describe how to install the hardware in an empty cabinet or rack. Skip this step if your cabinet or rack is pre-populated.

.Before you begin
* You should review the https://library.netapp.com/ecm/ecm_download_file/ECMP12475945[Safety Notices] document, and understand the precautions for moving and installing hardware.

* You should have the instructions packaged with the rail kit.

* You should be aware of the safety concerns associated with the weight of the platform and shelf.

NOTE: A fully loaded shelf can weigh up to 66.78 lbs (30.29 kg) and requires two people to lift or use a hydraulic lift. Avoid removing shelf components (from the front or rear of the shelf) to reduce the shelf weight, because shelf weight will become unbalanced.

image::../media/drw_affa1k_weight_caution_ieops-1698.svg[]

NOTE: Airflow through the storage system enters from the front where the bezel or end caps are installed and exhausts out the rear where the ports are located.

.Steps

. Install the rail kits for the platform and shelves, as needed, using the instructions included with the kits.

. Install and secure your platform in the cabinet or rack.

.. Position the enclosure onto the rails, and then support the enclosure from the bottom and slide it into place.

.. Secure the enclosure to the cabinet or rack using the included mounting screws.

+
. Install the shelf or shelves.
+

.. Position the back of the shelf onto the rails, and then support the shelf from the bottom and slide it into the cabinet or rack.
+
If you are installing multiple shelves, place the first shelf directly above the controllers. Place the second shelf directly under the controllers. Repeat this pattern for any additional drive shelves.

.. Secure the shelf to the cabinet or rack using the included mounting screws.
+
. Attach the cable management devices to the rear of the platform.
+
image::../media/drw_affa1k_install_cable_mgmt_ieops-1697.svg[]

. Attach the bezel to the front of the platform.

