---
sidebar: sidebar
permalink: a1k/install-requirements.html
keywords: a1k, install, setup, cautions
summary: Review the equipment needed and the lifting precautions for your platform and shelves.
---
= Requirements and considerations
:icons: font
:imagesdir: ../media/

[.lead]
Before installing your storage system, review the equipment needed and the lifting precautions for your platform and shelves. 

== Equipment needed for install
Confirm you have the following equipment and tools needed to install and setup your system.

** Phillips #2 screwdriver 
** Flashlight
** ESD strap 
** A paperclip or narrow tipped ball point pen for setting NS224 shelf IDs
** Laptop or console with a USB/serial connection
** Access to a Web browser to configure your storage system

== Lifting precautions 
You should be aware of the safety concerns associated with the weight of the platform and shelves.

=== AFF A1K platform weight
A fully loaded A1K platform can weigh up to 62.83 lbs (28.5 kg) and requires two people to lift or use a hydraulic lift.

image::../media/drw_a1k_weight_caution_ieops-1698.svg[AFF A1K lifting caution icon]

=== Shelf weight
A fully loaded shelf can weigh up to 66.78 lbs (30.29 kg) and requires two people to lift or use a hydraulic lift. Avoid removing shelf components (from the front or rear of the shelf) to reduce the shelf weight, because shelf weight will become unbalanced.

image::../media/drw_ns224_lifting_weight_ieops-1716.svg[NS224 lifting caution]


