---
permalink: a1k/install-cable.html
sidebar: sidebar
keywords: aff a1k, prepare installation
summary: Management network ports on the controllers are connected to switches. The HA interconnect and cluster interconnect ports are cabled on both controllers. The controller modules are connected to external storage, if ordered.
---
= Cable the hardware - AFF A1K
:icons: font
:imagesdir: ../media/

[.lead]
Cable your controllers and shelves according to your specific storage system configuration.

.Before you begin
Check the illustration arrow for the proper cable connector pull-tab orientation.

image::../media/drw_cable_pull_tab_direction_ieops-1699.svg[]

* As you insert the connector, you should feel it click into place; if you do not feel it click, remove it, turn the cable head over and try again.
* If connecting to an optical switch, insert the SFP into the controller port before cabling to the port.


== Step 1: Cable controllers to your network
Cable the controllers to your network as either a two-node switchless cluster or a switched cluster.

.Before you begin

Contact your network administrator for information about connecting the storage system to the switches.

.About this task
These procedures show common configurations. Keep in mind that the specific cabling depend on the components ordered for your storage system. For comprehensive configuration and slot priority details, see link:https://hwu.netapp.com[NetApp Hardware Universe^].

[role="tabbed-block"]
====

.Option 1: Cable switchless cluster
--
Cable your switchless cluster connections.

.Steps

. Cable the Cluster/HA interconnect ports e1a to e1a and e7a to e7a with the Cluster/HA interconnect cable.

+
NOTE: The cluster interconnect traffic and the HA traffic share the same physical ports.

+

image::../media/oie_cable_25Gb_Ethernet_SFP28_IEOPS-1069.svg[width=100pxx]
*Cluster/HA interconnect cables*
+
image::../media/drw_a1k_tnsc_cluster_cabling_ieops-1648.svg[width=500px]
+
. Cable the Ethernet module ports to your host network. 
+
The following are some typical host network cabling examples. See  link:https://hwu.netapp.com[NetApp Hardware Universe^] for your specific system configuration.

.. Cable ports e1b and e7b to your Ethernet data network switch. 
+
If present, cable ports e9a and e9b to your Ethernet data network switch as shown.
+
*100 GbE cable*
+
image::../media/oie_cable_sfp_gbe_copper.svg[width=100px]
+
image::../media/drw_a1k_network_cabling1_ieops-1649.svg[width=500px]

+
.. Cable your 10/25 GbE host network switches.
+
*4-ports, 10/25 GbE Host*
+
image::../media/oie_cable_sfp_gbe_copper.svg[width=100px]
+
image::../media/drw_a1k_network_cabling2_ieops-1650.svg[width=500px]
+


. Cable the controller management (wrench) ports to the management network switches with 1000BASE-T RJ-45 cables.
+
image::../media/oie_cable_rj45.svg[width=100px]
*1000BASE-T RJ-45 cables*
+
image::../media/drw_a1k_management_connection_ieops-1651.svg[width=500px]

IMPORTANT: DO NOT plug in the power cords yet. 


--
.Option 2: Cable switched cluster
--
Cable your switched cluster connections.

.Steps

. Make the following cabling connections:

+
NOTE: The cluster interconnect traffic and the HA traffic share the same physical ports.


+
.. Cable port e1a on Controller A and port e1a on Controller B to cluster network switch A. 
.. Cable port e7a on Controller A and port e7a on Controller B to cluster network switch B.
+
*100 GbE cable*
+
image::../media/oie_cable100_gbe_qsfp28.svg[width=100px]
+
image::../media/drw_a1k_switched_cluster_cabling_ieops-1652.svg[width=500px]

. Cable the Ethernet module ports to your host network. 
+
The following are some typical host network cabling examples. See  link:https://hwu.netapp.com[NetApp Hardware Universe^] for your specific system configuration.

.. Cable ports e1b and e7b to your Ethernet data network switch. 
+
If present, cable ports e9a and e9b to your Ethernet data network switch as shown.
+
*100 GbE cable*
+
image::../media/oie_cable_sfp_gbe_copper.svg[width=100px]
+
image::../media/drw_a1k_network_cabling1_ieops-1649.svg[width=500px]

+
.. Cable your 10/25 GbE host network switches.
+
*4-ports, 10/25 GbE Host*
+
image::../media/oie_cable_sfp_gbe_copper.svg[width=100px]
+
image::../media/drw_a1k_network_cabling2_ieops-1650.svg[width=500px]
+


. Cable the controller management (wrench) ports to the management network switches with 1000BASE-T RJ-45 cables.
+
image::../media/oie_cable_rj45.svg[width=100px]
*1000BASE-T RJ-45 cables*
+
image::../media/drw_a1k_management_connection_ieops-1651.svg[width=500px]

IMPORTANT: DO NOT plug in the power cords yet. 

--

====

== Step 2: Cable controllers to shelves
Cable your controllers to the shelf or shelves. 

These procedures show how to cable your controllers to one shelf and to two shelves. You can connect your controllers to a maximum of four shelves.


// start tabbed area

[role="tabbed-block"]
====

.Option 1: Cable to one NS224 shelf
--
Cable each controller to the NSM modules on the NS224 shelf. The graphics show cabling from each of the controllers: Controller A cabling in blue and Controller B cabling in yellow.

.Steps
. Connect controller A port e11a to NSM A port e0a.
. Connect controller A port e10b to port NSM B port e0b.
+
image:../media/drw_a1k_1shelf_cabling_a_ieops-1703.svg[]

. Connect controller B port e11a to NSM B port e0a.
. Connect controller B port e10b to NSM A port e0b.
+
image:../media/drw_a1k_1shelf_cabling_b_ieops-1704.svg[]

--

.Option 2: Cable to two NS224 shelves
--
Cable each controller to the NSM modules on both NS224 shelves. The graphics show cabling from each of the controllers: Controller A cabling in blue and Controller B cabling in yellow.

.Steps

. On shelf 1, cable the following connections:
.. Connect controller A port e11a to NSM A port e0a.

.. Connect controller A port e11b to NSM B port e0b.

.. Connect controller B port e11a to NSM B port e0.

.. Connect controller B port e11b to NSM A port e0b.
+
image:../media/drw_a1k_2shelf_cabling_a_ieops-1705.svg[200]
+

. On shelf 2, cable the following connections:
.. Connect controller A port e10a to NSM A port e0a.

.. Connect controller A port e11b to NSM B port e0b.

.. Connect controller B port e11b to NSM A port e0b.

.. Connect controller B port e10a to NSM B port e0a.
+
image:../media/drw_a1k_2shelf_cabling_b_ieops-1706.svg[200]
+

--

====

// end tabbed area



