---
permalink: a1k/install-prepare.html
sidebar: sidebar
keywords: aff a1k, prepare installation
summary: Prepare to install your AFF A1K system.
---
= Prepare for install - AFF A1K
:icons: font
:imagesdir: ../media/

[.lead]
Prepare to install your AFF A1K system.

.Before you begin
* Use the https://docs.netapp.com/us-en/ontap/software_setup/index.html[cluster setup worksheet] to record the values that you need during the complete system setup process.  If a default value is provided, you can use that value or else enter your own.

== Step 1: Prepare the site
Make sure that the site and the cabinet or rack you plan to use meet the specifications for your storage system.

.Steps

. Confirm that the site meets the requirements for temperature, humidity, altitude range, airflow, heat dissipation, wiring, power, and grounding. 
+
See https://hwu.netapp.com[NetApp Hardware Universe^] for site requirements.

. Confirm that your location provides the correct voltage of AC or DC power for your storage system.

+
Check https://hwu.netapp.com[NetApp Hardware Universe^] for power requirements specific to your system configuration.

. Obtain a 19-inch (48.3-cm) cabinet or rack to fit your storage system and drive shelf. See https://hwu.netapp.com[NetApp Hardware Universe^] for size requirements.
+

. Install any required network switches near the storage system.
+

See the https://docs.netapp.com/us-en/ontap-systems-switches/index.html[Switch documentation] for installation instructions and link:https://hwu.netapp.com[NetApp Hardware Universe^] (HWU) for compatibility information.


== Step 2: Unpack the boxes
Unpack all boxes and compare the contents to the items on the packing slip.

.  Carefully open all the boxes. Lay out the contents in an organized manner.

. Compare the contents you’ve unpacked with the list on the packing slip. 
+
The following items are some of the contents you might see in the boxes that you received. 
+

[%rotate, grid="none", frame="none", cols="12,9,4"]
|===
|*Hardware*
|*Cables* |
a|* Storage system
* Drive shelf 
* Rail kit with instructions 
* Cable management device 
* Bezel
a|* Power cords
* Ethernet cables and transceivers
* FC optical cable
* Management Ethernet cables (RJ-45 cables)
* USB-C serial port cable |
|===

+
Ensure that everything in the boxes matches the list on the packing slip. If there are any discrepancies, note them down for further action.

== Step 3: Obtain additional equipment and tools
Confirm you have all of the additional equipment and tools that you need to complete the hardware installation.

* Phillips #2 screwdriver 
* Flashlight
* ESD strap 
* Rack space: 
** 4U for the storage system 
** 2U for each NS224 shelf
* Laptop or console with a USB/serial connection
* Access to a Web browser to configure your storage system


