---
permalink: a1k/io-module-overview.html
sidebar: sidebar
keywords: aff a1k, replace io module
summary: The AFF A1K system offers flexibility in expanding or replacing I/O modules to enhance network connectivity and performance. Adding or replacing an I/O module is essential when upgrading network capabilities or addressing a failed module.
---
= Overview of add and replace I/O module - AFF A1K
:icons: font
:imagesdir: ../media/

[.lead]
The AFF A1K system offers flexibility in expanding or replacing I/O modules to enhance network connectivity and performance. Adding or replacing an I/O module is essential when upgrading network capabilities or addressing a failed module.

You can replace a failed I/O module in your AFF A1K storage system with the same type of I/O module, or with a different kind of I/O module. You can also add an I/O module into a system with empty slots.

* link:io-module-add.html[Add an I/O module]
+
Adding additional modules can improve redundancy, helping to ensure that the system remains operational even if one module fails.

* link:io-module-replace.html[Replace an I/O module]
+
Replacing a failing I/O module can restore the system to its optimal operating state. 