---
permalink: a1k/maintain-overview.html
sidebar: sidebar
keywords: aff a1k maintenance, maintenance, repairing a1k, repairing aff a1k, replace aff a1k components, replace aff a1k components
summary: Maintain the hardware of your AFF A1K storage system to ensure long-term reliability and optimal performance. Perform regular maintenance tasks such as replacing faulty components, as this helps prevent downtime and data loss.
---
= Overview of the maintenance procedures - AFF A1K
:icons: font
:imagesdir: ../media/

[.lead]
Maintain the hardware of your AFF A1K storage system to ensure long-term reliability and optimal performance. Perform regular maintenance tasks such as replacing faulty components, as this helps prevent downtime and data loss. 

The maintenance procedures assume that the AFF A1K system has already been deployed as a storage node in the ONTAP environment.

== System components
For the AFF A1K storage system, you can perform maintenance procedures on the following components.

[%rotate, grid="none", frame="none", cols="25,65"]

|===

a| link:bootmedia-replace-workflow-bmr.html[Boot media - automated recovery]

a| The boot media stores a primary and secondary set of ONTAP image files that the storage system uses to boot. During automated recovery, the system retrieves the boot image from the partner node and automatically runs the appropriate boot menu option to install the image on your replacement boot media. The automated boot media recovery process is supported only in ONTAP 9.17.1 and later. If your storage system is running an earlier version of ONTAP, use the link:bootmedia-replace-workflow.html[manual boot recovery procedure].

a| link:bootmedia-replace-workflow.html[Boot media - manual recovery]

a| The boot media stores a primary and secondary set of ONTAP image files that the system uses to boot the image from a USB drive and restore the configuration from the partner node.

a| link:chassis-replace-workflow.html[Chassis]

a| The chassis houses the fans, controller, power supplies, and PSUs, NVRAM12, system management module, I/O cards and blanking modules.

a| link:controller-replace-workflow.html[Controller]

a| A controller consists of a board, firmware, and software. It controls the drives and runs the ONTAP operating system software.

a| link:dimm-replace.html[DIMM]

a| A dual in-line memory module (DIMM) is a type of computer memory. They are installed to add system memory to a controller motherboard.

a| link:fan-replace.html[Fan]

a| A fan cools the controller.

a| link:nvram-replace.html[NVRAM]

a| The NVRAM (Non-Volatile Random Access Memory) is a module that allows the controller to protect and save in-flight data if the system loses power. The system ID resides in the NVRAM module. When replaced, the controller assumes the new system ID from the replacement NVRAM module.

a| link:nvdimm-battery-replace.html[NV battery]

a| The NV battery is responsible for providing power to the NVRAM module while data in-flight is being destaged to flash memory after a power loss.

a| link:io-module-overview.html[I/O module]

a| The I/O module (Input/Output module) is a hardware component that acts as an intermediary between the controller and various devices or systems that need to exchange data with the controller.

a| link:power-supply-replace.html[Power supply]

a| A power supply provides a redundant power source in a controller.

a| link:rtc-battery-replace.html[Real-time clock battery]

a| A real-time clock battery preserves system date and time information if the power is off.

a| link:system-management-replace.html[System management module]

a| The System management module provides the interface between the controller and a console or laptop for controller or system maintenance purposes. The System management module contains the boot media and stores the system serial number (SSN).

|===
