---
permalink: a70-90/bootmedia-replace-requirements.html
sidebar: sidebar
keywords: aff a70, aff a90, replace the boot media
summary: Before replacing the boot media in your AFF A70 or AFF A90 system, ensure you meet the necessary requirements for a successful replacement. This includes making sure you have a USB flash drive with the appropriate amount of storage and verifying that you have the correct replacement boot device. 
---
= Requirements for manual boot media recovery - AFF A70 and AFF A90
:icons: font
:imagesdir: ../media/

[.lead]
Before replacing the boot media in your AFF A70 or AFF A90 system, ensure you meet the necessary requirements for a successful replacement. This includes making sure you have a USB flash drive with the appropriate amount of storage and verifying that you have the correct replacement boot device. 

If your system is running in ONTAP 9.17.1 and later, use the link:bootmedia-replace-workflow-bmr.html[automatic boot recovery procedure].

include::../_include/bootmedia_replace_requirements.adoc[]

.What's next?

After you've reviewed the requirements to replace the boot media, you need to link:bootmedia-encryption-preshutdown-checks.html[check encryption key support and status on the boot media].

//2025-11-25 ontap-systems-internal/1315 and ontap-systems-internal/1380
