---
permalink: a70-90/bootmedia-encryption-preshutdown-checks.html
sidebar: sidebar
keywords: aff a70, aff a90, pre-shutdown checks for onboard encryption keys
summary: "To ensure data security on your AFF A70 or AFF A90 storage system, you need to verify the encryption key support and status on your boot media. Check if your ONTAP version supports NetApp Volume Encryption, and before you shut down the controller check if the key manager is active."
---
= Check encryption support on your boot media in your AFF A70 or AFF A90 system
:icons: font
:imagesdir: ../media/

[.lead]
To ensure data security on your AFF A70 or AFF A90 storage system, you need to verify the encryption key support and status on your boot media. Check if your ONTAP version supports NetApp Volume Encryption (NVE), and before you shut down the controller check if the key manager is active. 

If your system is running in ONTAP 9.17.1 and later, use the link:bootmedia-replace-workflow-bmr.html[automatic boot recovery procedure].

== Step 1: Check NVE support and download the correct ONTAP image

Determine whether your ONTAP version supports NetApp Volume Encryption (NVE) so you can download the correct ONTAP image for the boot media replacement.

include::../_include/encryption_check_bootmedia.adoc[]

== Step 2: Verify key manager status and back up configuration

Before shutting down the impaired controller, verify the key manager configuration and back up the necessary information.

include::../_include/encryption_key_mgr_bootmedia.adoc[]

.What's next?
After checking the encryption key support and status on the boot media, you need to link:bootmedia-shutdown.html[shut down the controller].
//2025-11-25 ontap-systems-internal/1315 and ontap-systems-internal/1380
