---
permalink: a70-90/dimm-replace.html
sidebar: sidebar
keywords: aff a70, aff a90, replace a dimm
summary: Replace a DIMM in your AFF A70 or AFF A90 system if excessive correctable or uncorrectable memory errors are detected. Such errors can prevent the storage system from booting ONTAP. The replacement process involves shutting down the impaired controller, removing it, replacing the DIMM, reinstalling the controller, and then returning the failed part to NetApp.
---
= Replace a DIMM - AFF A70 and AFF A90
:icons: font
:imagesdir: ../media/

[.lead]
Replace a DIMM in your AFF A70 or AFF A90 system if excessive correctable or uncorrectable memory errors are detected. Such errors can prevent the storage system from booting ONTAP. The replacement process involves shutting down the impaired controller, removing it, replacing the DIMM, reinstalling the controller, and then returning the failed part to NetApp.

.Before you begin

* Make sure all other components in the system are functioning properly; if not, you must contact technical support.

* Make sure you replace the failed component with a replacement component you received from NetApp.

== Step 1: Shut down the impaired controller
 
Shut down or take over the impaired controller using one of the following options.
 
[role="tabbed-block"]
====
 
.Option 1: Most systems
--
include::../_include/shutdown_most_frus.adoc[]
--
.Option 2: Controller is in a MetroCluster
--
include::../_include/shutdown_any_mcc_no_2-node_mcc.adoc[]
--
 
====

== Step 2: Remove the controller module

include::../_include/a70-90_controller_remove_physical.adoc[]

== Step 3: Replace the DIMM

To replace the DIMM, locate them inside the controller and follow the specific sequence of steps.

include::../_include/a70-90_dimm_replace.adoc[]

== Step 4: Reinstall the controller module

include::../_include/a70-90_controller_install_step_physical.adoc[]

== Step 5: Return the failed part to NetApp

include::../_include/complete_rma.adoc[]
