---
permalink: a70-90/index.html
sidebar: sidebar
keywords: aff a70 aff a90 maintenance, maintenance, repairing a70 aff a90,  replace a70 aff a90 components
summary: Maintain the AFF A90, AFF A70 hardware
---
= Maintain AFF A90, AFF A70 hardware
:icons: font
:imagesdir: ../media/

[.lead]
For the AFF A70 and A90 storage systems, you can perform maintenance procedures on the following components.

== Boot media

The boot media stores a primary and secondary set of boot image files that the system uses when it boots. 

== Chassis

The chassis is the physical enclosure housing all the controller components such as the controller/CPU unit, power supply, and I/O.

== Controller

A controller consists of a board, firmware, and software. It controls the drives and implements the ONTAP functions.

== DIMM

You must replace a DIMM (dual in-line memory module) when a memory mismatch is present, or you have a failed DIMM.

== Drive

A drive is a device that provides the physical storage media for data.

== Fan

The fan cools the controller.

== NVDIMM

The NVDIMM (non-volatile dual in-line memory module) manages the data transfer from the volatile memory to the non-volatile storage, and maintains data integrity in the event of a power loss or system shutdown. 

== NVDIMM battery

A NVDIMM battery is responsible for maintaining power to the NVDIMM module.

== PCIe card

A PCIe (peripheral component interconnect express) card is an expansion card that plugs into the PCIe slot on the motherboard. 

== Power supply

A power supply provides a redundant power source in a controller shelf.

== Real-time clock battery

A real time clock battery preserves system date and time information if the power is off. 