---
permalink: a70-90/install-prepare.html
sidebar: sidebar
keywords: aff a70-90k, prepare installation
summary: Prepare to install your AFF A70, AFF A90 platform.
---
= Prepare for installation - AFF A70, AFF A90
:icons: font
:imagesdir: ../media/

[.lead]
Prepare to install your platform.

.Before you begin
* Use the https://docs.netapp.com/us-en/ontap/software_setup/index.html[cluster setup worksheet] to record the values that you need when you link:complete-install.html#step-3-configure-your-cluster[configure your cluster].  If a default value is provided, you can use that value or else enter your own.

* Confirm you have all of the additional equipment and tools that you need to complete the hardware installation.

** Phillips #2 screwdriver 
** Flashlight
** ESD strap 
** A paperclip or narrow tipped ball point pen for setting NS224 shelf IDs
** Laptop or console with a USB/serial connection
** Access to a web browser to configure your storage system
* You should be aware of the safety concerns associated with the weight of the platform.
+
A fully loaded A70-90 platform can weigh up to 151.68 lbs (68.8 kg) and requires four people to lift or use a hydraulic lift.
+
image::../media/drw_a70-90_weight_icon_ieops-1730.svg[AFF A90, AFF A70 weight caution icon]

* You should be aware of the safety concerns associated with the weight of the shelf.
+
A fully loaded shelf can weigh up to 66.78 lbs (30.29 kg) and requires two people to lift or use a hydraulic lift. Avoid removing shelf components (from the front or rear of the shelf) to reduce the shelf weight, because shelf weight will become unbalanced.
+
image::../media/drw_ns224_lifting_weight_ieops-1716.svg[NS224 lifting caution]

* Airflow through the storage system enters from the front where the bezel or end caps are installed and exhausts out the rear where the ports are located.


== Step 1: Prepare the site
Make sure that the site and the cabinet or rack you plan to use meet the specifications for your storage system.

.Steps

. Confirm that your site meets the environmental and electrical requirements for your platform as shown in the https://hwu.netapp.com[NetApp Hardware Universe^].

. Make sure you have adequate rack space:
** 4U for the platform chassis
** 2U for each NS224 shelf

. Install any required network switches near the platform.
+

See the https://docs.netapp.com/us-en/ontap-systems-switches/index.html[Switch documentation^] for installation instructions and link:https://hwu.netapp.com[NetApp Hardware Universe^] for compatibility information.


== Step 2: Unpack the boxes
Unpack all boxes and compare the contents to the items on the packing slip.

. Carefully open all the boxes and lay out the contents in an organized manner.

. Compare the contents you’ve unpacked with the list on the packing slip. 

+
NOTE: You can get your packing list by scanning the QR code on the side of the shipping carton.

+
The following items are some of the contents you might see in the boxes. 
+
Ensure that everything in the boxes matches the list on the packing slip. If there are any discrepancies, note them down for further action.
+

[%rotate, grid="none", frame="none", cols="12,9,4"]
|===
|*Hardware*
|*Cables* |
a|* Platform with onboard drives installed
* Shelf (optional)
* Rail kits with instructions (optional)
* Two Cable management devices 
* Bezel
a|* Power cords
* Network cables
* Management Ethernet cables (RJ-45 cables)
* USB-C serial port cable
* Storage cables (if additional storage is ordered) |
|===



== Step 3: Register your hardware
Register your platform to get support benefits.

.Steps

. Locate the system serial number for your platform. 
+
You can find the number on the packing slip, in your confirmation email, or on the controller after you unpack it.
+
image::../media/drw_ssn_label.svg[Example of the system serial number showing location of the number,width=200]
+

. Go to the NetApp Support Site at http://mysupport.netapp.com/[mysupport.netapp.com^].
. Register the hardware:
+

[role="tabbed-block"]
====

.Option 1: Existing NetApp customer
--
.Steps
. Sign in with your username and password.
. Select *Systems* > *My Systems*.
. Confirm that the new system serial number is listed.

NOTE:  If the new system serial number isn't listed, follow the instructions for new NetApp customers.

--
.Option 2: New NetApp customer
--
. Click *Register Now*, and create an account.
. Select *Systems* > *Register Systems*.
. Enter the product system serial number and requested details.

After your registration is approved, you can download any required software. The approval process might take up to 24 hours.

--

====


