---
permalink: a70-90/install-cable.html
sidebar: sidebar
keywords: aff a70, a90, prepare installation
summary: Management network ports on the controllers are connected to switches. The HA interconnect and cluster interconnect ports are cabled on both controllers. The controller modules are connected to external storage, if ordered.
---
= Cable the hardware - AFF A70 and AFF A90
:icons: font
:imagesdir: ../media/

[.lead]
After you install the rack hardware for your AFF A70 or AFF A90 storage system, install the network cables for the controllers, and connect the cables between the controllers and storage shelves.

.Before you begin
Check the illustration arrow in the cabling diagrams for the proper cable connector pull-tab orientation.

image::../media/drw_cable_pull_tab_direction_ieops-1699.svg[Cable pull tab orientation example]

* As you insert the connector, you should feel it click into place; if you do not feel it click, remove it, turn the cable head over and try again.
* If connecting to an optical switch, insert the small form-factor pluggable (SFP) transceiver into the controller port before cabling to the port.


== Step 1: Connect the storage controllers to your network
Connect the storage controllers to your host network.

.Before you begin

Contact your network administrator for information about connecting the storage system to the switches.

.About this task
These procedures show common configurations. Keep in mind that the specific cabling depends on the components ordered for your storage system. For comprehensive configuration and slot priority details, see link:https://hwu.netapp.com[NetApp Hardware Universe^].

[role="tabbed-block"]
====

.Option 1: Connect the controllers to a switchless ONTAP cluster
--
Connect your storage controllers to each other to create the ONTAP cluster connections, and then connect the Ethernet ports on each controller to your host network.

.Steps

. Use the the Cluster/HA interconnect cable to connect to connect ports e1a to e1a and ports e7a to e7a. 

+
NOTE: The cluster interconnect traffic and the HA traffic share the same physical ports.

+
.. Connect port e1a on Controller A to port e1A on Controller B.
.. Connect port e7a on Controller A to port e1A on Controller B.
+
*Cluster/HA interconnect cables*
+
image::../media/oie_cable_25Gb_Ethernet_SFP28_IEOPS-1069.svg[Cluster HA cable, width=100pxx]

+
image::../media/drw_70-90_tnsc_cluster_cabling_ieops-1653.svg[Two-node switchless cluster cabling diagram, width=500px]
+
. Connect the Ethernet module ports to your host network. 
+
The following are some typical host network cabling examples. See  link:https://hwu.netapp.com[NetApp Hardware Universe^] for your specific system configuration.

.. Connect ports e9a and e9b to your Ethernet data network switch as shown.
+
NOTE: For maximum system performance for cluster and HA traffic, do not use ports e1b and e7b ports for host network connections.  Use a separate host card to maximize performance.

+
*100 GbE cable*
+
image::../media/oie_cable_sfp_gbe_copper.svg[100Gb Ethernet cable, width=100px]
+
image::../media/drw_70-90_network_cabling1_ieops-1654.svg[Cable to 100 Gb Ethernet network,width=500px]

+
.. Connect your 10/25 GbE host network switches.
+
*4-ports, 10/25 GbE Host*
+
image::../media/oie_cable_sfp_gbe_copper.svg[10/25 Gb cable,width=100px]
+
image::../media/drw_70-90_network_cabling2_ieops-1655.svg[Cable to 100Gb Ethernet network,width=500px]
+


. Use the 1000BASE-T RJ-45 cables to connect the controller management (wrench) ports to the management network switches.
+
image::../media/oie_cable_rj45.svg[RJ45 cables,width=100px]
*1000BASE-T RJ-45 cables*
+
image::../media/drw_70-90_management_connection_ieops-1656.svg[Connect to your management network,width=500px]

IMPORTANT: Do not plug in the power cords yet. 



--
.Option 2: Connect the controllers to a switched ONTAP cluster
--
Connect your storage controllers to the cluster network switches to create the ONTAP cluster connections, and then connect the Ethernet ports on each controller to your host network.

.Steps

. Make the following cabling connections:

+
NOTE: The cluster interconnect traffic and the HA traffic share the same physical ports.


+
.. Connect port e1a on Controller A and port e1a on Controller B to cluster network switch A. 
.. Connect port e7a on Controller A and port e7a on Controller B to cluster network switch B.
+
*100 GbE cable*
+
image::../media/oie_cable100_gbe_qsfp28.svg[100 Gb cable,width=100px]
+
image::../media/drw_70-90_switched_cluster_cabling_ieops-1657.svg[Cable cluster connections to cluster network,width=500px]

. Connect the Ethernet module ports to your host network. 
+
The following are some typical host network cabling examples. See  link:https://hwu.netapp.com[NetApp Hardware Universe^] for your specific system configuration.

.. Connect ports e9a and e9b to your Ethernet data network switch as shown.
+
NOTE: For maximum system performance for cluster and HA traffic, do not use ports e1b and e7b ports for host network connections.  Use a separate host card to maximize performance.
+
*100 GbE cable*
+
image::../media/oie_cable_sfp_gbe_copper.svg[100Gb Ethernet cable,width=100px]
+
image::../media/drw_70-90_network_cabling1_ieops-1654.svg[Cable to 100Gb Ethernet network,width=500px]

+
.. Connect your 10/25 GbE host network switches.
+
*4-ports, 10/25 GbE Host*
+
image::../media/oie_cable_sfp_gbe_copper.svg[10/25Gb Ethernet cable,width=100px]
+
image::../media/drw_70-90_network_cabling2_ieops-1655.svg[Cable to 10/25Gb Ethernet network,width=500px]
+


. Connect the controller management (wrench) ports to the management network switches with 1000BASE-T RJ-45 cables.
+
image::../media/oie_cable_rj45.svg[RJ-45 cables,width=100px]
*1000BASE-T RJ-45 cables*
+
image::../media/drw_70-90_management_connection_ieops-1656.svg[Connect to your management network,width=500px]

IMPORTANT: Do not plug in the power cords yet. 

--

====

== Step 2: Connect the storage controllers to the storage shelves
The following cabling procedures show how to connect your controllers to one shelf and to two shelves. You can directly connect up to four shelves to your controllers.


// start tabbed area

[role="tabbed-block"]
====

.Option 1: Connect to one NS224 storage shelf
--
Connect each controller to the NSM modules on the NS224 shelf. The graphics show cabling from each of the controllers: Controller A cabling is shown in blue and Controller B cabling is shown in yellow.

*100 GbE QSFP28 copper cables*

image::../media/oie_cable100_gbe_qsfp28.svg[100 GbE QSFP28 copper cable,width=100px]

.Steps
. Connect controller A port e11a to NSM A port e0a.
. Connect controller A port e11b to port NSM B port e0b.
+
image:../media/drw_a70-90_1shelf_cabling_a_ieops-1731.svg[Controller A e11a and e11b to a single NS224 shelf]

. Connect controller B port e11a to NSM B port e0a.
. Connect controller B port e11b to NSM A port e0b.
+
image:../media/drw_a70-90_1shelf_cabling_b_ieops-1732.svg[Controller B e11a and e11b to a single NS224 shelf]

--

.Option 2: Connect to two NS224 storage shelves
--
Connect each controller to the NSM modules on both NS224 shelves. The graphics show cabling from each of the controllers: Controller A cabling is shown in blue and Controller B cabling is shown in yellow.

*100 GbE QSFP28 copper cables*

image::../media/oie_cable100_gbe_qsfp28.svg[100 GbE QSFP28 copper cable,width=100px]

.Steps

. On on controller A, connect the following ports:
.. Connect port e11a to shelf 1, NSM A port e0a.

.. Connect port e11b to shelf 2, NSM B port e0b.

.. Connect port e8a to shelf 2, NSM A port e0a.

.. Connect port e8b to shelf 1, NSM B port e0b.
+
image:../media/drw_a70-90_2shelf_cabling_a_ieops-1733.svg[Controller-to-shelf connections for controller A]
+

. On controller B, connect the following ports:
.. Connect port e11a to shelf 1, NSM B port e0a.

.. Connect  port e11b to shelf 2, NSM A port e0b.

.. Connect port e8a to shelf 2, NSM B port e0a.

.. Connect port e8b to shelf 1, NSM A port e0b.
+
image:../media/drw_a70-90_2shelf_cabling_b_ieops-1734.svg[Controller-to-shelf connections for controller B]
+

--

====

// end tabbed area

.What's next?

After you’ve cabled the hardware for your AFF A70 or AFF A90 system, you link:install-power-hardware.html[power on the AFF A70 or AFF A90 storage system].


