---
sidebar: sidebar
permalink: a70-90/install-requirements.html
keywords: a1a70-90k, install, setup, cautions
summary: Review the equipment needed and the lifting precautions for your platform and shelves.
---
= Hardware requirements - AFF A70 and AFF A90
:icons: font
:imagesdir: ../media/

[.lead]
Review the equipment needed and the lifting precautions for your AFF A70 or AFF A90 storage system and storage shelves.

== Equipment needed for install
To install your AFF A70 or AFF A90 storage system, you need the following equipment and tools. 

** Access to a Web browser to configure your storage system
** Electrostatic discharge (ESD) strap 
** Flashlight
** Laptop or console with a USB/serial connection
** Paperclip or narrow tipped ball point pen for setting NS224 storage shelf IDs
** Phillips #2 screwdriver 

== Lifting precautions 
AFF A70 and AFF A90 storage systems and NS224 storage shelves are heavy. Exercise caution when lifting and moving these items.

=== AFF A70 and AFF A90 storage systems
An AFF A70 storage system or an AFF A90 storage system can weigh up to 151.68 lbs (68.8 kg). To lift the system, use four people or a hydraulic lift.

image::../media/drw_a70-90_weight_icon_ieops-1730.svg[AFF A90, AFF A70 weight caution icon]


=== NS224 shelf
An NS224 storage shelf can weigh up to 66.78 lbs (30.29 kg). To lift the storage shelf, use two people or a hydraulic lift. Keep all components in the storage shelf (both front and rear) to prevent unbalancing the shelf weight.

image::../media/drw_ns224_lifting_weight_ieops-1716.svg[NS224 lifting caution]

.Related information

*  https://library.netapp.com/ecm/ecm_download_file/ECMP12475945[Safety information and regulatory notices^]

.What's next?
After you've reviewed the hardware requirements, you link:install-prepare.html[prepare to install your AFF A70 or AFF A90 storage system].


