---
permalink: a70-90/io-module-overview.html
sidebar: sidebar
keywords: AFF A90, AFF A70, replace io module
summary: You can replace a failed I/O module in your AFF A70 or AFF A90 storage system with the same type of I/O module, or with a different kind of I/O module. You can also add an I/O module into a system with empty slots.
---
= Overview of add and replace I/O module - AFF A70 and AFF A90
:icons: font
:imagesdir: ../media/

[.lead]
The AFF A70 and AFF A90 systems offer flexibility in expanding or replacing I/O modules to enhance network connectivity and performance. Adding or replacing an I/O module is essential when upgrading network capabilities or addressing a failed module.

You can replace a failed I/O module in your AFF A70 or AFF A90 storage system with the same type of I/O module, or with a different kind of I/O module. You can also add an I/O module into a system with empty slots.


* link:io-module-add.html[Add an I/O module]
+
Adding additional modules can improve redundancy, helping to ensure that the system remains operational even if one module fails.

* link:io-module-replace.html[Replace an I/O module]
+
Replacing a failing I/O module can restore the system to its optimal operating state. 

* The I/O slots on AFF A70 and AFF A90 controllers are numbered 1 through 11.
+
image::../media/drw_a1K_back_slots_labeled_ieops-2162.svg[Slot numbering on AFF A70 and AFF A90 controllers]