---
permalink: a70-90/io-module-replace.html
sidebar: sidebar
keywords: aff a70, aff a90, replace a pcie card
summary: Replace an I/O module in your AFF A70 or AFF A90 system when the module fails or requires an upgrade to support higher performance or additional features. The replacement process involves shutting down the controller, replacing the failed I/O module, rebooting the controller, and returning the failed part to NetApp.
---
= Replace an I/O module - AFF A70 and AFF A90
:icons: font
:imagesdir: ../media/

[.lead]
Replace an I/O module in your AFF A70 or AFF A90 system when the module fails or requires an upgrade to support higher performance or additional features. The replacement process involves shutting down the controller, replacing the failed I/O module, rebooting the controller, and returning the failed part to NetApp.

You can use this procedure with all versions of ONTAP supported by your storage system.

.Before you begin
* You must have the replacement part available.
* Make sure all other components in the storage system are functioning properly; if not, contact technical support.

== Step 1: Shut down the impaired controller

Shut down or take over the impaired controller using one of the following options.

[role="tabbed-block"]
====

.Option 1: Most systems
--
include::../_include/shutdown_most_frus.adoc[]
--
.Option 2: Controller is in a MetroCluster
--
include::../_include/shutdown_any_mcc_supported_no_PCM_remove.adoc[]
--

====

== Step 2: Replace a failed I/O module

include::../_include/a70-90_io_module_replace.adoc[]

== Step 3: Reboot the controller

include::../_include/io_module_replace_reboot.adoc[]

== Step 4: Return the failed part to NetApp

include::../_include/complete_rma.adoc[]

