---
permalink: a70-90/nvram-replace.html
sidebar: sidebar
keywords: aff a70, aff a90, replace an nvram
summary: Replace the NVRAM in your AFF A70 or AFF A90 system when the non-volatile memory becomes faulty or requires an upgrade.
---
= Replace the NVRAM - AFF A70 and AFF A90
:icons: font
:imagesdir: ../media/

[.lead]
Replace the NVRAM in your AFF A70 or AFF A90 system when the non-volatile memory becomes faulty or requires an upgrade. The replacement process involves
shutting down the impaired controller, completely removing power, replacing the NVRAM module or the NVRAM DIMM, reassigning the disks, and returning the failed part to NetApp.

The NVRAM module consists of the NVRAM12 hardware and field-replaceable DIMMs. 
You can replace a failed NVRAM module or the DIMMs inside the NVRAM module. 

.Before you begin
* Make sure you have the replacement part available. You must replace the failed component with a replacement component you received from NetApp.

* Make sure all other components in the storage system are functioning properly; if not, contact https://support.netapp.com[NetApp Support].

== Step 1: Shut down the impaired controller

Shut down or take over the impaired controller using one of the following options.

[role="tabbed-block"]
====

.Option 1: Most systems
--
include::../_include/shutdown_most_frus.adoc[]
--
.Option 2: Controller is in a MetroCluster
--
include::../_include/shutdown_any_mcc_no_2-node_mcc.adoc[]
--

====

== Step 2: Replace the NVRAM module or NVRAM DIMM

include::../_include/a70-90_nvram_replace.adoc[]

== Step 4: Return the failed part to NetApp

include::../_include/complete_rma.adoc[]