---
permalink: a70-90/rtc-battery-replace.html
sidebar: sidebar
keywords: aff a70, aff a90, replace the real-time clock battery
summary: Replace the real-time clock (RTC) battery, commonly known as a coin cell battery, in your AFF A70 or AFF A90 system to ensure that services and applications relying on accurate time synchronization remain operational.
---
= Replace the real-time clock battery - AFF A70 and AFF A90
:icons: font
:imagesdir: ../media/

[.lead]
Replace the real-time clock (RTC) battery, commonly known as a coin cell battery, in your AFF A70 or AFF A90 system to ensure that services and applications relying on accurate time synchronization remain operational.

.Before you begin
* Understand that you can use this procedure with all versions of ONTAP supported by your system.
* Make sure all other components in the system are functioning properly; if not, you must contact technical support.

== Step 1: Shut down the impaired controller

Shut down or take over the impaired controller using one of the following options.

[role="tabbed-block"]
====

.Option 1: Most systems
--
include::../_include/shutdown_most_frus.adoc[]
--
.Option 2: Controller is in a MetroCluster
--
include::../_include/shutdown_any_mcc_no_2-node_mcc.adoc[]
--

====

== Step 2: Remove the controller module

include::../_include/a70-90_controller_remove_physical.adoc[]
 
== Step 3: Replace the RTC battery

include::../_include/a70-90_rtc_battery_replace.adoc[]

== Step 4: Reinstall the controller module

include::../_include/a70-90_controller_install_step_physical.adoc[]

== Step 5: Reset the time and date on the controller

include::../_include/rtc_battery_reset_time.adoc[]

== Step 6: Return the failed part to NetApp

include::../_include/complete_rma.adoc[]

