---
permalink: afx-2k/io-module-overview.html
sidebar: sidebar
keywords: afx 2k, replace io module
summary: The afx 2k storage system offers flexibility in expanding or replacing I/O modules to enhance network connectivity and performance. Adding or replacing an I/O module is essential when upgrading network capabilities or addressing a failed module.
---
= Overview of add and replace I/O module - AFX 2K
:icons: font
:imagesdir: ../media/

[.lead]
The AFX 2K storage system offers flexibility in expanding or replacing I/O modules to enhance network connectivity and performance. Adding or replacing an I/O module is essential when upgrading network capabilities or addressing a failed module.

You can replace a failed I/O module in your AFX 2K storage system with the same type of I/O module, or with a different kind of I/O module. You can also add an I/O module into a system with empty slots.

* link:io-module-add.html[Add an I/O module]
+
Adding additional modules can improve redundancy, helping to ensure that the system remains operational even if one module fails.

* link:io-module-replace.html[Replace an I/O module]
+
Replacing a failing I/O module can restore the system to its optimal operating state. 

.I/O slot numbering

The I/O slots on the AFX 2K controller are numbered 1 through 11, as shown in the following illustration.

image::../media/drw_afx_emr_rear_slots_ieops-2862.svg[Slot numbering on an AFX controller]

[cols="1,4"]
|===

a|
image::../media/icon_round_1.svg[Callout number 1] 
a|
HA

a|
image::../media/icon_round_2.svg[[Callout number 2]
a|
Cluster

a|
image::../media/icon_round_3.svg[[Callout number 3]
a|
Network

a|
image::../media/icon_round_4.svg[[Callout number 4]

image::../media/icon_round_5.svg[[Callout number 5]
a|
NVRAM

a|
image::../media/icon_round_6.svg[[Callout number 6]

image::../media/icon_round_7.svg[[Callout number 7]
a|
NVRAM12-EX

a|
image::../media/icon_round_8.svg[[Callout number 8]
a|
Storage

a|
image::../media/icon_round_9.svg[[Callout number 9]
a|
Network

a|
image::../media/icon_round_10.svg[[Callout number 10]
a|
Storage

a|
image::../media/icon_round_11.svg[[Callout number 11]
a|
Empty

|===