---
permalink: a900/bootmedia-shutdown.html
sidebar: sidebar
keywords:
summary: 'You can shut down or take over the impaired controller using different procedures, depending on the storage system hardware configuration.'
---
= Shut down the impaired controller - AFF A900
:icons: font
:imagesdir: ../media/

[.lead]
Shut down or take over the impaired controller using the appropriate procedure for your configuration.

If your storage system is running ONTAP 9.17.1 or later, use the link:bootmedia-replace-workflow-bmr.html[automated boot recovery procedure]. If your system is running an earlier version of ONTAP, you must use the manual boot recovery procedure.

[role="tabbed-block"]
====

.Most configurations
--
After completing the NVE or NSE tasks, you need to complete the shutdown of the impaired controller.

If your storage system is running ONTAP 9.17.1 or later, use the automated boot recovery procedure. If your system is running an earlier version of ONTAP, you must use the manual boot recovery process.

include::../_include/shutdown_most_frus.adoc[]
--
.Controller is in a MetroCluster
--

After completing the NVE or NSE tasks, you need to complete the shutdown of the impaired controller.

include::../_include/shutdown_any_mcc_supported.adoc[]
--

====
