---
permalink: a900/bootmedia-shutdown.html
sidebar: sidebar
keywords: aff a900, shut down the controller
summary: 'Shut down the controller in your AFF A900 storage system to prevent data loss and maintain system stability during the manual boot media recovery process.'
---
= Shut down the controller in your AFF A900 system during the manual boot recovery process
:icons: font
:imagesdir: ../media/

[.lead]
Shut down the controller in your AFF A900 storage system to prevent data loss and maintain system stability during the manual boot media recovery process.

If your storage system is running ONTAP 9.17.1 or later, use the link:bootmedia-replace-workflow-bmr.html[automated boot recovery procedure]. If your system is running an earlier version of ONTAP, you must use the manual boot recovery procedure.

[role="tabbed-block"]
====

.Most configurations
--
After completing the NVE or NSE tasks, you need to complete the shutdown of the controller.

If your storage system is running ONTAP 9.17.1 or later, use the automated boot recovery procedure. If your system is running an earlier version of ONTAP, you must use the manual boot recovery process.

include::../_include/shutdown_most_frus.adoc[]
--
.Controller is in a MetroCluster
--

After completing the NVE or NSE tasks, you need to complete the shutdown of the controller.

include::../_include/shutdown_any_mcc_supported.adoc[]
--

====
