---
permalink: a900/overview.html
sidebar: sidebar
summary: Key specifications for the A900 platform group
---
= Key specifications for AFF A900
:icons: font
:imagesdir: ../media/

[.lead]
The following are a selection of key specifications for AFF A900 in a single high availability pair. Visit https://hwu.netapp.com[NetApp Hardware Universe^] (HWU) for a complete list of AFF A900 specifications.

== Key specifications for AFF A900

Platform Configuration: AFF A900 Single Chassis HA Pair

Max Raw Capacity: 14.6880 PB

Memory: 2048.0000 GB

Form Factor: 8U chassis with 2 HA controllers 

ONTAP Version: ONTAP: 9.16.1P2

PCIe Expansion Slots: 20

Minimum ONTAP Version: ONTAP 9.10.1RC2

== Scaleout maximums
* Type: NAS; HA Pairs: 12; Raw Capacity: 176.3 PB / 156.5 PiB; Max Memory: 24576 GB
* Type: SAN; HA Pairs: 6; Raw Capacity: 88.1 PB / 78.3 PiB; Max Memory: 12288 GB
* Type: HA Pair; Raw Capacity: 14.7 PB / 13.0 PiB; Max Memory: 2048.0000

== IO

=== Onboard IO
No onboard IO data.

=== Total IO
* Protocol: Ethernet 100 Gbps; Ports: 32
* Protocol: Ethernet 25 Gbps; Ports: 64
* Protocol: Ethernet 10 Gbps; Ports: 64
* Protocol: FC 32 Gbps; Ports: 64
* Protocol: NVMe/FC  32 Gbps; Ports: 64
* Ports: 0
* Protocol: SAS 12 Gbps; Ports: 64

=== Management Ports
* Protocol: Ethernet 1 Gbps; Ports: 2
* Protocol: RS-232 115 Kbps; Ports: 6
* Protocol: USB 12 Mbps; Ports: 2

== Storage Networking Supported
CIFS
FC
iSCSI
NFS v3
NFS v4.0
NFS v4.1
NFS v4.2
NVMe/FC 
NVMe/TCP
S3
S3 with NAS
SMB 2.0
SMB 2.1
SMB 2.x
SMB 3.0
SMB 3.1
SMB 3.1.1
== System environment specifications
* Typical Power: 8004 BTU/hr
* Worst-case Power: 9937 BTU/hr
* Weight: 220.5 lb
100.0 kg
* Height: 8U
* Width: 19” IEC rack-compliant (17.7” 45.0 cm)
* Depth: 28.8”
(36.8” with cable management bracket)
* Operating Temp/Altitude/Humidity: 10°C to 35°C
50°F to 
95°F) at
<= 3048m
<= 10000 ft) elevation;8% to 80%
relative humidity, noncondensing
* Non-operating Temp/Humidity: -40°C to 70°C (-40°F to 158°F) upto 12192m (40000 ft)
10% to 95%  relative humidity, noncondensing, in original container
* Acoustic Noise: Declared sound power (LwAd): 7.4
Sound pressure (LpAm) (bystander positions): 65.0 dB

== Compliance
* Certifications EMC/EMI: AMCA,
FCC,
ICES,
KC,
Morocco,
VCCI
* Certifications safety: BIS,
CB,
CSA,
G_K_U-SoR,
IRAM,
NOM,
NRCS,
SONCAP,
TBS
* Certifications Safety/EMC/EMI: EAC,
UKRSEPRO
* Certifications Safety/EMC/EMI/RoHS: BSMI,
CE DoC,
UKCA DoC
* Standards EMC/EMI: BS-EN-55024,
BS-EN55035,
CISPR 32,
EN55022,
EN55024,
EN55032,
EN55035,
EN61000-3-2,
EN61000-3-3,
FCC Part 15 Class A,
ICES-003,
KS C 9832,
KS C 9835
* Standards Safety: ANSI/UL60950-1,
ANSI/UL62368-1,
BS-EN62368-1,
CAN/CSA C22.2 No. 60950-1,
CAN/CSA C22.2 No. 62368-1,
CNS 14336,
EN60825-1,
EN62368-1,
IEC 62368-1,
IEC60950-1,
IS 13252(part 1)

== High Availability
Ethernet based baseboard management controller (BMC) and ONTAP management interface
Redundant hot-swappable controllers
Redundant hot-swappable power supplies
SAS in-band management over SAS connections