---
permalink: asa800/controller-replace-recable-reassign-disks.html
sidebar: sidebar
keywords: asa a800, how to recable the system, how to reassign disks
summary: Return control of storage resources to the replacement controller so your ASA A800 system can resume normal operation.
---
= Give back the controller in an ASA A800 system to resume normal operations
:icons: font
:imagesdir: ../media/

[.lead]
Return control of storage resources to the replacement controller so your ASA A800 system can resume normal operation. The give back procedure varies based on the encryption type used by your system: no encryption or Onboard Key Manager (OKM) encryption.

== Step 1: Recable the system

include::../_include/recable_system_after_controller_rep.adoc[]

== Step 2: Reassign disks

If the storage system is in an HA pair, the system ID of the new controller module is automatically assigned to the disks when the giveback occurs at the end of the procedure. You must confirm the system ID change when you boot the _replacement_ controller and then verify that the change was implemented.

This step only applies only to systems running ONTAP in an HA pair.

include::../_include/800_controller_replace_recable_reassign_disks.adoc[]