---
permalink: asa800/pci-cards-and-risers-replace.html
sidebar: sidebar
keywords: asa a800, replace a pcie card
summary: "To replace a PCIe card, you must disconnect the cables from the cards, remove the SFP and QSFP modules from the cards before removing the riser, reinstall the riser, and then reinstall the SFP and QSFP modules before cabling the cards."
---
= Replace a PCIe card in your ASA A800 system
:icons: font
:imagesdir: ../media/

[.lead]

Replace or add an I/O module in your ASA A800 system when the module fails,  requires an upgrade to support higher performance, or additional features. The replacement process involves shutting down the controller, replacing the failed I/O module, rebooting the controller, and returning the failed part to NetApp.

.Before you begin

* You must have the NetApp new or replacement part available.
* Make sure all other components in the storage system are functioning properly; if not, contact technical support.
* You can use this procedure with all versions of ONTAP supported by your system.
* All other components in the system must be functioning properly; if not, you must contact technical support.


== Step 1: Shut down the impaired controller

Shut down or take over the impaired controller.

include::../_include/shutdown_most_frus.adoc[]

== Step 2: Remove the controller module

You must remove the controller module from the chassis when you replace the controller module or replace a component inside the controller module.

include::../_include/800_controller_remove_physical.adoc[]

== Step 3: Replace the PCIe card

Replace a PCIe card by removing the cabling and any QSFPs and SFPs from the ports on the PCIe cards in the target riser, removing the riser from the controller module, removing and replacing the PCIe card, reinstalling the riser and any QSFPs and SFPs onto the ports, and recable the ports.

include::../_include/800_pci_cards_and_risers_replace.adoc[]

== Step 4: Reinstall the controller module

Reinstall the controller module and reboot it.

include::../_include/800_controller_install_step_physical.adoc[]

== Step 5: Return the failed part to NetApp

include::../_include/complete_rma.adoc[]
//2025-11-25 ontap-systems-internal/1315 and ontap-systems-internal/1380
