---
permalink: a200/chassis-replace-complete-system-restore-rma.html
sidebar: sidebar
keywords: aff a200, verify and set HA state,  complete the replacement process
summary: "You must verify the HA state of the chassis and return the failed part to NetApp, as described in the RMA instructions shipped with the kit."
---
= Complete the chassis replacement for an AFF A200 system
:icons: font
:imagesdir: ../media/

[.lead]
Complete the chassis replacement for your AFF A200 system by verifying the HA state of the chassis and returning the failed component to NetApp.

== Step 1: Verify and set the HA state of the chassis
You must verify the HA state of the chassis, and, if necessary, update the state to match your system configuration.

.Steps
. In Maintenance mode, from either controller module, display the HA state of the local controller module and chassis: `ha-config show`
+
The HA state should be the same for all components.

. If the displayed system state for the chassis does not match your system configuration:
 .. Set the HA state for the chassis: `ha-config modify chassis _HA-state_`
+
The value for HA-state can be one of the following:

  *** `ha`
  *** `non-ha`

 .. Confirm that the setting has changed: `ha-config show`
. If you have not already done so, recable the rest of your system.


== Step 2: Return the failed part to NetApp

include::../_include/complete_rma.adoc[]
