settings:
  name: "Install and maintain"
  internal:
    pdf_enabled: false
  prod:
    pdf_enabled: true
    harmony_enabled: true
  rss_page: "whats-new.html"
sidebar:
  entries:
    - title: ONTAP hardware systems docs
      url: "/index.html"
    - title: Release notes
      entries:
        - title: What's new
          url: /whats-new.html
        - title: Supported hardware option 1
          url: /supported-platforms.html
        - title: Supported hardware option 2
          url: /supported-platforms-two.html
        - title: End-of-support
          url: /eoa-hardware.html
    - title: Get started
      url: /get-up-and-run.html
    - title: AFF systems
      url: /aff-landing/index.html 
      entries:
      - title: A-Series systems
        url: /aff-aseries/index.html 
        entries:   
        - section: a1k
        - section: a70-90
        - section: a20-30-50
        - section: a150
        - section: a250
        - section: a400
        - section: a800
        - section: a900
      - title: C-Series systems
        url: /aff-cseries/index.html
        entries:
        - section: c80
        - section: c250
        - section: c400
        - section: c800
    - title: ASA systems
      url: /allsan-landing/index.html
      entries:  
      - title: A-Series systems
        url: /allsan-a-series/index.html
        entries:    
        - section: asa150
        - section: asa250
        - section: asa400
        - section: asa800
        - section: asa900
      - title: C-Series systems
        url: /allsan-c-series/index.html
        entries:    
        - section: asa-c250
        - section: asa-c-400
        - section: asa-c800
    - title: ASA r2 systems
      url: /asa-r2/index.html
      entries:  
      - title: Install and setup
        url: /asa-r2/asa-r2-install-setup.html 
      - title: Maintain
        url: /asa-r2-landing-maintain/index.html
        entries:
        - section: asa-r2-a1k-maintain
        - section: asa-r2-a70-90-maintain
    - title: FAS systems
      url: /fas/index.html
      entries:
      - section: fas-70-90
      - section: fas2700
      - section: fas2800
      - section: fas8300
      - section: fas9500
    - title: End-of-availability systems
      url: /endofavail/index.html
      entries:
        - section: a200
        - section: a220
        - section: a300
        - section: a320
        - section: a700
        - section: a700s
        - section: c190
        - section: fas2600
        - section: fas500f
        - section: fas8200
        - section: fas9000
        - title: Other models
          url: /other/other-models.html
    - title: Drive shelves
      url: /drive-shelves/index.html
      entries:
        - section: ns224
        - section: sas3
    - title: Cabinet and rail kits
      entries:
        - title: SuperRail kit
          url: /platform-supplemental/superrail-install.html
        - title: AFF A700/FAS9000 two-post rail kit
          url: /platform-supplemental/telco-installation-instructions.html
        - title: 42U 1280 mm system cabinet
          entries:
          - title: Prepare to install cabinet
            entries:
            - title: Cabinet features
              url: /platform-supplemental/42u-1280mm-features.html
            - title: Required tools/equipment
              url: /platform-supplemental/42u-1280mm-required-tools.html
            - title: Space requirements and cabinet dimensions
              url: /platform-supplemental/42u-1280mm-space-and-dimensions.html
            - title: Supported PDU types and specs
              url: /platform-supplemental/42u-1280mm-supported-pdu-types-and-specifications.html
          - title: Unpack system cabinet
            url: /platform-supplemental/42u-1280mm-unpack.html
          - title: Install cabinet
            entries:
            - title: Overview
              url: /platform-supplemental/42u-1280mm-install.html
            - title: Install cabinet interconnect kit
              url: /platform-supplemental/42u-1280mm-install-cabinet-interconnect-kit.html
            - title: Install bolt-down kit
              url: /platform-supplemental/42u-1280mm-install-bolt-down-kit.html
            - title: Install support rails
              url: /platform-supplemental/42u-1280mm-install-additional-rails.html
            - title: Install equipment
              url: /platform-supplemental/42u-1280mm-install-equipment.html
            - title: Power on cabinet
              url: /platform-supplemental/42u-1280mm-power-on.html
          - title: Replace PDUs
            url: /platform-supplemental/42u-1280mm-replace-pdus.html
          - title: Reverse cabinet front door
            entries:
            - title: What you need
              url: /platform-supplemental/42u-1280mm-reverse-front-door.html
            - title: Remove illuminated badge
              url: /platform-supplemental/42u-1280mm-remove-illuminated-badge.html
            - title: Remove cabinet door
              url: /platform-supplemental/42u-1280mm-remove-door.html
            - title: Move badge power supply and cabling
              url: /platform-supplemental/42u-1280mm-move-badge-ps-and-cabling.html
            - title: Reverse door hinge and lock catch
              url: /platform-supplemental/42u-1280mm-reverse-hinge-and-lock.html
            - title: Reinstall door and illuminated badge
              url: /platform-supplemental/42u-1280mm-reinstall-door-and-badge.html
    - title: Legal notices
      url: "/legal-notices.html"
product-family:
  name: ONTAP hardware systems
  repo: ontap-systems-family

