---
sidebar: sidebar
permalink: whats-new.html
sidebar: sidebar
keywords: new, features, asa r2, aff, asa, fas
summary: 'Learn about the new platforms for ONTAP hardware systems.'
---
= What's new for ONTAP hardware systems
:icons: font
:imagesdir: ./media/

[.lead]
Learn what's new for ONTAP hardware systems.

== ASA r2 systems: ASA A1K, ASA A70, and ASA A90
The new NetApp ASA r2 systems (ASA A1K, ASA A70, and ASA A90) deliver a unified hardware and software solution that creates a simplified experience specific to the needs of SAN-only customers. 

On an ASA r2 system, ONTAP software and System Manager are streamlined to provide support for essential SAN functionality while removing visibility of features and functions not supported in SAN environments.

https://docs.netapp.com/us-en/asa-r2/learn-more/hardware-comparison.html[ Learn more about the new ASA r2 systems] in comparison to the ASA systems.

== AFF A20, AFF A30 and AFF A50
The new AFF A20, A30 and A50 hardware systems extend high-performance, intelligent, and comprehensive data management capabilities to more customers and workloads. 

The systems offer real-time ML-based ransomware detection, seamless cloud integration, and unmatched performance for mission-critical workloads including AI, VMware, databases, and analytics with support for block, file, and object storage.

link:https:/www.netapp.com/data-storage/aff-a-series/[Learn more about AFF A-Series systems].

== AFF C30, AFF C60 and AFF C80
The new AFF C30, AFF C60 and AFF C80 hardware systems make the performance and efficiency gains of flash more accessible to businesses by providing an industry-leading 1.5PB of storage capacity in two-rack deployments.

The solution offers exceptional density with 60TB drives on the AFF C60 and AFF C80, increased performance, and improved I/O flexibility.

link:https:/www.netapp.com/data-storage/aff-c-series/[Learn more about AFF C-Series systems].


