---
sidebar: sidebar
permalink: whats-new.html
sidebar: sidebar
keywords: new, features, asa r2, aff, asa, fas
summary: 'Learn about the new platforms for ONTAP hardware systems.'
---
= What's new for ONTAP hardware systems
:icons: font
:imagesdir: ./media/

[.lead]
Learn what's new for ONTAP hardware systems.

== February 2025

=== ASA A20, ASA A30, and ASA A50
The new ASA r2 hardware systems (ASA A20, ASA A30, and ASA A50) make block storage available to companies of every size for mission-critical apps like databases and virtual machines. 

link:https://docs.netapp.com/us-en/asa-r2/get-started/learn-about.html[Learn more about the ASA r2 systems].

== December 2024

=== AFF A20, AFF A30, and AFF A50
The new AFF A20, A30, and A50 hardware systems extend high-performance, intelligent, and comprehensive data management capabilities to more customers and workloads. 

The systems offer real-time ML-based ransomware detection, seamless cloud integration, and unmatched performance for mission-critical workloads including AI, VMware, databases, and analytics with support for block, file, and object storage.

link:https://www.netapp.com/data-storage/aff-a-series/[Learn more about AFF A-Series systems].

=== AFF C30, AFF C60, and AFF C80
The new AFF C30, AFF C60, and AFF C80 hardware systems make the performance and efficiency gains of flash more accessible to businesses by providing an industry-leading 1.5PB of storage capacity in two-rack deployments.

The solution offers exceptional density with 60TB drives, increased performance, and improved I/O flexibility.

link:https://www.netapp.com/data-storage/aff-c-series/[Learn more about AFF C-Series systems].

=== NS224 drive shelf with NSM100B shelf modules
Enhance your data center capabilities with the NS224 and the new NSM100B NVMe storage expansion module. Designed as a direct replacement for the NSM100 module, the new NSM100B shelf module integrates seamlessly into your existing setup. It supports both direct-attached and switch-attached configurations of NS224 shelves, offering exceptional flexibility to optimize your storage system's efficiency and scalability.


== September 2024

=== ASA r2 systems
The new ASA r2 hardware systems (ASA A1K, ASA A70, and ASA A90) deliver a unified hardware and software solution that creates a simplified experience specific to the needs of SAN-only customers. 

link:https://docs.netapp.com/us-en/asa-r2/get-started/learn-about.html[Learn more about the ASA r2 systems].

=== FAS70 and FAS90
The new FAS70 and FAS90 hardware systems deliver affordable, yet high-performing backup storage, enabling a secure cyber vault for recovery from ransomware attacks.

link:https://www.netapp.com/data-storage/fas/[Learn more about FAS systems].



