---
permalink: c80/nvram-replace.html
sidebar: sidebar
keywords: c80, replace an nvdimm
summary: 'The NVRAM module consists of the NVRAM12 and DIMMs and up to two NVMe SSD Flash Cache modules (Flash Cache or caching modules) per NVRAM module.'
---
= Replace NVRAM - AFF C80
:icons: font
:imagesdir: ../media/

[.lead]
Replace the NVRAM in your AFF C80 system when the non-volatile memory becomes faulty or requires an upgrade. The replacement process involves
shutting down the impaired controller, completely removing power by pulling the controller out a few inches, replacing the NVRAM module or the NVRAM DIMM, reassigning the disks, and returning the failed part to NetApp.

.Before you begin
* Make sure you have the replacement part available. You must replace the failed component with a replacement component you received from NetApp.

* Make sure all other components in the storage system are functioning properly; if not, contact https://support.netapp.com[NetApp Support].

== Step 1: Shut down the impaired controller

Shut down or take over the impaired controller using one of the following options.

[role="tabbed-block"]
====

.Option 1: Most systems
--
include::../_include/shutdown_most_frus.adoc[]
--
.Option 2: Controller is in a MetroCluster
--
include::../_include/shutdown_any_mcc_no_2-node_mcc.adoc[]
--

====

== Step 2: Replace the NVRAM module or NVRAM DIMM

include::../_include/a70-90_nvram_replace.adoc[]

== Step 4: Return the failed part to NetApp

include::../_include/complete_rma.adoc[]
//2025-11-25 ontap-systems-internal/1315 and ontap-systems-internal/1380
