---
sidebar: sidebar
permalink: fru-reference/io-module-fru-links.html
keywords: I/O module, field replaceable units, FRU, I/O module replacement
summary: "Find I/O module replacement procedures for your NetApp storage system organized by platform family. This reference provides direct links to step-by-step I/O module replacement workflows for AFF, ASA, and FAS systems to help you quickly locate the correct procedure for your specific model."
---
= Access I/O module replacement procedures by platform family
:icons: font
:imagesdir: ../media/

[.lead]
Find I/O module replacement procedures for your NetApp storage system organized by platform family. This reference provides direct links to step-by-step I/O module replacement workflows for AFF, ASA, and FAS systems to help you quickly locate the correct procedure for your specific model.

[role="tabbed-block"]
====
.AFF systems
--
* link:../a1k/io-module-replace.html[AFF A1K]
* link:../a20-30-50/io-module-replace.html[AFF A20/30/50]
* link:../a70-90/io-module-replace.html[AFF A70/90]
* link:../c30-60/io-module-replace.html[AFF C30/60]
* link:../c80/io-module-replace.html[AFF C80]
--

.ASA systems
--
* link:../asa-r2-a1k/io-module-replace.html[ASA A1K]
* link:../asa-r2-a20-30-50/io-module-replace.html[ASA A20/30/50]
* link:../asa-r2-70-90/io-module-replace.html[ASA 70/90]
* link:../asa-r2-c30/io-module-replace.html[ASA C30]
--

.FAS systems
--
* link:../fas50/io-module-replace.html[FAS50]
* link:../fas-70-90/io-module-replace.html[FAS70/90]
--
====

// 2025-09-18: ontap-systems-internal/issues/769