---
sidebar: sidebar
permalink: fru-reference/nvram-module-fru-links.html
keywords: NVRAM module, field replaceable units, FRU, NVRAM module replacement
summary: "Find NVRAM module replacement procedures for your NetApp storage system organized by platform family. This reference provides direct links to step-by-step NVRAM module replacement workflows for AFF, ASA, and FAS systems to help you quickly locate the correct procedure for your specific model."
---
= NVRAM module replacement procedures by platform family
:icons: font
:imagesdir: ../media/

[.lead]
Find NVRAM module replacement procedures for your NetApp storage system organized by platform family. This reference provides direct links to step-by-step NVRAM module replacement workflows for AFF, ASA, and FAS systems to help you quickly locate the correct procedure for your specific model.

[role="tabbed-block"]
====
.AFF systems
--
* link:../a1k/nvram-replace.html[AFF A1K]
* link:../a70-90/nvram-replace.html[AFF A70/90]
* link:../a700/nvram-module-or-nvram-dimm-replacement.html[AFF A700]
* link:../a700s/nvram-or-nvram-dimm-replacement.html[AFF A700s]
* link:../a900/nvram_module_or_nvram_dimm_replacement.html[AFF A900]
* link:../c80/nvram-replace.html[AFF C80]
--

.ASA systems
--
* link:../asa900/nvram_module_or_nvram_dimm_replacement.html[ASA A900]
* link:../asa-r2-a1k/nvram-replace.html[ASA A1K]
* link:../asa-r2-70-90/nvram-replace.html[ASA 70/90]
--

.FAS systems
--
* link:../fas-70-90/nvram-replace.html[FAS70/90]
* link:../fas9000/nvram-module-or-nvram-dimm-replacement.html[FAS9000]
* link:../fas9500/nvram_module_or_nvram_dimm_replacement.html[FAS9500]
--
====

// 2025-09-18: ontap-systems-internal/issues/769