---
sidebar: sidebar
permalink: fru-reference/system-management-fru-links.html
keywords: system management module, field replaceable units, FRU, system management replacement
summary: "Find system management module replacement procedures for your NetApp storage system organized by platform family. This reference provides direct links to step-by-step system management module replacement workflows for AFF, ASA, and FAS systems to help you quickly locate the correct procedure for your specific model."
---
= System management module replacement procedures by platform family
:icons: font
:imagesdir: ../media/

[.lead]
Find system management module replacement procedures for your NetApp storage system organized by platform family. This reference provides direct links to step-by-step system management module replacement workflows for AFF, ASA, and FAS systems to help you quickly locate the correct procedure for your specific model.

[role="tabbed-block"]
====
.AFF systems
--
* link:../a1k/system-management-replace.html[AFF A1K]
* link:../a70-90/system-management-replace.html[AFF A70/90]
* link:../c80/system-management-replace.html[AFF C80]
--

.ASA systems
--
* link:../asa-r2-a1k/system-management-replace.html[ASA A1K]
* link:../asa-r2-70-90/system-management-replace.html[ASA 70/90]
--

.FAS systems
--
* link:../fas-70-90/system-management-replace.html[FAS70/90]
--

.AFX systems
--
* link:../afx-1k/system-management-replace.html[AFX A1K]
--
====

// 2025-09-18: ontap-systems-internal/issues/769
// 2025-10-21: ontap-systems-internal/issues/1370