---
permalink: a320/chassis-replace-move-hardware.html
sidebar: sidebar
keywords: aff, a320, aff a320, replace, chassis, fan, controller, module, impair, model, shut, down, replacing, remove, move, equipment, rack, complete, replacement, process, replace the chassis, shut down the controllers when replacing a chassis, remove the controller modules, move the fans, replace a chassis from within the equipment rack or system cabinet, install the controller modules, complete the replacement process
summary: "Move the fans, hard drives, and controller module or modules from the impaired chassis to the new chassis, and swap out the impaired chassis from the equipment rack or system cabinet with the new chassis of the same model as the impaired chassis."
---
= Replace the chassis in an AFF A320 system
:icons: font
:imagesdir: ../media/

[.lead]
Replace the chassis in your AFF A320 system by moving the fans, hard drives, and controller modules from the impaired chassis to the replacement chassis.

== Step 1: Remove the controller modules

To replace the chassis, you must remove the controller modules from the old chassis.

. If you are not already grounded, properly ground yourself.
. Release the power cable retainers, and then unplug the cables from the power supplies.
. Loosen the hook and loop strap binding the cables to the cable management device, and then unplug the system cables and SFPs (if needed) from the controller module, keeping track of where the cables were connected.
+
Leave the cables in the cable management device so that when you reinstall the cable management device, the cables are organized.

. Remove and set aside the cable management devices from the left and right sides of the controller module.
. Remove the controller module from the chassis:
 .. Insert your forefinger into the latching mechanism on either side of the controller module.
 .. Press down on the orange tab on top of the latching mechanism until it clears the latching pin on the chassis.
+
The latching mechanism hook should be nearly vertical and should be clear of the chassis pin.

 .. Gently pull the controller module a few inches toward you so that you can grasp the controller module sides.
 .. Using both hands, gently pull the controller module out of the chassis and set it on a flat, stable surface.
. Repeat these steps for the other controller module in the chassis.

== Step 2: Move the fans

To move the fan modules to the replacement chassis when replacing the chassis, you must perform a specific sequence of tasks.

. If you are not already grounded, properly ground yourself.
. Remove the bezel (if necessary) with two hands, by grasping the openings on each side of the bezel, and then pulling it toward you until the bezel releases from the ball studs on the chassis frame.
. Press down the release latch on the fan module cam handle, and then rotate the cam handle downward.
+
The fan module moves a little bit away from the chassis.

. Pull the fan module straight out from the chassis, making sure that you support it with your free hand so that it does not swing out of the chassis.
+
CAUTION: The fan modules are short. Always support the bottom of the fan module with your free hand so that it does not suddenly drop free from the chassis and injure you.
+

. Set the fan module aside.
. Repeat the preceding steps for any remaining fan modules.
. Insert the fan module into the replacement chassis by aligning it with the opening, and then sliding it into the chassis.
. Push firmly on the fan module cam handle so that it is seated all the way into the chassis.
+
The cam handle raises slightly when the fan module is completely seated.

. Swing the cam handle up to its closed position, making sure that the cam handle release latch clicks into the locked position.
+
The fan LED should be green after the fan is seated and has spun up to operational speed.

. Repeat these steps for the remaining fan modules.

== Step 3: Replace a chassis from within the equipment rack or system cabinet

You must remove the existing chassis from the equipment rack or system cabinet before you can install the replacement chassis.

. Remove the screws from the chassis mount points.
. With two people, slide the old chassis off the rack rails in a system cabinet or equipment rack, and then set it aside.
. If you are not already grounded, properly ground yourself.
. Using two people, install the replacement chassis into the equipment rack or system cabinet by guiding the chassis onto the rack rails in a system cabinet or equipment rack.
. Slide the chassis all the way into the equipment rack or system cabinet.
. Secure the front of the chassis to the equipment rack or system cabinet, using the screws you removed from the old chassis.
. If you have not already done so, install the bezel.

== Step 4: Install the controller modules

After you install the controller modules into the new chassis, you must boot your system.

For HA pairs with two controller modules in the same chassis, the sequence in which you install the controller module is especially important because it attempts to reboot as soon as you completely seat it in the chassis.

. Align the end of the controller module with the opening in the chassis, and then gently push the controller module halfway into the system.
+
NOTE: Do not completely insert the controller module in the chassis until instructed to do so.

. Recable the console to the controller module, and then reconnect the management port.
. Plug the power cables into the power supplies and reinstall the power cable retainers.
. Complete the reinstallation of the controller module:
 .. Make sure the latch arms are locked in the extended position.
 .. Using the latch arms, push the controller module into the chassis bay until it stops.
 .. Press down and hold the orange tabs on top of the latching mechanism.
 .. Gently push the controller module into the chassis bay until it is flush with the edges of the chassis.
+
NOTE: The latching mechanism arms slide into the chassis.
+
The controller module begins to boot as soon as it is fully seated in the chassis.

 .. Release the latches to lock the controller module into place.
 .. Recable the power supply.
 .. If you have not already done so, reinstall the cable management device.
 .. Interrupt the normal boot process by pressing `Ctrl-C`.
. Repeat the preceding steps to install the second controller into the new chassis.
