---
permalink: a320/chassis-replace-overview.html
sidebar: sidebar
keywords: aff, a320, aff a320, replace, chassis, fan, controller, module, impair, model, shut, down, replacing, remove, move, equipment, rack, complete, replacement, process, replace the chassis, shut down the controllers when replacing a chassis, remove the controller modules, move the fans, replace a chassis from within the equipment rack or system cabinet, install the controller modules, complete the replacement process
summary: "You replace an impaired chassis the new chassis of the same model as the impaired chassis."
---
= Review requirements before replacing an AFF A320 chassis
:icons: font
:imagesdir: ../media/

[.lead]
Before replacing the chassis in your AFF A320 system, review the requirements for a successful replacement. The procedure moves all fans and controller modules from the impaired chassis to the replacement chassis and is disruptive.

All other components in the system must be functioning properly; if not, you must contact technical support.

* You can use this procedure with all versions of ONTAP supported by your system.
* This procedure is written with the assumption that you are moving the controller modules to the new chassis, and that the chassis is a new component from NetApp.
* This procedure is disruptive. For a two-node cluster, you will have a complete service outage and a partial outage in a multi-node cluster.
