---
permalink: a320/controller-replace-overview.html
sidebar: sidebar
keywords: aff, a320, aff a320, review, prerequisite, replacement, procedure, version, ontap, operating, system, replace, controller, module, replace the controller module
summary: You must review the prerequisites for the replacement procedure and select the correct one for your version of the ONTAP operating system.
---
= Review the requirements for replacing a controller in an AFF A320 system
:icons: font
:imagesdir: ../media/

[.lead]
Before replacing the controller in your AFF A320 system, review the prerequisites for the replacement procedure and select the correct one for your version of ONTAP.

include::../_include/console-logging-note.adoc[]

* All drive shelves must be working properly.
* The healthy controller must be able to take over the controller that is being replaced (referred to in this procedure as the "`impaired controller`").
* If your system is in a MetroCluster configuration, you must review the section https://docs.netapp.com/us-en/ontap-metrocluster/disaster-recovery/concept_choosing_the_correct_recovery_procedure_parent_concept.html[Choosing the correct recovery procedure] to determine whether you should use this procedure.
+
If this is the procedure you should use, note that the controller replacement procedure for a controller in a four or eight node MetroCluster configuration is the same as that in an HA pair. No MetroCluster-specific steps are required because the failure is restricted to an HA pair and storage failover commands can be used to provide nondisruptive operation during the replacement.

* You must replace the failed component with a replacement FRU component you received from your provider.
* You must be replacing a controller module with a controller module of the same model type. You cannot upgrade your system by just replacing the controller module.
* You cannot change any drives or drive shelves as part of this procedure.
* In this procedure, the boot device is moved from the impaired controller to the _replacement_ controller so that the _replacement_ controller will boot up in the same version of ONTAP as the old controller module.
* It is important that you apply the commands in these steps on the correct systems:
 ** The _impaired_ controller is the controller that is being replaced.
 ** The _replacement_ controller is the new controller that is replacing the impaired controller.
 ** The _healthy_ controller is the surviving controller.

