---
permalink: fas500f/overview.html
sidebar: sidebar
keywords: FAS500f specifications, FAS500f specs, NetApp FAS500f, FAS500f hardware
summary: Key specifications for the FAS500f storage system
---
= Key specifications for FAS500f
:icons: font
:imagesdir: ../media/

[.lead]
Review select specifications for the FAS500f storage system, reflective of a single high-availability pair. Visit https://hwu.netapp.com[NetApp Hardware Universe^] (HWU) for the complete list of FAS500f specifications. 

=== Key specifications for FAS500f

Platform Configuration: FAS500f Single Chassis HA Pair

Max Raw Capacity: 1.1016 PB

Memory: 128.0000 GB

Form Factor: 2U chassis with 2 HA controllers and 24 drive slots

PCIe Expansion Slots: 4

Minimum ONTAP Version: ONTAP 9.8RC1

=== Scaleout Maximums
|===
| Type | HA Pairs | Raw Capacity | Max Memory
| NAS | 12 | 13.2 PB / 11.7 PiB | 1536 GB
| SAN | 6 | 6.6 PB / 5.9 PiB | 768 GB
| HA Pair |  | 1.1 PB / 1.0 PiB | 128.0000
|===

=== IO

==== Onboard IO
|===
| Protocol | Ports
| Ethernet 25 Gbps | 4
| Ethernet 10 Gbps | 4
|===

==== Total IO
|===
| Protocol | Ports
| Ethernet 100 Gbps | 4
| Ethernet 25 Gbps | 20
| Ethernet 10 Gbps | 4
| FC 32 Gbps | 16
| NVMe/FC  32 Gbps | 16
|  | 0
| SAS 12 Gbps | 8
|===

==== Management Ports
|===
| Protocol | Ports
| Ethernet 1 Gbps | 2
| RS-232 115 Kbps | 4
| USB 12 Mbps | 4
|===

=== Storage Networking Supported
CIFS;
FC;
iSCSI;
NFS v3;
NFS v4.0;
NFS v4.1;
NFS v4.2;
NVMe/FC ;
NVMe/TCP;
S3;
S3 with NAS;
SMB 2.0;
SMB 2.1;
SMB 2.x;
SMB 3.0;
SMB 3.1;
SMB 3.1.1;

=== System Environment Specifications
* Typical Power: 2642 BTU/hr
* Worst-case Power: 3476 BTU/hr
* Weight: 54.3 lb 24.6 kg
* Height: 2U
* Width: 19" IEC rack-compliant (17.6" 44.7 cm)
* Depth: 21.38" (54.3 cm)
* Operating Temp/Altitude/Humidity: 10°C to 35°C (50°F to 95°F) at up to 3048m (10000 ft) elevation;8% to 80% relative humidity, noncondensing
* Non-operating Temp/Humidity: -40°C to 70°C (-40°F to 158°F) up to 12192m (40000 ft) 10% to 95%  relative humidity, noncondensing, in original container
* Acoustic Noise: Declared sound power (LwAd): 7.2; Sound pressure (LpAm) (bystander positions): 69.1 dB

=== Compliance
* Certifications EMC/EMI: AMCA,
FCC,
ICES,
KC,
Morocco,
VCCI
* Certifications safety: BIS,
CB,
CSA,
G_K_U-SoR,
IRAM,
NOM,
NRCS,
SONCAP,
TBS
* Certifications Safety/EMC/EMI: EAC,
UKRSEPRO
* Certifications Safety/EMC/EMI/RoHS: BSMI,
CE DoC,
UKCA DoC
* Standards EMC/EMI: BS-EN-55024,
BS-EN55035,
CISPR 32,
EN55022,
EN55024,
EN55032,
EN55035,
EN61000-3-2,
EN61000-3-3,
FCC Part 15 Class A,
ICES-003,
KS C 9832,
KS C 9835
* Standards Safety: ANSI/UL60950-1,
ANSI/UL62368-1,
BS-EN62368-1,
CAN/CSA C22.2 No. 60950-1,
CAN/CSA C22.2 No. 62368-1,
CNS 14336,
EN60825-1,
EN62368-1,
IEC 62368-1,
IEC60950-1,
IS 13252(part 1)

=== High Availability
Ethernet based baseboard management controller (BMC) and ONTAP management interface;
Redundant hot-swappable controllers;
Redundant hot-swappable power supplies;
SAS in-band management over SAS connections for external shelves;
// 2025-10-15 ontap-systems-internal/issues/1357

//2026-07-24 ontap-systems-internal/issues/1645
