---
permalink: a800/controller-replace-recable-reassign-disks.html
sidebar: sidebar
keywords: aff a800, how to recable the system, how to reassign disks
summary: You must recable the storage and confirm disk reassignment.
---
= Recable the system and reassign disks in an AFF A800 system
:icons: font
:imagesdir: ../media/

[.lead]
Recable your AFF A800 system after a controller replacement and reassign the disks to the replacement controller. If your system is in an HA pair, the giveback process automatically assigns the system ID to the disks; the exact steps depend on whether your system uses no encryption or Onboard Key Manager (OKM) encryption.

== Step 1: Recable the system

include::../_include/recable_system_after_controller_rep.adoc[]

== Step 2: Reassign disks

If the storage system is in an HA pair, the system ID of the new controller module is automatically assigned to the disks when the giveback occurs at the end of the procedure. You must confirm the system ID change when you boot the _replacement_ controller and then verify that the system applied the change.

This step applies only to systems running ONTAP in an HA pair.

include::../_include/800_controller_replace_recable_reassign_disks.adoc[]