---
permalink: asa-c800/maintain-overview.html
sidebar: sidebar
keywords: asa C800 maintenance, maintenance, repairing ASA C800, repairing asa C800, replace asa ASA C800 components, replace asa C800 components
summary: Maintain the ASA C800 hardware
---
= Maintain ASA C800 hardware
:icons: font
:imagesdir: ../media/

[.lead]
Maintain the hardware of your ASA C800 storage system to ensure long-term reliability and optimal performance. Perform regular maintenance tasks such as replacing faulty components, as this helps prevent downtime and data loss. 

The maintenance procedures assume that the ASA C800 storage system has already been deployed as a storage node in the ONTAP environment.

== System components
For the ASA C800 storage system, you can perform maintenance procedures on the following components.

[%rotate, grid="none", frame="none", cols="25,65"]

|===

a| link:bootmedia-replace-workflow-bmr.html[Boot media - automated recovery]

a|The boot media stores a primary and secondary set of ONTAP image files that the storage system uses to boot. During automated recovery, the system retrieves the boot image from the partner node and automatically runs the appropriate boot menu option to install the image on your replacement boot media. The automated boot media recovery process is supported only in ONTAP 9.17.1 and later. If your storage system is running an earlier version of ONTAP, use the link:bootmedia-replace-workflow.html[manual boot recovery procedure].

a| link:bootmedia-replace-workflow.html[Boot media - manual recovery]

a| The boot media stores a primary and secondary set of ONTAP image files that the storage system uses to boot the image from a USB drive and restore the configuration from the partner node. If your storage system is running ONTAP 9.17.1 and later, use the link:bootmedia-replace-workflow-bmr.html[automated boot recovery procedure].

a| link:chassis-replace-workflow.html[Chassis]


a| The chassis is the physical enclosure housing all the controller components such as the controller/CPU unit, power supply, and I/O.

a| link:controller-replace-workflow.html[Controller]

a| A controller consists of a board, firmware, and software. It controls the drives and implements the ONTAP functions.

a| link:dimm-replace.html[DIMM]

a| You must replace a DIMM (dual in-line memory module) when a memory mismatch is present, or you have a failed DIMM.

a| link:drive-replace.html[Drive]

a| A drive is a device that provides the physical storage media for data.

a| link:fan-replace.html[Fan]

a| The fan cools the controller.

a| link:nvdimm-replace.html[NVDIMM]

a| The NVDIMM (non-volatile dual in-line memory module) manages the data transfer from the volatile memory to the non-volatile storage, and maintains data integrity in the event of a power loss or system shutdown. 

a| link:nvdimm-battery-replace.html[NVDIMM battery]

a| A NVDIMM battery is responsible for maintaining power to the NVDIMM module.

a| link:pci-cards-and-risers-replace.html[PCIe card and risers]

a| A PCIe (peripheral component interconnect express) card is an expansion card that plugs into the PCIe slot on the motherboard or into risers plugged into the motherboard. 

a| link:power-supply-replace.html[Power supply]

a| A power supply provides a redundant power source in a controller shelf.

a| link:rtc-battery-replace.html[Real-time clock battery]

a| A real time clock battery preserves system date and time information if the power is off. 

|===