---
permalink: asa-r2-c30/io-module-overview.html
sidebar: sidebar
keywords: AFF c30, AFF c60, replace io module, add io module, hotswap io module
summary: The ASA C30 storage system offers flexibility in expanding or replacing I/O modules to enhance network connectivity and performance. Adding or replacing an I/O module is essential when upgrading network capabilities or addressing a failed module.
---
= Overview of add, hot-swap, and replace an I/O module - ASA C30
:icons: font
:imagesdir: ../media/

[.lead]
The ASA C30 storage system offers flexibility in expanding or replacing I/O modules to enhance network connectivity and performance. Adding, hot-swapping, or replacing an I/O module is essential when upgrading network capabilities or addressing a failed module.

* link:io-module-add.html[Add an I/O module]
+
Adding additional I/O modules can improve redundancy, helping to ensure that the storage system remains operational even if one I/O module fails.

* link:io-module-hotswap-ha-slot4.html[Hot-swap a cluster and HA I/O module]
+
Hot-swapping a failing cluster and HA I/O module can restore the storage system to its optimal operating state. Hot-swapping is done without having to shut down the impaired controller.
+
To use this procedure, your storage system must be running ONTAP 9.17.1 or later and meet specific system requirements.

* link:io-module-replace.html[Replace an I/O module]
+
Replacing a failing I/O module can restore the storage system to its optimal operating state. 
