---
permalink: a250/bootmedia-replace-requirements-bmr.html
sidebar: sidebar
keywords: a250, replace the boot media
summary: Before replacing the boot media in your AFF A250 system, verify that you meet the necessary requirements for a successful replacement.
---
= Review requirements for automated boot media recovery in an AFF A250 system
:icons: font
:imagesdir: ../media/

[.lead]
Before replacing the boot media in your AFF A250 system, verify that you meet the necessary requirements for a successful replacement. This includes confirming that you have the correct replacement boot media, confirming that the e0S (e0M wrench) port on the impaired controller isn't faulty, and determining whether Onboard Key Manager (OKM) or External Key Manager (EKM) is enabled.

The automated boot media recovery process is supported only in ONTAP 9.18.1 and later. If your storage system is running an earlier version of ONTAP, use the link:bootmedia-replace-workflow.html[manual boot recovery procedure].

include::../_include/bootmedia_replace_requirements_e0s_bmr.adoc[]

.What's next

After you've reviewed the boot media requirements, you link:bootmedia-shutdown-bmr.html[shut down the controller].
