---
permalink: fas8200/chassis-replace-overview.html
sidebar: sidebar
keywords: fas8200, replace the chassis
summary: "You replace an impaired chassis the new chassis of the same model as the impaired chassis."
---
= Review requirements before replacing your FAS8200 chassis
:icons: font
:imagesdir: ../media/

[.lead]
To replace the chassis, you must move the power supplies, fans, and controller modules from the impaired chassis to the new chassis, and swap out the impaired chassis from the equipment rack or system cabinet with the new chassis of the same model as the impaired chassis.

All other components in the system must be functioning properly. If they aren't, contact technical support.

* You can use this procedure with all versions of ONTAP supported by your system.
* This procedure is written with the assumption that you are moving the controller module or modules to the new chassis, and that the chassis is a new component from NetApp.
* This procedure is disruptive. For a two-controller cluster, you have a complete service outage and a partial outage in a multi-node cluster.
