---
permalink: fas8200/chassis-replace-overview.html
sidebar: sidebar
keywords: fas8200, replace the chassis
summary: "Before replacing the chassis in a FAS8200 system, verify that all other components are functioning properly and that the replacement chassis is a new component from NetApp of the same model. The procedure requires moving the power supplies, fans, and controller modules to the new chassis and is disruptive, causing a complete service outage in a two-controller cluster or a partial outage in a multi-node cluster."
---
= Review the requirements for replacing a chassis in a FAS8200 system
:icons: font
:imagesdir: ../media/

[.lead]
Before replacing the chassis in a FAS8200 system, verify that all other components are functioning properly and that the replacement chassis is a new component from NetApp of the same model. The procedure requires moving the power supplies, fans, and controller modules to the new chassis and is disruptive, causing a complete service outage in a two-controller cluster or a partial outage in a multi-node cluster.

All other components in the system must be functioning properly. If they aren't, contact technical support.

* You can use this procedure with all versions of ONTAP supported by your system.
* This procedure is written with the assumption that you are moving the controller module or modules to the new chassis, and that the chassis is a new component from NetApp.
* This procedure is disruptive. For a two-controller cluster, you have a complete service outage and a partial outage in a multi-node cluster.
