---
permalink: fas8200/maintain-overview.html
sidebar: sidebar
keywords: fas8200 maintenance, maintenance, repairing fas8200, replace fas8200 components
summary: "You can perform maintenance procedures on FAS8200 storage system components, including the boot media, chassis, controller, DIMMs, and power supply."
---
= Learn about maintaining a FAS8200 storage system
:icons: font
:imagesdir: ../media/

[.lead]
You can perform maintenance procedures on FAS8200 storage system components, including the boot media, chassis, controller, DIMMs, and power supply.

== Boot media

The boot media stores a primary and secondary set of boot image files that the system uses when it boots. 

== Caching module

You must replace the controller's caching module when your system registers a single AutoSupport (ASUP) message that the module has gone offline.

== Chassis
The chassis is the physical enclosure housing all the controller components such as the controller/CPU unit, power supply, and I/O.

== Controller

A controller consists of a board, firmware, and software. It controls the drives and implements the ONTAP functions.

== DIMM

You must replace a DIMM (dual in-line memory module) when a memory mismatch is present, or you have a failed DIMM.

== Drive

A drive is a device that provides the physical storage media for data.

== NVMEM battery

A battery is included with a controller and preserves cached data if the AC power fails.

== PCIe card

A PCIe (peripheral component interconnect express) card is an expansion card that plugs into the PCIe slot on the motherboard.

== Power supply

A power supply provides a redundant power source in a controller shelf.

== Real time clock battery
A real time clock battery preserves system date and time information if the power is off. 