---
permalink: afx-1k/io-module-overview.html
sidebar: sidebar
keywords: afx 1k, replace io module
summary: The AFX 1K system offers flexibility in expanding or replacing I/O modules to enhance network connectivity and performance. Adding or replacing an I/O module is essential when upgrading network capabilities or addressing a failed module.
---
= Overview of add and replace I/O module - AFX 1K
:icons: font
:imagesdir: ../media/

[.lead]
The AFX 1K system offers flexibility in expanding or replacing I/O modules to enhance network connectivity and performance. Adding or replacing an I/O module is essential when upgrading network capabilities or addressing a failed module.

You can replace a failed I/O module in your AFX 1K storage system with the same type of I/O module, or with a different kind of I/O module. You can also add an I/O module into a system with empty slots.

* link:io-module-add.html[Add an I/O module]
+
Adding additional modules can improve redundancy, helping to ensure that the system remains operational even if one module fails.

* link:io-module-replace.html[Replace an I/O module]
+
Replacing a failing I/O module can restore the system to its optimal operating state. 

.I/O slot numbering

The I/O slots on the AFX 1K controller are numbered 1 through 11, as shown in the following illustration.

image::../media/drw_a1K_back_slots_labeled_ieops-2162.svg[Slot numbering on an AFX 1K controller]