---
permalink: asa150/bootmedia-encryption-preshutdown-checks.html
sidebar: sidebar
keywords: asa a150, a150, asa, shutdown, checks, onboard, encryption, keys, impaired controller, disable, automatic, feedback
summary: 'Prior to shutting down the impaired controller and checking the status of the onboard encryption keys, you must check the status of the impaired controller, disable automatic giveback, and check what version of ONTAP the system is running.'
---
= Check encryption key support and status - ASA A150
:icons: font
:imagesdir: ../media/

[.lead]
To ensure data security on your storage system, you need to verify the encryption key support and status on your boot media. Check if your ONTAP version supports NetApp Volume Encryption (NVE), and before you shut down the controller check if the key manager is active.

== Step 1: Check NVE support and download the correct ONTAP image

Determine whether your ONTAP version supports NetApp Volume Encryption (NVE) so you can download the correct ONTAP image for the boot media replacement.

include::../_include/encryption_check_bootmedia.adoc[]

== Step 2: Verify key manager status and back up configuration

Before shutting down the impaired controller, verify the key manager configuration and back up the necessary information.

include::../_include/encryption_key_mgr_bootmedia.adoc[]
//2025-11-25 ontap-systems-internal/1315 and ontap-systems-internal/1380
