---
permalink: asa150/install-videos.html
sidebar: sidebar
keywords: asa a150, a150, asa, asa a220, video, rack, cable, system, manager, guided, setup, configuration
summary: "There are two videos; one showing how to rack and cable your system and one showing an example of using the System Manager Guided Setup to perform initial system configuration."
---
= Video steps - ASA A150
:icons: font
:imagesdir: ../media/

[.lead]
Use the following videos to learn how to rack and cable your system and perform initial system configuration.

If you have a MetroCluster configuration, use the https://docs.netapp.com/us-en/ontap-metrocluster/index.html[MetroCluster documentation^].

*Warning:* If your system is being installed with ONTAP 9.13.1P8 - 9.13.1P11, ONTAP 9.14.1P1 - 9.14.1P7 or ONTAP 9.15.1 - 9.15.1P2 and your system contains 10 or more internal solid-state drives, you must take additional steps to prepare the system for installation. See issue  https://mysupport.netapp.com/site/bugs-online/product/ONTAP/JiraNgage/CONTAP-285173[CONTAP-285173 - ADP does not leave a spare root partition on an AFF A150 with 10 or more internal drives^].

Hardware installation and cabling::

The following video shows how to install and cable your system.

video::561d941a-f387-4eb9-a10a-afb30029eb36[panopto, title="Animation - Install and setup of an AFF A150"]

NOTE: The ASA A150 uses the same installation procedure as the AFF A150 system.
