---
permalink: fas50/maintain-overview.html
sidebar: sidebar
keywords: aff a20 aff a30 aff a50 maintenance, maintenance, repairing a20 aff a30 aff a50, replace a20 aff a30 aff a50 components
summary: Maintain the hardware of your FAS50 storage systems to ensure long-term reliability and optimal performance. Perform regular maintenance tasks such as replacing faulty components, as this helps prevent downtime and data loss.
---
= Overview of hardware maintenance -  FAS50
:icons: font
:imagesdir: ../media/

[.lead]
Maintain the hardware of your FAS50 storage system to ensure long-term reliability and optimal performance. Perform regular maintenance tasks such as replacing faulty components, as this helps prevent downtime and data loss.

The maintenance procedures assume that the FAS50 storage system has already been deployed as a storage node in the ONTAP environment.

== System components
For the FAS50 storage systems, you can perform maintenance procedures on the following components.

[%rotate, grid="none", frame="none", cols="25,65"]

|===

a| link:bootmedia-replace-workflow-bmr.html[Boot media - automated recovery]

a| The boot media stores a primary and secondary set of ONTAP image files that the storage system uses to boot the image from the partner node and automatically run the appropriate boot menu option to install the boot image on your replacement boot media. The automated boot media recovery process is supported only in ONTAP 9.17.1 and later. If your storage system is running an earlier version of ONTAP, use the link:bootmedia-replace-workflow.html[manual boot recovery procedure].

a| link:bootmedia-replace-workflow.html[Boot media- manual recovery]

a| The boot media stores a primary and secondary set of ONTAP image files that the storage system uses to boot the image from a USB drive and restore the configuration from the partner node.

a| link:caching-module-hot-swap.html[Caching module]

a| A caching module (Flash Cache module) utilizes high-speed SSDs to store frequently accessed data for quicker retrieval.

a| link:chassis-replace-workflow.html[Chassis]

a| The chassis is the physical enclosure housing all the controller components such as the controller/CPU unit, power supply, and I/O.

a| link:controller-replace-workflow.html[Controller]

a| A controller consists of a board, firmware, and software. It controls the drives and runs the ONTAP operating system software.

a| link:dimm-replace.html[DIMM]

a| A dual in-line memory module (DIMM) is a type of computer memory. They are installed to add system memory to a controller motherboard.

a| link:fan-replace.html[Fan]

a| A fan cools the controller and drives.

a| link:io-module-overview.html[I/O module]

a| The I/O module (Input/Output module) is a hardware component that acts as an intermediary between the controller and various devices or systems that need to exchange data with the controller.

a| link:nvdimm-battery-replace.html[NV battery]

a| The non-volatile memory (NV) battery is responsible for providing power to the NVMEM components while data in-flight is being destaged to flash memory after a power loss.


a| link:power-supply-replace.html[Power supply]

a| A power supply provides a redundant power source in a controller.

a| link:rtc-battery-replace.html[Real-time clock battery]

a| A real-time clock battery preserves system date and time information if the power is off.
|===
