---
permalink: fas9500/maintain-overview.html
sidebar: sidebar
keywords: FAS9500 maintenance, maintenance, repairing FAS9500, repairing aff FAS9500, replace FAS9500 components, replace FAS9500 components
summary: Maintain the ASA FAS9500 hardware
---
= Maintain FAS9500 hardware
:icons: font
:imagesdir: ../media/

[.lead]
Maintain the hardware of your FAS9500 storage system to ensure long-term reliability and optimal performance. Perform regular maintenance tasks such as replacing faulty components, as this helps prevent downtime and data loss. 

The maintenance procedures assume that the FAS9500 storage system has already been deployed as a storage node in the ONTAP environment.

== System components
For the FAS9500 storage system, you can perform maintenance procedures on the following components.

[%rotate, grid="none", frame="none", cols="25,65"]

|===

a| link:bootmedia-replace-workflow-bmr.html[Boot media - automated recovery]

a|The boot media stores a primary and secondary set of ONTAP image files that the storage system uses to boot. During automated recovery, the system retrieves the boot image from the partner node and automatically runs the appropriate boot menu option to install the image on your replacement boot media. The automated boot media recovery process is supported only in ONTAP 9.17.1 and later. If your storage system is running an earlier version of ONTAP, use the link:bootmedia-replace-workflow.html[manual boot recovery procedure].

a| link:bootmedia-replace-workflow.html[Boot media- manual recovery]

a| The boot media stores a primary and secondary set of ONTAP image files that the storage system uses to boot the image from a USB drive and restore the configuration from the partner node. If your storage system is running ONTAP 9.17.1 and later, use the link:bootmedia-replace-workflow-bmr.html[automated boot recovery procedure]. 

a|link:caching_module_hotswap[Caching module]

a| You must replace the controller’s caching module when your system registers a single AutoSupport (ASUP) message that the module has gone offline.

a| link:chassis-replace-workflow.html[Chassis]


a| The chassis is the physical enclosure housing all the controller components such as the controller/CPU unit, power supply, and I/O.

a| link:controller-replace-workflow.html[Controller]

a| A controller consists of a board, firmware, and software. It controls the drives and implements the ONTAP functions.

a| link:dimm-replace.html[DIMM]

a| You must replace a DIMM (dual in-line memory module) when a memory mismatch is present, or you have a failed DIMM.

a|
link:dcpm-nvram11-battery-replace[DCPM]

a| The DCPM (destage controller power module) contains the NVRAM11 battery.

a| link:fan-replace.html[Fan]

a| The fan cools the controller.

a|link:pci_cards_and_risers_replace[I/O module] 

a| The  I/O module (Input/Output module) is a hardware component that acts as an intermediary between the controller and various devices or systems that need to exchange data with the controller.

a|link:led_module_replace[LED USB] 

a| The LED USB module provides connectivity to console ports and system status. 

a|link:nvram_module_or_nvram_dimm_replacement[NVRAM] 

a| The NVRAM module (Non-Volatile Random Access Memory) allows the controller to retain data across power cycles or system reboots, while the NVRAM DIMM maintaints NVRAM settings.

a| link:power-supply-replace[Power supply] 

a| A power supply provides a redundant power source in a controller.

a|link:rtc-battery-replace[Real-time clock battery]

a| A real time clock battery preserves system date and time information if the power is off. 

|===