---
permalink: fas2800/chassis-replace-overview.html
sidebar: sidebar
keywords: fas2820, replace, chassis, shut down, controller, metrocluster, power, supply, ha, state, controller, configuration, switch, aggregates, replace, move, remove, swap
summary: "To replace the chassis in your FAS2820 system, you must move the power supplies, hard drives, and controller module or modules from the impaired chassis to the new chassis of the same model."
---
= Review requirements before replacing the chassis in your FAS2820 system
:icons: font
:imagesdir: ../media/

[.lead]
To replace the chassis in your FAS2820 system, move the power supplies, hard drives, and controller modules from the impaired chassis to the new chassis. Then, swap the impaired chassis out of the equipment rack or system cabinet and install the new chassis of the same model in its place.

All other components in the system must be functioning properly. If they aren't, contact technical support.

* You can use this procedure with all versions of ONTAP supported by your system.
* This procedure is written with the assumption that you are moving all drives and controller module or modules to the new chassis, and that the chassis is a new component from NetApp.
* This procedure is disruptive. For a two-controller cluster, this procedure causes a complete service outage and a partial outage in a multi-node cluster.
