---
permalink: fas2800/maintain-overview.html
sidebar: sidebar
keywords: fas2800 maintenance, maintenance, repairing, repairing fas2700, replace fas2800 components, replace fas2800 components
summary: Maintain the FAS2820 hardware
---
= Maintain FAS2820 hardware
:icons: font
:imagesdir: ../media/

[.lead]
Maintain the hardware of your FAS2820 storage system to ensure long-term reliability and optimal performance. Perform regular maintenance tasks such as replacing faulty components, as this helps prevent downtime and data loss. 

The maintenance procedures assume that the FAS2820 storage system has already been deployed as a storage node in the ONTAP environment.

== System components
For the FAS2820 storage system, you can perform maintenance procedures on the following components.

[%rotate, grid="none", frame="none", cols="25,65"]

|===

a| link:bootmedia-replace-workflow-bmr.html[Boot media - automated recovery]

a| The boot media stores a primary and secondary set of ONTAP image files that the storage system uses to boot. During automated recovery, the system retrieves the boot image from the partner node and automatically runs the appropriate boot menu option to install the image on your replacement boot media. The automated boot media recovery process is supported only in ONTAP 9.17.1 and later. If your storage system is running an earlier version of ONTAP, use the link:bootmedia-replace-workflow.html[manual boot recovery procedure].

a| link:bootmedia-replace-workflow.html[Boot media- manual recovery]

a| The boot media stores a primary and secondary set of ONTAP image files that the storage system uses to boot the image from a USB drive and restore the configuration from the partner node. If your storage system is running ONTAP 9.17.1 and later, use the link:bootmedia-replace-workflow-bmr.html[automated boot recovery procedure]. 

a| link:caching=module-replace[Caching module] 

a| You must replace the controller’s caching module when your system registers a single AutoSupport (ASUP) message that the module has gone offline.

a| link:chassis-replace-workflow.html[Chassis]


a| The chassis is the physical enclosure housing all the controller components such as the controller/CPU unit, power supply, and I/O.

a| link:controller-replace-workflow.html[Controller]

a| A controller consists of a board, firmware, and software. It controls the drives and implements the ONTAP functions.

a| link:dimm-replace.html[DIMM]

a| You must replace a DIMM (dual in-line memory module) when a memory mismatch is present, or you have a failed DIMM.

a| link:drive-replace[Drive] 

a| A drive is a device that provides the physical storage media for data.

a| link:nvmem-nvram-battery-replace[NVMEM battery] 

a| A battery is included with the controller and preserves cached data if the AC power fails.

a| link:pcie-cards-and-risers-replace[Mezzanine card]

a| A Mezzanine card is an expansion card that is designed to be inserted into a specialized slot on the motherboard and holds the card I/O cards.

a| link:power-supply-replace[Power supply] 

a| A power supply provides a redundant power source in a controller.

a| link:rtc-battery-replace[Real-time clock battery]

a| A real time clock battery preserves system date and time information if the power is off. 

|===