---
permalink: fas2800/power-supply-swap-out.html
sidebar: sidebar
keywords: fas2820, swap, power, supply, turn off, disconnect, remove, install, connect, turn on, replacement
summary: "Hot-swapping a power supply unit in your FAS2820 system involves turning off, disconnecting, and removing the impaired power supply, and installing, connecting, and turning on the replacement power supply."
---
= Hot-swap a power supply unit in a FAS2820 system
:icons: font
:imagesdir: ../media/

[.lead]
Hot-swap a power supply unit in your FAS2820 system if it fails or degrades, without interrupting system operation. This procedure involves turning off and removing the impaired power supply, then installing and powering on the replacement.

If any other components in the system aren't functioning properly, contact technical support.

* The power supplies are redundant and hot-swappable.
* This procedure is written for replacing one power supply at a time.
+
NOTE: Replace the power supply within two minutes of removing it from the chassis. The system continues to function, but ONTAP sends messages to the console about the degraded power supply until the power supply is replaced.  

* Power supplies are auto-ranging.

video::0631b48a-ad6f-4433-a2bd-af54014778c2[panopto, title="Animation - Replace power supply"]


.Steps

. Identify the power supply you want to replace, based on console error messages or through the LEDs on the power supplies.
. If you are not already grounded, properly ground yourself.
. Turn off the power supply and disconnect the power cables:
 .. Turn off the power switch on the power supply.
 .. Open the power cable retainer, and then unplug the power cable from the power supply.
 .. Unplug the power cable from the power source.
. Squeeze the latch on the power supply cam handle, and then open the cam handle to fully release the power supply from the mid plane.
+
image::../media/drw_2850_replace_PSU_IEOPS-702.svg[Replace a PSU]
+
. Use the cam handle to slide the power supply out of the system.
+
CAUTION: When removing a power supply, always use two hands to support its weight.
+

. Make sure that the on/off switch of the new power supply is in the Off position.
. Support and align the edges of the power supply with the opening in the system chassis using both hands, and then gently push the power supply into the chassis using the cam handle.
+
The power supplies are keyed and can only be installed one way.
+
NOTE: Do not use excessive force when sliding the power supply into the system. You can damage the connector.

. Close the cam handle so that the latch clicks into the locked position and the power supply is fully seated.
. Reconnect the power supply cabling:
 .. Reconnect the power cable to the power supply and the power source.
 .. Secure the power cable to the power supply using the power cable retainer.

+
After power is restored to the power supply, the status LED should be green.
. Turn on the power to the new power supply, and then verify the operation of the power supply activity LEDs.
+
The power supply LEDs are lit when the power supply comes online.

include::../_include/complete_rma_step.adoc[]
