---
permalink: asa250/bootmedia-replace-bmr.html
sidebar: sidebar
keywords: asa a250, replace the boot media
summary: The boot media in your ASA A250 system stores essential firmware and configuration data. The replacement process involves removing the controller module, removing the impaired boot media, installing the replacement boot media in the controller module, and then reinstalling the controller module.
---
= Replace the boot media for automated boot recovery - ASA A250
:icons: font
:imagesdir: ../media/

[.lead]
The boot media in your ASA A250 system stores essential firmware and configuration data. The replacement process involves removing and opening the controller module, removing the impaired boot media, installing the replacement boot media in the controller module, and then reinstalling the controller module.

The automated boot media recovery process is supported only in ONTAP 9.18.1 and later. If your storage system is running an earlier version of ONTAP, use the link:bootmedia-replace-overview.html[manual boot recovery procedure].

include::../_include/250_bootmedia-replace-bmr.adoc[]

.What's next
After physically replacing the impaired boot media, link:bootmedia-recovery-image-boot-bmr.html[restore the ONTAP image from the partner node].
