---
permalink: c30-60/bootmedia-replace-requirements-bmr.html
sidebar: sidebar
keywords: aff c30, aff c60, replace the boot media
summary: Before replacing the boot media in your AFF C30 or AFF C60 storage system, ensure you meet the necessary requirements for a successful replacement.
---
= Requirements for automatic boot media recovery - AFF C30 and AFF C60
:icons: font
:imagesdir: ../media/

[.lead]
Before replacing the boot media in your AFF C30 or AFF C60 storage system, ensure you meet the necessary requirements for a successful replacement. This includes verifying that you have the correct replacement boot media, confirming that the e0S (e0M wrench) port on the impaired controller is not faulty, and determining whether Onboard Key Manager (OKM) or External Key Manager (EKM) is enabled.

The automated boot media recovery process is supported only in ONTAP 9.17.1 and later. If your storage system is running an earlier version of ONTAP, use the link:bootmedia-replace-workflow.html[manual boot recovery procedure].

include::../_include/g_bootmedia_replace_requirements_eos_bmr.adoc[]

.What's next

After you've reviewed the boot media requirements, you link:bootmedia-shutdown-bmr.html[shut down the controller].
