---
permalink: c30-60/io-module-overview.html
sidebar: sidebar
keywords: AFF c30, AFF c60, replace io module, add io module, hotswap io module
summary: The AFF C30 and AFF C60 storage systems offer flexibility in expanding or replacing I/O modules to enhance network connectivity and performance. Adding, hot-swapping, or replacing an I/O module is essential when upgrading network capabilities or addressing a failed module.
---
= Learn about adding and replacing I/O modules in your AFF C30 or AFF C60 storage system
:icons: font
:imagesdir: ../media/

[.lead]
The AFF C30 and AFF C60 storage systems offer flexibility in expanding or replacing I/O modules to enhance network connectivity and performance. Adding, hot-swapping, or replacing an I/O module is essential when upgrading network capabilities or addressing a failed module.

You can replace a failed I/O module in your storage system with the same type of I/O module, or with a different type of I/O module. You can hot-swap a cluster and HA I/O module when your storage system meets specific requirements. You can also add an I/O module to a storage system with available slots.

* link:io-module-add.html[Add an I/O module]
+
Adding additional I/O modules can improve redundancy, helping to ensure that the storage system remains operational even if one I/O module fails.

* link:io-module-hotswap.html[Hot-swap an I/O module]
+
You can hot-swap certain I/O modules for an equivalent I/O module to restore the storage system to its optimal operating state. Hot-swapping is done without having to perform a manual takeover.
+
To use this procedure, your storage system must be running ONTAP 9.17.1 or later and meet specific system requirements.

* link:io-module-replace.html[Replace an I/O module]
+
Replacing a failing I/O module can restore the storage system to its optimal operating state. 
