---
permalink: c30-60/io-module-add.html
sidebar: sidebar
keywords: aff c30, aff c60, add I/O module
summary: "To replace an I/O module, you must disconnect the cables from the module, remove the SFP and QSFP modules from the module, remove the module, install the replacement module, reinstall the SFP and QSFP modules, and then cable the I/O module."
---
= Add I/O module - AFF C30 and AFF C60
:icons: font
:imagesdir: ../media/

[.lead]
You can add an I/O module to your AFF C30 and AFF C60 storage systems when there are slots available or when all slots are fully populated.

.About this task

If needed, you can turn on the storage system location (blue) LEDs to aid in physically locating the affected storage system. Log into the BMC using SSH and enter the `system location-led _on_` command.

A storage system has three location LEDs: one on the operator display panel and one on each controller. Location LEDs remain illuminated for 30 minutes. 

You can turn them off by entering the `system location-led _off_` command. If you are unsure if the LEDs are on or off, you can check their state by entering the `system location-led show` command.

== Step 1: Shut down the impaired controller module

//[role="tabbed-block"]
//====

//.Option 1: Most systems
//--
include::../_include/shutdown_most_frus_no_PCM_remove.adoc[]
//--
//.Option 2: MetroCluster configuration
//--
//include::../_include/shutdown_any_mcc_supported_no_PCM_remove.adoc[]
//--
//
//====


== Step 2: Add the new I/O module

include::../_include/add_io_module_thumb.adoc[]
