---
permalink: c30-60/nvdimm-battery-replace.html
sidebar: sidebar
keywords: aff c30, aff c60, replace the NV battery, NV battery
summary: Replace the NV battery in your AFF C30 or AFF C60 storage system when the battery begins to lose charge or fails, as it is responsible for preserving critical system data during power outages. The replacement process involves shutting down the impaired controller, removing the controller module, replacing the NV battery, reinstalling the controller module, and returning the failed part to NetApp.
---
= Replace the NV battery - AFF C30 and AFF C60
:icons: font
:imagesdir: ../media/

[.lead]
Replace the NV battery in your AFF C30 or AFF C60 storage system when the battery begins to lose charge or fails, as it is responsible for preserving critical system data during power outages. The replacement process involves shutting down the impaired controller, removing the controller module, replacing the NV battery, reinstalling the controller module, and returning the failed part to NetApp.

.Before you begin
All other components in the storage system must be functioning properly; if not, contact https://mysupport.netapp.com/site/global/dashboard[NetApp Support] before continuing with this procedure.

.About this task
If needed, you can turn on the storage system location (blue) LEDs to aid in physically locating the affected storage system. Log into the BMC using SSH and enter the `system location-led _on_` command.

A storage system has three location LEDs: one on the operator display panel and one on each controller. Location LEDs remain illuminated for 30 minutes. 

You can turn them off by entering the `system location-led _off_` command. If you are unsure if the LEDs are on or off, you can check their state by entering the `system location-led show` command.

== Step 1: Shut down the impaired controller

Shut down or take over the impaired controller using one of the following options.

[role="tabbed-block"]
====

.Option 1: Most systems
--
include::../_include/shutdown_most_frus.adoc[]
--
.Option 2: Controller is in a MetroCluster
--
include::../_include/shutdown_any_mcc_no_2-node_mcc.adoc[]
--

====

== Step 2: Remove the controller

include::../_include/g_controller_remove.adoc[]

. Open the controller cover by turning the thumbscrew counterclockwise to loosen, and then open the cover.

== Step 3: Replace the NV battery

include::../_include/g_nvdimm_battery_replace.adoc[]


== Step 4: Reinstall the controller

Reinstall the controller into the chassis and reboot it.

include::../_include/g_controller_reinstall.adoc[]


== Step 5: Return the failed part to NetApp

include::../_include/complete_rma.adoc[]


