---
permalink: c30-60/rtc-battery-replace.html
sidebar: sidebar
keywords: aff c30, aff c60, replace the real-time clock battery
summary: Replace the real-time clock (RTC) battery, commonly known as a coin cell battery, in your AFF C30 or AFF C60 system to ensure that services and applications relying on accurate time synchronization remain operational.
---
= Replace the real-time clock battery - AFF C30 and AFF C60
:icons: font
:imagesdir: ../media/

[.lead]
Replace the real-time clock (RTC) battery, commonly known as a coin cell battery, in your AFF C30 or AFF C60 system to ensure that services and applications relying on accurate time synchronization remain operational.

.Before you begin
All other components in the storage system must be functioning properly; if not, contact https://mysupport.netapp.com/site/global/dashboard[NetApp Support] before continuing with this procedure.

.About this task
* You can use this procedure with all versions of ONTAP supported by your storage system.
* If needed, you can turn on the storage system location (blue) LEDs to aid in physically locating the affected storage system. Log into the BMC using SSH and enter the `system location-led _on_` command.
+
A storage system has three location LEDs: one on the operator display panel and one on each controller. Location LEDs remain illuminated for 30 minutes. 
+
You can turn them off by entering the `system location-led _off_` command. If you are unsure if the LEDs are on or off, you can check their state by entering the `system location-led show` command.

== Step 1: Shut down the impaired controller

Shut down or take over the impaired controller using one of the following options.

[role="tabbed-block"]
====

.Option 1: Most systems
--
include::../_include/shutdown_most_frus.adoc[]
--
.Option 2: Controller is in a MetroCluster
--
include::../_include/shutdown_any_mcc_no_2-node_mcc.adoc[]
--

====
== Step 2: Remove the controller

include::../_include/g_controller_remove.adoc[]

. Open the controller cover by turning the thumbscrew counterclockwise to loosen, and then open the cover.
 
== Step 3: Replace the RTC battery

include::../_include/g_rtc_battery_replace.adoc[]


== Step 4: Reinstall the controller

Reinstall the controller into the chassis and reboot it.

include::../_include/g_controller_reinstall.adoc[]

== Step 5: Reset the time and date on the controller

NOTE: After replacing the RTC battery, inserting the controller and powering on first BIOS reset, you will see the following error messages: 
`RTC date/time error. Reset date/time to default`
`RTC power failure error`
These messages are expected and you can continue with this procedure.

. On the healthy controller, check the date and time:
+
`cluster date show`
+
NOTE: If your storage system stops at the boot menu, select the option for  `Reboot node` and respond _y_ when prompted, then boot to LOADER by pressing _Ctrl-C_.
+
. On the impaired controller, at the LOADER prompt, check the time and date: 
+
`cluster date show`

.. If necessary, modify the date: 
+
`set date _mm/dd/yyyy_`

.. If necessary, set the time, in GMT: 
+
`set time hh:mm:ss`

.. Confirm the date and time.
. At the LOADER prompt, enter `bye` to reinitialize the I/O modules, other components, and let the controller reboot.

== Step 6: Return the failed part to NetApp

include::../_include/complete_rma.adoc[]
