---
permalink: a20-30-50/bootmedia-overview.html
sidebar: sidebar
keywords: aff a20, aff a30, aff a50, overview, the boot media
summary: Learn about the automated method and the manual method for replacing the boot media.
---
= Overview of replacing the boot media - AFF A20, AFF A30, and AFF A50
:icons: font
:imagesdir: ../media/

[.lead]

You can replace a failed boot media manually by using USB module for the boot image or through the automated boot media recovery (BMR) option.

* link:bootmedia-replace-workflow-bmr.html[Automated boot media recovery]
+
Automated boot media recovery uses the boot image from the partned node and automatically runs the appropriate boot menu option to install the boot image to the replacement boot media.

* link:bootmedia-replace-workflow.html[Manual boot media replace]
+
Manual boot media replace uses the traditional method of downloading the ONTAP image from the NetApp support site, transferring the image to a USB drive, downloading it to the target replacement boot media, and manually walking through the boot menu options to install the ONTAP image on the replacement boot media. 
