---
permalink: a20-30-50/bootmedia-replace-bmr.html
sidebar: sidebar
keywords: aff a20, aff a30, aff a50, replace the boot media
summary: The boot media in your AFF A20, AFF A30, or AFF A50 storage system stores essential firmware and configuration data. The replacement process involves removing the controller module, removing the impaired boot media, installing the replacement boot media, and then reinstalling the controller module.
---
= Replace the boot media for automatic boot recovery - AFF A20, AFF A30, and AFF A50
:icons: font
:imagesdir: ../media/

[.lead]
The boot media in your AFF A20, AFF A30, or AFF A50 storage system stores essential firmware and configuration data. The replacement process involves removing the controller module, removing the impaired boot media, installing the replacement boot media, and then reinstalling the controller module.

The automatic boot media recovery process is supported only in ONTAP 9.17.1 and later. If your storage system is running an earlier version of ONTAP, use the link:bootmedia-replace-workflow.html[manual boot recovery procedure].

include::../_include/g_bootmedia_replace-bmr.adoc[]

.What's next
After physically replacing the impaired boot media, link:bootmedia-recovery-image-boot-bmr.html[restore the ONTAP image from the partner node].