---
permalink: a20-30-50/bootmedia-recovery-image-boot-bmr.html
sidebar: sidebar
keywords: aff a20, aff a30, aff a50, boot the recovery image
summary: You can restore image on the boot media from the partner controller through the automated boot recovery process.  
---
= Automated boot recovery  - AFF A20, AFF A30, and AFF A50
:icons: font
:imagesdir: ../media/

[.lead]
You can restore the ONTAP image (boot media recovery) from the partner node using the `boot_recovery -partner` with ASA r2 systems running ONTAP 9.16.0 and later.

.Before you begin

When you boot a node and the boot media on that node is corrupted, you'll see the following messages and the boot process with stop at the LOADER prompt:

....

Can't find primary boot device u0a.0
Can't find backup boot device u0a.1
ACPI RSDP Found at 0x777fe014
 
 
Starting AUTOBOOT press Ctrl-C to abort...
Could not load fat://boot0/X86_64/freebsd/image1/kernel:Device not found
 
ERROR: Error booting OS on: 'boot0' file: fat://boot0/X86_64/Linux/image1/vmlinuz (boot0,fat)
 
 
ERROR: Error booting OS on: 'boot0' file: fat://boot0/X86_64/freebsd/image1/kernel (boot0,fat)
 
 
Autoboot of PRIMARY image failed. Device not found (-6)
LOADER-A>

....

If you see this message, you must restore the ONTAP image


Select the single node automated recovery option that matches your configuration.

[role="tabbed-block"]
====

.Option 1: Recovery with no encryption
--
include::../_include/bmr_single_node_no_encrypt.adoc[]
--
.Option 2: Recovery with Onboard Key Manager present
--
include::../_include/bmr_single_node_okm.adoc[]
--
.Option 3: Recovery with External Key Manager present
--
include::../_include/bmr_single_node_ekm.adoc[]
--

====