---
permalink: a20-30-50/install-cable.html
sidebar: sidebar
keywords: aff a20, aff a30, aff a50, prepare installation
summary: Management network ports on the controllers are connected to switches. The HA interconnect and cluster interconnect ports are cabled on both controllers. The controller modules are connected to external storage, if ordered.
---
= Cable the hardware - AFF A20, AFF A30, and AFF A50
:icons: font
:imagesdir: ../media/

[.lead]
After you install your AFF A20, AFF A30, or AFF A50 storage system hardware, cable the controllers to the network and shelves.

.About this task
The cabling graphics have arrow icons showing the proper orientation of the cable connector pull-tab when inserting a connector into a port.

image::../media/drw_cable_pull_tab_direction_ieops-1699.svg[Cable pull tab orientation example]

* As you insert the connector, you should feel it click into place; if you do not feel it click, remove it, turn it over and try again.
* If cabling to an optical switch, insert the small form-factor pluggable (SFP) transceiver into the controller port before the switch port.


== Step 1: Cable the controllers to your network
Cable the controllers to your host network.

.Before you begin

Contact your network administrator for information about connecting the storage system to the switches.

.About this task
These procedures show common configurations. Keep in mind that the specific cabling depends on the components ordered for your storage system. For comprehensive configuration and slot priority details, see link:https://hwu.netapp.com[NetApp Hardware Universe^].

[role="tabbed-block"]
====

.Option 1: Cable the controllers to a switchless ONTAP cluster
--
Cable the controllers to each other to create the ONTAP cluster connections, and then cable the Ethernet ports on each controller to your host network.

.Steps

. Cable the Cluster/HA interconnect connections: 
+
NOTE: The cluster interconnect traffic and the HA traffic share the same physical ports.
+
*Cluster/HA interconnect cables*
+
image::../media/oie_cable_25Gb_Ethernet_SFP28_IEOPS-1069.svg[Cluster HA cable, width=100pxx]

+
image::../media/drw_isi_g_switchless_2p_100gbe_cabling_ieops-1925.svg[Two-node switchless cluster cabling diagram]

+
.. Cable controller A port e3a to controller B port e3a.
.. Cable controller A port e3b to controller B port e3b.

+
. Cable the host network connections. 
+
The following graphics show examples of optional host network cabling. If needed, see  link:https://hwu.netapp.com[NetApp Hardware Universe^] for your specific storage system configuration.

.. Option 1: Cable the 10/25 GbE host network switches.(or, Cable to a 25GbE host network.) Cable ports e2a, e2b, e2c and e2d on each controller to the Ethernet host network switches.
+
*10/25 GbE cables*
+
image::../media/oie_cable_sfp_gbe_copper.svg[10/25 Gb cable,width=100px]
+
image::../media/drw_isi_g_4p_25gbe_optional_cabling_ieops-1923.svg[Cable to 10/25gbe ethernet host network switches]

+
.. Option 2: Cable the FC host network switches.Cable ports e1a, e1b, e1c and e1d on each controller to the FC host network switches.
+
*64 Gb FC cables*
+
image::../media/oie_cable_sfp_gbe_copper.svg[64 Gb fc cable,width=100px]
+
image::../media/drw_isi_g_4p_64gb_fc_optional_cabling_ieops-1924.svg[Cable to 64Gb fc host network switches]
+

. Cable the management (wrench) ports on each controller to the management network switches.
+
*1000BASE-T RJ-45 cables*
+
image::../media/oie_cable_rj45.svg[RJ45 cables,width=100px]
+
image::../media/drw_isi_g_wrench_cabling_ieops-1928.svg[Connect to your management network,width=500px]

IMPORTANT: Do not plug in the power cords yet. 



--
.Option 2: Cable the controllers to a switched ONTAP cluster
--
Cable the controllers to the cluster network switches to create the ONTAP cluster connections, and then cable the Ethernet ports on each controller to your host network.

.Steps

. Cable the controllers to the cluster network switches:

+
NOTE: The cluster interconnect traffic and the HA traffic share the same physical ports.


+
.. Cable Controller A port e3a and Controller B port e3a to cluster network switch A. 
.. Cable Controller A port e3b and Controller B port e3b to cluster network switch B.
+
*100 GbE cable*
+
image::../media/oie_cable100_gbe_qsfp28.svg[100 Gb cable,width=100px]
+
image::../media/drw_isi_g_2p_100gbe_switched_cluster_cabling_ieops-1926.svg[Cable cluster connections to cluster network,width=500px]

. Cable the Ethernet ports to the host network. 
+
The following examples show some typical host network cabling. See  link:https://hwu.netapp.com[NetApp Hardware Universe^] for your specific system configuration.

.. Cable ports e9a and e9b to the Ethernet data network switch.
+
*100 GbE cable*
+
image::../media/oie_cable_sfp_gbe_copper.svg[100Gb Ethernet cable,width=100px]
+
image::../media/drw_70-90_network_cabling1_ieops-1654.svg[Cable to 100Gb Ethernet network,width=500px]

+
.. Cable the 10/25 GbE host network switches.
+
*4-ports, 10/25 GbE Host*
+
image::../media/oie_cable_sfp_gbe_copper.svg[10/25Gb Ethernet cable,width=100px]
+
image::../media/drw_70-90_network_cabling2_ieops-1655.svg[Cable to 10/25Gb Ethernet network,width=500px]
+


. Cable the controller management (wrench) ports to the management network switches.
+
image::../media/oie_cable_rj45.svg[RJ-45 cables,width=100px]
*1000BASE-T RJ-45 cables*
+
image::../media/drw_isi_g_wrench_cabling_ieops-1928.svg[Connect to your management network,width=500px]

IMPORTANT: Do not plug in the power cords yet. 

--

====

== Step 2: Cable the controllers to the shelves
This procedure shows how to cable the controllers to one NS224 shelf.

For the maximum number of shelves supported for your storage system, see link:https://hwu.netapp.com[NetApp Hardware Universe^].

.About this task
* You cable each controller to each NSM module on the NS224 shelf.
* The graphics show controller A cabling in blue and controller B cabling in yellow.

.Steps

*100 GbE QSFP28 copper cables*

image::../media/oie_cable100_gbe_qsfp28.svg[100 GbE QSFP28 copper cable,width=100px]

. Cable controller A to the shelf:
.. Cable controller A port e3a to NSM A port e0a.
.. Cable controller A port e3b to port NSM B port e0b.
+
image:../media/drw_isi_g_1_ns224_controller_a_cabling_ieops-1945.svg[Controller A ports e3a and e3b cabled to one NS224 shelf]

. Cable controller B to the shelf:
.. Cable controller B port e3a to NSM B port e0a.
.. Cable controller B port e3b to NSM A port e0b.
+
image:../media/drw_isi_g_1_ns224_controller_b_cabling_ieops-1946.svg[Controller B ports e3a and e3b cabled to one NS224 shelf]

.What's next?

After you’ve cabled the hardware for your storage system system, you link:install-power-hardware.html[power on the storage system].


