---
permalink: a20-30-50/io-module-overview.html
sidebar: sidebar
keywords: aff a20, aff a30, and aff a50, replace io module, add io module, hotswap io module
summary: The AFF A20, AFF A30, and AFF A50 storage systems offer flexibility in expanding or replacing I/O modules to enhance network connectivity and performance. Adding, hot-swapping, or replacing an I/O module is essential when upgrading network capabilities or addressing a failed module.
---
= Overview of I/O module maintenance - AFF A20, AFF A30, and AFF A50
:icons: font
:imagesdir: ../media/

[.lead]
The AFF A20, AFF A30, and AFF A50 storage systems offer flexibility in expanding or replacing I/O modules to enhance network connectivity and performance. Adding, hot-swapping, or replacing an I/O module is essential when upgrading network capabilities or addressing a failed module.

* link:io-module-add.html[Add an I/O module]
+
You can add I/O modules to improve redundancy, helping to ensure that the storage system remains operational even if one I/O module fails. You can add I/O modules when there are slots available or when all slots are fully populated.

* link:io-module-hotswap-ha-slot4.html[Hot-swap an I/O module]
+
// Jan 2026: updated for 9.18.1 support changes. https://jira.ngage.netapp.com/browse/AFFFASDOC-358
+
You can hot-swap a failed cluster and HA I/O module or Ethernet client I/O module for an equivalent I/O module to restore the storage system to its optimal operating state. Hot-swapping is done without having to manually take over the controller with the failed I/O module.
+
To use this procedure, your storage system must be running ONTAP 9.17.1 or later and meet specific requirements.

* link:io-module-replace.html[Replace an I/O module]
+
You can replace a failed I/O module to restore the storage system to its optimal operating state. This procedure requires a manual takeover of the controller with the failed I/O module.
