---
permalink: a20-30-50/io-module-hotswap.html
sidebar: sidebar
keywords: aff a20, aff a30, aff a50, hotswap a pcie card
summary: Replace an I/O module in your AFF A20, AFF A30, or AFF A50 system when the module fails or requires an upgrade to support higher performance or additional features. The replacement process involves shutting down the controller, replacing the failed I/O module, rebooting the controller, and returning the failed part to NetApp.
---
= Hot-swap a cluster/HA I/O module - AFF A20, AFF A30, and AFF A50
:icons: font
:imagesdir: ../media/

[.lead]
You can hot-swap a failed cluster/HA I/O module for an equivalent module when your AFF A20, AFF A30, or AFF A50 storage system meets specific system requirements. Your system must be running ONTAP 9.17.1 or later, must be a two-node system in a single cluster/HA I/O module configuration, and must be in a takeover state.

The hot-swap process does not require a controller shutdown or reboot. The process involves preparing the I/O module slot for removal, hot-swapping the failed cluster/HA I/O module for an equivalent module, bringing the replacement cluster/HA I/O module online, and returning the failed part to NetApp.

If your system is not running ONTAP 9.17.1 or later, or does not meet the system requirements, you must use the link:io-module-replace.html[replace an I/O module procedure].


include::../_include/g_io_module_hotswap.adoc[]

//Jul 25, 2025: GH issue #1185.Support cluster/HA I/O hot-swap.