---
permalink: asa-r2-a1k/bootmedia-overview.html
keywords: asa r2 a1k, overview, the boot media
summary: Learn about the automated method and the manual method for replacing the boot media.
---
= Overview of replacing the boot media - ASA A1K
:icons: font
:imagesdir: ../media/

[.lead]

You can replace a failed boot media manually by using USB module for the boot image or through the automated boot media replace (BMR) option.

* link:bootmedia-replace-requirements-bmr.html[Automated boot media replacement]
+
Automated boot media replace uses the boot image from the partned node and automatically runs the appropriate boot menu option to install the boot image to the replacement boot media.

* link:bootmedia-replace-requirements.html[Manual boot media replace]
+
Manual boot media replace uses the traditional method of downloading the ONTAP image from the NetApp support site, transferring the image to a USB drive, downloading it to the target replacement boot media, and manually walking through the boot menu options to install the ONTAP image on the replacement boot media. 
