---
permalink: asa-r2-a1k/maintain-overview.html
sidebar: sidebar
keywords: asa r2 a1k maintenance, maintenance, repairing a1k, repairing asa a1k, replace asa a1k components, replace asa a1k components
summary: Maintain the AFF A1K hardware
---
= Maintain ASA r2 A1K hardware
:icons: font
:imagesdir: ../media/

[.lead]
For the ASA r2 A1K storage system, you can perform maintenance procedures on the following components.

== Boot media

The boot media stores a primary and secondary set of ONTAP image files that the system uses when it boots. 

== Controller

A controller consists of a board, firmware, and software. It controls the drives and runs the ONTAP operating system software.

== DIMM

A dual in-line memory module (DIMM) is a type of computer memory. They are installed to add system memory to a controller motherboard.

== Fan

A fan cools the controller.

== NVRAM

The NVRAM (Non-Volatile Random Access Memory) is a module that allows the controller to protect and save in-flight data if the system loses power. The system ID resides in the NVRAM module. When replaced, the controller assumes the new system ID from the replacement NVRAM module. 

== NV battery

The NVRAM battery is responsible for providing power to the NVRAM module while data in-flight is being destaged to flash memory after a power loss.

== I/O module

The I/O module (Input/Output module) is a hardware component that acts as an intermediary between the controller and various devices or systems that need to exchange data with the controller. 


== Power supply

A power supply provides a redundant power source in a controller.

== Real-time clock battery

A real time clock battery preserves system date and time information if the power is off. 

== System Management module

The System Management module provides the interface between the controller and a console or laptop for controller or system maintenance purposes. The System management module contains the boot media and stores the system serial number (SSN).
