Replace the controller in your AFF A800 system when a hardware failure requires it. The replacement process involves removing the impaired controller, moving the components to the replacement controller, installing the replacement controller, and rebooting it.

== Step 1: Remove the controller module

You must remove the controller module from the chassis when you replace the controller module or replace a component inside the controller module.

include::../_include/800_controller_remove_physical.adoc[]

== Step 2: Move the power supplies


Move the power supplies to the replacement controller module.

include::../_include/800_controller_replace_move_psus.adoc[]


== Step 3: Move the fans

Move the fan modules to the replacement controller module.

include::../_include/800_controller_replace_move_fans.adoc[]


== Step 4: Move the NVDIMM battery

Move the NVDIMM battery to the replacement controller module.

include::../_include/800_controller_replace_move_nvdimm_battery.adoc[]

== Step 5: Remove the PCIe risers

Remove the PCIe risers from the impaired controller module.

include::../_include/800_controller_replace_move_remove_risers.adoc[]


== Step 6: Move system DIMMs

Move the system DIMMS to the replacement controller module.

include::../_include/800_controller_replace_move_dimms.adoc[]

== Step 7: Move the NVDIMMs

Move the NVDIMMS to the replacement controller module.

include::../_include/800_controller_replace_move_nvdimms.adoc[]


== Step 8: Move the boot media

Move the boot media to the replacement controller module.

include::../_include/800_controller_replace_move_bootmedia.adoc[]

== Step 9: Install the PCIe risers

Install the risers in the replacement controller module.

include::../_include/800_controller_replace_move_install_risers.adoc[]

== Step 10: Install the controller module

Reinstall the controller module and reboot it.

include::../_include/800_controller_install_step_physical.adoc[]

.What's next?

After you've replaced the impaired A800 controller, you need to link:controller-replace-system-config-restore-and-verify.html[restore the system configuration]
