The System Management module is not hot-swappable and consists of:

** Boot media, allowing boot media replacement without removing thr controller module.
** BMC
** Management switch

The System Management module also contains the following ports for external management:

** RJ45 Serial
** USB Serial (Type-C)
** USB Type-A (Boot recovery)
** e0M RJ45 Ethernet

To replace the System Management module or or the boot media, you must shut down the impaired controller.  

.Before you begin
* This procedure uses the following terminology:
 ** The impaired controller is the controller on which you are performing maintenance.
 ** The healthy controller is the HA partner of the impaired controller.
 * All other system components must be working properly.
* The partner controller must be able to take over the impaired controller.
* You must replace the failed component with a replacement FRU component you received from your provider.

== Step 1: Shut down the impaired controller

Shut down or take over the impaired controller using one of the following options.

[role="tabbed-block"]
====

.Option 1: Most systems
--
include::../_include/shutdown_most_frus.adoc[]
--
.Option 2: Controller is in a MetroCluster
--
include::../_include/shutdown_any_mcc_supported.adoc[]
--

====

== Step 2: Replace the impaired System Management module

. Remove the System Management module:
+
image::../media/drw_A1K_sys-mgmt_remove_IEOPS-1384.svg[System Management module remove]
+
[cols="1,4"]
|===
a|
image::../media/legend_icon_01.svg[Callout number 1,width=30px]
a|
System Management module cam latch
|===

.. If you are not already grounded, properly ground yourself.
.. Remove any cables connected to the System Management module. Make sure that label where the cables were connected, so that you can connect them to the correct ports when you reinstall the module. 
.. Depress the system management cam button.
The cam button moves away from the chassis.
 .. Rotate the cam lever all the way down and remove the System Management module from the controller module.
.. Place the System Management module on an anti-static mat, so that the boot media is accessible.
. Remove the boot media from the management module:
+
image::../media/drw_A1K_boot_media_remove_replace_IEOPS-1377.svg[Boot media replace]
+
[cols="1,4"]
|===
a|
image::../media/legend_icon_01.svg[Callout number 1,width=30px]
a|
System Management module cam latch
a|
image::../media/legend_icon_02.svg[Callout number 2,width=30px]
a|
Boot media locking button
a|
image::../media/legend_icon_03.svg[Callout number 3,width=30px]
a|
Boot media
|===

.. Press the blue locking button.
The boot media rotates slightly upward.
.. Rotate the boot media up,  slide it out of the socket.
.. Install th eboot media in the replacement System Management module:
... Align the edges of the boot media with the socket housing, and then gently push it squarely into the socket.
... Rotate the boot media down toward until it engages the locking button.
. Align the edges of the replacement System Management module with the opening and gently push it in until the cam handle engages and rotates upward.
. Push the module in completely and then rotate the cam handle into the locked position.
. Recable the System Management module.

== Step 3: Reboot the controller module

After you replace the FRU, you must reboot the controller module.

. Enter `bye` at the LOADER prompt.
. Return the controller to normal operation by giving back its storage: `storage failover giveback -ofnode _impaired_node_name_`
. Restore automatic giveback by using the `storage failover modify -node local -auto-giveback true` command.
. If an AutoSupport maintenance window was triggered, end it by using the `system node autosupport invoke -node * -type all -message MAINT=END` command.

== Step 4: Return the failed part to NetApp

include::../_include/complete_rma.adoc[]


