You must boot the ONTAP image from the USB drive, restore the file system, and verify the environmental variables.

. From the LOADER prompt, boot the recovery image from the USB flash drive: `boot_recovery`
+
The image is downloaded from the USB flash drive.

. When prompted, either enter the name of the image or accept the default image displayed inside the brackets on your screen.
. Restore the var file system:
+

[options="header" cols="1,2"]

|===

| If your system has...| Then...
a|
A network connection
a|
.. On the impaired controller, press `Y` when you see `Do you want to restore the backup configuration now?` 

.. On the impaired controller, press `Y` when prompted to overwrite `/etc/ssh/ssh_host_ecdsa_key`. 

.. On the healthy partner controller, set the impaired controller to advanced privilege level: `set -privilege advanced`.

.. On the healthy partner controller, run the restore backup command: `system node restore-backup -node local -target-address impaired_node_IP_address`.

+
NOTE: If you see any message other than a successful restore, contact https://support.netapp.com[NetApp Support].

.. On the healthy partner controller, return the impaired controller to admin level: `set -privilege admin`.

.. On the impaired controller, press `y` when you see `Was the restore backup procedure successful?`.

.. On the impaired controller, press `y` when you see `...would you like to use this restored copy now?`. 

.. On the impaired controller, press `y` when prompted to reboot the impaired controller and press `ctrl-c` for the Boot Menu.

a|
No network connection
a|
Contact https://support.netapp.com[NetApp Support].

a|
No network connection and is in a MetroCluster IP configuration
a|
Contact https://support.netapp.com[NetApp Support].

|===

== Restore the system

[role="tabbed-block"]
====

.Option 1: Systems with no encryprion
--
include::../_include/shutdown_most_frus.adoc[]
need include to boot ONTAP with option 1 - see https://docs.netapp.com/us-en/ontap/system-admin/manage-node-boot-menu-task.html?q=boot+menu+option+1
--
.Option 2: Systems with onboard key manager server configuration
--
include::../_include/restore_onboard_key_manager_server_config.adoc[]
--
.Option 3: Systems with extrernal key manager server configuration
--
include::../_include/restore_external_key_manager_server_config.adoc[]
--

====
