== Step 1: Boot the controllers and give back the controllers 
After the controllers reboot, boot ONTAP and give back the controllers.

.Steps
. Check the console output:
.. If the controller boots to the LOADER prompt, reboot the controller with the `boot_ontap` command.

.. If the console displays `waiting for giveback` after the reboot, log into the partner controller and check that the replaced controller is ready for giveback with the `storage failover show` command.

. Perform the giveback:

.. Connect the console cable to the partner controller.
.. Return the impaired controller to normal operation by giving back its storage: `storage failover giveback -ofnode _impaired_node_name_`

.. If automatic giveback was disabled, reenable it: `storage failover modify -node _impaired_node_name_ -auto-giveback _true_`

.. If AutoSupport is enabled, restore/unsuppress automatic case creation: `system node autosupport invoke -node * -type all -message MAINT=END`

== Step 2: Verify storage system health

After the controller has given back the storage, you should check the overall health with https://mysupport.netapp.com/site/tools/tool-eula/activeiq-configadvisor[Active IQ Config Advisor].

.Steps
. After the giveback is complete, run Active IQ Config Advisor to verify the health of the storage system.
. Correct any issues you encounter.


== Step 3: Return the failed part to NetApp

include::../_include/complete_rma.adoc[]
