After completing the hardware replacement, you verify the low-level system configuration of the replacement controller and reconfigure system settings as necessary.

== Step 1: Set and verify system time

include::../_include/set_time_after_controller_rep.adoc[]

== Step 2: Verify and set the HA state of the chassis

You must verify the `HA` state of the controller module and, if necessary, update the state to match your system configuration.

. Boot to Maintenance mode on the replacement controller module and verify that all components display the same `HA` state: `ha-config show`
+
The HA state should be the same for all components.

. If the displayed system state of the controller module does not match your system configuration, set the `HA` state for the controller module: `ha-config modify controller _ha-state_`

+
The value for HA-state can be one of the following:

*** `ha`
*** `mcc` (not supported)
*** `mccip` (not supported in ASA r2 systems)
*** `non-ha` (not supported)

  . If the displayed system state of the controller module does not match your system configuration, set the `HA` state for the controller module: `ha-config modify controller _ha-state_`
  . Confirm that the setting has changed: `ha-config show`


