Recable the storage and network connections, and then give back the controller.

== Step 1: Recable the controller

include::../_include/recable_system_after_controller_rep.adoc[]

== Step 2: Give back the controller
Transfer the ownership of storage resources back to the replacement controller.

. If your storage system has Encryption configured, you must restore Storage or Volume Encryption functionality using the following procedure to reboot the system:
.. Boot to Menu and run Option 10
.. Input the passphrase & backup up data, then do Normal boot see https://kb.netapp.com/on-prem/ontap/DM/Encryption/Encryption-KBs/Restore_onboard_key_management_encryption_keys[Restore onboard key management encryption keys]. 
.. Perform CFO only giveback
.. Perform Onboard Sync and verify SVM-KEK is set to true see https://kb.netapp.com/on-prem/ontap/DM/Encryption/Encryption-KBs/Onboard_keymanager_sync_fails_after_motherboard_replacement[Giveback after MB replacement fails - operation was vetoed by keymanager]
.. Giveback SFO, (no force)
. If your system does not have Encryption configured, complete the following procedure to reboot the system:
.. Boot to Menu and run Option 1.
.. Give back the controller:
 .. From the healthy controller, give back the replaced controller's storage: `storage failover giveback -ofnode _replacement_node_name_`

+
The _replacement_ controller takes back its storage and completes booting.
+

NOTE: If the giveback is vetoed, you can consider overriding the vetoes.

+

http://mysupport.netapp.com/documentation/productlibrary/index.html?productID=62286[Find the High-Availability Configuration content for your version of ONTAP 9]

+

 .. After the giveback has been completed, confirm that the HA pair is healthy and that takeover is possible: `storage failover show`

. Verify that the expected volumes are present for each controller: `vol show -node node-name`
. If you disabled automatic takeover on reboot, enable it from the healthy controller: `storage failover modify -node replacement-node-name -onreboot true`
