
== Step 1: Boot the controllers and give back the controllers 
After the controllers reboot, boot ONTAP and give back the controllers.

.Steps
. Check the console output:
.. If the controller boots to the LOADER prompt, reboot the controller with the `boot_ontap` command.

.. If the console displays `waiting for giveback` after the reboot, log into the partner controller and check that the replaced controller is ready for giveback with the `storage failover show` command.

. Perform the giveback:

.. Connect the console cable to the partner controller.
.. Give back the controller with the `storage failover giveback -fromnode local` command.

== Step 2: Verify storage system health

After the controller has given back the storage, you should check the overall health with https://mysupport.netapp.com/site/tools/tool-eula/activeiq-configadvisor[Active IQ Config Advisor].

.Steps
. After the giveback is complete, run Active IQ Config Advisor to verify the health of the storage system.
. Correct any issues you encounter.


== Step 3: Return the failed part to NetApp

include::../_include/complete_rma.adoc[]
