Move the hard drives, and controller module from the impaired chassis to the new chassis, and swap out the impaired chassis with the new chassis of the same model as the impaired chassis.

== Step 1: Remove the controller module

include::../_include/a70-90_controller_remove_physical.adoc[]

. Repeat these steps for the other controller module in the chassis.

== Step 2: Move drives to the new chassis

You need to move the drives from each bay opening in the old chassis to the same bay opening in the new chassis.

. Gently remove the bezel from the front of the system.
. Remove the drives:
 .. Press the release button at the top of the carrier face below the LEDs.
 .. Pull the cam handle to its fully open position to unseat the drive from the midplane, and then gently slide the drive out of the chassis.
+
The drive should disengage from the chassis, allowing it to slide free of the chassis.
+
NOTE: When removing a drive, always use two hands to support its weight.
+
NOTE: Drives are fragile. Handle them as little as possible to prevent damage to them.

. Keep track of what drive bay each drive was from and set the drives aside on a static-free cart or table.


== Step 3: Replace chassis from within the equipment rack or system cabinet

You must remove the existing chassis from the equipment rack or system cabinet before you can install the replacement chassis.

. Remove the screws from the chassis mount points.
. With two people, slide the old chassis off the rack rails in a system cabinet or equipment rack, and then set it aside.
. Using two people, install the replacement chassis into the equipment rack or system cabinet by guiding the chassis onto the rack rails in a system cabinet or equipment rack.
. Slide the chassis all the way into the equipment rack or system cabinet.
. Secure the front of the chassis to the equipment rack or system cabinet, using the screws you removed from the old chassis.
. Install the drives from the old chassis into the replacement chassis:
.. Align the drive from the old chassis with the same bay opening in the new chassis.
. Gently push the drive into the chassis as far as it will go.
+
The cam handle engages and begins to rotate upward.

.. Firmly push the drive the rest of the way into the chassis, and then lock the cam handle by pushing it up and against the drive carrier.
+
Be sure to close the cam handle slowly so that it aligns correctly with the front of the drive carrier. It clicks when it is secure.

.. Repeat the process for the remaining drives in the system.
. If you have not already done so, install the bezel.

== Step 4: Reinstall the controller modules

Reinstall the controller modules into the chassis and reboot them.

. If you opened the air duct, close air duct by rotating it down as far as it will go.
+
It should lie flush against the controller module sheet metal.

. Align the end of the controller module with the opening in the chassis, and then gently push the controller all the way into the chassis.

.. Rotate the locking latches upward into the locked position.
.. If you have not already done so, reinstall the cable management device and recable the controller.
+
If you removed the media converters (QSFPs or SFPs), remember to reinstall them if you are using fiber optic cables.

. Repeat the preceding steps to install the second controller into the new chassis.

. Plug the power cords into the power supplies.

+
NOTE: If you have DC power supplies, reconnect the power block to the power supplies after the controller module is fully seated in the chassis.

+
The controller module begins to boot as soon as it is installed and power is restored. If it boots to the LOADER prompt, reboot the controller with the `boot_ontap` command. 

