There are several key tasks that must be completed prior to replacing the chassis.

Before replacing the chassis, make sure to review the following requirements.

* Make sure all other components in the system are functioning properly; if not, contact technical support.
* You can use the chassis replacement procedure with all versions of ONTAP supported by your system.
* The chassis replacement procedure is written with the assumption that you are moving the bezel, NVMe drives, and controller modules to the new chassis, and that the replacement chassis is a new component from NetApp.
* *The chassis replacement procedure is disruptive.* For a two-node cluster, you will have a complete service outage and a partial outage in a multi-node cluster.

== Step 1:  Review requirements

. Review the requirements in link:chassis-replace-requirements.html[Review the chassis replace requirements]

== Step 2: Run Config Advisor

. Verify system health by downloading and running link:https://mysupport.netapp.com/site/tools/tool-eula/activeiq-configadvisor[Active IQ Conf Advisor] from the the http://mysupport.netapp.com/[NetApp Support Site^].

. Resolve any issues before replacing the chassis.

. Verify that both controller modules are running and cabled correctly.

. Make any necessary corrections to configuration or cabling..  

== Step 3: Open a console session, session logs, and location LED

. Open a console session to monitor the system

. Save the console sessions to a log file on the console.

+ 
You should do scree captures to take scheen shots of the UI tools for later reference.

. Turn on the blue Location LED on the storage system to help you identify the correct controllers:

+
`storage shelf show`
+
`storage shelf location-led modify -shelf-name _shelf_name_ -led-status on`
+

NOTE: The Location LED remains lit for 30 minutes.


== Step 4: Label the cables and ground yourself

. Label all the cables associated with the storage system. This aids recabling later in this procedure.

. If you are not already properly grounded, ground yourself.

.What's next?
After you’ve prepared to replace your AFF A70 or AFF A90 chassis hardware, you need to link:a70-90/chassis-replace-shutdown.adoc.html[shutdown your AFF A70 or AFF A90 storage system].
