The NVRAM module consists of the NVRAM12 and DIMMs. You can replace a failed NVRAM module or the DIMMs inside the NVRAM module. To replace a failed NVRAM module, you must remove it from the chassis, move the DIMMs to the replacement module, and install the replacement NVRAM module into the chassis

All other components in the system must be functioning properly; if not, you must contact technical support.

You must replace the failed component with a replacement FRU component you received from your provider.

== Step 1: Shut down the impaired controller

Shut down or take over the impaired controller using one of the following options.

[role="tabbed-block"]
====

.Option 1: Most systems
--
include::../_include/shutdown_most_frus.adoc[]
--
.Option 2: Controller is in a MetroCluster
--
include::../_include/shutdown_any_mcc_supported.adoc[]
--

====

== Step 2: Replace the NVRAM module

To replace the NVRAM module, locate it in slot 4/5 in the chassis and follow the specific sequence of steps.

. On the front of the chassis, use your thumbs to firmly push each drive in until you feel a positive stop. This ensures that the drives are firmly seated against the chassis midplane.  
+
image::../media/drw_a800_drive_seated_IEOPS-960.svg[width=400px]
+
. Go to the rear of the chassis. If you are not already grounded, properly ground yourself. 

. Unplug the power cord from the PSU.
+
NOTE: If your system has DC power supplies, disconnect the power cable block from the PSU.
+
. Rotate the cable management tray down by pulling the buttons on the inside of the cable management tray and rotating it down.
. Remove the target NVRAM module from the chassis:
 .. Depress the cam latch button.
+
The cam button moves away from the chassis.

 .. Rotate the cam latch as far as it will go.
+
.. Remove the NVRAM module from the enclosure by hooking your finger into the cam lever opening and pulling the module out of the enclosure.
+
image::../media/drw_a70-90_nvram12_remove_replace_ieops-1370.svg[Remove the NVRAM12 module and DIMMs]
+
[cols="1,4"]
|===
a|
image:../media/legend_icon_01.svg[Callout number 1,width=30px]|
Cam locking button
a|
image:../media/legend_icon_02.svg[Callout number 2,width=30px]
a|
DIMM locking tab
|===
. Set the NVRAM module on a stable surface.
. Remove the DIMMs, one at a time, from the old NVRAM module and install them in the replacement NVRAM module.
. Install the replacement NVRAM module into the chassis:
 .. Align the module with the edges of the chassis opening in slot 4/5.
 .. Gently slide the module into the slot all the way, and then push the cam latch all the way up to lock the module in place.
 . Recable the PSU.

 +
NOTE: If your system has DC power supplies, reconnect the power cable block to the PSU.
+

 . Rotate the cable management tray up to the closed position.

== Step 3: Replace a NVRAM DIMM

To replace NVRAM DIMMs in the NVRAM module, you must remove the NVRAM module, and then replace the target DIMM.

. If you are not already grounded, properly ground yourself.
. Unplug the power cord from the PSU.
+
NOTE: If your system has DC power supplies, disconnect the power cable block from the PSU.
+
. Rotate the cable management tray down by gently pulling the pins on the ends of the tray and rotating the tray down.
. Remove the target NVRAM module from the chassis:
 .. Depress the cam button.
+
The cam button moves away from the chassis.

.. Rotate the cam latch as far as it will go.
+

.. Remove the NVRAM module from the chassis by hooking your finger into the cam lever opening and pulling the module out of the chassis.
+
image::../media/drw_a70-90_nvram12_remove_replace_ieops-1370.svg[Remove the NVRAM12 module and DIMMs]
+
[cols="1,4"]
|===
a|
image:../media/legend_icon_01.svg[Callout number 1,width=30px]|
Cam locking button
a|
image:../media/legend_icon_02.svg[Callout number 2,width=30px]
a|
DIMM locking tab
|===

. Set the NVRAM module on a stable surface.
. Locate the DIMM to be replaced inside the NVRAM module, and then remove it by pressing down on the DIMM locking tabs and lifting the DIMM out of the socket.
+
. Install the replacement DIMM by aligning the DIMM with the socket and gently pushing the DIMM into the socket until the locking tabs lock in place.
. Install the NVRAM module into the chassis:
 .. Gently slide the module into the slot until the cam latch begins to engage with the I/O cam pin, and then rotate the cam latch all the way up to lock the module in place.
. Recable the PSU.
+
NOTE: If your system has DC power supplies, reconnect the power cable block to the PSU.
+
. Rotate the cable management tray up to the closed position.

== Step 4: Reboot the controller

After you replace the FRU, you must reboot the controller module.

. To boot ONTAP from the LOADER prompt, enter `bye`.

== Step 5: Reassign disks

You must confirm the system ID change when you boot the replacement controller and then verify that the change was implemented.

CAUTION: Disk reassignment is only needed when replacing the NVRAM module and does not apply to NVRAM DIMM replacement. 

.Steps
. If the replacement controller is in Maintenance mode (showing the `*>` prompt), exit Maintenance mode and go to the LOADER prompt: `halt`
. From the LOADER prompt on the replacement controller, boot the controller and entering y when prompted to override the system ID due to a system ID mismatch.
. Wait until the Waiting for giveback... message is displayed on the console of the controller with the replacement module and then, from the healthy controller, verify that the new partner system ID has been automatically assigned: `storage failover show`
+
In the command output, you should see a message that the system ID has changed on the impaired controller, showing the correct old and new IDs. In the following example, node2 has undergone replacement and has a new system ID of 151759706.
+
----
node1:> storage failover show
                                    Takeover
Node              Partner           Possible     State Description
------------      ------------      --------     -------------------------------------
node1             node2             false        System ID changed on partner (Old:
                                                  151759755, New: 151759706), In takeover
node2             node1             -            Waiting for giveback (HA mailboxes)
----

. Give back the controller:
 .. From the healthy controller, give back the replaced controller's storage: `storage failover giveback -ofnode replacement_node_name`
+
The replacement controller takes back its storage and completes booting.
+
If you are prompted to override the system ID due to a system ID mismatch, you should enter `y`.
+
NOTE: If the giveback is vetoed, you can consider overriding the vetoes.
+
For more information, see the https://docs.netapp.com/us-en/ontap/high-availability/ha_manual_giveback.html#if-giveback-is-interrupted[Manual giveback commands^] topic to override the veto.

 .. After the giveback has been completed, confirm that the HA pair is healthy and that takeover is possible: `storage failover show`
+
The output from the `storage failover show` command should not include the System ID changed on partner message.
. Verify that the disks were assigned correctly: `storage disk show -ownership`
+
The disks belonging to the replacement controller should show the new system ID. In the following example, the disks owned by node1 now show the new system ID, 151759706:
+
----
node1:> storage disk show -ownership

Disk  Aggregate Home  Owner  DR Home  Home ID    Owner ID  DR Home ID Reserver  Pool
----- ------    ----- ------ -------- -------    -------    -------  ---------  ---
1.0.0  aggr0_1  node1 node1  -        151759706  151759706  -       151759706 Pool0
1.0.1  aggr0_1  node1 node1           151759706  151759706  -       151759706 Pool0
.
.
.
----

. If the system is in a MetroCluster configuration, monitor the status of the controller: `metrocluster node show`
+
The MetroCluster configuration takes a few minutes after the replacement to return to a normal state, at which time each controller will show a configured state, with DR Mirroring enabled and a mode of normal. The `metrocluster node show -fields node-systemid` command output displays the old system ID until the MetroCluster configuration returns to a normal state.

. If the controller is in a MetroCluster configuration, depending on the MetroCluster state, verify that the DR home ID field shows the original owner of the disk if the original owner is a controller on the disaster site.
+
This is required if both of the following are true:

 ** The MetroCluster configuration is in a switchover state.
 ** The replacement controller is the current owner of the disks on the disaster site.
+
See https://docs.netapp.com/us-en/ontap-metrocluster/manage/concept_understanding_mcc_data_protection_and_disaster_recovery.html#disk-ownership-changes-during-ha-takeover-and-metrocluster-switchover-in-a-four-node-metrocluster-configuration[Disk ownership changes during HA takeover and MetroCluster switchover in a four-node MetroCluster configuration] for more information.

. If your system is in a MetroCluster configuration, verify that each controller is configured: `metrocluster node show - fields configuration-state`
+
----
node1_siteA::> metrocluster node show -fields configuration-state

dr-group-id            cluster node           configuration-state
-----------            ---------------------- -------------- -------------------
1 node1_siteA          node1mcc-001           configured
1 node1_siteA          node1mcc-002           configured
1 node1_siteB          node1mcc-003           configured
1 node1_siteB          node1mcc-004           configured

4 entries were displayed.
----

. Verify that the expected volumes are present for each controller: `vol show -node node-name`
. If storage encryption is enabled, you must restore functionality.
. If you disabled automatic takeover on reboot, enable it from the healthy controller: `storage failover modify -node replacement-node-name -onreboot true`

== Step 6: Return the failed part to NetApp

include::../_include/complete_rma.adoc[]