To replace the controller, you must remove the impaired controller, move FRU components from the impaired controller module to the replacement controller module, install the replacement controller module in the chassis, and then boot the system to Maintenance mode.

== Step 1: Remove the controller module

include::../_include/a70-90_controller_remove_physical.adoc[]

== Step 2: Move the power supplies

Move the power supplies to the replacement controller.

. Rotate the cam handle such that it can be used to pull power supply out of the controller module while pressing the locking tab.
+
CAUTION: The power supply is short. Always use two hands to support it when removing it from the controller module so that it does not suddenly swing free from the controller module and injure you.
+
image::../media/drw_a70-90_psu_remove_replace_ieops-1368.svg[PSU remove]
+
[cols="1,4"]
|===
a|
image::../media/legend_icon_01.svg[Callout number 1,width=30px]
|
Terracotta  supply locking tab
a|
image::../media/legend_icon_02.svg[Callout number 2,width=30px]
a|
Power supply
|===

. Move the power supply to the new controller module, and then install it.
. Using both hands, support and align the edges of the power supply with the opening in the controller module, and then gently push the power supply into the controller module until the locking tab clicks into place.
+
The power supplies will only properly engage with the internal connector and lock in place one way.
+
NOTE: To avoid damaging the internal connector, do not use excessive force when sliding the power supply into the system.

== Step 3: Move the fans

Move the fans to the replacement controller module.

. Remove the fan module by pinching the locking tabs on the side of the fan module, and then lifting the fan module straight out of the controller module.
+
image::../media/drw_a70-90_fan_remove_replace_ieops-1366.svg[Remove fans]
+
[cols="1,4"]
|===
a|
image::../media/legend_icon_01.svg[Callout number 1,width=30px]
a|
Fan locking tabs
a|
image::../media/legend_icon_02.svg[Callout number 2,width=30px]
a|
Fan module
|===

. Move the fan module to the replacement controller module, and then install the fan module by aligning its edges with the opening in the controller module, and then sliding the fan module into the controller module until the locking latches click into place.
. Repeat these steps for the remaining fan modules.

== Step 4: Move the NV battery

Move the battery backup unit to the replacement controller module.

. Open the air duct cover in the middle of the controller module and locate the NV battery.
+
image::../media/drw_a70-90_remove_replace_nvmembat_ieops-1369.svg[Move the NV battery]
+
[cols="1,4"]
|===
a|
image::../media/legend_icon_01.svg[Callout number 1,width=30px]
|
NV battery air duct
a|
image::../media/legend_icon_02.svg[Callout number 2,width=30px]
a|
NV battery pack plug
|===

*Attention:* The NV module LED blinks while destaging contents to the flash memory when you halt the system. After the destage is complete, the LED turns off.

. Lift the battery up to access the battery plug.
. Squeeze the clip on the face of the battery plug to release the plug from the socket, and then unplug the battery cable from the socket.
. Lift the battery out of the air duct and controller module.
. Move the battery pack to the replacement controller module and then install it in the replacement controller module:
.. Open the NV battery air duct in the replacement controller module.
 .. Plug the battery plug into the socket and make sure that the plug locks into place.
 .. Insert the battery pack into the slot and press firmly down on the battery pack to make sure that it is locked into place.
 .. Close the NV battery air duct.
 
== Step 5: Move system DIMMs

Move the DIMMs to the replacement controller module.

. Open the controller air duct on the top of the controller.
.. Insert your fingers in the recesses at the far ends of the air duct.
.. Lift the air duct and rotate it upward as far as it will go.
. Locate the system DIMMs on the motherboard.

+
image::../media/drw_s70_90_dimm_ieops-1513.svg[DIMM map]
+
[cols="1,4"]
|===
a|
image::../media/legend_icon_01.svg[Callout number 1,width=30px]
|
System DIMM
|===

. Note the orientation of the DIMM in the socket so that you can insert the DIMM in the replacement controller module in the proper orientation.
. Eject the DIMM from its slot by slowly pushing apart the two DIMM ejector tabs on either side of the DIMM, and then slide the DIMM out of the slot.
+
NOTE: Carefully hold the DIMM by the edges to avoid pressure on the components on the DIMM circuit board.

. Locate the slot where you are installing the DIMM.
. Insert the DIMM squarely into the slot.
+
The DIMM fits tightly in the slot, but should go in easily. If not, realign the DIMM with the slot and reinsert it.
+
NOTE: Visually inspect the DIMM to verify that it is evenly aligned and fully inserted into the slot.

. Push carefully, but firmly, on the top edge of the DIMM until the ejector tabs snap into place over the notches at the ends of the DIMM.
. Repeat these steps for the remaining DIMMs.
. Close the motherboard air duct.

== Step 6: Move the I/O modules

Move the I/O modules to the replacement controller module.

image::../media/drw_a70_90_io_remove_replace_ieops-1532.svg[Remove I/O module]

[cols="1,4"]
|===
a|
image::../media/legend_icon_01.svg[Callout number 1,width=30px]
|
I/O module cam lever
|===

. Unplug any cabling on the target I/O module.
+
Make sure that you label the cables so that you know where they came from.
. Rotate the cable management arm down by pulling the buttons on the inside of the cable management arm and rotating it down.
. Remove the I/O modules from the controller module:
.. Depress the target I/O module cam latch button.
+
The cam lever moves away from the controller module.
.. Rotate the cam latch down as far as it will go. For horizontal modules, rotate the cam away from the module as far as it will go.
.. Remove the module from the controller module by hooking your finger into the cam lever opening and pulling the module out of the controller module.
+
Make sure that you keep track of which slot the I/O module was in.
.. Install the replacement I/O module into the replacement controller module by gently sliding the I/O module into the slot until the I/O cam latch begins to engage with the I/O cam pin, and then push the I/O cam latch all the way up to lock the module in place.
. Repeat these steps to move the remaining I/O modules, except the modules in slots 6 and 7, to the replacement controller module. 
+
NOTE: To move the I/O modules from slots 6 and 7, you must move the carrier containing these I/O modules from the impaired controller module to the replacement controller module. 
+
. Move the carrier containing the I/O modules in slots 6 and 7 to the replacement controller module:

.. Press the button on the right-most handle on the carrier handle.
..Slide the carrier out of the impaired controller module insert it into the replacement controller module in the same position it was in the impaired controller module.
.. Gently push the carrier all the way into the replacement controller module until it locks into place. 


== Step 10: Install the controller module

include::../_include/a70-90_controller_install_step_physical.adoc[]
. Plug the power cables into the power supplies and reinstall the power cable retainers.
+
NOTE: If your system has DC power supplies, make sure the thumbscrews on the power supply cable are tight.
