Use this procedure to replace a failed I/O module.

* You can use this procedure with all versions of ONTAP supported by your storage system.
* All other components in the storage system must be functioning properly; if not, you must contact technical support.

== Step 1: Shut down the impaired controller
 
Shut down or take over the impaired controller using one of the following options.
 
[role="tabbed-block"]
====
 
.Option 1: Most systems
--
include::../_include/shutdown_most_frus.adoc[]
--
.Option 2: Controller is in a MetroCluster
--
include::../_include/shutdown_any_mcc_no_2-node_mcc.adoc[]
--
 
====


== Step 2: Replace a failed I/O module

To replace an I/O module, locate it within the controller module and follow the specific sequence of steps.

. On the front of the chassis, use your thumbs to firmly push each drive in until you feel a positive stop. This ensures that the drives are firmly seated against the chassis midplane.  
+
image::../media/drw_a800_drive_seated_IEOPS-960.svg[width=400px]
+
. Go to the rear of the chassis. If you are not already grounded, properly ground yourself. 

. Disconnect power to the controller module by pulling the controller module out about three inches:

.. Press down on both of the controller module locking latches, and then rotate both latches downward at the same time.
.. Pull the controller module about 3 inches out of the chassis to disengage power.

. Unplug any cabling on the target I/O module.
+
Make sure that you label the cables so that you know where they came from.

. Rotate the cable management tray down by pulling the buttons on the inside of the cable management tray and rotating it down.

. Remove the I/O module from the controller module:

+
NOTE: This following illustration shows removing a horizontal and vertical I/O module. Typically, you will only remove one I/O module.
+

image::../media/drw_a70_90_io_remove_replace_ieops-1532.svg[Remove I/O module]
+
[cols="1,4"]
|===
a|
image:../media/legend_icon_01.svg[Callout number 1,width=30px] 
a|
Cam locking button

|===

.. Depress the cam latch button.
+
The cam latch moves away from the controller module.
.. Rotate the cam latch down as far as it will go. For horizontal modules, rotate the cam away from the module as far as it will go.
.. Remove the module from the controller module by hooking your finger into the cam lever opening and pulling the module out of the controller module.
+
Make sure that you keep track of which slot the I/O module was in.
+
. Set the I/O module aside.

. Install the replacement I/O module into the target slot:
.. Align the I/O module with the edges of the slot.
.. Gently slide the module into the slot all the way into the controller module, and then rotate the cam latch all the way up to lock the module in place.

. Cable the I/O module.

. Repeat the remove and install steps to replace additional modules for the controller.

. Reconnect power to the controller module:
.. Firmly push the controller module into the chassis until it meets the midplane and is fully seated.
+
The locking latches rise when the controller module is fully seated.
+
.. Rotate the locking latches upward into the locked position.
+
. Rotate the cable management tray into the locked position.

== Step 3: Reboot the controller

After you replace an I/O module, you must reboot the controller module.

NOTE: If the new I/O module is not the same model as the failed module, you must first reboot the BMC.

.Steps
. Reboot the BMC if the replacement module is not the same model as the old module:
.. From the LOADER prompt, change to advanced privilege mode: _set privilege advanced_
.. Reboot the BMC: _sp reboot_
. From the LOADER prompt, reboot the node: _bye_
+
NOTE: This reinitializes the I/O cards and other components and reboots the node.

+
NOTE: Be sure to exit Maintenance mode after completing the conversion.

. Return the node to normal operation: _storage failover giveback -ofnode impaired_node_name_

. If automatic giveback was disabled, reenable it: _storage failover modify -node local -auto-giveback true_

== Step 4: Return the failed part to NetApp

include::../_include/complete_rma.adoc[]
