Prepare to replace the impaired chassis with the new chassis of the same model.


== Step 1: Locate and monitor your system
You should open a console session and save sessions logs for future reference, and also turn on the system location LED to find the impaired chassis.

. Connect to the serial console port to interface with and monitor the system.

. Locate and turn on the controller LED:

.. Use the `system controller location-led show` command to show the current state of the location LED.
+
The Location LED remains lit for 30 minutes.

.. Change the state of the location LED to "on" with the `system controller location-led modify -node _node1_ -state on`. 

 

== Step 2: Verify replacement components

You should verify that you received the necessary components, remove them from packaging, and save the packaging.

. Before opening the packaging, you should look at the packaging label and verify:
* Component part number.
* Part description.
* Quantity in the box.

. Remove the contents from the packaging and use the packaging to returning the failed component to NetApp.

== Step 3: Label the cables and controller modules and ground yourself

You should label the cables and controllers before removing them from the controller modules or chassis.

. Label all the cables associated with the storage system. This aids recabling later in this procedure.

. Label the controller modules.

. If you are not already properly grounded, ground yourself.


