If the storage system has available slots, install the new I/O module into one of the available slots. If all slots are occupied, remove an existing I/O module to make space and then install the new one.

.Before you begin

* Check the https://hwu.netapp.com/[NetApp Hardware Universe^] to ensure the new I/O module is compatible with your storage system and ONTAP version.

* If multiple slots are available, check the slot priorities in https://hwu.netapp.com/[NetApp Hardware Universe^]  and use the best one available for your I/O module.

* Make sure that all other components are functioning properly.

* Make sure you have the replacement component you received from NetApp.


// start tabbed area

[role="tabbed-block"]
====

.Add I/O module to an available slot
--
You can add a new I/O module into a storage system with available slots.

.Steps
. If you are not already grounded, properly ground yourself.

. Rotate the cable management tray down by pulling the buttons on the inside of the cable management tray and rotating it down.
. Remove the target slot blanking module from the carrier:

 .. Depress the cam latch on the blanking module in the target slot.
 .. Rotate the cam latch away from the module as far as it will go.
 .. Remove the module from the enclosure by hooking your finger into the cam lever opening and pulling the module out of the enclosure.
. Install the I/O module:
 .. Align the I/O module with the edges of the enclosure slot opening.
 .. Gently slide the module into the slot all the way into the enclosure, and then rotate the cam latch all the way up to lock the module in place.
 . Cable the I/O module to the designated device.

+
NOTE: Make sure that any unused I/O slots have blanks installed to prevent possible thermal issues.
. Rotate the cable management tray up to the closed position.
. From the LOADER prompt, reboot the node: 
+
`bye`
+
NOTE: This reinitializes the I/O module and other components and reboots the node.
+

. Press <enter> when console messages stop.
* If you see the _login_ prompt, go to the next step.
* If you do not see the login prompt, log in to the partner node.
. Give back only the root with override-destination-checks option:
+
`storage failover giveback -ofnode impaired-node -only-root true -override -destination-checks true`
+
NOTE: The following command is only available in the Diagnostic mode privilege level. For more information on privilege levels, see link:https://docs.netapp.com/us-en/ontap/system-admin/administrative-privilege-levels-concept.html[Understand the privilege levels for ONTAP CLI commands^]. 
+
If you encounter errors, contact https://support.netapp.com[NetApp Support].
. Wait 5 minutes after the giveback report completes, and check failover status and giveback status:
+
`storage failover show` and `storage failover show-giveback`
+
NOTE: The following command is only available in the Diagnostic mode privilege level.
. If the HA internconnect links were taken down, bring them back up:
+
`system ha interconnect link on -node healthy-node -link 0`
+
`system ha interconnect link on -node healthy-node -link 1`

. Return the impaired controller to normal operation by giving back its storage: 
+
`storage failover giveback -ofnode _impaired_node_name_`

. Repeat these steps for controller B.

. From the healthy node, restore automatic giveback if you disabled it:
+
`storage failover modify -node local -auto-giveback-of _true_`

. If AutoSupport is enabled, restore automatic case creation:
+
`system node autosupport invoke -node * -type all -message MAINT=END`

--

.Add I/O module to a fully-populated system
--
You can add an I/O module to a fully-populated system by removing an existing I/O module and installing a new one in its place.

.About this task
Make sure you understand the following scenarios for adding a new I/O module to a fully-populated system:

[options="header" cols="1,2"]
|===
| Scenario| Action required
a|
NIC to NIC (same number of ports)
a|
The LIFs will automatically migrate when its controller module is shut down.
a|
NIC to NIC (different number of ports)	
a|
Permanently reassign the selected LIFs to a different home port. See https://docs.netapp.com/ontap-9/topic/com.netapp.doc.onc-sm-help-960/GUID-208BB0B8-3F84-466D-9F4F-6E1542A2BE7D.html[Migrating a LIF^] for more information.
a|
NIC to storage I/O module
a|
Use System Manager to permanently migrate the LIFs to different home ports, as described in https://docs.netapp.com/ontap-9/topic/com.netapp.doc.onc-sm-help-960/GUID-208BB0B8-3F84-466D-9F4F-6E1542A2BE7D.html[Migrating a LIF^].

|===
 
.Steps
. If you are not already grounded, properly ground yourself.

. Unplug any cabling on the target I/O module.
. Rotate the cable management tray down by pulling the buttons on the inside of the cable management tray and rotating it down.
. Remove the target I/O module from the chassis:


.. Depress the  cam latch button.

.. Rotate the cam latch away from the module as far as it will go.
.. Remove the module from the enclosure by hooking your finger into the cam lever opening and pulling the module out of the enclosure.
+
Make sure that you keep track of which slot the I/O module was in.
+

. Install the I/O module into the target slot in the enclosure:
.. Align the module with the edges of the enclosure slot opening.
.. Gently slide the module into the slot all the way into the enclosure, and then rotate the cam latch all the way up to lock the module in place.
. Cable the I/O module to the designated device.
. Repeat the remove and install steps to replace additional modules for the controller.
. Rotate the cable management tray up to the closed position.

. Reboot the controller from the LOADER prompt:_bye_

+
This reinitializes the PCIe cards and other components and reboots the node.

. Press <enter> when console messages stop.
* If you see the _login_ prompt, go to the next step.
* If you do not see the login prompt, log in to the partner node.
. Give back only the root with override-destination-checks option:
+
`storage failover giveback -ofnode impaired-node -only-root true -override -destination-checks true`
+
NOTE: The following command is only available in the Diagnostic mode privilege level. For more information on privilege levels, see link:https://docs.netapp.com/us-en/ontap/system-admin/administrative-privilege-levels-concept.html[Understand the privilege levels for ONTAP CLI commands^]. 
+
If you encounter errors, contact https://support.netapp.com[NetApp Support].
. Wait 5 minutes after the giveback report completes, and check failover status and giveback status:
+
`storage failover show` and `storage failover show-giveback`
+
NOTE: The following command is only available in the Diagnostic mode privilege level.
. If the HA internconnect links were taken down, bring them back up:
+
`system ha interconnect link on -node healthy-node -link 0`
+
`system ha interconnect link on -node healthy-node -link 1`

. Return the impaired controller to normal operation by giving back its storage:
+
`storage failover giveback -ofnode impaired_node_name` 

. Enable automatic giveback if it was disabled: 
+
`storage failover modify -node local -auto-giveback-of true`

. Do one of the following:
+
* If you removed a storage I/O module and installed a new NIC I/O module, use the following network command for each port:
+
`storage port modify -node <node name>__ -port <port name>__ -mode network`

* If you removed a NIC I/O module and installed a storage I/O module, install and cable your NX224 shelves, as described in link:../nx224/hot-add-shelf-overview.html[Hot-add workflow].

. Repeat these steps for controller B.
--

====

// end tabbed area