// start tabbed block area

[role="tabbed-block"]
====

.No encryption
--
Return the impaired controller to normal operation by giving back its storage.

.Steps
. From the LOADER prompt, enter
+ 
`boot_ontap`

. Press <enter> when console messages stop.
* If you see the _login_ prompt, go to the next step at the end of this section.
* If you do not see login prompt, press the <enter> key, if still no prompt, log into the partner node.
. Give back only the root with override-destination-checks option:
+
`storage failover giveback -ofnode impaired-node -only-root true -override -destination-checks true`
+
NOTE: The following command is only available in the Diagnostic mode privilege level. For more information on privilege levels, see link:https://docs.netapp.com/us-en/ontap/system-admin/administrative-privilege-levels-concept.html[Understand the privilege levels for ONTAP CLI commands^]. 
+
If you encounter errors, contact https://support.netapp.com[NetApp Support].
. Wait 5 minutes after the giveback report completes, then check failover and giveback status:
+
`storage failover show` and `storage failover show-giveback`
+
NOTE: The following command is only available in the Diagnostic mode privilege level.
. If the HA internconnect links were taken down, bring them back up:
+
`system ha interconnect link on -node healthy-node -link 0`
+
`system ha interconnect link on -node healthy-node -link 1`

. Return the impaired controller to normal operation by giving back its storage:
+
`storage failover giveback -ofnode _impaired_node_name_`
. If automatic giveback was disabled, reenable it: 
+
`storage failover modify -node local -auto-giveback-of true`

. If AutoSupport is enabled, restore/unsuppress automatic case creation:
+ 
`system node autosupport invoke -node * -type all -message MAINT=END`
--

.OKM encryption
--
Reset onboard encryption and return the controller to normal operation.

.Steps
. From the LOADER prompt, enter:
+
`boot_ontap maint`

. Boot to the ONTAP  menu from the LOADER prompt `boot_ontap menu` and select option 10.
. Enter the OKM passphrase. You can get this passphrase from the customer, or contact https://support.netapp.com[NetApp Support].
+
NOTE: You will be prompted twice for the passphrase.

. Enter the backup key data when prompted.
. At the boot menu, enter option `1` for normal boot.
. Move the console cable to the partner node and enter the following login:
+
`admin`

. Give back only the root with override-destination-checks option: 
+
`storage  failover giveback -ofnode impaired-node -only-root true -override-destination-checks true`
+
NOTE: The following command is only available in the Diagnostic mode privilege level. For more information on privilege levels, see link:https://docs.netapp.com/us-en/ontap/system-admin/administrative-privilege-levels-concept.html[Understand the privilege levels for ONTAP CLI commands^]. 
+
If you encounter errors, contact https://support.netapp.com[NetApp Support].
. Wait 5 minutes after the giveback report completes, then check failover and giveback status:
+ 
`storage failover show` and `storage failover show-giveback`
+
NOTE: The following command is only available in the Diagnostic mode privilege level.
. Move the console cable to the replacement node and enter the following:
+ 
`security key-manager onboard sync`
+
NOTE: You will be prompted for the cluster-wide passphrase of OKM for the cluster.

. Check status of the keys with the following command: 
+
`security key-manager key query -key-type svm-KEK` 
+
If the _Restored_ column shows anything but _true_, contact https://support.netapp.com[NetApp Support]. 
. Return the impaired controller to normal operation by giving back its storage:
+ 
`storage failover giveback -ofnode _impaired_node_name_`

.. If the HA interconnect links were taken down, bring them back up to resume automatic giveback:
+
`system ha interconnect link on -node healthy-node -link 0`
+
`system ha interconnect link on -node healthy-node -link 1`
. If automatic giveback was disabled, reenable it:
+ 
`storage failover modify -node local -auto-giveback-of true`

. If AutoSupport is enabled, restore/unsuppress automatic case creation:
+
`system node autosupport invoke -node * -type all -message MAINT=END`

--

====

// end tabbed block area
