// start tabbed block area

[role="tabbed-block"]
====

.No encryption
--
Return the impaired controller to normal operation by giving back its storage.

.Steps
. From the LOADER prompt, enter
+ 
`boot_ontap`

. Press <enter> when console messages stop.
* If you see the _login_ prompt, go to the next step at the end of this section.
* If you see _Waiting for giveback_, press the <enter> key, log into the partner node. 
. Return the impaired controller to normal operation by giving back its storage:
+ 
`storage failover giveback -ofnode _impaired_node_name_`

. If automatic giveback was disabled, reenable it: 
+
`storage failover modify -node local -auto-giveback true`

. If AutoSupport is enabled, restore/unsuppress automatic case creation:
+ 
`system node autosupport invoke -node * -type all -message MAINT=END`
--

.OKM encryption
--
Reset onboard encryption and return the controller to normal operation.

.Steps
. From the LOADER prompt, enter:
+
`boot_ontap maint`

. Boot to the ONTAP  menu from the LOADER prompt `boot_ontap menu` and select option 10.
. Enter the OKM passphrase. You can get this passphrase from the customer, or contact https://support.netapp.com[NetApp Support].
+
NOTE: You will be prompted twice for the passphrase.

. Enter the backup key data when prompted.
. At the boot menu, enter option `1` for normal boot.
. Press <enter> when _Waiting for giveback_ is displayed.
. Move the console cable to the partner node and enter the following login:
+
`admin`

. Give back only the CFO aggregates (the root aggregate): 
+
`storage failover giveback -fromnode local -only-cfo-aggregates true`
+
* If you encounter errors, contact https://support.netapp.com[NetApp Support].
. Wait 5 minutes after the giveback report completes, and check failover status and giveback status:
+ 
`storage failover show` and `storage failover show-giveback`
. Move the console cable to the replacement node and enter the following:
+ 
`security key-manager onboard sync`
+
NOTE: You will be prompted for the cluster-wide passphrase of OKM for the cluster.

. Check status of the keys with the following command: 
+
`security key-manager key query -key-type svm-KEK` 
+
If the _Restored_ column shows anything but _true_, contact https://support.netapp.com[NetApp Support]. 
. Return the impaired controller to normal operation by giving back its storage:
+ 
`storage failover giveback -ofnode _impaired_node_name_`

. If automatic giveback was disabled, reenable it:
+ 
`storage failover modify -node local -auto-giveback true`

. If AutoSupport is enabled, restore/unsuppress automatic case creation:
+
`system node autosupport invoke -node * -type all -message MAINT=END`

--

====

// end tabbed block area
