Restore the ONTAP image from the partner node when the boot media is corrupted.


.About this task
If a node's boot media is corrupted, the boot process will halt at the LOADER prompt and display boot error messages.

When you encounter these boot error messages, you need to restore the ONTAP image from the partner node.

.Show example of boot error messages
[%collapsible]

====
....
Can't find primary boot device u0a.0 
Can't find backup boot device u0a.1 
ACPI RSDP Found at 0x777fe014 

Starting AUTOBOOT press Ctrl-C to abort... 
Could not load fat://boot0/X86_64/freebsd/image1/kernel: Device not found

ERROR: Error booting OS on: 'boot0' file: fat://boot0/X86_64/Linux/image1/vmlinuz (boot0, fat) 
ERROR: Error booting OS on: 'boot0' file: fat://boot0/X86_64/freebsd/image1/kernel (boot0, fat) 

Autoboot of PRIMARY image failed. Device not found (-6) 
LOADER-A>
....

====


.Steps

. From the LOADER prompt, enter the command:
+
`boot_recovery -partner`
+
The screen displays the following message:
+
`Starting boot media recovery (BMR) process. Press Ctrl-C to abort…`

+

. Monitor the boot media recovery process as LOADER configures the local ports and executes `netboot` from the partner node.
+
When netboot is running, the `Starting BMR` message displays.
+


. Continue monitoring the recovery process while it reboots twice during the recovery process.  
.. If there is no NetApp Storage Encryption (NSE) on the system, you will see the tje following mesage:
`key manager is not configured. Exiting.` 
+
The login prompt is displayed.
+
.. Log into the node.
.. Return the impaired controller to normal operation by giving back its storage:
+
`storage failover giveback -ofnode _impaired_node_name_`. 

.. If NSE is found, you will see: 
+
`key manager is configured.`
+
The system will run the appropriate boot menu option to restore the key manager.***





****************stopped here - need to point path where to go*****
+

// start tabbed area
+
[role="tabbed-block"]
====



.Onboard Key Manager (OKM)
--
If Onboard Key Manager (OKM) is detected, the system displays the following prompt.  
....
key manager is configured.
Entering Bootmenu Option 10...
 
This option must be used only in disaster recovery procedures. Are you sure? (y or n):
....

.. From the Bootmenu Option prompt, enter `Y` to confirm you want to start the OKM recovery process.

.. Enter the passphrase for onboard key manager when prompted, and enter the passphrase again to confirm.
+
.Show example of passphrase prompts
[%collapsible]

=====
....
Enter the passphrase for onboard key management:
Enter the passphrase again to confirm:
Enter the backup data:
TmV0QXBwIEtleSBCbG9iAAECAAAEAAAAcAEAAAAAAAA3yR6UAAAAACEAAAAAAAAA
QAAAAAAAAACJz1u2AAAAAPX84XY5AU0p4Jcb9t8wiwOZoqyJPJ4L6/j5FHJ9yj/w
RVDO1sZB1E4HO79/zYc82nBwtiHaSPWCbkCrMWuQQDsiAAAAAAAAACgAAAAAAAAA
3WTh7gAAAAAAAAAAAAAAAAIAAAAAAAgAZJEIWvdeHr5RCAvHGclo+wAAAAAAAAAA
IgAAAAAAAAAoAAAAAAAAAEOTcR0AAAAAAAAAAAAAAAACAAAAAAAJAGr3tJA/LRzU
QRHwv+1aWvAAAAAAAAAAACQAAAAAAAAAgAAAAAAAAABHVFpxAAAAAHUgdVq0EKNp
.
.
.
.
....
=====

+
.. Continue to monitor the recovery process as it restores the backup config, env file, mdb, and rdb from the partner node.
+
When the recovery process is complete, the node will reboot. The following messages indicate a successful recovery:
+

....
Trying to recover keymanager secrets.... 
Setting recovery material for the onboard key manager 
Recovery secrets set successfully
Trying to delete any existing km_onboard.wkeydb file.
 
Successfully recovered keymanager secrets.
....

.. When the node reboots, verify the boot media recovery was successful by confirming that the system is back online and operational.

.. Return the impaired controller to normal operation by giving back its storage:
+
`storage failover giveback -ofnode _impaired_node_name_`

.. After the partner node is fully up and serving data, synchronize the OKM keys across the cluster.
+
`security key-manager onboard sync` 
 

--

.External Key Manager (EKM)
--

If EKM is configured, the system displays the following prompt.

....
Error when fetching key manager config from partner <IP>:

Has key manager been configured on this system? {y|n}
....

.. Enter `Y` if EKM has been configured.
+
....
key manager is configured.
Entering Bootmenu Option 11...
....

+
You'll be prompted for the EKM settings that were initially used during setup. You should have copies of the following files or information from the partner node:


.. Enter each EKM configuration setting when prompted:
... Enter the client certificate contents:
+
.Show example of client certificate contents
[%collapsible]

=====

=====

... Enter the client key file contents.
+
.Show example of client certificate file contents
[%collapsible]

=====
....
-----BEGIN CERTIFICATE-----
MIIEPDCCAiSgAwIBAgIRAPhBSP8jLvD9euDHmrDJfKUwDQYJKoZIhvcNAQELBQAw
WjELMAkGA1UEBhMCVVMxCzAJBgNVBAgTAk1EMRAwDgYDVQQHEwdCZWxjYW1wMRAw
DgYDVQQKEwdHZW1hbHRvMRowGAYDVQQDExFLZXlTZWN1cmUgUm9vdCBDQTAeFw0y
MjAyMTAyMDUyMThaFw00MjAyMDUyMDUyMThaMCIxDjAMBgNVBAMTBWFkbWluMRAw
DgYKCZImiZPyLGQBARMAMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA
0wvPm/zL6GTQ+v79Ies5SoIt8bRo3r2EXgyaGIZpTihb/zKMXVbjDrjwAs5pr851
81tgW2gPYWO2Ase3+zuxQG6ANYT4IgZr3MwC7R1/O1JxJuOSCZTav/LO13HKYTvK
X5GsfVqVEjzbx6vsHJC0NuP0hIgK3XjY3hMKTAJ4HYX73uWpJnOFqHDKOC7Xj72e
8tTQD+SWbi6SUuQV6USfyCELIWSx+JGK52aZKjTVrqrWRDnnXfLDVcY8kco3fyFD
o7sI6wTU+r1LBiv/KkcUvd1uKNJkObiSVeL2k1Fy9lPBP0D/RB+YEz1sx0QtdMx7
VMmLVbcl7Lp2cmBYBZOs+wIDAQABozUwMzAOBgNVHQ8BAf8EBAMCA4gwEwYDVR0l
BAwwCgYIKwYBBQUHAwIwDAYDVR0TAQH/BAIwADANBgkqhkiG9w0BAQsFAAOCAgEA
LurhZW48Yt43zj4dpWPGtMHsJOqv/6dEGBK5u/3eXxSFiqHcEWpI2SHqrRoEFxgq
NZGtoqci+Y829gUPzhRdjlhChtsEiFfUP//v6rELVVIImMJcXBDQs8fndy8My4tp
nPMYOphKUOamGsI4CyYQRRLu5ZRwmn8UpxgFbcJKn7YqO5WCswX2/FmdoHbjzl1k
EO2BfbrxK7bdkxACVBCOequPW9l3MERcIsTuJ0hvC+ymSBTvq4ZW8dDi83ZdBpPL
+pLvnK21rSjjzwtHD5RsvMTM/QwKMgO7fAQw7JB4IogZiLvu0sSaSQUm1WZOiExi
mb/JFhQkbkDF9eyKlprwd/ijG7aVJAD5DDnmOgJxnvJNnn2h5WCEu5UVJxAxEuBG
OhXLzfi7+b4rThqlwonxeQN6ShSwK04VmLeVATzg1dT+BGIP9UKtYf3lfYzoCUsl
qV5dJyJX3bQiSU1NCzeTbF65kH1dXfu9X0viy0WD6O/BoEhnZMsiMJA+zxJWealh
4hGlKBb4JOVcNNGAah7rthcS9hubhflwinTalCTAidw65itM9iH64OWq8YZFZE4F
E6QjK37wnczekwWNuGP/WjhQZ/bId2Ac3qmiFwnikA2+qiNPWvN1w/Mds9GXBQvQ
00yKg2zThsZMedLeJ45fPRh1UFQJJCwQzWR94ui1Iw8=
-----END CERTIFICATE-----
....

=====

... Enter the KMIP server file contents.
+
.Show example of KMIP server file contents
[%collapsible]

=====

=====

... Enter the server configuration file contents.
+
.Show example of server configuration file contents
[%collapsible]

=====

=====
+
.Show example of configuration information needed from partner node - need to give examples of these....
[%collapsible]

=====
* A copy of the /cfcard/kmip/servers.cfg file from another cluster node, or, the following information:
** The KMIP server address.
** The KMIP port.
** The Keystore UUID.
* A copy of the /cfcard/kmip/certs/client.crt file from another cluster node, or, the client certificate.
* A copy of the /cfcard/kmip/certs/client.key file from another cluster node, or, the client key.
* 4) A copy of the /cfcard/kmip/certs/CA.pem file from another cluster node, or, the KMIP server.
=====


.. Depending on whether the key is successfully restored, take one of the following actions:

* If the EKM configuration has been restored, the process attempts to restore the Mroot-AK onto the node, then restores the backup config, env file, mdb, and rdb from the partner node and reboots the node. ***Proceed to step 4.

* If the key is not successfully restored, the system will halt and indicate that it could not restore the key. and display error and warning messages. Rerun the recovery process by entering `boot_recovery -partner`.
+
.Show example of key recovery error and warning messages
[%collapsible]
+
=====
....

ERROR: kmip_init: halting this system with encrypted mroot...
WARNING: kmip_init: authentication keys might not be available.
********************************************************
*                 A T T E N T I O N                    *
*                                                      *
*       System cannot connect to key managers.         *
*                                                      *
********************************************************
ERROR: kmip_init: halting this system with encrypted mroot...
.
Terminated
 
Uptime: 11m32s
System halting...
 
LOADER-B>
....
=====

.. When the node reboots, verify the boot media recovery was successful by confirming that the system is back online and operational.

.. Return the impaired controller to normal operation by giving back its storage:
+
`storage failover giveback -ofnode _impaired_node_name_`.

--

====

// end tabbed area

[start=4]


. If automatic giveback was disabled, reenable it: 
+
`storage failover modify -node local -auto-giveback true`.

. If AutoSupport is enabled, restore automatic case creation: 
+
`system node autosupport invoke -node * -type all -message MAINT=END`.