.Before you begin

* Determine if Onboard Key Manger (OKM) or Eternal Key Manager (EKM) is configured using one of the following methods:
** You can ask the customer or system administrator if OKM or EKM are enabled.
** To check if OKM is enabled, you can use the `security key-manager onboard show`.
** To check if EKM is enabled, you can use the `security key-manager external show`.
* For OKM, you need the OKM passphrase file contents.
* For EKM, you need copies of the following files from the partner node:
** /cfcard/kmip/servers.cfg file.
** /cfcard/kmip/certs/client.crt file. 
** /cfcard/kmip/certs/client.key file.
** /cfcard/kmip/certs/CA.pem file.


.Steps

. From the LOADER prompt, enter the command:
+
`boot_recovery -partner`
+
The screen displays the following message:
+
`Starting boot media recovery (BMR) process. Press Ctrl-C to abort…`

. Monitor the boot media install recovery process.
+
The process completes and displays the `Installation complete.` message.  

. The system checks for encryption and encryption type and displays one of two messages. Depending on what message is displayed, take one of the following actions:

+
[options="header" cols="1,2"]
|===
| If you see this message...| Do this...
a|
`key manager is not configured. Exiting.` 
a|
Encryption is not installed on the system. Complete the following steps:

.. Log into the node when the login prompt is displayed and give back the storage:
+
`storage failover giveback -ofnode _impaired_node_name_`

.. Go to step 5 to enable automatic giveback if it was disabled.

a|

`key manager is configured.` 
a|
Go to step 4 to restore the appropriate key manager.

The node access the boot menu and runs:

* Option 10 for systems with Onboard Key Manager (OKM).
* Option 11 for systems with External Key Manager (EKM). 

|===

. Select the appropriate key manager restoration process.

+

// start tabbed area

+

[role="tabbed-block"]
====

.Onboard Key Manager (OKM)
--
If OKM is detected, the system displays the following message and begins running BootMenu Option 10.  
....
key manager is configured.
Entering Bootmenu Option 10...
 
This option must be used only in disaster recovery procedures. Are you sure? (y or n):
....

.. Enter `Y` at the prompt to confirm you want to start the OKM recovery process.

.. Enter the passphrase for onboard key manager when prompted, and enter the passphrase again when prompted, to confirm.
+
.Show example of passphrase prompts
[%collapsible]

=====
....
Enter the passphrase for onboard key management:
Enter the passphrase again to confirm:
Enter the backup data:
-----BEGIN PASSPHRASE-----
<passphrase_value>
-----END PASSPHRASE-----
....
=====

+
.. Continue to monitor the recovery process as it restores the appropriate files from the partner node.
+
When the recovery process is complete, the node will reboot. The following messages indicate a successful recovery:
+

....
Trying to recover keymanager secrets.... 
Setting recovery material for the onboard key manager 
Recovery secrets set successfully
Trying to delete any existing km_onboard.keydb file.
 
Successfully recovered keymanager secrets.
....

.. When the node reboots, verify the boot media recovery was successful by confirming that the system is back online and operational.

.. Return the impaired controller to normal operation by giving back its storage:
+
`storage failover giveback -ofnode _impaired_node_name_`

.. After the partner node is fully up and serving data, synchronize the OKM keys across the cluster.
+
`security key-manager onboard sync` 
 
--

.External Key Manager (EKM)

--
If EKM is detected, the system displays the following message and begins running BootMenu Option 11. 
....
key manager is configured.
Entering Bootmenu Option 11...
....

.. The next step depends on which version of ONTAP your system is running:
+
[options="header" cols="1,2"]
|===
|If your system is running...| Do this...
a|
ONTAP 9.16.0
a|
.. Press `Ctlr-C` to exit BootMenu Option 11.
.. Press `Ctlr-C`  to exit the EKM configuration process and return to the boot menu.
.. Select BootMenu Option 8.
.. Reboot the node.

+ 
If `AUTOBOOT`  is set, the node reboots and uses the configuration files from the partner node.
+
If `AUTOBOOT` is not set, enter the appropriate boot command. The node reboots and uses the configuration files from the partner node. 

.. Reboot the node so that EKM protects the boot media partition.

.. Proceed to step c.

a|
ONTAP 9.16.1
a|
Proceed to the next step.

|===


.. Enter the following EKM configuration setting when prompted:
+
[options="header",cols="2"]
|===
| Action | Example
 
a| 
Enter the client certificate contents from the `/cfcard/kmip/certs/client.crt` file.
a|
.Show example of client certificate contents
[%collapsible]

=====
....
-----BEGIN CERTIFICATE-----
<certificate_value>
-----END CERTIFICATE-----
....
=====
 
a|
Enter the client key file contents from the `/cfcard/kmip/certs/client.key` file.

a|
.Show example of client key file contents
[%collapsible]

=====
....
-----BEGIN RSA PRIVATE KEY-----
<key_value>
-----END RSA PRIVATE KEY-----
....
=====

a|
Enter the KMIP server CA(s) file contents from the `/cfcard/kmip/certs/CA.pem` file.
a|
.Show example of KMIP server file contents
[%collapsible]

=====
....
-----BEGIN CERTIFICATE-----
<KMIP_certificate_CA_value>
-----END CERTIFICATE-----
....
=====

 
a| 
Enter the server configuration file contents from the `/cfcard/kmip/servers.cfg` file.
a| 
.Show example of server configuration file contents
[%collapsible]

=====
....
xxx.xxx.xxx.xxx:5696.host=xxx.xxx.xxx.xxx
xxx.xxx.xxx.xxx:5696.port=5696
xxx.xxx.xxx.xxx:5696.trusted_file=/cfcard/kmip/certs/CA.pem
xxx.xxx.xxx.xxx:5696.protocol=KMIP1_4
1xxx.xxx.xxx.xxx:5696.timeout=25
xxx.xxx.xxx.xxx:5696.nbio=1
xxx.xxx.xxx.xxx:5696.cert_file=/cfcard/kmip/certs/client.crt
xxx.xxx.xxx.xxx:5696.key_file=/cfcard/kmip/certs/client.key
xxx.xxx.xxx.xxx:5696.ciphers="TLSv1.2:kRSA:!CAMELLIA:!IDEA:!RC2:!RC4:!SEED:!eNULL:!aNULL"
xxx.xxx.xxx.xxx:5696.verify=true
xxx.xxx.xxx.xxx:5696.netapp_keystore_uuid=<id_value>
....
=====
 
a| 
If prompted, enter the ONTAP Cluster UUID from the partner.
a| 
.Show example of ONTAP Cluster UUID
[%collapsible]

=====
....
Notice: bootarg.mgwd.cluster_uuid is not set or is empty.
Do you know the ONTAP Cluster UUID? {y/n} y
Enter the ONTAP Cluster UUID: <cluster_uuid_value>
 
 
System is ready to utilize external key manager(s).
....
=====
 
a| 
If prompted, enter the temporary network interface and settings for the node.
a| 
.Show example of a temporary network setting
[%collapsible]

=====
....
In order to recover key information, a temporary network interface needs to be
configured.
 
Select the network port you want to use (for example, 'e0a')
e0M
 
Enter the IP address for port : xxx.xxx.xxx.xxx
Enter the netmask for port : xxx.xxx.xxx.xxx
Enter IP address of default gateway: xxx.xxx.xxx.xxx
Trying to recover keys from key servers....
[discover_versions]
[status=SUCCESS reason= message=]
....
=====

|===

.. Depending on whether the key is successfully restored, take one of the following actions:

* If the EKM configuration has been successfully restored, the process attempts to restore the appropriate files from the partner node and reboots the node. Go to step d.
+
.Show example of successful restore messages
[%collapsible]

=====
....

System is ready to utilize external key manager(s).
Trying to recover keys from key servers....
[discover_versions]
[status=SUCCESS reason= message=]
...
kmip2_client: Successfully imported the keys from external key server: xxx.xxx.xxx.xxx:xxxx
Successfully recovered keymanager secrets.
....
=====

* If the key is not successfully restored, the system will halt and indicate that it could not restore the key. The error and warning messages are displayed. Rerun the recovery process by entering `boot_recovery -partner`.
+
.Show example of key recovery error and warning messages
[%collapsible]

=====
....

ERROR: kmip_init: halting this system with encrypted mroot...
WARNING: kmip_init: authentication keys might not be available.
********************************************************
*                 A T T E N T I O N                    *
*                                                      *
*       System cannot connect to key managers.         *
*                                                      *
********************************************************
ERROR: kmip_init: halting this system with encrypted mroot...
.
Terminated
 
Uptime: 11m32s
System halting...
 
LOADER-B>
....


=====


.. When the node reboots, verify that the boot media recovery was successful by confirming that the system is back online and operational.

.. Return the controller to normal operation by giving back its storage:
+
`storage failover giveback -ofnode _impaired_node_name_`.
--
====

// end tabbed area

[start=5]

. If automatic giveback was disabled, reenable it: 
+
`storage failover modify -node local -auto-giveback true`.

. If AutoSupport is enabled, restore automatic case creation: 
+
`system node autosupport invoke -node * -type all -message MAINT=END`.