After physically replacing the impaired boot media, restore the image on the boot media through the automated boot recovery process.

.Steps

. From the LOADER prompt, enter the command:
+
`boot_recovery -partner`
+
The screen displays the following message:
+
`Starting boot media recovery (BMR) process. Press Ctrl-C to abort…`

. Monitor the boot media install recovery process.

. The process completes and displays the `Installation complete.` message.  

. The system checks for encryption and encryption type and displays one of two messages: 

+
[options="header" cols="1,2"]
|===
| If the message displaying is...| Then...
a|
`key manager is not configured. Exiting.` 
a|
Encryption is not installed on the system. 

Log into the node when the login prompt is displayed and give back the storage:

`storage failover giveback -ofnode _impaired_node_name_`

a|

`key manager is configured.` 
a|
Encryption is installed on the system and the key manager configuration must be restored.

The node access the boot menu and runs:

* Option 10 for systems with Onboard Key Manager (OKM).
* Option 11 for systems with External Key Manager (EKM). 

|===

. Select the appropriate key manager restoration process.

+

// start tabbed area

+

[role="tabbed-block"]
====

.Onboard Key Manager (OKM)
--
If OKM is detected, the system displays the following message and begins running BootMenu Option 10.  
....
key manager is configured.
Entering Bootmenu Option 10...
 
This option must be used only in disaster recovery procedures. Are you sure? (y or n):
....

.. Enter `Y` at the prompt to confirm you want to start the OKM recovery process.

.. Enter the passphrase for onboard key manager when prompted, and enter the passphrase again to confirm.
+
.Show example of passphrase prompts
[%collapsible]

=====
....
Enter the passphrase for onboard key management:
Enter the passphrase again to confirm:
Enter the backup data:
TmV0QXBwIEtleSBCbG9iAAECAAAEAAAAcAEAAAAAAAA3yR6UAAAAACEAAAAAAAAA
QAAAAAAAAACJz1u2AAAAAPX84XY5AU0p4Jcb9t8wiwOZoqyJPJ4L6/j5FHJ9yj/w
RVDO1sZB1E4HO79/zYc82nBwtiHaSPWCbkCrMWuQQDsiAAAAAAAAACgAAAAAAAAA
3WTh7gAAAAAAAAAAAAAAAAIAAAAAAAgAZJEIWvdeHr5RCAvHGclo+wAAAAAAAAAA
IgAAAAAAAAAoAAAAAAAAAEOTcR0AAAAAAAAAAAAAAAACAAAAAAAJAGr3tJA/LRzU
QRHwv+1aWvAAAAAAAAAAACQAAAAAAAAAgAAAAAAAAABHVFpxAAAAAHUgdVq0EKNp
.
.
.
.
....
=====

+
.. Continue to monitor the recovery process as it restores the backup config, env file, mdb, and rdb from the partner node.
+
When the recovery process is complete, the node will reboot. The following messages indicate a successful recovery:
+

....
Trying to recover keymanager secrets.... 
Setting recovery material for the onboard key manager 
Recovery secrets set successfully
Trying to delete any existing km_onboard.keydb file.
 
Successfully recovered keymanager secrets.
....

.. When the node reboots, verify the boot media recovery was successful by confirming that the system is back online and operational.

.. Return the impaired controller to normal operation by giving back its storage:
+
`storage failover giveback -ofnode _impaired_node_name_`

.. After the partner node is fully up and serving data, synchronize the OKM keys across the cluster.
+
`security key-manager onboard sync` 
 
--

.External Key Manager (EKM)

--
If EKM is detected, the system displays the following message and begins running BootMenu Option 11. 
....
key manager is configured.
Entering Bootmenu Option 11...
....

.. The next step depends on which version of ONTAP your system is running:
+
[options="header" cols="1,2"]
|===
|If your system is running...| Then...
a|
ONTAP 9.16.0
a|
.. Press `Ctlr-C` to exit BootMenu Option 11
.. Press `Ctlr-C`  to exit the EKM configuration process and return to the boot menu.
.. Select BootMenu Option 8.
.. Reboot the node. 

+ 
If `AUTOBOOT`  is set, the node reboots and uses the configuration files from the partner node.
+
If `AUTOBOOT` is not set, enter the appropriate boot command. The node reboots and uses the configuration files from the partner node. 

.. Reboot the node so that EKM picks up the correct keys.

.. Proceed to step c.

a|
ONTAP 9.16.1
a|
Proceed to the next step.

|===


.. Enter each EKM configuration setting when prompted:
... Enter the client certificate contents from the `/cfcard/kmip/certs/client.crt.` file:
+
.Show example of client certificate contents
[%collapsible]

=====
....
-----BEGIN CERTIFICATE-----
MIIEPDCCAiSgAwIBAgIRAPhBSP8jLvD9euDHmrDJfKUwDQYJKoZIhvcNAQELBQAw
WjELMAkGA1UEBhMCVVMxCzAJBgNVBAgTAk1EMRAwDgYDVQQHEwdCZWxjYW1wMRAw
DgYDVQQKEwdHZW1hbHRvMRowGAYDVQQDExFLZXlTZWN1cmUgUm9vdCBDQTAeFw0y
MjAyMTAyMDUyMThaFw00MjAyMDUyMDUyMThaMCIxDjAMBgNVBAMTBWFkbWluMRAw
DgYKCZImiZPyLGQBARMAMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA
0wvPm/zL6GTQ+v79Ies5SoIt8bRo3r2EXgyaGIZpTihb/zKMXVbjDrjwAs5pr851
81tgW2gPYWO2Ase3+zuxQG6ANYT4IgZr3MwC7R1/O1JxJuOSCZTav/LO13HKYTvK
X5GsfVqVEjzbx6vsHJC0NuP0hIgK3XjY3hMKTAJ4HYX73uWpJnOFqHDKOC7Xj72e
8tTQD+SWbi6SUuQV6USfyCELIWSx+JGK52aZKjTVrqrWRDnnXfLDVcY8kco3fyFD
.
.
.
.
-----END CERTIFICATE-----
....
=====

... Enter the client key file contents from the `/cfcard/kmip/certs/client.key` file.
+
.Show example of client key file contents
[%collapsible]

=====
....
-----BEGIN RSA PRIVATE KEY-----
MIIEpQIBAAKCAQEA0wvPm/zL6GTQ+v79Ies5SoIt8bRo3r2EXgyaGIZpTihb/zKM
XVbjDrjwAs5pr85181tgW2gPYWO2Ase3+zuxQG6ANYT4IgZr3MwC7R1/O1JxJuOS
CZTav/LO13HKYTvKX5GsfVqVEjzbx6vsHJC0NuP0hIgK3XjY3hMKTAJ4HYX73uWp
JnOFqHDKOC7Xj72e8tTQD+SWbi6SUuQV6USfyCELIWSx+JGK52aZKjTVrqrWRDnn
XfLDVcY8kco3fyFDo7sI6wTU+r1LBiv/KkcUvd1uKNJkObiSVeL2k1Fy9lPBP0D/
RB+YEz1sx0QtdMx7VMmLVbcl7Lp2cmBYBZOs+wIDAQABAoIBAAxdpMx/A3OadKRA
TJSwM6sp9Yc0CvECKb9Y/a5yMblipAFP9OmDLcqvC2EetxKWBlM8B2lTr5MFRKTl
DuKpnLkpwFlicSeNOMS3L3S1Rb80FW0x6FynXCnjEDuPb0xDNJhk8LZnmFR5PGd2
q18BG44bzTf2wKw5aHuaof/SJTeVhuOjpPX4GxGZjpUz+vTXb5UPaqJpKU7MvJGC
36xlf1NEF7JDg/1OLb4rDQyjhETXVA7K180TJbtOJJbUFCj9Rug17+zZxZsaVTK1
iCNGxBl6IpQ3lRdDNhxCmX2P1hpeH5C8X8pYQZ1VLzj2Psj8GBH8jty0nMRcyFy6
.
.
.
.

-----END RSA PRIVATE KEY-----
....
=====

... Enter the KMIP server CA(s) file contents from the  `/cfcard/kmip/certs/CA.pem` file.
+
.Show example of KMIP server file contents
[%collapsible]

=====
....
-----BEGIN CERTIFICATE-----
MIIFgjCCA2qgAwIBAgIRAK5suvIVYhYMZV70M23kxFwwDQYJKoZIhvcNAQELBQAw
WjELMAkGA1UEBhMCVVMxCzAJBgNVBAgTAk1EMRAwDgYDVQQHEwdCZWxjYW1wMRAw
DgYDVQQKEwdHZW1hbHRvMRowGAYDVQQDExFLZXlTZWN1cmUgUm9vdCBDQTAeFw0y
MjAyMDkxNzE3NTJaFw0zMjAyMDcxNzE3NTJaMFoxCzAJBgNVBAYTAlVTMQswCQYD
VQQIEwJNRDEQMA4GA1UEBxMHQmVsY2FtcDEQMA4GA1UEChMHR2VtYWx0bzEaMBgG
A1UEAxMRS2V5U2VjdXJlIFJvb3QgQ0EwggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAw
ggIKAoICAQDpox2e7FufWsebHs3+EkwUv7FSnMnsNiPLffmnqGZTjUN7AdjWDHjS
KoBpK6TGkkFFyK96xcXp2mQbPj6qeP/bVkSjKTvvs0mMRk6VyfEKd85YFpIjnC/2
E9BRx2CrUrySWmmLgbuE9tGYVBe/UvSj81vTusrBPvkKqATHo3GHiqhsFau1wL0l
hEeuYZWneCS45mGcOkI1iN5iPr1kNBql65+uar4FHhAdI2bmmG/T5G0a5TlaN4f7
NPiQrssMldveq0KW87uenmlvNQvw/r0B17edgk68ywMhA42TZeGvWAsbVHPalFwq
lz+eEwkYiaAlQrWq+K9EABW5Lrn3c11ifsGxPzO1CSFz+vryXeEkN6BM274V2ftL
Lj3V+MPcazRBu6k4Eu1yT5+mqbWKqa5yoVyM68hisuR0+rjXkRB3eth2j11C4yT/
Ieub92myytCOzC41JWxTjMJ3E5swNBn7rucOMKxVPUVKSNVyBS+YewqRGbdUH1jK
psGEGp1lfVdaW7W//mTY+SEpQ9o9Mzu8c2Syawm5TUBbAVgcEdie+hT4/F1bgtO+
.
.
.
.
.
-----END CERTIFICATE-----
....
=====

... Enter the server configuration file contents from the `/cfcard/kmip/servers.cfg` file.
+
.Show example of server configuration file contents
[%collapsible]

=====
....
10.225.89.37:5696.host=10.225.89.37
10.225.89.37:5696.port=5696
10.225.89.37:5696.trusted_file=/cfcard/kmip/certs/CA.pem
10.225.89.37:5696.protocol=KMIP1_4
10.225.89.37:5696.timeout=25
10.225.89.37:5696.nbio=1
10.225.89.37:5696.cert_file=/cfcard/kmip/certs/client.crt
10.225.89.37:5696.key_file=/cfcard/kmip/certs/client.key
10.225.89.37:5696.ciphers="TLSv1.2:kRSA:!CAMELLIA:!IDEA:!RC2:!RC4:!SEED:!eNULL:!aNULL"
10.225.89.37:5696.verify=true
10.225.89.37:5696.netapp_keystore_uuid=26649a0c-aeab-11ef-b7b4-d039eaa9ec70
....
=====
+
... If prompted, enter the ONTAP Cluster UUID from the partner.
+
.Show example of ONTAP Cluster UUID
[%collapsible]

=====
....
Notice: bootarg.mgwd.cluster_uuid is not set or is empty.
Do you know the ONTAP Cluster UUID? {y/n} y
Enter the ONTAP Cluster UUID: 7b0f6db4-aea8-11ef-910f-d039eaaa0f91
 
 
System is ready to utilize external key manager(s).
....
=====
+

... If prompted, enter the temporary network interface and settings for the node.
+
.Show example of a temporary network setting
[%collapsible]

=====
....
In order to recover key information, a temporary network interface needs to be
configured.
 
Select the network port you want to use (for example, 'e0a')
e0M
 
Enter the IP address for port : 10.53.251.23
Enter the netmask for port : 255.255.252.0
Enter IP address of default gateway: 10.53.248.1
Trying to recover keys from key servers....
[discover_versions]
[status=SUCCESS reason= message=]
....
=====



... Depending on whether the key is successfully restored, take one of the following actions:

* If the EKM configuration has been restored, the process attempts to restore the Mroot-AK onto the node, then restores the backup config, env file, mdb, and rdb from the partner node and reboots the node. Proceed to step c.
+
.Show example of successful restore messages
[%collapsible]

=====
....

System is ready to utilize external key manager(s).
Trying to recover keys from key servers....
[discover_versions]
[status=SUCCESS reason= message=]
...
kmip2_client: Successfully imported the keys from external key server: 10.225.89.37:5696
Successfully recovered keymanager secrets.
....
=====

* If the key is not successfully restored, the system will halt and indicate that it could not restore the key. The error and warning messages are displayed. Rerun the recovery process by entering `boot_recovery -partner`.
+
.Show example of key recovery error and warning messages
[%collapsible]

=====
....

ERROR: kmip_init: halting this system with encrypted mroot...
WARNING: kmip_init: authentication keys might not be available.
********************************************************
*                 A T T E N T I O N                    *
*                                                      *
*       System cannot connect to key managers.         *
*                                                      *
********************************************************
ERROR: kmip_init: halting this system with encrypted mroot...
.
Terminated
 
Uptime: 11m32s
System halting...
 
LOADER-B>
....


=====


.. When the node reboots, verify the boot media recovery was successful by confirming that the system is back online and operational.

.. Return the impaired controller to normal operation by giving back its storage:
+
`storage failover giveback -ofnode _impaired_node_name_`.
--
====

// end tabbed area

[start=6]

. If automatic giveback was disabled, reenable it: 
+
`storage failover modify -node local -auto-giveback true`.

. If AutoSupport is enabled, restore automatic case creation: 
+
`system node autosupport invoke -node * -type all -message MAINT=END`.