You can restore the ONTAP image (boot media recovery) from the partner node using the `boot_recovery partner` with ASA r2 platforms running ONTAP 9.16.0 and later. 


== Single node boot media replacement

.Before you begin

You can restore the ONTAP image (boot media recovery) from the partner node using the `boot_recovery partner` command with ASA r2 platforms running ONTAP 9.16.0 and later. 

When you boot a node and the boot media on that node is corrupted, you'll see the following messages and the boot process with stop at the LOADER prompt:

----

Can't find primary boot device u0a.0
Can't find backup boot device u0a.1
ACPI RSDP Found at 0x777fe014
 
 
Starting AUTOBOOT press Ctrl-C to abort...
Could not load fat://boot0/X86_64/freebsd/image1/kernel:Device not found
 
ERROR: Error booting OS on: 'boot0' file: fat://boot0/X86_64/Linux/image1/vmlinuz (boot0,fat)
 
 
ERROR: Error booting OS on: 'boot0' file: fat://boot0/X86_64/freebsd/image1/kernel (boot0,fat)
 
 
Autoboot of PRIMARY image failed. Device not found (-6)
LOADER-A>

-----

If you see this message, you must restore the ONTAP image

.Steps




. Check which version of LOADER is on your system with the 
. From the LOADER prompt, use the _boot_recovery partner_ command.

+
If online key manager (OKM) is configured, you wil see the following displayed:

====
key manager is configured.
Entering Bootmenu Option 10...
 
This option must be used only in disaster recovery procedures. Are you sure? (y or n):
====

Enter _y_ to start the OKM recovery process.
+

== Boot media replacement on systems with OKM

== Boot media replacement on systems with EKM