.Before you begin

* Determine your key manager type:
** Onboard Key Manager (OKM): Requires cluster-wide passphrase and backup data
** External Key Manager (EKM): Requires the following files from the partner node:
*** `/cfcard/kmip/servers.cfg`
*** `/cfcard/kmip/certs/client.crt`
*** `/cfcard/kmip/certs/client.key`
*** `/cfcard/kmip/certs/CA.pem`


.Steps

. From the LOADER prompt, start the boot media recovery process:
+
`boot_recovery -partner`
+
The screen displays the following message:
+
`Starting boot media recovery (BMR) process. Press Ctrl-C to abort…`

. Monitor the boot media install recovery process.
+
The process completes and displays the `Installation complete` message.  

. The system checks for encryption and displays one of the following messages:
+
[options="header" cols="1,2"]
|===
| If you see this message...| Do this...
a|
`key manager is not configured. Exiting.` 
a|
Encryption is not installed on the system. 

.. Wait for the login prompt to display.
.. Log into the node and give back the storage:
+
`storage failover giveback -ofnode _impaired_node_name_`

.. Go to <<reenable-auto-giveback,re-enabling automatic giveback>> if it was disabled.

a|
`key manager is configured.` 
a|
Encryption is installed. Go to <<restore-key-manager,restoring the key manager>>.

|===
+
NOTE: If the system cannot identify the key manager configuration, it displays an error message and prompts you to confirm whether key manager is configured and which type (onboard or external). Answer the prompts to proceed.

[[restore-key-manager]]
. Restore the key manager using the appropriate procedure for your configuration:
+
// start tabbed area
+
[role="tabbed-block"]
====

.Onboard Key Manager (OKM)
--
The system displays the following message and begins running BootMenu Option 10:
....
key manager is configured.
Entering Bootmenu Option 10...
 
This option must be used only in disaster recovery procedures. Are you sure? (y or n):
....

.. Enter `y` at the prompt to confirm you want to start the OKM recovery process.

.. Enter the passphrase for onboard key management when prompted.

.. Enter the passphrase again when prompted to confirm.

.. Enter the backup data for onboard key manager when prompted.
+
.Show example of passphrase and backup data prompts
[%collapsible]

=====
....
Enter the passphrase for onboard key management:
-----BEGIN PASSPHRASE-----
<passphrase_value>
-----END PASSPHRASE-----
Enter the passphrase again to confirm:
-----BEGIN PASSPHRASE-----
<passphrase_value>
-----END PASSPHRASE-----
Enter the backup data:
-----BEGIN BACKUP-----
<passphrase_value>
-----END BACKUP-----
....
=====

.. Monitor the recovery process as it restores the appropriate files from the partner node.
+
When the recovery process is complete, the node reboots. The following messages indicate a successful recovery:
+
....
Trying to recover keymanager secrets.... 
Setting recovery material for the onboard key manager 
Recovery secrets set successfully
Trying to delete any existing km_onboard.keydb file.
 
Successfully recovered keymanager secrets.
....

.. After the node reboots, verify that the system is back online and operational.

.. Return the impaired controller to normal operation by giving back its storage:
+
`storage failover giveback -ofnode _impaired_node_name_`

.. After the partner node is fully up and serving data, synchronize the OKM keys across the cluster:
+
`security key-manager onboard sync`
+
Go to <<reenable-auto-giveback,re-enabling automatic giveback>> if it was disabled.
--

.External Key Manager (EKM)
--
The system displays the following message and begins running BootMenu Option 11:
....
key manager is configured.
Entering Bootmenu Option 11...
....

.. Enter the EKM configuration settings when prompted:
+
... Enter the client certificate contents from the `/cfcard/kmip/certs/client.crt` file:
+
.Show example of client certificate contents
[%collapsible]

=====
....
-----BEGIN CERTIFICATE-----
<certificate_value>
-----END CERTIFICATE-----
....
=====
 
... Enter the client key file contents from the `/cfcard/kmip/certs/client.key` file:
+
.Show example of client key file contents
[%collapsible]

=====
....
-----BEGIN RSA PRIVATE KEY-----
<key_value>
-----END RSA PRIVATE KEY-----
....
=====

... Enter the KMIP server CA(s) file contents from the `/cfcard/kmip/certs/CA.pem` file:
+
.Show example of KMIP server file contents
[%collapsible]

=====
....
-----BEGIN CERTIFICATE-----
<KMIP_certificate_CA_value>
-----END CERTIFICATE-----
....
=====

... Enter the server configuration file contents from the `/cfcard/kmip/servers.cfg` file:
+
.Show example of server configuration file contents
[%collapsible]

=====
....
xxx.xxx.xxx.xxx:5696.host=xxx.xxx.xxx.xxx
xxx.xxx.xxx.xxx:5696.port=5696
xxx.xxx.xxx.xxx:5696.trusted_file=/cfcard/kmip/certs/CA.pem
xxx.xxx.xxx.xxx:5696.protocol=KMIP1_4
1xxx.xxx.xxx.xxx:5696.timeout=25
xxx.xxx.xxx.xxx:5696.nbio=1
xxx.xxx.xxx.xxx:5696.cert_file=/cfcard/kmip/certs/client.crt
xxx.xxx.xxx.xxx:5696.key_file=/cfcard/kmip/certs/client.key
xxx.xxx.xxx.xxx:5696.ciphers="TLSv1.2:kRSA:!CAMELLIA:!IDEA:!RC2:!RC4:!SEED:!eNULL:!aNULL"
xxx.xxx.xxx.xxx:5696.verify=true
xxx.xxx.xxx.xxx:5696.netapp_keystore_uuid=<id_value>
....
=====
 
... If prompted, enter the ONTAP Cluster UUID from the partner node. You can check the cluster UUID from the partner node using the `cluster identify show` command.
+
.Show example of ONTAP Cluster UUID prompt
[%collapsible]

=====
....
Notice: bootarg.mgwd.cluster_uuid is not set or is empty.
Do you know the ONTAP Cluster UUID? {y/n} y
Enter the ONTAP Cluster UUID: <cluster_uuid_value>
 
 
System is ready to utilize external key manager(s).
....
=====
 
... If prompted, enter the temporary network interface and settings for the node:
+
* The IP address for the port
* The netmask for the port
* The IP address of the default gateway
+
.Show example of temporary network setting prompts
[%collapsible]

=====
....
In order to recover key information, a temporary network interface needs to be
configured.
 
Select the network port you want to use (for example, 'e0a')
e0M
 
Enter the IP address for port : xxx.xxx.xxx.xxx
Enter the netmask for port : xxx.xxx.xxx.xxx
Enter IP address of default gateway: xxx.xxx.xxx.xxx
Trying to recover keys from key servers....
[discover_versions]
[status=SUCCESS reason= message=]
....
=====

.. Verify the key restoration status:
+
** If you see `kmip2_client: Successfully imported the keys from external key server: xxx.xxx.xxx.xxx:5696` in the output, the EKM configuration has been successfully restored. The process restores the appropriate files from the partner node and reboots the node. Proceed to the next step.
+
** If the key is not successfully restored, the system halts and displays error and warning messages. Rerun the recovery process from the LOADER prompt: `boot_recovery -partner`
+
.Show example of key recovery error and warning messages
[%collapsible]

=====
....
ERROR: kmip_init: halting this system with encrypted mroot...
WARNING: kmip_init: authentication keys might not be available.
********************************************************
*                 A T T E N T I O N                    *
*                                                      *
*       System cannot connect to key managers.         *
*                                                      *
********************************************************
ERROR: kmip_init: halting this system with encrypted mroot...
.
Terminated
 
Uptime: 11m32s
System halting...
 
LOADER-B>
....
=====

.. After the node reboots, verify that the system is back online and operational.

.. Return the controller to normal operation by giving back its storage:
+
`storage failover giveback -ofnode _impaired_node_name_`
+
Go to <<reenable-auto-giveback,re-enabling automatic giveback>> if it was disabled.

--
====

// end tabbed area

[start=5]

[[reenable-auto-giveback]]
. If automatic giveback was disabled, reenable it: 
+
`storage failover modify -node local -auto-giveback true`

. If AutoSupport is enabled, restore automatic case creation: 
+
`system node autosupport invoke -node * -type all -message MAINT=END`

//2025-11-17 ontap-systems-internal/issues/1391
