
.Before you begin

* Ensure your console is connected to the impaired controller.
* Verify the e0S interface (e0M wrench port) on the impaired controller is not faulty.
* Verify you have a USB flash drive with the recovery image.
* Determine if your system uses encryption. You will need to select the appropriate option in step 3 based on whether encryption is enabled.

.Steps

. From the LOADER prompt on the impaired controller, boot the recovery image from the USB flash drive:
+
`boot_recovery`
+
The recovery image is downloaded from the USB flash drive.

. When prompted, enter the name of the image or press *Enter* to accept the default image displayed in brackets.

. Restore the var file system:
+
[options="header" cols="1,2"]
|===
| If your system has... | Then...

a|
A network connection and is running ONTAP 9.16.0 or earlier
a|
Complete the following steps on the impaired controller and partner controller:

 .. *On the impaired controller:* Press `Y` when you see `Do you want to restore the backup configuration now?`

 .. *On the impaired controller:* If prompted, press `Y` to overwrite _/etc/ssh/ssh_host_ecdsa_key_.

 .. *On the partner controller:* Set the impaired controller to advanced privilege level:
+
`set -privilege advanced`

 .. *On the partner controller:* Run the restore backup command:
+
`system node restore-backup -node local -target-address _impaired_node_IP_address_`
+
NOTE: If you see any message other than a successful restore, contact NetApp Support.

 .. *On the partner controller:* Return to admin level:
+
`set -privilege admin`

 .. *On the impaired controller:* Press `Y` when you see `Was the restore backup procedure successful?`

 .. *On the impaired controller:* Press `Y` when you see `...would you like to use this restored copy now?`

 .. *On the impaired controller:* Press `Y` when prompted to reboot, then press `Ctrl-C` when you see the Boot Menu.

 .. *On the impaired controller:* Do one of the following:
+
* If the system does not use encryption, select _Option 1 Normal Boot_ from the Boot Menu.
+
* If the system uses encryption, go to link:bootmedia-encryption-restore.html[Restore encryption].

a|
A network connection and is running ONTAP 9.16.1 or later
a|
Complete the following steps on the impaired controller:

 .. Press `Y` when prompted to restore the backup configuration.
+
After the restore procedure is successful, this message displays: `syncflash_partner: Restore from partner complete`

 .. Press `Y` when prompted to confirm that the restore backup was successful.

 .. Press `Y` when prompted to use the restored configuration.

 .. Press `Y` when prompted to reboot the node.

 .. Press `Y` when prompted to reboot again, then press `Ctrl-C` when you see the Boot Menu.

 .. Do one of the following:
+
* If the system does not use encryption, select _Option 1 Normal Boot_ from the Boot Menu.
+
* If the system uses encryption, go to link:bootmedia-encryption-restore.html[Restore encryption].

a|
No network connection
a|
 .. Press `N` when prompted to restore the backup configuration.
 .. Reboot the system when prompted by the system.
 .. Select the *Update flash from backup config* (sync flash) option from the displayed menu.
+
If you are prompted to continue with the update, press `Y`.
 .. Press `Ctrl-C` when you see the Boot Menu.
 .. Do one of the following:
+
* If the system does not use encryption, select _Option 1 Normal Boot_ from the Boot Menu.
+
* If the system uses encryption, go to link:bootmedia-encryption-restore.html[Restore encryption].

a|
No network connection and is in a MetroCluster IP configuration
a|
 .. Press `N` when prompted to restore the backup configuration.
 .. Reboot the system when prompted by the system.
 .. Wait for the iSCSI storage connections to connect.
+
You can proceed after you see the following messages:
+
----
date-and-time [node-name:iscsi.session.stateChanged:notice]: iSCSI session state is changed to Connected for the target iSCSI-target (type: dr_auxiliary, address: ip-address).
date-and-time [node-name:iscsi.session.stateChanged:notice]: iSCSI session state is changed to Connected for the target iSCSI-target (type: dr_partner, address: ip-address).
date-and-time [node-name:iscsi.session.stateChanged:notice]: iSCSI session state is changed to Connected for the target iSCSI-target (type: dr_auxiliary, address: ip-address).
date-and-time [node-name:iscsi.session.stateChanged:notice]: iSCSI session state is changed to Connected for the target iSCSI-target (type: dr_partner, address: ip-address).
----
 .. Select the *Update flash from backup config* (sync flash) option from the displayed menu.
+
If you are prompted to continue with the update, press `Y`.
 .. Press `Ctrl-C` when you see the Boot Menu.
 .. Do one of the following:
+
* If the system does not use encryption, select _Option 1 Normal Boot_ from the Boot Menu.
+
* If the system uses encryption, go to link:bootmedia-encryption-restore.html[Restore encryption].

|===

. Connect the console cable to the partner controller.

. Return the controller to normal operation by giving back its storage:
+
`storage failover giveback -fromnode local`

. If you disabled automatic giveback, reenable it:
+
`storage failover modify -node local -auto-giveback true`

. If AutoSupport is enabled, restore automatic case creation:
+
`system node autosupport invoke -node * -type all -message MAINT=END`

//2025-11-25 ontap-systems-internal/1315 and ontap-systems-internal/1380
