
Complete the appropriate steps to restore encryption on your system based on your key manager type. If you are unsure which key manager your system uses, check the settings you captured at the beginning of the boot media replacement procedure.

[role="tabbed-block"]
====

.Onboard Key Manager (OKM)
--
Restore the Onboard Key Manager (OKM) configuration from the ONTAP boot menu.

.Before you begin

Ensure you have the following information available:

* Cluster-wide passphrase entered while https://docs.netapp.com/us-en/ontap/encryption-at-rest/enable-onboard-key-management-96-later-nse-task.html[enabling onboard key management]
* https://docs.netapp.com/us-en/ontap/encryption-at-rest/backup-key-management-information-manual-task.html[Backup information for the Onboard Key Manager]
* Verification that you have the correct passphrase and backup data using the https://kb.netapp.com/on-prem/ontap/Ontap_OS/OS-KBs/How_to_verify_onboard_key_management_backup_and_cluster-wide_passphrase[How to verify onboard key management backup and cluster-wide passphrase] procedure

.Steps

*On the impaired controller:*

. Connect the console cable to the impaired controller.

. From the ONTAP boot menu, select the appropriate option:
+
[cols="1a,2a" options="header"]
|===
| ONTAP version| Select this option
a|
ONTAP 9.8 or later
a|
Select option 10.

// Start snippet: collapsible block
.Show example boot menu
[%collapsible]
=====
....

Please choose one of the following:

(1)  Normal Boot.
(2)  Boot without /etc/rc.
(3)  Change password.
(4)  Clean configuration and initialize all disks.
(5)  Maintenance mode boot.
(6)  Update flash from backup config.
(7)  Install new software first.
(8)  Reboot node.
(9)  Configure Advanced Drive Partitioning.
(10) Set Onboard Key Manager recovery secrets.
(11) Configure node for external key management.
Selection (1-11)? 10

....
=====
// End snippet


a|
ONTAP 9.7 and earlier
a|
Select the hidden option `recover_onboard_keymanager`

// Start snippet: collapsible block
.Show example boot menu
[%collapsible]
=====
....

Please choose one of the following:

(1)  Normal Boot.
(2)  Boot without /etc/rc.
(3)  Change password.
(4)  Clean configuration and initialize all disks.
(5)  Maintenance mode boot.
(6)  Update flash from backup config.
(7)  Install new software first.
(8)  Reboot node.
(9)  Configure Advanced Drive Partitioning.
Selection (1-19)? recover_onboard_keymanager

....
=====
// End snippet

|===

+
. Confirm that you want to continue the recovery process when prompted:
+
.Show example prompt
[%collapsible]
=====
`This option must be used only in disaster recovery procedures. Are you sure? (y or n):`
=====

. Enter the cluster-wide passphrase twice.
+
While entering the passphrase, the console does not show any input.
+
.Show example prompt
[%collapsible]
=====
`Enter the passphrase for onboard key management:`

`Enter the passphrase again to confirm:`
=====
+

. Enter the backup information:
.. Paste the entire content from the BEGIN BACKUP line through the END BACKUP line, including the dashes.
+
.Show example prompt
[%collapsible]
=====
....
Enter the backup data:

--------------------------BEGIN BACKUP--------------------------
0123456789012345678901234567890123456789012345678901234567890123
1234567890123456789012345678901234567890123456789012345678901234
2345678901234567890123456789012345678901234567890123456789012345
3456789012345678901234567890123456789012345678901234567890123456
4567890123456789012345678901234567890123456789012345678901234567
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
0123456789012345678901234567890123456789012345678901234567890123
1234567890123456789012345678901234567890123456789012345678901234
2345678901234567890123456789012345678901234567890123456789012345
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

---------------------------END BACKUP---------------------------

....
=====
+
.. Press Enter twice at the end of the input.
+
The recovery process completes and displays the following message:
+
`Successfully recovered keymanager secrets.`
+
.Show example prompt
[%collapsible]
=====
....

Trying to recover keymanager secrets....
Setting recovery material for the onboard key manager
Recovery secrets set successfully
Trying to delete any existing km_onboard.wkeydb file.

Successfully recovered keymanager secrets.

***********************************************************************************
* Select option "(1) Normal Boot." to complete recovery process.
*
* Run the "security key-manager onboard sync" command to synchronize the key database after the node reboots.
***********************************************************************************

....
=====
+
WARNING: Do not proceed if the displayed output is anything other than `Successfully recovered keymanager secrets`. Perform troubleshooting to correct the error.

. Select option `1` from the boot menu to continue booting into ONTAP.
+
.Show example prompt
[%collapsible]
=====
....

***********************************************************************************
* Select option "(1) Normal Boot." to complete the recovery process.
*
***********************************************************************************


(1)  Normal Boot.
(2)  Boot without /etc/rc.
(3)  Change password.
(4)  Clean configuration and initialize all disks.
(5)  Maintenance mode boot.
(6)  Update flash from backup config.
(7)  Install new software first.
(8)  Reboot node.
(9)  Configure Advanced Drive Partitioning.
(10) Set Onboard Key Manager recovery secrets.
(11) Configure node for external key management.
Selection (1-11)? 1

....
=====

. Confirm that the controller's console displays the following message:
+
`Waiting for giveback...(Press Ctrl-C to abort wait)`
+
*On the partner controller:*

. Giveback the impaired controller:
+
`storage failover giveback -fromnode local -only-cfo-aggregates true`
+
*On the impaired controller:*

. After booting with only the CFO aggregate, synchronize the key manager:
+
`security key-manager onboard sync`

. Enter the cluster-wide passphrase for the Onboard Key Manager when prompted.
+
.Show example prompt
[%collapsible]
=====
....

Enter the cluster-wide passphrase for the Onboard Key Manager:

All offline encrypted volumes will be brought online and the corresponding volume encryption keys (VEKs) will be restored automatically within 10 minutes. If any offline encrypted volumes are not brought online automatically, they can be brought online manually using the "volume online -vserver <vserver> -volume <volume_name>" command.

....
=====
+
NOTE: If the sync is successful, the cluster prompt is returned with no additional messages. If the sync fails, an error message appears before returning to the cluster prompt. Do not continue until the error is corrected and the sync runs successfully.

. Verify that all keys are synced:
+
`security key-manager key query -restored false`
+
The command should return no results. If any results appear, repeat the sync command until no results are returned.
+
*On the partner controller:*

. Giveback the impaired controller:
+
`storage failover giveback -fromnode local`

. Restore automatic giveback if you disabled it:
+
`storage failover modify -node local -auto-giveback true`

. If AutoSupport is enabled, restore automatic case creation:
+
`system node autosupport invoke -node * -type all -message MAINT=END`

--

.External Key Manager (EKM)
--
Restore the External Key Manager configuration from the ONTAP boot menu.

.Before you begin

Gather the following files from another cluster node or from your backup:

* `/cfcard/kmip/servers.cfg` file or the KMIP server address and port
* `/cfcard/kmip/certs/client.crt` file (client certificate)
* `/cfcard/kmip/certs/client.key` file (client key)
* `/cfcard/kmip/certs/CA.pem` file (KMIP server CA certificates)

.Steps

*On the impaired controller:*

. Connect the console cable to the impaired controller.

. Select option `11` from the ONTAP boot menu.
+
.Show example boot menu
[%collapsible]
=====
....

(1)  Normal Boot.
(2)  Boot without /etc/rc.
(3)  Change password.
(4)  Clean configuration and initialize all disks.
(5)  Maintenance mode boot.
(6)  Update flash from backup config.
(7)  Install new software first.
(8)  Reboot node.
(9)  Configure Advanced Drive Partitioning.
(10) Set Onboard Key Manager recovery secrets.
(11) Configure node for external key management.
Selection (1-11)? 11
....

=====

. Confirm you have gathered the required information when prompted:
+
.Show example prompt
[%collapsible]
=====
....
Do you have a copy of the /cfcard/kmip/certs/client.crt file? {y/n} 
Do you have a copy of the /cfcard/kmip/certs/client.key file? {y/n}
Do you have a copy of the /cfcard/kmip/certs/CA.pem file? {y/n}
Do you have a copy of the /cfcard/kmip/servers.cfg file? {y/n}
....
=====

. Enter the client and server information when prompted:
.. Enter the client certificate (client.crt) file contents, including the BEGIN and END lines.
.. Enter the client key (client.key) file contents, including the BEGIN and END lines.
.. Enter the KMIP server CA(s) (CA.pem) file contents, including the BEGIN and END lines.
.. Enter the KMIP server IP address.
.. Enter the KMIP server port (press Enter to use the default port 5696).
+
.Show example
[%collapsible]
=====

....
Enter the client certificate (client.crt) file contents:
-----BEGIN CERTIFICATE-----
<certificate_value>
-----END CERTIFICATE-----

Enter the client key (client.key) file contents:
-----BEGIN RSA PRIVATE KEY-----
<key_value>
-----END RSA PRIVATE KEY-----

Enter the KMIP server CA(s) (CA.pem) file contents:
-----BEGIN CERTIFICATE-----
<certificate_value>
-----END CERTIFICATE-----

Enter the IP address for the KMIP server: 10.10.10.10
Enter the port for the KMIP server [5696]:

System is ready to utilize external key manager(s).
Trying to recover keys from key servers....
kmip_init: configuring ports
Running command '/sbin/ifconfig e0M'
..
..
kmip_init: cmd: ReleaseExtraBSDPort e0M
....
=====
+
The recovery process completes and displays the following message:
+
`Successfully recovered keymanager secrets.`
+
.Show example
[%collapsible]
=====
....
System is ready to utilize external key manager(s).
Trying to recover keys from key servers....
Performing initialization of OpenSSL
Successfully recovered keymanager secrets.
....
=====

. Select option `1` from the boot menu to continue booting into ONTAP.
+
.Show example prompt
[%collapsible]
=====
....

***************************************************************************
* Select option "(1) Normal Boot." to complete the recovery process.
*
***************************************************************************

(1)  Normal Boot.
(2)  Boot without /etc/rc.
(3)  Change password.
(4)  Clean configuration and initialize all disks.
(5)  Maintenance mode boot.
(6)  Update flash from backup config.
(7)  Install new software first.
(8)  Reboot node.
(9)  Configure Advanced Drive Partitioning.
(10) Set Onboard Key Manager recovery secrets.
(11) Configure node for external key management.
Selection (1-11)? 1

....
=====

. Restore automatic giveback if you disabled it:
+
`storage failover modify -node local -auto-giveback true`

. If AutoSupport is enabled, restore automatic case creation:
+
`system node autosupport invoke -node * -type all -message MAINT=END`

--

====
//2025-11-25 ontap-systems-internal/1315 and ontap-systems-internal/1380
