Before shutting down the impaired controller, you should determine if your cluster version supports NVE or is running OKM or EKM. You need this information in order to download the correct version of the ONTAP image for the system.

== Check if your version of ONTAP supports encryption

.Steps
 . Determine if your ONTAP version supports NVE: `version -v`
+ 
NVE is not supported if the command output displays the text _1Ono-DARE_ (for “no Data At Rest Encryption”), or if you are using a platform that is not listed in Support details.

+
....
cluster1::> version -v
NetApp Release 9.x.x: Tue May 10 19:30:23 UTC 2016 <1Ono-DARE>
....

+

The output of `1Ono-DARE`  indicates that NVE is not supported on your cluster version.


.. IF NVE is supported, download the ONTAP image with NetApp Volume Encryption.
.. If NVE is not supported, download the ONTAP version without NetApp Volume Encryption.

. Determine if Onboard Key Manager is enabled (OKM).
.. If the node is running ONTAP 9.14.1 or later, enter the `security key-manager keystore show` command. If OKM is enabled, it will be listed as _OKM_in the command output.

.. If the node is running ONTAP 9.13.1 or earlier, enter the `security key-manager show-key-store` command. If OKM is enabled, it will be listed as _onboardM_in the command output.

. Determine if External Key Manager is enabled by entering the `security key-manager show-key-store` command.  If it is enabled, it will be listed as _external_ in the command output.

== Determine the status of any key managers

. Display the information for the active `Key Manager` using the _security key-manager key query_ command:

[cols="1a,2a,3a" options="header"]
|===
| If Key Manager displays...| Restored column displays...| Then...
a|
`external` 
a|
`true`  
a| 
It is safe to shutdown the impaired controller.
a|
`onboard`
a|
`true`
a|
Manually back up the OKM information:

. Go to advanced mode by entering _set -priv advanced_ and enter _y_ when prompted
. Enter the command to display the key management information: _security key-manager onboard show-backup_.
 . Copy the contents of the backup information to a separate file or your log file. You'll need it in disaster scenarios where you might need to manually recover OKM.
 . Shut down the impaired controller.
a|
`external` 
a|
Anything other than `true`
a|
. Restore the external key management authentication keys to all nodes in the cluster by entering the _security key-manager external restore_ command.
+
If the command fails, contact NetApp Support at http://mysupport.netapp.com/[mysupport.netapp.com^].

 . Verify that the `Restored` column displays `true` for all authentication keys by entering the  _security key-manager key query_ command.
 .If all the authentication keys are `true`, you can safely shut down the impaired controller.
a|
`onboard`
a|
Anything other than `true`
a|
. Enter the onboard security key-manager sync command: _security key-manager onboard sync_
+
NOTE: Enter the 32 character, alphanumeric onboard key management passphrase at the prompt. If the passphrase cannot be provided, contact NetApp Support. http://mysupport.netapp.com/[mysupport.netapp.com^]

 . Verify the `Restored` column displays `true` for all authentication keys: `security key-manager key query`
 . Verify that the `Key Manager` type displays `onboard`, and then manually back up the OKM information.
  . Enter the command to display the key management backup information: _security key-manager onboard show-backup_
 . Copy the contents of the backup information to a separate file or your log file. You'll need it in disaster scenarios where you might need to manually recover OKM.
 . You can safely shut down the controller.

|===
