.Steps

. Determine which key manager is enabled on your system:
+

[cols="1a,2a" options="header"]
|===
| ONTAP version| Run this command
a|
ONTAP 9.14.1 or later
a|

`security key-manager keystore show` 

* If EKM is enabled, `EKM` is listed in the command output.
* If OKM is enabled, `OKM` is listed in the command output.
* If no key manager is enabled, `No key manager keystores configured` is listed in the command output.

a|
ONTAP 9.13.1 or earlier
a|

`security key-manager show-key-store` 

* If EKM is enabled, `external` is listed in the command output.
* If OKM is enabled, `onboard` is listed in the command output.
* If no key manager is enabled, `No key managers configured` is listed in the command output.
|===

. Depending on whether a key manager is configured on your system, do one of the following:
+
*If no key manager is configured:*
+
You can safely shut down the impaired controller and proceed to the shutdown procedure.
+
*If a key manager is configured (EKM or OKM):*
+
.. Enter the following query command to display the status of the authentication keys in your key manager:
+
`security key-manager key query`

.. Review the output and check the value in the `Restored` column. This column indicates whether the authentication keys for your key manager (either EKM or OKM) have been successfully restored.

. Complete the appropriate procedure based on your key manager type:
+

[role="tabbed-block"]
====

.External Key Manager (EKM)
--
Complete these steps based on the value in the `Restored` column.

*If all keys show `true` in the Restored column:*

You can safely shut down the impaired controller and proceed to the shutdown procedure.

*If any keys show a value other than `true` in the Restored column:*

.. Restore the external key management authentication keys to all nodes in the cluster:
+
`security key-manager external restore`
+
If the command fails, contact NetApp Support.

.. Verify that all authentication keys are restored:
+
`security key-manager key query`
+
Confirm that the `Restored` column displays `true` for all authentication keys.

.. If all keys are restored, you can safely shut down the impaired controller and proceed to the shutdown procedure.

--

.Onboard Key Manager (OKM)
--
Complete these steps based on the value in the `Restored` column.

*If all keys show `true` in the Restored column:*

.. Back up the OKM information:
... Switch to advanced privilege mode:
+
`set -priv advanced`
+
Enter `y` when prompted to continue.

... Display the key management backup information:
+
`security key-manager onboard show-backup`

... Copy the backup information to a separate file or your log file.
+
You will need this backup information if you need to manually recover OKM during the replacement procedure.

... Return to admin mode:
+
`set -priv admin`

.. You can safely shut down the impaired controller and proceed to the shutdown procedure.

*If any keys show a value other than `true` in the Restored column:*

.. Synchronize the onboard key manager:
+
`security key-manager onboard sync`
+
Enter the 32-character alphanumeric onboard key management passphrase when prompted.
+
NOTE: This is the cluster-wide passphrase you created when you initially configured the Onboard Key Manager. If you do not have this passphrase, contact NetApp Support.

.. Verify all authentication keys are restored:
+
`security key-manager key query`
+
Confirm that the `Restored` column displays `true` for all authentication keys and the `Key Manager` type shows `onboard`.

.. Back up the OKM information:
... Switch to advanced privilege mode:
+
`set -priv advanced`
+
Enter `y` when prompted to continue.

... Display the key management backup information:
+
`security key-manager onboard show-backup`

... Copy the backup information to a separate file or your log file.
+
You will need this backup information if you need to manually recover OKM during the replacement procedure.

... Return to admin mode:
+
`set -priv admin`

.. You can safely shut down the impaired controller and proceed to the shutdown procedure.

--
====

// end tabbed area
//2025-11-25 ontap-systems-internal/1315 and ontap-systems-internal/1380
