
== Requirements
* You must replace the failed component with a replacement FRU component of the same capacity that you received from NetApp.

* The e0S (e0M wrench) port on the impaired controller cannot be faulty. 
+
The e0S port is used for automated boot recovery.
  
* Determine if Onboard Key Manger (OKM) or Eternal Key Manager (EKM) is configured using one of the following methods:
** You can ask the system administrator if OKM or EKM are enabled.
** To check if OKM is enabled, you can use the `security key-manager onboard show`.
** To check if EKM is enabled, you can use the `security key-manager external show`.
* For OKM, you need the OKM passphrase file contents.
* For EKM, you need copies of the following files from the partner node:
** /cfcard/kmip/servers.cfg file.
** /cfcard/kmip/certs/client.crt file. 
** /cfcard/kmip/certs/client.key file.
** /cfcard/kmip/certs/CA.pem file.

== Considerations

* It is important that you apply the commands in these steps on the correct controller:
** The _impaired_ controller is the controller on which you are performing maintenance.
** The _healthy_ controller is the HA partner of the impaired controller.

* If needed, you can turn on the platform chassis location (blue) LEDs to aid in physically locating the affected platform. Log into the BMC using SSH and enter the `system location-led _on_` command.
+
A platform chassis has three location LEDs: one on the operator display panel and one on each controller. Location LEDs remain illuminated for 30 minutes. 
+
You can turn them off by entering the `system location-led _off_` command. If you are unsure if the LEDs are on or off, you can check their state by entering the `system location-led show` command.
