You must verify the HA state of the chassis and return the failed part to NetApp, as described in the RMA instructions shipped with the kit.

== Step 1: Verify and set the HA state of the chassis

You must verify the HA state of the chassis, and, if necessary, update the state to match your storage system configuration.

. In Maintenance mode, from either controller, display the HA state of the local controller and chassis: `ha-config show`
+
The HA state should be the same for all components.

. If the displayed system state for the chassis does not match your storage system configuration:
.. Set the HA state for the chassis: `ha-config modify chassis _HA-state_`
+
The value for HA-state can be one of the following:

*** `ha`
// *** `mcc` (not supported in ASA)
.. Confirm that the setting has changed: `ha-config show`
. If you have not already done so, recable the rest of your storage system.



== Step 2: Return the failed part to NetApp

include::../_include/complete_rma.adoc[]
