You must review the requirements and considerations for the controller replacement procedure and select the correct one for your version of the ONTAP operating system.

== Requirements

* All drive shelves must be working properly.
* The healthy controller must be able to take over the controller that is being replaced (referred to in this procedure as the "`impaired controller`").
* If your system is in a MetroCluster configuration, you must review the section https://docs.netapp.com/us-en/ontap-metrocluster/disaster-recovery/concept_choosing_the_correct_recovery_procedure_parent_concept.html[Choosing the correct recovery procedure] to determine whether you should use this procedure.
* You must replace the failed component with a replacement FRU component you received from your provider.
* You must replace a controller module with a controller module of the same model type. You cannot upgrade your system by just replacing the controller module.
* You cannot change any drives or drive shelves as part of this procedure.
* It is important that you apply the commands in these steps on the correct systems:
 ** The _impaired_ controller is the controller that is being replaced.
 ** The _replacement_ controller is the new controller that is replacing the impaired controller.
 ** The _healthy_ controller is the surviving controller.
* You must always capture the controller's console output to a text log file.
+
This provides you a record of the procedure so that you can troubleshoot any issues that you might encounter during the replacement process.

== Considerations
* If needed, you can turn on the platform chassis location (blue) LEDs to aid in physically locating the affected platform. Log into the BMC using SSH and enter the `system location-led _on_` command.
+
A platform chassis has three location LEDs: one on the operator display panel and one on each controller. Location LEDs remain illuminated for 30 minutes. 
+
You can turn them off by entering the `system location-led _off_` command. If you are unsure if the LEDs are on or off, you can check their state by entering the `system location-led show` command.

