// Install the controller module - AFF A20, A30, and AFF A50


After you replace the faulty FRU component, reinstall the controller into the chassis and reboot it.

. Close the controller cover and turn the thumbscrew clockwise until tightened.

. If you rotated the controller handles upright (but not in the locked position) to move them out of the way while you serviced the controller, rotate them down to the horizontal position.
+
The following illustration shows the operation of the controller handles (from the left side of a controller) when reinstalling the controller, and can be used as a reference for the rest of the controller reinstallation steps:
+
image::../media/drw_g_and_t_handles_reinstall_ieops-1838.svg[controller handle operation to install a controller]
+
[cols="1,4"]

|===
a|
image::../media/legend_icon_01.svg[Callout number 1,width=30px] 
a|
Rotate the handles down to the horizontal position.
a|
image::../media/legend_icon_02.svg[Callout number 2,width=30px] 
a|
Push handles to reinsert the controller into the chassis halfway and then, when instructed, push until the controller is fully seated.
a|
image::../media/legend_icon_03.svg[Callout number 3,width=30px] 
a|
Rotate handles to the upright position and lock in place with the locking tabs.

|===
+
. Insert the controller halfway into the chassis.
+
Align the rear of the controller with the opening in the chassis, and then gently push the controller using the handles.
+
NOTE: Do not completely insert the controller in the chassis until instructed to do so.
+

. Recable the controller, as needed.

. Fully seat the controller in the chassis:

.. Firmly push on the handles until the controller meets the midplane and is fully seated.
+
NOTE: Do not use excessive force when sliding the controller into the chassis; it could damage the connectors.
+
.. Rotate the controller handles upward to the closed position and lock in place with the tabs.

. Reconnect the power cable to the power supply on the impaired controller.

* If you have AC power supplies, reconnect the power cable to the power supply.

* If you have DC power supplies, reconnect the power block to the power supply.
+
[NOTE]
====
The controller boots when power is restored. 

If it boots to the LOADER prompt, reboot the controller with the `boot_ontap` command.
====

. Restore automatic giveback if you disabled it by using the `storage failover modify -node local -auto-giveback true` command.

. If AutoSupport is enabled, restore/unsuppress automatic case creation by using the `system node autosupport invoke -node * -type all -message MAINT=END` command.

