Review the requirements and considerations for the controller replacement procedure.

== Requirements

* All shelves must be working properly.
* The healthy controller must be able to take over the controller that is being replaced (referred to in this procedure as the "`impaired controller`").
* If your system is in a MetroCluster configuration, you must review the section https://docs.netapp.com/us-en/ontap-metrocluster/disaster-recovery/concept_choosing_the_correct_recovery_procedure_parent_concept.html[Choosing the correct recovery procedure] to determine whether you should use this procedure.
* You must replace a controller with a controller of the same model type. You cannot upgrade your system by just replacing the controller.
* You cannot change any drives or shelves as part of this procedure.
* You must always capture the controller's console output to a text log file.
+
The console output provides you with a record of the procedure you can use to troubleshoot issues you might encounter during the replacement process.

== Considerations
It is important that you apply the commands in this procedure to the correct controller:

* The _impaired_ controller is the controller that is being replaced.
* The _replacement_ controller is the new controller that is replacing the impaired controller.
* The _healthy_ controller is the surviving controller.


