

// New include specific to g-platform family because the slot 4 location for the cluster/HA I/O module is unique to g-platforms.


Prepare the I/O module slot 4 so that it is safe to remove the failed cluster and HA I/O module:

. Properly ground yourself.

. Unplug cabling from the failed cluster and HA I/O module.
+
Make sure to label the cables so that you know where they came from.

. If AutoSupport is enabled, suppress automatic case creation by invoking an AutoSupport message: 
+
`system node autosupport invoke -node * -type all -message MAINT=_number_of_hours_down_h`
+
For example, the following AutoSupport message suppresses automatic case creation for two hours:
+
`node1::> system node autosupport invoke -node * -type all -message MAINT=2h`

. Disable automatic giveback from the console of the impaired controller (the controller that took over the healthy partner controller): 
+
`storage failover modify -node local -auto-giveback false`
+
NOTE: When you see _Do you want to disable auto-giveback?_, enter `y`.

. Prepare the I/O module slot 4 on the impaired controller for removal:
+
`system controller slot module remove -node impaired_node_name_ -slot _slot_number_`
+
NOTE: When you see _Do you want to continue?_, enter `y`. 
+
For example, the following command prepares slot 4 on node1 (the impaired controller) for removal, and displays a message that it is safe to remove:
+
----
node1::> system controller slot module remove -node node1 -slot 4

Warning: IO_2X_100GBE_NVDA_NIC module in slot 4 of node node1 will be powered off for removal.

Do you want to continue? {y|n}: y

The module has been successfully removed from service and powered off. It can now be safely removed.
----

. Verify I/O module slot 4 on the impaired controller is powered off:
+
`system controller slot module show`
+
The output should show slot 4 status as `powered-off` on the impaired controller.



