

// New include specific to g-platform family because the slot 4 location for the cluster/HA I/O module is unique to g-platforms.


Prepare the I/O module slot 4 so that it is safe to remove the failed cluster/HA I/O module:

. Properly ground yourself.

. Unplug cabling from the failed cluster/HA I/O module.
+
Make sure to label the cables so that you know where they came from.

. Prepare the I/O module slot 4 on the impaired controller for removal:
+
`system controller slot module remove -node _node_name_ -slot _slot_number_`
+
NOTE: When you see _Do you want to continue?_, enter `y`. 
+
For example, the following command prepares slot 4 on node1 for removal, and displays a message that it is safe to remove:
+
----
node1::> system controller slot module remove -node node1 -slot 4

Warning: IO_2X_100GBE_NVDA_NIC module in slot 4 of node node1 will be powered off for removal.

Do you want to continue? {y|n}: y

The module has been successfully removed from service and powered off. It can now be safely removed.
----

. Verify I/O module slot 4 on the impaired controller is powered off:
+
`system controller slot module show`
+
The screen output should show `powered-off` for the slot 4 status on the impaired controller.



