
// Jan 2026: updated for 9.18.1GA support changes. https://jira.ngage.netapp.com/browse/AFFFASDOC-358

// July 2025: New include specific to g-platform family because the slot 4 location for the cluster/HA I/O module is unique to g-platforms.


Prepare the storage system and I/O module slot so that it is safe to remove the failed I/O module:

.Steps

. Properly ground yourself.

. Unplug cabling from the failed I/O module.
+
//Question to team and ADind from Tish: Do we want to reverse steps 2 and 3 so we disable autosupport before unplugging the cables?
+
Make sure to label the cables so that later in this procedure you can reconnect them to the same ports.

+
[NOTE]
====
The I/O module should be failed (ports should be in the link down state); however, if the links are still up and they contain the last functioning cluster port, unplugging the cables triggers an automatic takeover. 

// If the ports are not already in the link down state, taking ports down can cause a node takeover if all cluster ports are taken down. Please wait for several minutes after taking ports down to ensure automatic node takeovers or LIF failovers complete before continuing.

Wait five minutes after unplugging the cables to ensure any takeovers or LIF failovers complete before continuing with this procedure.

//Do we want the customer to do anything to verify a takeover or LIF failover is not in progress/has completed? T says nothing to verify,it is all automated and should be handled even if it doesn’t complete lif failover.   

//We expect this procedure to be used when the card is failed, but we need a note just in case. A failover in ONTAP refers to the process of transferring the storage of a node to another node, typically due to a failure or to prepare for a takeover. A takeover is the process of a node taking over the storage of its partner node. While a failover can be a precursor to a takeover, they are not the same. A failover is a temporary measure to ensure data availability, whereas a takeover is a permanent transfer of storage management responsibilities.
====

. If AutoSupport is enabled, suppress automatic case creation by invoking an AutoSupport message: 
+
`system node autosupport invoke -node * -type all -message MAINT=<number of hours down>h`
+
For example, the following AutoSupport message suppresses automatic case creation for two hours:
+
`node2::> system node autosupport invoke -node * -type all -message MAINT=2h`

. As needed for the version of ONTAP your storage system is running and the state of the controllers, disable automatic giveback:
//"If the partner node has been taken over, disable automatic giveback:" What's T mean by "partner"? I understand it as the healthy controller....maybe could be either controller.
+
[options="header" cols="1,2,3"]

|===
|ONTAP version| If...| Then...
a|
9.17.1 or 9.18.1RC
a|
If the impaired controller took over the healthy controller automatically
a|
Disable automatic giveback:

. Enter the following command from the console of the impaired controller 
+
`storage failover modify -node local -auto-giveback false`

. Enter `y` when you see the prompt _Do you want to disable auto-giveback?_
a|
9.18.1GA or later
a|
If either controller took over its partner automatically
a|
Disable automatic giveback:

. Enter the following command from the console of the controller that took over its partner: 
+
`storage failover modify -node local -auto-giveback false`

. Enter `y` when you see the prompt _Do you want to disable auto-giveback?_
a|
9.18.1GA or later
a|
Both controllers are up and running I/O (serving data)
a|
Go to the next step.
|===

. Prepare the failed I/O module for removal by removing it from service and powering it off:


.. Enter the following command:
+
`system controller slot module remove -node _impaired_node_name_ -slot _slot_number_`

.. Enter `y` when you see the prompt _Do you want to continue?_ 
+
For example, the following command prepares the failed module in slot 4 on node 2 (the impaired controller) for removal, and displays a message that it is safe to remove:
+
----
node2::> system controller slot module remove -node node2 -slot 4

Warning: IO_2X_100GBE_NVDA_NIC module in slot 4 of node node2 will be powered off for removal.

Do you want to continue? {y|n}: y

The module has been successfully removed from service and powered off. It can now be safely removed.
----

. Verify the failed I/O module is powered off:
+
`system controller slot module show`
+
The output should show `_powered-off_` in the `_status_` column for the failed module and its slot number.



