

.Before you begin
* Your storage system must meet all of the following requirements in order to use this procedure; otherwise, you must use the link:io-module-replace.html[replace an I/O module procedure].
** Your storage system must be running ONTAP 9.17.1 or later.
** Your storage system must be in a takeover state; the impaired node (node with the failed cluster/HA I/O module) must have taken over the partner node.
** The I/O module that failed must be a cluster/HA module (in slot 4) and you must be replacing it with an equivalent module. You cannot change the module type.
** Your storage system configuration must have only one cluster/HA module (located in slot 4), not two cluster/HA modules.
** Your storage system must be a two-node configuration.

* All other components in the storage system must be functioning properly; if not, contact https://mysupport.netapp.com/site/global/dashboard[NetApp Support] before continuing with this procedure.

.About this task

If needed, you can turn on the storage system location (blue) LEDs to aid in physically locating the affected storage system. Log into the BMC using SSH and enter the `system location-led _on_` command.

A storage system has three location LEDs: one on the operator display panel and one on each controller. Location LEDs remain illuminated for 30 minutes. 

You can turn them off by entering the `system location-led _off_` command. If you are unsure if the LEDs are on or off, you can check their state by entering the `system location-led show` command.


== Step 1: Prepare the I/O module slot 4

Prepare the I/O module slot 4 so that it is safe to remove the failed cluster/HA module:

Prepare the I/O module slot 4, by removing the cluster/HA module from service and powering it off:

. If you are not already grounded, properly ground yourself.

. Unplug cabling from the failed I/O module.
+
Make sure to label the cables so that you know where they came from.

. In admin privilege level, prepare the I/O module slot for removal, responding y when prompted whether to continue: system controller slot module remove -node node_name -slot slot_number.
+
 The following command prepares slot 4 on node1 for removal, and displays a message that it is safe to remove:
+
::> system controller slot module remove -node node1 -slot 4
+
Warning: IO_2X_100GBE_NVDA_NIC module in slot 4 of node node1 will be

          powered off for removal.
+
Do you want to continue? {y|n}: y
+
The module has been successfully removed from service and powered off. It can now be safely removed.

. Display the slot status with the system controller slot module show command.
+
Verify the I/O module slot status displays powered-off in the screen output for the I/O module that needs replacing.
+
See the Command man pages for your version of ONTAP for more details.


== Step 2: Replace the failed cluster/HA I/O module

include::../_include/g_io_module_cluster_ha_slot4_hotswap.adoc[]

// May 29, 205: created new g-family include for hot-swapping a cluster/HA I/O module in slot 4.


== Step 3: Bring the replacement cluster/HA I/O module online

Bring the replacement cluster/HA I/O module online and verify it is online and recognized.

. Bring the replacement I/O module online by using the system controller slot module insert command:
+
The following command prepares slot 4 on node1 for power-on, and displays a message that it is powered on:
+
::> system controller slot module insert -node node1 -slot 4
+
Warning: IO_2X_100GBE_NVDA_NIC module in slot 4 of node node1 will be

          powered on and initialized.
+
Do you want to continue? {y|n}: y
+
The module has been successfully powered on, initialized and placed into service.

. Verify that a hotplug.init.success EMS event is logged for each port reporting that initialization succeeded.
+
NOTE: this might take several minutes to allow for any required firmware updates and port initialization.

. Verify the slot status using the system controller slot module show command.

. Verify the I/O module slot status displays powered-on and ready for operation for the I/O module inserted.

. Verify that the replacement I/O module is online and recognized, and then visually confirm that the amber attention LED is not lit: sysconfig -av slot_number

. Cable the I/O module.

== Step 4: Return the failed part to NetApp

include::../_include/complete_rma.adoc[]
