//This include applies only to the cluster/HA I/O module in slot 4 running 9.17.1.

.Before you begin
* Your storage system must meet all of the following requirements in order to use this procedure; otherwise, you must use the link:io-module-replace.html[replace an I/O module procedure].
** Your storage system must be running ONTAP 9.17.1 or later.
** The I/O module that failed must be a cluster/HA module (in slot 4) and you must be replacing it with an equivalent module. You cannot change the module type.
** Your storage system configuration must have only one cluster/HA module (located in slot 4), not two cluster/HA modules.
** The controller with the failed cluster/HA I/O module must have taken over the healthy controller. The take over should have occured automatically if the module is failed.
+
You can verify the take over state...
** Your storage system must be a two-node cluster configuration.

* All other components in the storage system must be functioning properly; if not, contact https://mysupport.netapp.com/site/global/dashboard[NetApp Support] before continuing with this procedure.

.About this task

* It is critical to apply the commands to the correct controller when you are performing maintenance:

** The _impaired controller_ is the controller on which you are performing maintenance.
** The _healthy controller_ is the HA partner of the impaired controller.

* If needed, you can turn on the storage system location (blue) LEDs to aid in physically locating the affected storage system. Log into the BMC using SSH and enter the `system location-led _on_` command.
+
A storage system has three location LEDs: one on the operator display panel and one on each controller. Location LEDs remain illuminated for 30 minutes. 
+
You can turn them off by entering the `system location-led _off_` command. If you are unsure if the LEDs are on or off, you can check their state by entering the `system location-led show` command.


== Step 1: Prepare the I/O module slot 4

Prepare the I/O module slot 4 so that it is safe to remove the failed cluster/HA module:

Prepare the I/O module slot 4, by removing the cluster/HA I/O module from service and powering it off:

. If you are not already grounded, properly ground yourself.

. Unplug cabling from the failed I/O module.
+
Make sure to label the cables so that you know where they came from.

. Prepare the I/O module slot 4 on the impaired controller for removal:
+
`system controller slot module remove -node _node_name_ -slot _slot_number_`
+
NOTE: When you see _Do you want to continue?_, enter `y`. 
+
For example, the following command prepares slot 4 on node1 for removal, and displays a message that it is safe to remove:
+
----
node1::> system controller slot module remove -node node1 -slot 4

Warning: IO_2X_100GBE_NVDA_NIC module in slot 4 of node node1 will be powered off for removal.

Do you want to continue? {y|n}: y

The module has been successfully removed from service and powered off. It can now be safely removed.
----

. Verify I/O module slot 4 on the impaired controller is powered off:
+
`system controller slot module show`
+
The screen output should show `powered-off`for the slot 4 status on the impaired controller.
+
See the Command man pages for your version of ONTAP for more details.


== Step 2: Replace the failed cluster/HA I/O module

include::../_include/g_io_module_cluster_ha_slot4_hotswap.adoc[]

// May 29, 205: created new g-family include for hot-swapping a cluster/HA I/O module in slot 4.


== Step 3: Bring the replacement cluster/HA I/O module online

Bring the replacement cluster/HA I/O module online and verify it is online and recognized.

. Bring the replacement cluster/HA I/O module online:
+
`system controller slot module insert -node _node_name_ -slot _slot_name_`
+
NOTE: When you see _Do you want to continue?_, enter `y`. 
+
The output should confirm the cluster/HA I/O module was successfully brought online (powered on, initialized, and placed into service).
+
For example, the following command prepares slot 4 on node1 for power-on, and displays a message that the process was successful:
+
----
node1::> system controller slot module insert -node _node1_ -slot _4_

Warning: IO_2X_100GBE_NVDA_NIC module in slot 4 of node node1 will be powered on and initialized.

Do you want to continue? {y|n}: `y`

The module has been successfully powered on, initialized and placed into service.
----

. Verify that a hotplug.init.success EMS event is logged for each port reporting that initialization succeeded.
+
NOTE: This might take several minutes to allow for any required firmware updates and port initialization.

. Verify the slot status:
+
`system controller slot module show`

. From the output, verify the I/O module slot 4 status displays powered-on and ready for operation for the cluster/HA I/O module you inserted.

. Verify that the replacement cluster/HA I/O module is online and recognized: 
+
`sysconfig -av _slot_number_`

. Visually confirm that the amber attention LED for slot 4 is not illuminated.

== Step 4: Return the failed part to NetApp

include::../_include/complete_rma.adoc[]
