// Jan 2026: updated for 9.18.1GA support changes. https://jira.ngage.netapp.com/browse/AFFFASDOC-358

// New include specific to g-platform family because the requirements reference 9.17.1 and slot 4, which are unique to g-platforms.

To use this procedure, your storage system must be running ONTAP 9.17.1 or later, and your storage system must meet all requirements for the version of ONTAP your storage system is running.

NOTE: If your storage system is not running ONTAP 9.17.1 or later, or does not meet all requirements for the version of ONTAP your storage system is running, you cannot use this procedure, you must use the link:io-module-replace.html[replace an I/O module procedure].

[role="tabbed-block"]
====

.ONTAP 9.17.1 or 9.18.1RC
--
* You are hot-swapping a failed cluster and HA I/O module in slot 4 with an equivalent I/O module. You cannot change the I/O module type.
//+
//Hot-swapping the cluster and HA I/O module means that you do not have to perform a manual takeover; the impaired controller (the controller with the failed cluster and HA I/O module) has automatically taken over the healthy controller.
//+
//When the impaired controller has taken over the healthy controller, the only way to recover without an outage is to hot-swap the I/O module.

* The controller with the failed cluster and HA I/O module (the impaired controller) must have already taken over the healthy partner controller. The takeover should have occurred automatically if the I/O module has failed.
+
For two-node clusters, the storage system cannot discern which controller has the failed I/O module, so either controller might initiate the takeover. Hot swapping is only supported when the controller with the failed I/O module (the impaired controller) has taken over the healthy controller. Hot-swapping the I/O module is the only way to recover without an outage.
+
You can verify that the impaired controller successfully took over the healthy controller by entering the `storage failover show` command.
+
If you are not sure which controller has the failed I/O module, contact https://mysupport.netapp.com/site/global/dashboard[NetApp Support].

* Your storage system configuration must have only one cluster and HA I/O module located in slot 4, not two cluster and HA I/O modules.

* Your storage system must be a two-node (switchless or switched) cluster configuration.

* All other components in the storage system must be functioning properly; if not, contact https://mysupport.netapp.com/site/global/dashboard[NetApp Support] before continuing with this procedure.
--
.ONTAP 9.18.1GA or later
--
* You are hot swapping an Ethernet I/O module in any slot having any combination of ports used for cluster, HA, and client with an equivalent I/O module. You cannot change the I/O module type. 
+
Ethernet I/O modules with ports used for storage or MetroCluster are not hot-swappable.
// Dec 12 T said: Cluster and HA are not required to be shared on the same ports for 9.18.1 GA and beyond, so we probably want to list them separately. You could have a card with cluster and client, storage and client, cluster and HA and DR (disaster recovery, aka MetroCluster), or each of these individually.  

//ports used for client are host connections, right?

// Target cards/ports not supported, only client-side cards/ports. Storage ports are considered target ports?

* Your storage system (switchless or switched cluster configuration) can have any number of nodes supported for your storage system. 
// You are not required to have a two-node cluster like for 9.17.1 and 9.18.1RC.
 

//3.	If a node has been taken over by its partner, I don’t think you can perform any CLI commands so it would not be able to hot swap (you would just power off and replace the card using the old method).
//[Lisa] Per #2 and #3: It sounds like I need to add a requirement for using the 9.18.1GA and beyond hot-swap procedure, “Your storage system cannot be in a takeover state.  If either controller automatically took over its partner, you cannot hot-swap the failed I/O module, you must use the Replace an I/O module procedure.” Correct?

* All nodes in the cluster must be running a version of ONTAP 9.18.1GA or later. However, it does not need to be the same version on all nodes. For example, one node can be running 9.18.1GA and another node can be running a patch release.
+
You cannot hot-swap an I/O module if any node in the cluster is running a version of ONTAP earlier than 9.18.1GA. Mixed-version ONTAP clusters are not supported.
//For 9.18.1GA or later, all nodes in the cluster must also be running 9.18.1GA or later and be on the same ONTAP version (9.18.1).  For example, if a node is running 9.18.1GA, but another node in the cluster is running 9.17.1, then hot plug is not supported. If a node is running 9.18.1 GA and another node in the cluster is running 9.18.1 P3, hot plug is still supported.  

* The controllers in your storage system can be in either of the following states:

** Both controllers can be up and running I/O (serving data).
//Then you do NOT need to disable and re-enable automatic giveback in this procedure.

** Either controller can be in a takeover state.
//Then you need to disable and re-enable automatic giveback on the impaired controller (the one that took over the health partner).
+
In certain situations, ONTAP can automatically perform a takeover of either controller due to the failed I/O module. For example, if the failed I/O module contained all of the cluster ports (all of the cluster links on that controller go down) ONTAP automatically performs a takeover.

//If the controller with the failed I/O module (the impaired controller) took over the healthy partner controller, you need to disable automatic giveback on the impaired controller before hot-swapping the failed I/O module. After hot-swapping the failed I/O module, you need to re-enable automatic giveback on the impaired controller.

//The above paragraphs are a rewrite of this: For example, if all the Cluster links on a node go down, ONTAP automatically performs a takeover. It is possible the failed I/O module contained all the cluster ports and this occurred. The surviving node could have the bad card, and you would want to disable and re-enable automatic giveback like you did in 9.17.1. If both nodes are up, you don’t need to execute those steps. 

// In 9.18.1, (these checks will be removed and) hot plug is supported regardless of the cluster size or takeover state.  Nodes losing RDB Quorum during the hot plug operation will be handled by the feature.

* All other components in the storage system must be functioning properly; if not, contact https://mysupport.netapp.com/site/global/dashboard[NetApp Support] before continuing with this procedure.
--


====




