// Jan 2026: updated for 9.18.1GA support changes. https://jira.ngage.netapp.com/browse/AFFFASDOC-358

// New include specific to g-platform family because the requirements reference 9.17.1 and slot 4, which are unique to g-platforms.

To use this procedure, your storage system must be running ONTAP 9.17.1 or later, and your storage system must meet all requirements for the version of ONTAP your storage system is running.

NOTE: If your storage system is not running ONTAP 9.17.1 or later, or does not meet all requirements for the version of ONTAP your storage system is running, you cannot use this procedure, you must use the link:io-module-replace.html[replace an I/O module procedure].

[role="tabbed-block"]
====

.ONTAP 9.17.1 or 9.18.1RC
--
* You are hot-swapping a failed cluster and HA I/O module in slot 4 with an equivalent I/O module. You cannot change the I/O module type.
//+
//Hot-swapping the cluster and HA I/O module means that you do not have to perform a manual takeover; the impaired controller (the controller with the failed cluster and HA I/O module) has automatically taken over the healthy controller.
//+
//When the impaired controller has taken over the healthy controller, the only way to recover without an outage is to hot-swap the I/O module.

* The controller with the failed cluster and HA I/O module (the impaired controller) must have already taken over the healthy partner controller. The takeover should have occurred automatically if the I/O module is failed.
+
For two-node clusters, the storage system cannot discern which controller has the failed I/O module, so either controller might initiate the takeover. Hot swapping is only supported when the controller with the failed I/O module (the impaired controller) has taken over the healthy controller. Hot-swapping the I/O module is the only way to recover without an outage.
+
You can verify that the impaired controller successfully took over the healthy controller by entering the `storage failover show` command.
+
If you are not sure which controller has the failed I/O module, contact https://mysupport.netapp.com/site/global/dashboard[NetApp Support].

* Your storage system configuration must have only one cluster and HA I/O module located in slot 4, not two cluster and HA I/O modules.

* Your storage system must be a two-node (switchless or switched) cluster configuration.

* All other components in the storage system must be functioning properly; if not, contact https://mysupport.netapp.com/site/global/dashboard[NetApp Support] before continuing with this procedure.
--
.ONTAP 9.18.1GA or later
--
* You are hot-swapping one of the following types of I/O modules with an equivalent I/O module. You cannot change the I/O module type:
+
** A failed Ethernet client I/O module but only if it does not have ports used for storage connections or used for MetroCluster connections.
+
** A failed cluster and HA I/O module.
+
Hot-swapping an I/O module means that you do not have to perform a manual takeover; the impaired controller (the controller with the failed I/O module) has been automatically taken over by the healthy controller.

* Your storage system (switchless or switched cluster configuration) can have any number of nodes supported for your storage system. (You are not required to have a two-node cluster.)
+
However, if your storage system is a two-node cluster, the controller with the failed I/O module (the impaired controller) must have already taken over the healthy partner controller. The takeover should have occurred automatically if the I/O module is failed.
+
For a two-node cluster, the storage system cannot discern which controller has the failed I/O module, so either controller might initiate the takeover. Hot swapping in a two-node cluster is only supported when the controller with the failed I/O module (the impaired controller) has taken over the healthy controller. Hot-swapping the I/O module is the only way to recover without an outage.
+
You can verify that the impaired controller successfully took over the healthy controller by entering the `storage failover show` command.
+
If you are not sure which controller has the failed I/O module, contact https://mysupport.netapp.com/site/global/dashboard[NetApp Support].

* All other components in the storage system must be functioning properly; if not, contact https://mysupport.netapp.com/site/global/dashboard[NetApp Support] before continuing with this procedure.
--


====




