== Equipment needed for install
To install your platform and shelves, you need the following equipment and tools. 

** Access to a Web browser to configure your storage system
** Electrostatic discharge (ESD) strap 
** Flashlight
** Laptop or console with a USB/serial connection
** Paperclip or narrow tipped ball point pen for setting NS224 storage shelf IDs
** Phillips #2 screwdriver 

== Lifting precautions 
Platforms and NS224 shelves are heavy. Exercise caution when lifting and moving these items.

=== Platform weights
Take the necessary precautions when moving or lifting your platform.

[role="tabbed-block"]
====

.A1K platform
--

An A1K platform can weigh up to 62.83 lbs (28.5 kg). To lift the platform, use two people or a hydraulic lift.

image::../media/drw_a1k_weight_caution_ieops-1698.svg[AFF A1K lifting caution icon]

--
.A70 and A90 platforms
--

An A70 or A90 platform can weigh up to 151.68 lbs (68.8 kg). To lift the platform, use four people or a hydraulic lift.

image::../media/drw_a70-90_weight_icon_ieops-1730.svg[AFF A90, AFF A70 weight caution icon]

--
.A20, A30 and A50 platforms
--

An A20, A30, or an A50 platform can weigh up to 61.5 lbs (27.9 kg). To lift the platform, use two people or a hydraulic lift.

image::../media/drw_g_lifting_weight_ieops-1831.svg[AFF A20, A30, or an A50 weight caution icon]

--

====


=== Shelf weight
An NS224 shelf can weigh up to 66.78 lbs (30.29 kg). To lift the shelf, use two people or a hydraulic lift. Keep all components in the shelf (both front and rear) to prevent unbalancing the shelf weight.

image::../media/drw_ns224_lifting_weight_ieops-1716.svg[NS224 lifting caution]

.Related information

*  https://library.netapp.com/ecm/ecm_download_file/ECMP12475945[Safety information and regulatory notices^]
