== Step 1: Prepare the site
To install your storage system, ensure that the site and the cabinet or rack that you plan to use meet specifications for your configuration.

.Steps

. Use https://hwu.netapp.com[NetApp Hardware Universe^] to confirm that your site meets the environmental and electrical requirements for your storage system.

. Make sure you have adequate rack space:
** 4U in an HA configuration for the storage system 
** 2U for each NS224 storage shelf

+
*NOTE:* See link:https://hwu.netapp.com[NetApp Hardware Universe^] for rack space requirements for other supported storage shelves.
+

. Install any required network switches.
+

See the https://docs.netapp.com/us-en/ontap-systems-switches/index.html[Switch documentation^] for installation instructions and link:https://hwu.netapp.com[NetApp Hardware Universe^] for compatibility information.


== Step 2: Unpack the boxes
After you've ensured that the site and the cabinet or rack that you plan to use for your storage system meet the required specifications, unpack all boxes and compare the contents to the items on the packing slip.

.Steps

. Carefully open all the boxes and lay out the contents in an organized manner.

. Compare the contents you’ve unpacked with the list on the packing slip. 

+
NOTE: You can get your packing list by scanning the QR code on the side of the shipping carton.

+
The following items are some of the contents you might see in the boxes. 
+
Ensure that everything in the boxes matches the list on the packing slip. If there are any discrepancies, note them down for further action.
+

[%rotate, grid="none", frame="none", cols="12,9,4"]
|===
|*Hardware*
|*Cables* |
a|* Bezel
* Cable management device 
* Storage system
* Rail kits with instructions (optional)
* Storage shelf 
a|* Management Ethernet cables (RJ-45 cables)
* Network cables
* Power cords
* Storage cables (if you ordered additional shelves) 
* USB-C serial port cable |
|===



== Step 3: Register your storage system
After you've ensured that your site meets the requirements for your storage system specifications, and you've verified that you have all the parts you ordered, you should register your storage system.

.Steps

. Locate the serial number for your storage system. 
+
You can find the number on the packing slip, in your confirmation email, or on the controller's System Management module after you unpack it.
+
image::../media/drw_ssn_label.svg[Example of system serial number,width=200]
+

. Go to the http://mysupport.netapp.com/[NetApp Support Site^].
. Determine whether you need to register your storage system:
+
[cols="1a,2a" options="header"]
|===
| If you are a...| Follow these steps...
a|
Existing NetApp customer
a|

 .. Sign in with your username and password.
 .. Select *Systems* > *My Systems*.
 .. Confirm that the new serial number is listed.
 .. If it is not, follow the instructions for new NetApp customers.

a|
New NetApp customer
a|

 .. Click *Register Now*, and create an account.
 .. Select *Systems* > *Register Systems*.
 .. Enter the storage system's serial number and requested details.

After your registration is approved, you can download any required software. The approval process might take up to 24 hours.
|===


