// to reference this file and have pdf work correctly, use one block based on context and uncomment it

// if the context is a1k

// :a1k:
// include::../_include/install_prepare_fragment_conditional.adoc[]
// :a1k!:

// if the context is a70-90

// :a70-90:
// include::../_include/install_prepare_fragment_conditional.adoc[]
// :a70-90!:

// if the context is a20-30-50:

// :a20-30-50:
// include::../_include/install_prepare_fragment_conditional.adoc[]
// :a-20-30-50!:

== Equipment needed for install
To install your storage system, you need the following equipment and tools. 

** Access to a Web browser to configure your storage system
** Electrostatic discharge (ESD) strap 
** Flashlight
** Laptop or console with a USB/serial connection
** Paperclip or narrow tipped ball point pen for setting NS224 storage shelf IDs
** Phillips #2 screwdriver 

== Lifting precautions 
Storage systems and shelves are heavy. Exercise caution when lifting and moving these items.

=== Storage system weight
Take the necessary precautions when moving or lifting your storage system.

// next two bullets applies to A1K and A70-90
ifdef::a1k[]
An A1K storage system can weigh up to 62.83 lbs (28.5 kg). To lift the storage system, use two people or a hydraulic lift.

image::../media/drw_a1k_weight_caution_ieops-1698.svg[AFF A1K lifting caution icon]
endif::a1k[]

// next two bullets applies only to a20-30-50
ifdef::a70-90[]
An A70 or A90 storage system can weigh up to 151.68 lbs (68.8 kg). To lift the storage system, use four people or a hydraulic lift.

image::../media/drw_a70-90_weight_icon_ieops-1730.svg[AFF A90, AFF A70 weight caution icon]

endif::a70-90[]
// next two bullets applies only to a20-30-50
ifdef::a20-30-50[]
An A20, A30, or an A50 storage system can weigh up to 61.5 lbs (27.9 kg). To lift the storage system, use two people or a hydraulic lift.

image::../media/drw_g_lifting_weight_ieops-1831.svg[AFF A20, A30, or an A50 weight caution icon]
endif::a20-30-50[]

=== Shelf weight
An NS224 shelf can weigh up to 66.78 lbs (30.29 kg). To lift the shelf, use two people or a hydraulic lift. Keep all components in the shelf (both front and rear) to prevent unbalancing the shelf weight.

image::../media/drw_ns224_lifting_weight_ieops-1716.svg[NS224 lifting caution]

.Related information

*  https://library.netapp.com/ecm/ecm_download_file/ECMP12475945[Safety information and regulatory notices^]
