== Equipment needed for install
To install your storage system, you need the following equipment and tools. 

** Access to a Web browser to configure your storage system
** Electrostatic discharge (ESD) strap 
** Flashlight
** Laptop or console with a USB/serial connection
** Paperclip or narrow tipped ball point pen for setting NS224 storage shelf IDs
** Phillips #2 screwdriver 

== Lifting precautions 
Storage systems and NS224 storage shelves are heavy. Exercise caution when lifting and moving these items.

=== Storage system weights
Take the necessary precautions when moving or lifting your storage system.

[role="tabbed-block"]
====

.ASA A1K storage system
--

An A1K storage system can weigh up to 62.83 lbs (28.5 kg). To lift the system, use two people or a hydraulic lift.

image::../media/drw_a1k_weight_caution_ieops-1698.svg[AFF A1K lifting caution icon]

--
.ASA A70 and ASA A90 storage systems
--

An A70 storage system or an A90 storage system can weigh up to 151.68 lbs (68.8 kg). To lift the system, use four people or a hydraulic lift.

image::../media/drw_a70-90_weight_icon_ieops-1730.svg[AFF A90, AFF A70 weight caution icon]

--

====


=== Storage shelf weight
An NS224 storage shelf can weigh up to 66.78 lbs (30.29 kg). To lift the storage shelf, use two people or a hydraulic lift. Keep all components in the storage shelf (both front and rear) to prevent unbalancing the shelf weight.

image::../media/drw_ns224_lifting_weight_ieops-1716.svg[NS224 lifting caution]

.Related information

*  https://library.netapp.com/ecm/ecm_download_file/ECMP12475945[Safety information and regulatory notices^]
