
// start tabbed area

[role="tabbed-block"]
====

.AFF systems
--
AFF A-Series and C-Series models are a robust scale-out platform built for virtualized environments and can be deployed as an independent system or a high-performance tier in a NetApp ONTAP configuration. link:https:://www.netapp.com/data-storage/all-flash-san-storage-array[Learn more about the AFF systems].

[horizontal]
AFF A20, A30, A50:: 
Available beginning with ONTAP 9.16.1

AFF C30, C60:: Available beginning with ONTAP 9.16.1

AFF A1K, A70, A90:: Available beginning with ONTAP 9.15.1

AFF A150:: Available beginning with ONTAP 9.13.1 

AFF C250, C400, C800:: 
Available beginning with ONTAP 9.12.1P1

AFF A900:: Available beginning with ONTAP 9.10.1

AFF A250:: Available beginning with ONTAP 9.8

AFF A800:: Available beginning with ONTAP 9.8

AFF A400:: Available beginning with ONTAP 9.7

--


.ASA r2 systems
--
ASA r2 systems deliver a unified hardware and software solution that creates a simplified experience specific to the needs of SAN-only customers. link:https:://docs.netapp.com/us-en/asa-r2/get-started/learn-about.html[Learn more about the ASA r2 systems].

[horizontal]
ASA A1K, ASA A70, ASA A90:: Available beginning with ONTAP 9.16.0


--

.ASA systems
--
link:https://www.netapp.com/data-storage/all-flash-san-storage-array[Get the datasheet for ASA systems].

[horizontal]
.ASA C250, C400, C800::
Available beginning with ONTAP 9.13.1P1

.ASA A150, ASA A250, ASA A400, ASA A900::
Available beginning with ONTAP 9.13.1
--

.FAS systems
--

[horizontal]

FAS70 and FAS90::
Available beginning with ONTAP 9.15.1

FAS2820::
Available beginning with ONTAP 9.13.1

FAS9500::
Available beginning with ONTAP 9.11.1, ONTAP 9.10.1P3

FAS8300::
Available beginning with ONTAP 9.7

FAS8700::
Available beginning with ONTAP 9.7

--
====

// end tabbed area







