
// start tabbed area

[role="tabbed-block"]
====

.AFF systems
--
The AFF A-Series and AFF C-Series systems provide a robust, scale-out platform tailored for virtualized environments. They can be deployed as standalone systems or as high-performance tiers in NetApp ONTAP configurations. link:https://www.netapp.com/data-storage/all-flash-san-storage-array[Learn more about AFF systems].

AFF A-Series and AFF C-Series systems are supported beginning in the following ONTAP releases.


[horizontal]
ONTAP 9.16.1:: 
* AFF A20 
* AFF A30 
* AFF A50
* AFF C30 
* AFF C60
* AFF C80
ONTAP 9.15.1:: 
* AFF A1K
* AFF A70
* AFF A90
ONTAP 9.12.1P1:: 
* AFF A150
* AFF C250
* AFF C400
* AFF C800
ONTAP 9.10.1:: 
* AFF A900
ONTAP 9.8::
* AFF A250
ONTAP 9.7::
* AFF A400
* AFF A800

--

.ASA r2 systems
--
ASA r2 systems deliver a unified hardware and software solution that creates a simplified experience specific to the needs of SAN-only customers. link:https://docs.netapp.com/us-en/asa-r2/get-started/learn-about.html[Learn more about the ASA r2 systems].

ASA r2 systems are supported beginning in the following ONTAP releases.

[horizontal]
ONTAP 9.16.0::
* ASA A1K
* ASA A70
* ASA A90
--

.ASA systems
--
ASA A-Series and ASA C-Series systems deliver a simplified and dedicated SAN experience that provides continuous data availability for enterprise mission critical databases and other SAN workloads using FCP or iSCSI protocol. link:https://www.netapp.com/data-storage/all-flash-san-storage-array[Learn more about the ASA systems].

ASA systems are supported beginning in the following ONTAP releases.

[horizontal]

ONTAP 9.13.1P1::
* ASA C250
* ASA C400
* ASA C800

ONTAP 9.13.1::
* ASA A150
* ASA A250
* ASA A400
* ASA A900 

ONTAP 9.8::
* ASA AFF A250
* ASA AFF A800

ONTAP 9.7::
* ASA AFF A400

--

.FAS systems
--
FAS systems deliver efficient and secure secondary storage - the ultimate solution for tiering, backup, and disaster recovery. link:https://www.netapp.com/data-storage/fas/[Learn more about FAS systems].

FAS systems are supported beginning in the following ONTAP releases.

[horizontal]

ONTAP 9.15.1::
* FAS70
* FAS90

ONTAP 9.13.1:: 
* FAS2820

ONTAP 9.11.1:: 
* FAS9500

ONTAP 9.10.1P3:: 
* FAS9500

ONTAP 9.7::
* FAS2750
* FAS8300
* FAS8700

--

.Drive shelves
--
Drive shelves are specifically designed for NetApp AFF, ASA, and FAS systems and help deliver the performance, resiliency, and flexibility your digital transformation needs. 

Drive shelves are available beginning with the following ONTAP releases.

[horizontal]

ONTAP 9.16.1:: NS224 with NSM100B modules

ONTAP 9.6:: NS224 shelf with NSM100 modules

--

====

// end tabbed area







