
// start tabbed area

[role="tabbed-block"]
====

.AFF systems
--
The AFF A-Series and C-Series models provide a robust, scale-out platform tailored for virtualized environments. They can be deployed as standalone systems or as high-performance tiers in NetApp ONTAP configurations.
link:https://www.netapp.com/data-storage/all-flash-san-storage-array[Learn more about AFF systems].

[horizontal]
ONTAP 9.16.1:: 
* AFF A20 
* AFF A30 
* AFF A50
* AFF C30 
* AFF C60
ONTAP 9.15.1:: 
* AFF A1K
* AFF A70
* AFF A90
ONTAP 9.13.1:: AFF A150
ONTAP 9.12.1P1:: 
* AFF C250
* AFF C400
* AFF C800
ONTAP 9.10.1:: AFF A900
ONTAP 9.8:: 
* AFF A250
* AFF A800

--

.ASA r2 systems
--
ASA r2 systems deliver a unified hardware and software solution that creates a simplified experience specific to the needs of SAN-only customers. link:https:://docs.netapp.com/us-en/asa-r2/get-started/learn-about.html[Learn more about the ASA r2 systems].

[horizontal]
ONTAP 9.16.0::
* ASA A1K
* ASA A70
* ASA A90
--

.ASA systems
--
ASA A-Series and C-Series models deliver a simplified and dedicated SAN experience that provides continuous data availability for enterprise mission critical databases and other SAN workloads using FCP or iSCSI protocol. link:https:://www.netapp.com/data-storage/all-flash-san-storage-array[Learn more about the ASA systems].

[horizontal]

ONTAP 9.13.1P1::
* ASA C250
* ASA C400
* ASA C800

ONTAP 9.13.1::
* ASA A150
* ASA A250
* ASA A400
* ASA A900 
--

.FAS systems
--
FAS systems deliver efficient and secure secondary storage - the ultimate solution for tiering, backup, and disaster recovery. link:https:://www.netapp.com/data-storage/fas/[Learn more about FAS systems].

[horizontal]

ONTAP 9.15.1::
* FAS70
* FAS90

ONTAP 9.13.1:: 
* FAS2820
* FAS2700

ONTAP 9.11.1:: FAS9500

ONTAP 9.7::
* FAS8300
* FAS8700

--

.Shelves
--
Shelves are available beginning with the following ONTAP releases.

[horizontal]

ONTAP 9.6:: NS224 shelf

--

====

// end tabbed area







