== Install RoCE-capable PCIe cards or I/O modules
If your platform model supports the use of RoCE-capable PCIe cards or I/O modules, your HA pair must have enough available RoCE-capable Ethernet ports to support the number of shelves you are hot-adding. 

.Steps
. For each shelf you are hot-adding, verify that there are two RoCE-capable ports on each controller. 
+
These ports can be on board the controllers, on RoCE-capable PCIe cards, a combination of both, or on RoCE-capable I/O modules, as supported by your platform model.
+
. If your HA pair does not have enough available RoCE-capable ports, install the additional PCIe cards or I/O modules into the correct controller slots, as supported by your platform model. 
+ 
.. Identify the correct controller slots for your platform model. See https://hwu.netapp.com[NetApp Hardware Universe^]. 
+
.. See your platform model's documentation for PCIe card or I/O module installation instructions.

== Configure RoCE-capable ports for storage use

If your HA pair has non-dedicated RoCE-capable Ethernet ports that you are using to hot-add an NS224 shelf, you must configure the ports for storage use (not networking use).

.Before you begin

* Make sure you installed any additional RoCE-capable PCIe cards or I/O modules in each controller.

.About this task

* For some platform models, when a RoCE-capable PCIe card or I/O module is installed in a supported slot on a controller, the ports automatically default to storage use (instead of networking); however, it is recommended that you complete the following procedure to verify the RoCE-capable ports are configured for storage use.

* If you determine that the non-dedicated RoCE-capable ports in your HA pair are not configured for storage use, it is a nondisruptive procedure to configure them. You do not need to reboot the controllers, unless one or both controllers are in maintenance mode. This procedure assumes that neither controller is in maintenance mode.

* If in the future you need to change ports from storage use to networking use, enter the command, `storage port modify -node _node_name_ -port _port_name_ -mode network`.

.Steps

. Log in to the cluster using SSH or the serial console port.
. Enter the following command to verify if the non-dedicated ports in the HA pair are configured for storage use:
+
`storage port show`
+
* If your HA pair is running ONTAP 9.8 or later, the non-dedicated ports display `storage` in the `Mode` column.
+
* If your HA pair is running ONTAP 9.7, the non-dedicated ports, which display `false` in the `Is Dedicated?` column, also display `enabled` in the `State` column.
+
[NOTE]
====
When non-dedicated ports are not configured for storage use, the command output displays the following:

* If your HA pair is running ONTAP 9.8 or later, the non-dedicated ports display `network` in the `Mode` column.

* If your HA pair is running ONTAP 9.7, the non-dedicated ports, which display `false` in the `Is Dedicated?`` column, also display `disabled` in the `State` column.
====

. If the non-dedicated ports are configured for storage use, you are done with this procedure.
+
Otherwise, you need to configure the ports by completing the following steps.
+
. Configure the non-dedicated ports for storage use, on one of the controllers:
+
You must repeat the applicable command for each port you are configuring.
+
[options="header" cols="1,3"]
|===
| If your HA pair is running...| Use this command...
a|
ONTAP 9.8 or later
a|
`storage port modify -node _node_name_ -port _port_name_ -mode storage`
a|
ONTAP 9.7
a|
`storage port enable -node _node_name_ -port _port_name_`
|===


. Repeat the previous step for the second controller.

. Verify that the non-dedicated ports on both controllers are configured for storage use: `storage port show`
+
* If your HA pair is running ONTAP 9.8 or later, the non-dedicated ports display `storage` in the `Mode` column.
+
* If your HA pair is running ONTAP 9.7, the non-dedicated ports, which display `false` in the `Is Dedicated?` column, also display `enabled` in the `State` column.

== Disable automatic drive assignment

If you are manually assigning drive ownership for the NS224 shelf you are hot-adding, then you need to disable automatic drive assignment if it is enabled.

If you are unsure whether you should manually assign drive ownership, or want to understand the automatic assignment of drive ownership policies for your storage system, go to https://docs.netapp.com/us-en/ontap/disks-aggregates/disk-autoassignment-policy-concept.html[About automatic assignment of disk ownership^].

.Steps

. Verify whether automatic drive assignment is enabled: `storage disk option show`
+
You can enter the command on either node.
+
If automatic drive assignment is enabled, the output shows `on` in the `Auto Assign` column (for each node).

. If automatic drive assignment is enabled, disable it: `storage disk option modify -node _node_name_ -autoassign off`
+
You must disable automatic drive assignment on both nodes.
