.Before you begin

* Make sure you installed any additional RoCE-capable PCIe cards or I/O modules in each controller.

.About this task

* For some systems, when a RoCE-capable PCIe card or I/O module is installed in a supported slot on a controller, the ports automatically default to storage use instead of networking. However, it is recommended that you complete the following procedure to verify the RoCE-capable ports are configured for storage use.

* If you determine that the non-dedicated RoCE-capable ports in your HA pair are not configured for storage use, it is a nondisruptive procedure to configure them. You do not need to reboot the controllers, unless one or both controllers are in maintenance mode. This procedure assumes that neither controller is in maintenance mode.

* If in the future you need to change ports from storage use to networking use, enter the command, `storage port modify -node _node_name_ -port _port_name_ -mode network`.

.Steps

. Log in to the cluster using SSH or the serial console port.
. Enter the following command to verify if the non-dedicated ports in the HA pair are configured for storage use:
+
`storage port show`
+
* If your HA pair is running ONTAP 9.8 or later, the non-dedicated ports display `storage` in the `Mode` column.
+
* If your HA pair is running ONTAP 9.7, the non-dedicated ports, which display `false` in the `Is Dedicated?` column, also display `enabled` in the `State` column.
+
[NOTE]
====
When non-dedicated ports are not configured for storage use, the command output displays the following:

* If your HA pair is running ONTAP 9.8 or later, the non-dedicated ports display `network` in the `Mode` column.

* If your HA pair is running ONTAP 9.7, the non-dedicated ports, which display `false` in the `Is Dedicated?` column, also display `disabled` in the `State` column.
====

. If the non-dedicated ports are configured for storage use, you are done with this procedure.
+
Otherwise, you need to configure the ports by completing the following steps.
+
. Configure the non-dedicated ports for storage use on one of the controllers.
+
You must repeat the applicable command for each port you are configuring.
+
[options="header" cols="1,3"]
|===
| If your HA pair is running...| Use this command...
a|
ONTAP 9.8 or later
a|
`storage port modify -node _node_name_ -port _port_name_ -mode storage`
a|
ONTAP 9.7
a|
`storage port enable -node _node_name_ -port _port_name_`
|===

. Repeat the previous step for the second controller.

. Verify that the non-dedicated ports on both controllers are configured for storage use: `storage port show`
+
* If your HA pair is running ONTAP 9.8 or later, the non-dedicated ports display `storage` in the `Mode` column.
+
* If your HA pair is running ONTAP 9.7, the non-dedicated ports, which display `false` in the `Is Dedicated?` column, also display `enabled` in the `State` column.
