.Before you begin

* Make sure you installed any additional RoCE-capable PCIe cards or I/O modules in each controller.

* Make sure that the non-dedicated ports on the RoCE-capable PCIe cards or I/O modules you installed are configured for storage use.

.About this task

* Recabling port connections is a nondisruptive procedure when your shelf has multipath-HA connectivity.

* You move one cable at a time to always maintain connectivity to the shelf during this procedure.
+
NOTE: Moving a cable does not require any wait time between unplugging the cable from one port and plugging it into another port.

* If needed, refer to the shelf cabling illustrations for your system in link:hot-add-aff-cable-overview.html[Overview of cabling for a hot-add].

== AFF A1K

When you hot-add shelves to an AFF A1K HA pair, you need to recable existing shelves to balance connectivity across multiple RoCE-capable I/O modules. 

* If you are hot-adding a second shelf, the first shelf must be recabled across slots 11 and 10. For a second shelf, the procedure assumes the existing shelf is cabled to a RoCE-capable I/O module in slot 11 on each controller. 

* If you are hot-adding a fourth shelf, the third shelf must be recabled across slots 9 and 8. For a fourth shelf, the procedure assumes the third shelf is cabled to slot 9 on each controller.

.Steps

. Do one of the following if you are hot-adding a second shelf or a fourth shelf.
+
NOTE: If you have an AFF A1K HA pair and you are hot-adding a third shelf and installing a third or fourth RoCE-capable I/O module in each controller, the third shelf is cabled to only the third or third and fourth I/O modules. You do not need to recable any existing shelves.
+
* If you are hot-adding a second shelf, recable the first shelf across the RoCE-capable I/O modules in slot 11 and slot 10 on each controller.
+
.. On controller A, move the cable from slot 11 port b (e11b) to slot 10 port b (e10b).
.. Repeat the same cable move on controller B.
+
* If you are hot-adding a fourth shelf, recable the third shelf across the RoCE-capable I/O modules in slot 9 and slot 8 on each controller.
+
.. On controller A, move the cable from slot 9 port b (e9b) to slot 8 port b (e8b).
.. Repeat the same cable move on controller B.

. Verify that the recabled shelf is cabled correctly using https://mysupport.netapp.com/site/tools/tool-eula/activeiq-configadvisor[Active IQ Config Advisor^].
+
If any cabling errors are generated, follow the corrective actions provided.

== AFF A70, AFF A90, or AFF C80

When you hot-add a second shelf to an AFF A70, AFF A90, or AFF C80 HA pair, you need to recable the first shelf across the RoCE-capable I/O modules in slot 11 and slot 8 on each controller. 

The procedure assumes the existing shelf is cabled to a RoCE-capable I/O module in slot 11 on each controller.

.Steps

. If you are hot-adding a second shelf, recable the first shelf across the RoCE-capable I/O modules in slot 11 and slot 8 on each controller.
+
.. On controller A, move the cable from slot 11 port b (e11b) to slot 8 port b (e8b).
.. Repeat the same cable move on controller B.

. Verify that the recabled shelf is cabled correctly using https://mysupport.netapp.com/site/tools/tool-eula/activeiq-configadvisor[Active IQ Config Advisor^].
+
If any cabling errors are generated, follow the corrective actions provided.

== AFF A800 or AFF C800

When you hot-add a second shelf to an AFF A800 or AFF C800 HA pair, you need to recable the first shelf across the two sets of RoCE-capable ports in slot 5 and slot 3 on each controller. 

The procedure assumes the existing shelf is cabled to RoCE-capable PCIe cards in slot 5 on each controller.

.Steps

. If you are hot-adding a second shelf, recable the first shelf across the two sets of RoCE-capable ports in slot 5 and slot 3 on each controller.
+
.. On controller A, move the cable from slot 5 port b (e5b) to slot 3 port b (e3b).
.. Repeat the same cable move on controller B.

. Verify that the recabled shelf is cabled correctly using https://mysupport.netapp.com/site/tools/tool-eula/activeiq-configadvisor[Active IQ Config Advisor^].
+
If any cabling errors are generated, follow the corrective actions provided.

== AFF A700

When you hot-add a second shelf to an AFF A700 HA pair, you need to recable the first shelf across the two sets of RoCE-capable ports in slot 3 and slot 7 on each controller. 

The procedure assumes the existing shelf is cabled to RoCE-capable I/O modules in slot 3 on each controller.

.Steps

. If you are hot-adding a second shelf, recable the first shelf across the two sets of RoCE-capable ports in slot 3 and slot 7 on each controller.
+
.. On controller A, move the cable from slot 3 port b (e3b) to slot 7 port b (e7b).
.. Repeat the same cable move on controller B.

. Verify that the recabled shelf is cabled correctly using https://mysupport.netapp.com/site/tools/tool-eula/activeiq-configadvisor[Active IQ Config Advisor^].
+
If any cabling errors are generated, follow the corrective actions provided.

== AFF A400 or AFF C400

When you hot-add a second shelf to an AFF A400 or AFF C400 HA pair, you need to recable the first shelf across two sets of RoCE-capable ports on each controller. 

For the AFF A400, the procedure assumes the existing shelf is cabled to RoCE-capable onboard ports e0c/e0d on each controller, and you recable across onboard e0c/e0d and slot 5. 

For the AFF C400, the procedure assumes the existing shelf is cabled to RoCE-capable ports in slot 4 on each controller, and you recable across slot 4 and slot 5.

.Steps

. If you are hot-adding a second shelf, depending on your system, do one of the following:
+
* On the AFF A400:
+
Recable the first shelf across the two sets of RoCE-capable ports, onboard e0c/e0d and in slot 5, on each controller.
+
.. On controller A, move the cable from port e0d to slot 5 Port b (e5b).
.. Repeat the same cable move on controller B.
+
* On the AFF C400:
+
Recable the first shelf across the two sets of RoCE-capable ports in slot 4 and slot 5, on each controller.
+
.. On controller A, move the cable from slot 4 port a (e4a) to slot 5 port b (e5b).
.. Repeat the same cable move on controller B.

. Verify that the recabled shelf is cabled correctly using https://mysupport.netapp.com/site/tools/tool-eula/activeiq-configadvisor[Active IQ Config Advisor^].
+
If any cabling errors are generated, follow the corrective actions provided.

== AFF A900

When you hot-add shelves to an AFF A900 HA pair, you need to recable existing shelves to balance connectivity across multiple RoCE-capable I/O modules. 

* If you are hot-adding a second shelf, the first shelf must be recabled across slots 2 and 10. For a second shelf, the procedure assumes the existing shelf is cabled to a RoCE-capable I/O module in slot 2 on each controller.

* If you are hot-adding a fourth shelf, the third shelf must be recabled across slots 1 and 11. For a fourth shelf, the procedure assumes the third shelf is cabled to slot 1 on each controller.

.Steps

. Do one of the following if you are hot-adding a second shelf or a fourth shelf.
+
* If you are hot-adding a second shelf, recable the first shelf across the RoCE-capable I/O modules in slot 2 and slot 10 on each controller.
+
.. On controller A, move the cable from slot 2 port b (e2b) to slot 10 port b (e10b).
.. Repeat the same cable move on controller B.
+
* If you are hot-adding a fourth shelf, recable the third shelf across the RoCE-capable I/O modules in slot 1 and slot 11 on each controller.
+
.. On controller A, move the cable from slot 1 port b (e1b) to slot 11 port b (e11b).
.. Repeat the same cable move on controller B.

. Verify that the recabled shelf is cabled correctly using https://mysupport.netapp.com/site/tools/tool-eula/activeiq-configadvisor[Active IQ Config Advisor^].
+
If any cabling errors are generated, follow the corrective actions provided.

== AFF A30, AFF C30, AFF A50, or AFF C60

When you hot-add a second shelf to an AFF A30, AFF C30, AFF A50, or AFF C60 HA pair, you need to recable the first shelf across the RoCE-capable I/O modules in slot 3 and slot 1 on each controller. 

The procedure assumes the existing shelf is cabled to a RoCE-capable I/O module in slot 3 on each controller.

.Steps

. If you are hot-adding a second shelf, recable the first shelf across the RoCE-capable I/O modules in slot 3 and slot 1 on each controller.
+
.. On controller A, move the cable from slot 3 port b (e3b) to slot 1 port b (e1b).
.. Repeat the same cable move on controller B.

. Verify that the recabled shelf is cabled correctly using https://mysupport.netapp.com/site/tools/tool-eula/activeiq-configadvisor[Active IQ Config Advisor^].
+
If any cabling errors are generated, follow the corrective actions provided.
