// This is a generic topic that can be used in other platforms, like Vino.

// Jan 2026: updated for 9.18.1GA support changes. https://jira.ngage.netapp.com/browse/AFFFASDOC-358

// July 2025: New include specific to g-platform family because the steps for bringing the replacement cluster/HA I/O module online specify/reference slot 4, which is unique to g-platforms.

// Jan 2026: Changed slot number from 4 to 7 in examples. Slot4/5 in Vino is NVRAM module.

Bring the replacement I/O module online, verify the I/O module ports initialized successfully, verify the slot is powered on, and then verify the I/O module is online and recognized.

.About this task
After the I/O module is replaced and the ports are returned to a healthy state, LIFs are reverted to the replaced I/O module.

.Steps

. Bring the replacement I/O module online:
+
.. Enter the following command:
+
`system controller slot module insert -node _impaired_node_name_ -slot _slot_number_`

.. Enter `y` when you see the prompt, _Do you want to continue?_ 
+
The output should confirm the I/O module was successfully brought online (powered on, initialized, and placed into service).
+
For example, the following command brings slot 7 on node 2 (the impaired controller) online, and displays a message that the process was successful:
+
----
node2::> system controller slot module insert -node node2 -slot 7

Warning: IO_2X_100GBE_NVDA_NIC module in slot 7 of node node2 will be powered on and initialized.

Do you want to continue? {y|n}: `y`

The module has been successfully powered on, initialized and placed into service.
----

. Verify that each port on the I/O module successfully initialized:
+
.. Enter the following command from the console of the impaired controller:
+
`event log show -event \*hotplug.init*`
+
NOTE: It might take several minutes for any required firmware updates and port initialization.
+
The output should show one or more hotplug.init.success EMS events indicating each port on the I/O module initiated successfully. 
+
//The output should show one or more hotplug.init.success EMS events and `_hotplug.init.success:_` in the `_Event_` column, indicating each port on the I/O module initiated successfully.
+
For example, the following output shows initialization succeeded for I/O ports e7b and e7a:
+
----
node2::> event log show -event *hotplug.init*                        

Time                Node             Severity      Event

------------------- ---------------- ------------- ---------------------------

7/11/2025 16:04:06  node2      NOTICE        hotplug.init.success: Initialization of ports "e7b" in slot 7 succeeded

7/11/2025 16:04:06  node2      NOTICE        hotplug.init.success: Initialization of ports "e7a" in slot 7 succeeded

2 entries were displayed.
----
+
.. If the port initialization fails, review the EMS log for the next steps to take.

. Verify the I/O module slot is powered on and ready for operation:
+
`system controller slot module show`
+
The output should show the slot status as `_powered-on_` and therefore ready for operation of the I/O module.

. Verify that the I/O module is online and recognized.
+
Enter the command from the console of the impaired controller:
+
`system controller config show -node local -slot _slot_number_`
+
If the I/O module was successfully brought online and is recognized, the output shows I/O module information, including port information for the slot.
+
For example, you should see output similar to the following for a I/O module in slot 7:
+
----
node2::> system controller config show -node local -slot 7

Node: node2
Sub- Device/
Slot slot Information
---- ---- -----------------------------
   7    - Dual 40G/100G Ethernet Controller CX6-DX
                  e7a MAC Address: d0:39:ea:59:69:74 (auto-100g_cr4-fd-up)
                          QSFP Vendor:        CISCO-BIZLINK
                          QSFP Part Number:   L45593-D218-D10
                          QSFP Serial Number: LCC2807GJFM-B
                  e7b MAC Address: d0:39:ea:59:69:75 (auto-100g_cr4-fd-up)
                          QSFP Vendor:        CISCO-BIZLINK
                          QSFP Part Number:   L45593-D218-D10
                          QSFP Serial Number: LCC2809G26F-A
                  Device Type:        CX6-DX PSID(NAP0000000027)
                  Firmware Version:   22.44.1700
                  Part Number:        111-05341
                  Hardware Revision:  20
                  Serial Number:      032403001370
----

