---
permalink: c190/bootmedia-replace-overview.html
sidebar: sidebar
keywords: AFF c190, nondisruptive, disruptive, replace the boot media, manual, manual boot recovery
summary: "Learn about boot media replacement on an AFF C190 system and understand the different replacement methods. The AFF C190 system supports only manual boot media recovery procedures. Automated boot media recovery is not supported."
---
= Overview of boot media replacement - AFF C190
:icons: font
:imagesdir: ../media/

[.lead]
Learn about boot media replacement on an AFF C190 system and understand the different replacement methods. The boot media stores primary and secondary boot image files that the system uses during startup. Depending on your network configuration, you can perform either a nondisruptive replacement (HA pair connected to network) or a disruptive replacement (requires two reboots).

include::../_include/console-logging-note.adoc[]

The AFF C190 system supports only manual boot media recovery procedures. Automated boot media recovery is not supported.


You must have a USB flash drive, formatted to FAT32, with the appropriate amount of storage to hold the `image_xxx.tgz` file.

* The nondisruptive and disruptive methods for replacing a boot media both require you to restore the var file system:
 ** For nondisruptive replacement, the HA pair must be connected to a network to restore the var file system.
 ** For disruptive replacement, you do not need a network connection to restore the var file system, but the process requires two reboots.
* You must replace the failed component with a replacement FRU component you received from your provider.
* It is important that you apply the commands in these steps on the correct controller:
 ** The _impaired_ controller is the controller on which you are performing maintenance.
 ** The _healthy_ controller is the HA partner of the impaired controller.
