---
permalink: c190/chassis-replace-overview.html
sidebar: sidebar
keywords: aff c190, replace the chassis
summary: "You replace an impaired chassis the new chassis of the same model as the impaired chassis."
---
= Review requirements before replacing the chassis in an AFF C190 system
:icons: font
:imagesdir: ../media/

[.lead]
Before replacing the chassis in your AFF C190 system, review the requirements for a successful replacement. The chassis replacement procedure requires moving all drives, power supplies, and controller modules from the impaired chassis to the replacement chassis and is disruptive.

All other components in the system must be functioning properly; if not, you must contact technical support.

* You can use this procedure with all versions of ONTAP supported by your system.
* This procedure is written with the assumption that you are moving all drives and controller module or modules to the new chassis, and that the chassis is a new component from NetApp.
* This procedure is disruptive. For a two-node cluster, you will have a complete service outage and a partial outage in a multi-node cluster.
