---
permalink: c190/maintain-overview.html
sidebar: sidebar
keywords: c190 maintenance, maintenance, repairing c190, repairing c190, replace c190 components, replace c190 components
summary: Maintain the AFF C190 hardware
---
= Learn about maintaining an AFF C190 storage system
:icons: font
:imagesdir: ../media/

[.lead]
Maintain the hardware of your AFF C190 storage system to ensure long-term reliability and optimal performance. Perform regular maintenance tasks such as replacing faulty components to prevent downtime and data loss.

== Boot media

The boot media stores a primary and secondary set of boot image files that the system uses when it boots. 

== Chassis

The chassis is the physical enclosure housing all the controller components such as the controller/CPU unit, power supply, and I/O.

== Controller

A controller consists of a board, firmware, and software. It controls the drives and implements the ONTAP functions.

== DIMM

You must replace a DIMM (dual in-line memory module) when a memory mismatch is present, or you have a failed DIMM.

== Drive

A drive is a device that provides the physical storage media for data.

== Fan

The fan cools the controller.

== NVMEM battery

A battery is included with the controller and provides the backup power if the AC power fails.

== Power supply

A power supply provides a redundant power source in a controller shelf.

== Real-time clock battery

A real time clock battery preserves system date and time information if the power is off. 