---
sidebar: sidebar
permalink: fas-70-90/install-requirements.html
keywords: fas70, fas90, install, setup, cautions
summary: Review the equipment needed and the lifting precautions for your platform and shelves.
---
= Requirements and considerations for FAS70 and FAS90 systems
:icons: font
:imagesdir: ../media/

[.lead]
Review the equipment needed and the lifting precautions for your FAS70 or FAS90 storage system and storage shelves. 

== Equipment needed for install
To install your FAS70 or FAS90 storage system, you need the following equipment and tools. 

** Access to a Web browser to configure your storage system
** Electrostatic discharge (ESD) strap 
** Flashlight
** Laptop or console with a USB/serial connection
** Paperclip or narrow tipped ball point pen for setting NS224 storage shelf IDs
** Phillips #2 screwdriver 

== Lifting precautions 
FAS70 and FAS90 storage systems, NS224 storage shelves, and DS460C storage shelves are heavy. Exercise caution when lifting and moving these items.

=== FAS70 and FAS90 storage systems
A FAS70 or FAS90 storage system can weigh up to 62.83 lbs (28.5 kg). To lift the system, use two people or a hydraulic lift.

image::../media/drw_a1k_weight_caution_ieops-1698.svg[FAS70 and FAS90 lifting caution icon]

=== NS224 shelf
An NS224 storage shelf can weigh up to 66.78 lbs (30.29 kg). To lift the storage shelf, use two people or a hydraulic lift. Keep all components in the storage shelf (both front and rear) to prevent unbalancing the shelf weight.

image::../media/drw_ns224_lifting_weight_ieops-1716.svg[NS224 lifting caution]

=== DS460C shelf
A DS460C shelf can weigh up to 360.4 (181.1  kg). To lift the storage shelf, you may need up to five people or a hydraulic lift. Keep all components in the storage shelf (both front and rear) to prevent unbalancing the shelf weight.

image::../media/drw_ds460c_weight_warning_ieops-1932.svg[DS460C lifting caution]

.Related information

*  https://library.netapp.com/ecm/ecm_download_file/ECMP12475945[Safety information and regulatory notices^]
* https://hwu.netapp.com[NetApp Hardware Universe^]

.What's next?
After you've reviewed the installation requirements and considerations, you link:install-prepare.html[prepare to install your FAS70 or FAS90 storage system].

