---
permalink: a150/maintain-overview.html
sidebar: sidebar
keywords: aff A150 maintenance, maintenance, repairing a150, repairing aff a150, replace aff a150 components, replace aff a150 components
summary: Maintain the ASA A150 hardware
---
= Learn about maintaining your AFF A150 storage system
:icons: font
:imagesdir: ../media/

[.lead]
Maintain the hardware of your AFF A150 storage system to ensure long-term reliability and optimal performance. Perform regular maintenance tasks such as replacing faulty components to help prevent downtime and data loss.

== Boot media

The boot media stores a primary and secondary set of boot image files that the system uses when it boots. 


== Chassis
The chassis is the physical enclosure housing all the controller components such as the controller/CPU unit, power supply, and I/O.

== Controller

A controller consists of a board, firmware, and software. It controls the drives and implements the ONTAP functions.

== DIMM

You must replace a DIMM (dual in-line memory module) when a memory mismatch is present, or you have a failed DIMM.

== Drive

A drive is a device that provides the physical storage media for data.

== NVEM Battery

A battery is included with a controller and preserves cached data if the AC power fails.

== Power supply

A power supply provides a redundant power source in a controller shelf.

== Real time clock battery
A real time clock battery preserves system date and time information if the power is off. 

//July 2025: ontap-systems 370: deleted caching module since not supported for this platform.