---
permalink: asa-r2-70-90/bootmedia-replace-requirements-bmr.html
sidebar: sidebar
keywords: asa r2 a70, a90, replace the boot media
summary: Before replacing the boot media in your ASA A70 or A90 system, ensure you meet the necessary requirements for a successful replacement.
---
= Requirements for automated boot media recovery - ASA A70 and ASA A90
:icons: font
:imagesdir: ../media/

[.lead]
Before replacing the boot media in your ASA A70 or ASA A90 system, ensure you meet the necessary requirements for a successful replacement. This includes verifying that you have the correct replacement boot media, confirming the cluster ports on the impaired controller are working properly, and determining whether Onboard Key Manager (OKM) or External Key Manager (EKM) is enabled.

include::../_include/bootmedia_replace_requirements_cluster_bmr.adoc[]

.What's next

After you've reviewed the boot media requirements, you link:bootmedia-shutdown-bmr.html[shut down the controller].

//May 22, 2025: GH#1231, changed include name bootmedia_replace_requirements_bmr to add the "cluster" designation. This include used only for one platform family: aff a1k, aff 70-90, asa a1k, asa 70-90, fas70-90, aff c80.