---
permalink: asa-r2-70-90/controller-replace-move-hardware.html
sidebar: sidebar
keywords: asa r2 a70, asa r2 a90, move the controller module hardware
summary: Replace the controller in your ASA A70 or ASA A90 system when a hardware failure requires it. This process involves removing the impaired controller,  moving the components to the replacement controller, installing the replacement controller, and rebooting the system.
---
= Replace the controller in an ASA A70 or ASA A90 system
:icons: font
:imagesdir: ../media/

[.lead]
Replace the controller in your ASA A70 or ASA A90 system when a hardware failure requires it. This process involves removing the impaired controller,  moving the components to the replacement controller, installing the replacement controller, and rebooting the system.

== Step 1: Remove the controller module
You must remove the controller module from the chassis when you replace the controller module or replace a component inside the controller module.


include::../_include/a70-90_controller_remove_physical.adoc[]

== Step 2: Move the power supplies

Move the power supplies to the replacement controller.

include::../_include/a70-90_controller_replace_move_psu.adoc[]

== Step 3: Move the fans

Move the fans modules to the replacement controller module.

include::../_include/a70-90_controller_replace_move_fans.adoc[]

== Step 4: Move the NV battery

Move the NV battery to the replacement controller module.

include::../_include/a70-90_controller_replace_move_nvbattery.adoc[]

== Step 5: Move system DIMMs

Move the DIMMs to the replacement controller module.

include::../_include/a70-90_controller_replace_move_dimms.adoc[]

== Step 6: Move the I/O modules

Move the I/O modules to the replacement controller module.

include::../_include/a70-90_controller_replace_move_io_modules.adoc[]

== Step 7: Move the System Management module

Move the System Management module to the replacement controller module.

include::../_include/a70-90_controller_replace_move_sys_mgmt.adoc[]

== Step 8: Move the NVRAM module

Move the NVRAM module to the replacement controller module.

include::../_include/a70-90_controller_replace_move_nvram.adoc[]

== Step 9: Install the controller module
Reinstall the controller module and reboot it.

include::../_include/a70-90_controller_install_controller_replace.adoc[]

.What's next?

After you've replaced the impaired ASA A70 or ASA A90 controller, you need to link:controller-replace-system-config-restore-and-verify.html[restore the system configuration].
//2025-11-25 ontap-systems-internal/1315 and ontap-systems-internal/1380
