---
permalink: asa-r2-70-90/dimm-replace.html
sidebar: sidebar
keywords: asa r2 a70, asa r2 a90, replace a dimm
summary: Replace a DIMM in your  ASA A70 or  ASA A90 system if excessive correctable or uncorrectable memory errors are detected. Such errors can prevent the storage system from booting ONTAP. The replacement process involves shutting down the impaired controller, removing it, replacing the DIMM, reinstalling the controller, and then returning the failed part to NetApp.
---
= Replace a DIMM - ASA A70 and ASA A90
:icons: font
:imagesdir: ../media/

[.lead]
Replace a DIMM in your ASA A70 or ASA A90 system if excessive correctable or uncorrectable memory errors are detected. Such errors can prevent the storage system from booting ONTAP. The replacement process involves shutting down the impaired controller, removing it, replacing the DIMM, reinstalling the controller, and then returning the failed part to NetApp.

.Before you begin

* All other components in the system must be functioning properly; if not, you must contact technical support.

* You must replace the failed component with a replacement FRU component you received from your provider.

== Step 1: Shut down the impaired controller
 
Shut down or take over the impaired controller.
 
include::../_include/shutdown_most_frus.adoc[]

== Step 2: Remove the controller module

include::../_include/a70-90_controller_remove_physical.adoc[]

== Step 3: Replace a DIMM

include::../_include/a70-90_dimm_replace_asa_r2.adoc[]


== Step 4: Reinstall the controller module

include::../_include/a70-90_controller_install_step_physical.adoc[]

== Step 5: Return the failed part to NetApp

include::../_include/complete_rma.adoc[]

