---
permalink: asa-r2-70-90/io-module-add.html
sidebar: sidebar
keywords: asa r2 a70, asa r2 a90, add I/O module
summary: Add an I/O module to your  ASA A70 or  ASA A90 system to enhance network connectivity and expand your system’s ability to handle data traffic.
---
= Add an I/O module - ASA A70 and ASA A90
:icons: font
:imagesdir: ../media/

[.lead]
Add an I/O module to your  ASA A70 or  ASA A90 system to enhance network connectivity and expand your system’s ability to handle data traffic.

You can add an I/O module to your ASA A70 and ASA A90 storage system when there are empty slots available or when all slots are fully populated.

.About this task

If needed, you can turn on the storage system location (blue) LEDs to aid in physically locating the affected storage system. Log into the BMC using SSH and enter the `system location-led _on_` command.

A storage system has two location LEDs, one on each controller. Location LEDs remain illuminated for 30 minutes. 

You can turn them off by entering the `system location-led _off_` command. If you are unsure if the LEDs are on or off, you can check their state by entering the `system location-led show` command.

== Step 1: Shut down the impaired controller module

Shut down or take over the impaired controller module.

include::../_include/shutdown_most_frus.adoc[]

== Step 2: Add the new I/O module

include::../_include/add_io_module_cam.adoc[]