---
permalink: asa-r2-70-90/io-module-replace.html
sidebar: sidebar
keywords: asa r2 a70, asa r2 a90, replace a pcie card
summary: "To replace a PCIe card, you must disconnect the cables from the cards, remove the SFP and QSFP modules from the cards before removing the riser, reinstall the riser, and then reinstall the SFP and QSFP modules before cabling the cards."
---
= Replace an I/O module - ASA A70 and ASA A90
:icons: font
:imagesdir: ../media/

[.lead]
Replace an I/O module in your ASA A70 or ASA A90 system when the module fails or requires an upgrade to support higher performance or additional features. The replacement process involves shutting down the controller, replacing the failed I/O module, rebooting the controller, and returning the failed part to NetApp.

ou can use this procedure with all versions of ONTAP supported by your storage system.

.Before you begin
* You must have the replacement part available.
* Make sure all other components in the storage system are functioning properly; if not, contact technical support.


== Step 1: Shut down the impaired controller
 
Shut down or take over the impaired controller.
 

include::../_include/shutdown_most_frus.adoc[]

== Step 2: Replace a failed I/O module
include::../_include/a70-90_io_module_replace_asa_r2.adoc[]

== Step 3: Reboot the controller

include::../_include/io_module_replace_reboot.adoc[]

== Step 4: Return the failed part to NetApp

include::../_include/complete_rma.adoc[]