---
permalink: asa-r2-70-90/nvdimm-battery-replace.html
sidebar: sidebar
keywords: asa r2 a70, asa r2 a90, replace the NV battery, NV battery
summary: Replace the NV battery in your ASA A70 or ASA A90 system when the battery begins to lose charge or fails, as it is responsible for preserving critical system data during power outages. The replacement process involves shutting down the impaired controller, removing the controller module, replacing the NV battery, reinstalling the controller module, and returning the failed part to NetApp.
---
= Replace the NV battery - ASA A70 and ASA A90
:icons: font
:imagesdir: ../media/

[.lead]
Replace the NV battery in your ASA A70 or ASA A90 system when the battery begins to lose charge or fails, as it is responsible for preserving critical system data during power outages. The replacement process involves shutting down the impaired controller, removing the controller module, replacing the NV battery, reinstalling the controller module, and returning the failed part to NetApp.

All other components in the system must be functioning properly; if not, you must contact technical support.

== Step 1: Shut down the impaired controller

Shut down or take over the impaired controller.
-
include::../_include/shutdown_most_frus.adoc[]

== Step 2: Remove the controller module

include::../_include/a70-90_controller_remove_physical.adoc[]

== Step 3: Replace the NV battery

include::../_include/a70-90_nvdimm_battery_replace_asa_r2.adoc[]

== Step 4: Reinstall the controller module

include::../_include/a70-90_controller_install_step_physical.adoc[]

== Step 5: Return the failed part to NetApp

include::../_include/complete_rma.adoc[]


