---
permalink: asa-r2-70-90/nvram-replace.html
sidebar: sidebar
keywords: asa r2 a70, asa r2 a90, replace an nvdimm
summary: 'The NVRAM module consists of the NVRAM12 and DIMMs and up to two NVMe SSD Flash Cache modules (Flash Cache or caching modules) per NVRAM module.'
---
= Replace NVRAM - ASA A70 and ASA A90
:icons: font
:imagesdir: ../media/

[.lead]
Replace the NVRAM in your ASA A70 or ASA A90 system when the non-volatile memory becomes faulty or requires an upgrade. The replacement process involves
shutting down the impaired controller, completely removing power by pulling the controller out a few inches, replacing the NVRAM module or the NVRAM DIMM, reassigning the disks, and returning the failed part to NetApp.

The NVRAM module consists of the NVRAM12 hardware and field-replaceable DIMMs. 
You can replace a failed NVRAM module or the DIMMs inside the NVRAM module. 

.Before you begin
* Make sure you have the replacement part available. You must replace the failed component with a replacement component you received from NetApp.

* Make sure all other components in the storage system are functioning properly; if not, contact https://support.netapp.com[NetApp Support].

== Step 1: Shut down the impaired controller
Shut down or take over the impaired controller.

include::../_include/shutdown_most_frus.adoc[]

== Step 2: Replace the NVRAM module or NVRAM DIMM

include::../_include/a70-90_nvram_replace_asa_r2.adoc[]


== Step 4: Return the failed part to NetApp

include::../_include/complete_rma.adoc[]