---
permalink: asa-r2-70-90/system-management-replace.html
sidebar: sidebar
keywords:  ASA A70,  ASA A90, replace the system management module
summary: Replace the System Management module in your ASA A70 or ASA A90 system when it becomes defective or its firmware is corrupted. The replacement process involves shutting down the controller, replacing the failed System Management module, rebooting the controller, updating the license keys, and returning the failed part to NetApp.
---
= Replace the system management module - ASA A70 and ASA A90
:icons: font
:imagesdir: ../media/

[.lead]
Replace the System Management module in your ASA A70 or ASA A90 system when it becomes defective or its firmware is corrupted. The replacement process involves shutting down the controller, replacing the failed System Management module, rebooting the controller, updating the license keys, and returning the failed part to NetApp.

.Before you begin
* This procedure uses the following terminology:
 ** The impaired controller is the controller on which you are performing maintenance.
 ** The healthy controller is the HA partner of the impaired controller.
 * All other system components must be working properly.
* The partner controller must be able to take over the impaired controller.
* You must replace the failed component with a replacement FRU component you received from your provider.

.About this task
The System Management module, located at the back of the controller in slot 8,  contains onboard components for system management, as well as ports for external management. The target controller must be shut down to replace an impaired System Management module or replace the boot media.

== Step 1: Shut down the impaired controller

Shut down or take over the impaired controller.

include::../_include/shutdown_most_frus.adoc[]

== Step 2: Replace the System Management module

include::../_include/a70-90_system_mgmt_replace_asa_r2.adoc[]

== Step 3: Reboot the controller

include::../_include/reboot_controller.adoc[]

== Step 4: Install licenses and register serial number

include::../_include/install_licenses_serial_number-system_mgmt_module.adoc[]

== Step 5: Return the failed part to NetApp

include::../_include/complete_rma.adoc[]
