---
permalink: c800/rtc-battery-replace.html
sidebar: sidebar
keywords: aff c800, replace the real-time clock battery
summary: "Replace the real-time clock battery, commonly known as a coin cell battery, in your AFF C800 system to ensure that services and applications relying on accurate time synchronization remain operational."
---
= Replace the real-time clock battery in an AFF C800 system
:icons: font
:imagesdir: ../media/

[.lead]
Replace the real-time clock (RTC) battery, commonly known as a coin cell battery, in your AFF C800 system to ensure that services and applications relying on accurate time synchronization remain operational.

.Before you begin
* Understand that you can use this procedure with all versions of ONTAP supported by your system.
* Make sure all other components in the system are functioning properly; if not, you must contact technical support.

== Step 1: Shut down the impaired controller

Shut down or take over the impaired controller.

include::../_include/shutdown_most_frus.adoc[]

== Step 2: Remove the controller module

You must remove the controller module from the chassis when you replace the controller module or replace a component inside the controller module.

include::../_include/800_controller_remove_physical.adoc[]

== Step 3: Replace the RTC battery

Replace the RTC battery.

include::../_include/800_rtc_battery_replace.adoc[]

== Step 4: Reinstall the controller module

Reinstall the controller module and reboot it.

include::../_include/800_controller_install_step_physical.adoc[]

== Step 5: Return the failed part to NetApp

include::../_include/complete_rma.adoc[]


//2025-11-25 ontap-systems-internal/1315 and ontap-systems-internal/1380
