---
permalink: fas2600/chassis-replace-overview.html
sidebar: sidebar
keywords: fas2600, replace the chassis
summary: "Before replacing the chassis in your FAS2600 system, review the requirements for moving components to the replacement chassis and swapping it into the equipment rack or system cabinet."
---
= Review the requirements for replacing a chassis in a FAS2600 system
:icons: font
:imagesdir: ../media/

[.lead]
Before replacing the chassis in your FAS2600 system, review the requirements for moving the power supplies, hard drives, and controller module or modules from the impaired chassis to the new chassis, and swapping the impaired chassis in the equipment rack or system cabinet for the new one of the same model.

All other components in the system must be functioning properly. If they aren't, contact technical support.

* You can use this procedure with all versions of ONTAP supported by your system.
* This procedure is written with the assumption that you are moving all drives and controller module or modules to the new chassis, and that the chassis is a new component from NetApp.
* This procedure is disruptive. For a two-node cluster, you have a complete service outage, and for a multi-node cluster, you have a partial outage.

video::FcitUi3YEyI[youtube]
