---
permalink: fas2600/controller-replace-overview.html
sidebar: sidebar
keywords: fas2600, prerequisite, replace the controller module
summary: 'Before replacing the controller in your FAS2600 system, review the prerequisites for the replacement procedure and select the correct one for your version of the ONTAP operating system.'
---
= Review requirements before replacing the controller in your FAS2600 system
:icons: font
:imagesdir: ../media/

[.lead]
Before replacing the controller in your FAS2600 system, review the prerequisites for the replacement procedure and select the correct one for your version of the ONTAP operating system.

include::../_include/console-logging-note.adoc[]

* All drive shelves must be working properly.
* If your system is in an HA pair, the healthy controller must be able to take over the controller that is being replaced (referred to in this procedure as the "`impaired controller`").
* This procedure includes steps for automatically or manually reassigning drives to the _replacement_ controller, depending on your system's configuration.
+
You should perform the drive reassignment as directed in the procedure.

* You must replace the failed component with a replacement FRU component you received from your provider.
* You must be replacing a controller module with a controller module of the same model type. You cannot upgrade your system by just replacing the controller module.
* You cannot change any drives or drive shelves as part of this procedure.
* In this procedure, the boot device is moved from the impaired controller to the _replacement_ controller so that the _replacement_ controller will boot up in the same version of ONTAP as the old controller module.
* It is important that you apply the commands in these steps on the correct systems:
 ** The _impaired_ controller is the controller that is being replaced.
 ** The _replacement_ controller is the new controller that is replacing the impaired controller.
 ** The _healthy_ controller is the surviving controller.

