---
permalink: asa-r2-a20-30-50/bootmedia-replace-requirements-bmr.html
sidebar: sidebar
keywords: asa a20, asa a30, asa a50, replace the boot media
summary: Before replacing the boot media in your ASA A20, ASA A30 or ASA A50 storage system, ensure you meet the necessary requirements and considerations for a successful replacement. This includes verifying that you have the correct replacement boot media, confirming that the e0S (e0M wrench) port on the impaired controller is is working properly, and determining whether Onboard Key Manager (OKM) or External Key Manager (EKM) is enabled.
---
= Requirements to replace the boot media - ASA A20, ASA A30, and ASA A50
:icons: font
:imagesdir: ../media/

[.lead]
Before replacing the boot media in your ASA A20, ASA A30 or ASA A50 storage system, ensure you meet the necessary requirements and considerations for a successful replacement. This includes verifying that you have the correct replacement boot media, confirming that the e0S (e0M wrench) port on the impaired controller is is working properly, and determining whether Onboard Key Manager (OKM) or External Key Manager (EKM) is enabled.

Review the following requirements.

include::../_include/bootmedia_replace_requirements_e0s_bmr.adoc[]

.What's next

After you've reviewed the boot media requirements, you link:bootmedia-shutdown-bmr.html[shut down the impaired controller].


//May 22, 2025: GH#1231, changed include name g_bootmedia_replace_requirements_bmr to make generic (remove "g") and add the "eos" designation. This include is used for the following platform family: aff a20-30-50, aff c30-60, fas50, asa a20-30-50, asa c30; and for some older platforms.