---
permalink: asa-r2-a20-30-50/bootmedia-replace-requirements-bmr.html
sidebar: sidebar
keywords: asa a20, asa a30, asa a50, replace the boot media
summary: Learn about the requirements for replacing the boot media.
---
= Requirements - ASA A20, ASA A30, and ASA A50
:icons: font
:imagesdir: ../media/

[.lead]
Before replacing the boot media in your ASA A20, ASA A30 or ASA A50 storage system, ensure you meet the necessary requirements and considerations for a successful replacement. This includes verifying that you have the correct replacement boot media, confirming that there are no defective cluster ports on the controller, and determining whether Onboard Key Manager (OKM) or External Key Manager (EKM) is enabled.

= Requirements
include::../_include/g_bootmedia_replace_requirements_bmr.adoc[]

//March 2025:
//Can't use this general include file ASA70-90 uses since it references ports ASA 20-30-50 does not use. Must continue to use the above g requirements include file.
//include::../_include/bootmedia_replace_requirements_bmr.adoc[]

== Considerations

* It is important that you apply the commands in these steps on the correct controller:
** The _impaired_ controller is the controller on which you are performing maintenance.
** The _healthy_ controller is the HA partner of the impaired controller.

* If needed, you can turn on the platform chassis location (blue) LEDs to aid in physically locating the affected platform. Log into the BMC using SSH and enter the `system location-led _on_` command.
+
A platform chassis has three location LEDs: one on the operator display panel and one on each controller. Location LEDs remain illuminated for 30 minutes. 
+
You can turn them off by entering the `system location-led _off_` command. If you are unsure if the LEDs are on or off, you can check their state by entering the `system location-led show` command.


.What's next

After you've reviewed the boot media requirements, you link:bootmedia-shutdown-bmr.html[shut down the impaired controller].



// Kill below: old, use above from ASA 70-90 BMR looks like generic include for all Vino and Gizo.
//[.lead]
include::../_include/g_bootmedia_replace_requirements_bmr.adoc[]

//.What's next

//After you've reviewed the boot media requirements, link:bootmedia-shutdown-bmr.html[shut down the impaired controller].
