---
permalink: asa-r2-a20-30-50/dimm-replace.html
sidebar: sidebar
keywords: asa a20, asa a30, asa a50, replace a dimm
summary: Replace a DIMM in your ASA A20, ASA A30, or ASA A50 system if excessive correctable or uncorrectable memory errors are detected. Such errors can prevent the storage system from booting ONTAP. The replacement process involves shutting down the impaired controller, removing it, replacing the DIMM, reinstalling the controller, and then returning the failed part to NetApp.
---
= Replace a DIMM - ASA A20, ASA A30, and ASA A50
:icons: font
:imagesdir: ../media/

[.lead]
Replace a DIMM in your ASA A20, ASA A30, or ASA A50 system if excessive correctable or uncorrectable memory errors are detected. Such errors can prevent the storage system from booting ONTAP. The replacement process involves shutting down the impaired controller, removing it, replacing the DIMM, reinstalling the controller, and then returning the failed part to NetApp.

You must replace a DIMM in the controller when your storage system encounters errors such as, excessive CECC (Correctable Error Correction Codes) errors that are based on Health Monitor alerts or uncorrectable ECC errors, typically caused by a single DIMM failure preventing the storage system from booting ONTAP. 

.Before you begin

* Ensure all other components in the storage system are working correctly; if not, contact https://mysupport.netapp.com/site/global/dashboard[NetApp Support] before continuing."

* You must replace the failed FRU component with a replacement FRU component you received from your provider.

.About this task
If needed, you can turn on the storage system location (blue) LEDs to aid in physically locating the affected storage system. Log into the BMC using SSH and enter the `system location-led _on_` command.

A storage system has three location LEDs: one on the operator display panel and one on each controller. Location LEDs remain illuminated for 30 minutes. 

You can turn them off by entering the `system location-led _off_` command. If you are unsure if the LEDs are on or off, you can check their state by entering the `system location-led show` command.

== Step 1: Shut down the impaired controller

include::../_include/shutdown_most_frus.adoc[]


== Step 2: Remove the controller

include::../_include/g_controller_remove.adoc[]

. Open the controller cover by turning the thumbscrew counterclockwise to loosen, and then open the cover. 


== Step 3: Replace a DIMM

include::../_include/g_dimm_replace_asa_r2.adoc[]



== Step 4: Reinstall the controller

Reinstall the controller into the chassis and reboot it.

include::../_include/g_controller_reinstall.adoc[]

== Step 5: Return the failed part to NetApp

include::../_include/complete_rma.adoc[]



