---
permalink: asa-r2-a20-30-50/io-module-overview.html
sidebar: sidebar
keywords: ASA A90, ASA A70, replace io module, io module add, io module hotswap
summary: The ASA A20, ASA A30, and ASA A50 systems offer flexibility in expanding or replacing I/O modules to enhance network connectivity and performance. Adding, hot-swapping or replacing an I/O module is essential when upgrading network capabilities or addressing a failed module.
---
= Overview of add, hot-swap, and replace an I/O module - ASA A20, ASA A30, and ASA A50
:icons: font
:imagesdir: ../media/

[.lead]
The ASA A20, ASA A30, and ASA A50 systems offer flexibility in expanding or replacing I/O modules to enhance network connectivity and performance. Adding, hot-swapping or replacing an I/O module is essential when upgrading network capabilities or addressing a failed module.

You can replace a failed I/O module in your storage system with the same type of I/O module, or with a different type of I/O module. You can also add an I/O module to a storage system with available slots.

* link:io-module-add.html[Add an I/O module]
+
Adding additional I/O modules can improve redundancy, helping to ensure that the storage system remains operational even if one I/O module fails.

* link:io-module-hotswap-ha-slot4.html[Hot-swap a cluster and HA I/O module]
+
Hot-swapping a failing cluster and HA I/O module can restore the storage system to its optimal operating state. Hot-swapping is done without having to shut down the impaired controller.
+
To use this procedure, your storage system must be running ONTAP 9.17.1 or later and meet specific system requirements.

* link:io-module-replace.html[Replace an I/O module]
+
Replacing a failing I/O module can restore the storage system to its optimal operating state. 
