---
permalink: asa-r2-key-specifications/asa-a90-key-specifications.html
sidebar: sidebar
summary: Key specifications for ASA A90
---
= Key specifications for ASA A90
:icons: font
:imagesdir: ../media/

[.lead]
The following are a selection of key specifications for ASA A90 in a single high availability pair. Visit https://hwu.netapp.com[NetApp Hardware Universe^] (HWU) for a complete list of ASA A90 specifications.

=== Key specifications for ASA A90

Platform Configuration: ASA A90 Single Chassis HA Pair

Max Raw Capacity: 2.6622 PB

Memory: 2048.0000 GB

Form Factor: 4U chassis with 2 HA controllers and 48 drive slots

ONTAP Version: ONTAP: 9.16.1P2

PCIe Expansion Slots: 18

Minimum ONTAP Version: ONTAP 9.16.0

=== Scaleout Maximums
* Type: NAS
* Type: SAN; HA Pairs: 6; Raw Capacity: 16.0 PB / 14.2 PiB; Max Memory: 12288 GB
* Type: HA Pair; Raw Capacity: 2.7 PB / 2.4 PiB; Max Memory: 2048.0000

=== IO

==== Onboard IO
No onboard IO data.

==== Total IO
* Protocol: Ethernet 200 Gbps; Ports: 24
* Protocol: Ethernet 100 Gbps; Ports: 36
* Protocol: Ethernet 25 Gbps; Ports: 56
* Protocol: Ethernet 10 Gbps; Ports: 56
* Protocol: FC 64 Gbps; Ports: 56
* Protocol: NVMe/FC  64 Gbps; Ports: 56
* Ports: 0

==== Management Ports
* Protocol: Ethernet 1 Gbps; Ports: 2
* Protocol: RS-232 115 Kbps; Ports: 4
* Protocol: USB 600 Mbps; Ports: 2

=== Storage Networking Supported
FC
iSCSI
NVMe/FC 
NVMe/TCP
=== System Environment Specifications
* Typical Power: 8304 BTU/hr
* Worst-case Power: 10948 BTU/hr
* Weight: 170.4 lb
77.3 kg
* Height: 4U
* Width: 19” IEC rack-compliant (17.6” 44.7 cm)
* Depth: 34.5”
(36.6” with cable management bracket)
* Operating Temp/Altitude/Humidity: 10°C to 35°C
50°F to 
95°F) at
<= 3048m
<= 10000 ft) elevation;8% to 80%
relative humidity, noncondensing
* Non-operating Temp/Humidity: -40°C to 70°C (-40°F to 158°F) upto 12192m (40000 ft)
10% to 95%  relative humidity, noncondensing, in original container
* Acoustic Noise: Declared sound power (LwAd): 8.6
Sound pressure (LpAm) (bystander positions): 71.6 dB

=== Compliance
* Certifications EMC/EMI: AMCA,
FCC,
ICES,
KC,
Morocco,
VCCI
* Certifications safety: BIS,
CB,
CSA,
G_K_U-SoR,
IRAM,
NOM,
NRCS,
SONCAP,
TBS
* Certifications Safety/EMC/EMI: EAC,
UKRSEPRO
* Certifications Safety/EMC/EMI/RoHS: BSMI,
CE DoC,
UKCA DoC
* Standards EMC/EMI: BS-EN-55032,
BS-EN55035,
CISPR 32,
EN55022,
EN55024,
EN55032,
EN55035,
EN61000-3-2,
EN61000-3-3,
FCC Part 15 Class A,
ICES-003,
KS C 9832,
KS C 9835
* Standards Safety: ANSI/UL60950-1,
ANSI/UL62368-1,
BS-EN62368-1,
CAN/CSA C22.2 No. 60950-1,
CAN/CSA C22.2 No. 62368-1,
CNS 15598-1,
EN60825-1,
EN62368-1,
IEC 62368-1,
IEC60950-1,
IS 13252(part 1)

=== High Availability
Ethernet based baseboard management controller (BMC) and ONTAP management interface
Redundant hot-swappable controllers
Redundant hot-swappable power supplies
SAS in-band management over SAS connections for external shelves