---
permalink: afx/afx-cable-overview.html
sidebar: sidebar
keywords: afx, afx 1k, cable, overview, cisco 9332, cisco 9364, cabling, hardware, switches, storage shelves, disk shelves, controller nodes
summary: Learn how to cable your controller nodes to the network, switches, and storage shelves. 
---
= Supported configurations for your AFX 1K storage system
:icons: font
:imagesdir: ../media/

[.lead]
Learn about the supported hardware components and cabling options for the AFX 1K storage system, including compatible storage disk shelves, switches, and cable types required for proper system setup. 

== Supported AFX 1K cabling configuration
The initial configuration of the AFX 1K storage system supports a minimum of four controller nodes connected through dual switches to the storage disk shelves. 

Additional controller nodes and disk shelves can be used to expand on the initial AFX 1K storage system configuration. Expanded AFX 1K configurations follow the same switch-based cabling methodology as the four node schema depicted below. 

image:../media/drw_afx_cable_overview_half_node_ieops-2358.svg[AFK 1K four node cabling]

== Supported hardware components
Review the compatible storage disk shelves, switches, and cable types for the AFX 1K storage system.

[options="header"]
|===
a| *Controller Shelf* a| *Disk Shelf* a| *Supported Switches* a| *Supported Cables*
a|
AFX 1K
a|
NX224
a|
* Cisco Nexus 9332D-GX2B (400GbE)
* Cisco Nexus 9364D-GX2A (400GbE)
a|
* 400GbEx100GbE QSFP breakout cable cables

NOTE: Breakout cables are used for connections between the switches, controller, and disk shelf. 

* RJ-45 cables
* Cluster/HA interconnect cables
* ISL cables for connection between switch A and switch B
|===

== Cabling and configuration considerations for Cisco switches
Before configuring your Cisco 9332D-GX2b or 9364D-GX2A switch, review the following considerations. 

=== Support for NVIDIA CX6-DX Ethernet ports
If connecting a switch port to an ONTAP controller using NVIDIA  ConnectX-6 Dx (CX6-DX) NIC port (part number X50130B), you must hard-code the switch port speed.

[subs=+quotes]
----
(cs1)# *configure*
(cs1)(config)# *interface Ethernet1/16/?*
(cs1)(config-if)# *speed 100000*
(cs1)(config-if)# *no negotiate auto*
(cs1)(config-if)# *exit*
(cs1)(config)# *exit*
(cs1)# *copy running-config startup-config*
----
See the https://hwu.netapp.com/Switch/Index[Hardware Universe^] for more information on switch ports.

== Network requirements for your AFX 1K system
Record the required information for each network you connect to your AFX 1K storage system. 

=== Gather network information
Before you begin the installation of your AFX storage system, gather the required network information

* Host names and IP addresses for each of the storage system controllers and all applicable switches.
+
Most storage system controllers are managed through the e0M interface by connecting to the Ethernet service port (wrench icon).
+
Refer to the https://hwu.netapp.com[Hardware Universe^] for the latest information.

* Cluster management IP address
+
The cluster management IP address is a unique IPv4 address for the cluster management interface used by the cluster administrator to access the admin storage VM and manage the cluster. You can obtain this IP address from the administrator responsible for assigning IP addresses in your organization.

* Network subnet mask
+
During cluster setup, ONTAP recommends a set of network interfaces appropriate for your configuration. You can adjust the recommendation if necessary.

* Network gateway IP address

* Partner node IP address

* DNS domain names

* DNS name server IP addresses

* NTP server IP addresses

* Data subnet mask

* IP subnet for management network traffic.

== Network requirements for Cisco switches
For Cisco Nexus 9332D-GX2B and and 9364D-GX2A switch installation and maintenance, be sure to review cabling and network requirements.

=== Network requirements

You need the following network information for all switch configurations.

* IP subnet for management network traffic
* Host names and IP addresses for each of the storage system controllers and all applicable switches
* Most storage system controllers are managed through the e0M interface by connecting to the Ethernet service port (wrench icon). 
* Refer to the https://hwu.netapp.com[Hardware Universe^] for the latest information.

=== Cabling requirements

* You have the appropriate number and type of cables and cable connectors for your switches. See the https://hwu.netapp.com[Hardware Universe^].

* Depending on the type of switch you are initially configuring, you need to connect to the switch console port with the included console cable.

.What's next?
After reviewing the supported system configuration and hardware components, you link:cable-hardware.html[cable the controllers and storage shelves for your AFX 1K system].
