---
sidebar: sidebar
permalink: afx/deploy-hardware.html
keywords: afx, afx 1k, install, setup, hardware, deploy
summary: Learn how to install the rail kits for the AFX storage system and storage shelves, and secure the AFX hardware in the cabinet or telco rack. 
---
= Install your AFX storage system
:icons: font
:imagesdir: ../media/

[.lead]
After you prepare to install your AFX storage system, install the hardware for the system. First, install the rail kits. Then install and secure your storage system in a cabinet or telco rack.


.Before you begin

* Make sure you have the instructions packaged with the rail kit.

* Be aware of the safety concerns associated with the weight of the storage system and storage shelf.

* Understand that the airflow through the storage system enters from the front where the bezel or end caps are installed and exhausts out the rear where the ports are located.

.Steps

. Install the rail kits for your storage system and storage shelves, as needed, using the instructions included with the kits.

. Install and secure your storage system in the cabinet or telco rack:

.. Position the storage system onto the rails in the middle of the cabinet or telco rack, and then support the storage system from the bottom and slide it into place.

.. Secure the storage system to the cabinet or telco rack using the included mounting screws.

+
. Attach the bezel to the front of the storage system.
+
. If your AFX system came with a cable management device, attach it to the rear of the storage system.
+
image::../media/drw_affa1k_install_cable_mgmt_ieops-1697.svg[Install cable management device]
+
. Install and secure the storage shelf:
+

.. Position the back of the storage shelf onto the rails, and then support the shelf from the bottom and slide it into the cabinet or telco rack.
+
If you are installing multiple storage shelves, place the first storage shelf directly above the controllers. Place the second storage shelf directly under the controllers. Repeat this pattern for any additional storage shelves.

.. Secure the storage shelf to the cabinet or telco rack using the included mounting screws.


.What's next?
After you've installed the hardware for your AFX system, you link:cable-hardware.html[cable the controllers and storage shelves for your AFX system].

// 2024 Sept 23, ONTAPDOC 1922