---
sidebar: sidebar
permalink: /afx/install-network-reqs.html
keywords: shared storage cluster switch
summary: From ONTAP 9.9.1, you can use Cisco Nexus 9364d-gx2a switches to combine storage and cluster functionality into a shared switch scenario.
---
= Network requirements for your AFX 1K system
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Record the required information for each network you connect to your AFX 1K storage system. 

== Gather network information
Before you begin the installation of your AFX storage system, gather the required network information

* Host names and IP addresses for each of the storage system controllers and all applicable switches.
+
Most storage system controllers are managed through the e0M interface by connecting to the Ethernet service port (wrench icon).
+
Refer to the https://hwu.netapp.com[Hardware Universe^] for the latest information.

* Cluster management IP address
+
The cluster management IP address is a unique IPv4 address for the cluster management interface used by the cluster administrator to access the admin storage VM and manage the cluster. You can obtain this IP address from the administrator responsible for assigning IP addresses in your organization.

* Network subnet mask
+
During cluster setup, ONTAP recommends a set of network interfaces appropriate for your configuration. You can adjust the recommendation if necessary.

* Network gateway IP address

* Partner node IP address

* DNS domain names

* DNS name server IP addresses

* NTP server IP addresses

* Data subnet mask

* IP subnet for management network traffic.

== Network requirements for Cisco switches
For Cisco Nexus 9332D-GX2B and and 9364D-GX2A switch installation and maintenance, be sure to review cabling and network requirements.

=== Network requirements

You need the following network information for all switch configurations.

* IP subnet for management network traffic
* Host names and IP addresses for each of the storage system controllers and all applicable switches
* Most storage system controllers are managed through the e0M interface by connecting to the Ethernet service port (wrench icon). 
* Refer to the https://hwu.netapp.com[Hardware Universe^] for the latest information.

=== Cabling requirements

* You have the appropriate number and type of cables and cable connectors for your switches. See the https://hwu.netapp.com[Hardware Universe^].

* Depending on the type of switch you are initially configuring, you need to connect to the switch console port with the included console cable.