---
sidebar: sidebar
permalink: /afx/install-network-reqs.html
keywords: shared storage cluster switch
summary: From ONTAP 9.9.1, you can use Cisco Nexus 9364d-gx2a switches to combine storage and cluster functionality into a shared switch scenario.
---
= Network requirements for your AFX 1K system
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Record the required information for each network you connect to your AFX 1K storage system. 

== Gather network information
Before you begin the installation of your AFX storage system, gather the required network information

* Host names and IP addresses for each of the storage system controllers and all applicable switches.
+
Most storage system controllers are managed through the e0M interface by connecting to the Ethernet service port (wrench icon).
+
Refer to the https://hwu.netapp.com[Hardware Universe^] for the latest information.

* Cluster management IP address
+
The cluster management IP address is a unique IPv4 address for the cluster management interface used by the cluster administrator to access the admin storage VM and manage the cluster. You can obtain this IP address from the administrator responsible for assigning IP addresses in your organization.

* Network subnet mask
+
During cluster setup, ONTAP recommends a set of network interfaces appropriate for your configuration. You can adjust the recommendation if necessary.

* Network gateway IP address

* Partner node IP address

* DNS domain names

* DNS name server IP addresses

* NTP server IP addresses

* Data subnet mask

* IP subnet for management network traffic.


