---
sidebar: sidebar
permalink: afx/prepare-hardware.html
keywords: prepare, hardware installation, afx, afx 1k
summary: Prepare to install the AFX storage system in your ONTAP environment and register the hardware to access support benefits. 
---
= Prepare to install an AFX storage system
:icons: font
:imagesdir: ../media/

[.lead]
Prepare to install your AFX storage system by getting the site ready, unpacking the boxes and comparing the contents of the boxes to the packing slip, and registering the system to access support benefits.

== Step 1: Prepare the site
To install your AFX storage system, ensure that the site and the cabinet or rack that you plan to use meet specifications for your configuration.

.Steps

. Use https://hwu.netapp.com[NetApp Hardware Universe^] to confirm that your site meets the environmental and electrical requirements for your storage system.

. Make sure you have adequate cabinet or rack space for your storage system, shelves, and any switches:
+

** 4U in an HA configuration
** 2U for each NS224 storage shelf
** 1U for most switches


[start=3]

. Install any required network switches.

+

See the https://docs.netapp.com/us-en/ontap-systems-switches/index.html[Switch documentation^] for installation instructions and link:https://hwu.netapp.com[NetApp Hardware Universe^] for compatibility information.

== Step 2: Unpack the boxes
After you've ensured that the site and the cabinet or rack that you plan to use for your AFX storage system meet the required specifications, unpack all boxes and compare the contents to the items on the packing slip.

.Steps

. Carefully open all the boxes and lay out the contents in an organized manner.

. Compare the contents you’ve unpacked with the list on the packing slip. If there are any discrepancies, note them down for further action. 

+
You can get your packing list by scanning the QR code on the side of the shipping carton.

+
The following items are some of the contents you might see in the boxes. 

+

[%rotate, grid="none", frame="none", cols="12,9,4"]
|===
|*Hardware*
|*Cables* |
a|* Bezel
* Storage system
* Rail kits with instructions (optional)
* Storage shelf (if you ordered additional storage)
a|* Management Ethernet cables (RJ-45 cables)
* Network cables
* Power cords
* Storage cables (if you ordered additional storage) 
* USB-C serial port cable |
|===



== Step 3: Register your storage system
After you've ensured that your site meets the requirements for your AFX storage system specifications, and you've verified that you have all the parts you ordered, you should register your system.

.Steps

. Locate the serial numbers for your storage system. 
+
You can find the serial numbers in the following locations:

- On the packing slip
- In your confirmation email
- On each controller or for some systems, on the system management module of each controller
+
image::../media/drw_ssn_label.svg[Example of the system serial number,width=200]
+

. Go to the http://mysupport.netapp.com/[NetApp Support Site^].

. Determine whether you need to register your storage system:
+
[cols="1a,2a" options="header"]
|===
| If you are a...| Follow these steps...
a|
Existing NetApp customer
a|

 .. Sign in with your username and password.
 .. Select *Systems* > *My Systems*.
 .. Confirm that the new serial number is listed.
 .. If the serial number is not listed, follow the instructions for new NetApp customers.

a|
New NetApp customer
a|

 .. Click *Register Now*, and create an account.
 .. Select *Systems* > *Register Systems*.
 .. Enter the storage system's serial number and requested details.

After your registration is approved, you can download any required software. The approval process might take up to 24 hours.
|===

.What's next?
After you've prepared to install your AFX hardware, you link:deploy-hardware.html[install the hardware for your AFX storage system].

