---
permalink: asa-c250/overview.html
sidebar: sidebar
summary: Key specifications for the ASA-C250 platform group
---
= Key specifications for ASA C400
:icons: font
:imagesdir: ../media/

[.lead]
The following are a selection of key specifications for ASA C400 in a single high availability pair. Visit https://hwu.netapp.com[NetApp Hardware Universe^] (HWU) for a complete list of ASA C400 specifications.

== ASA C250

=== Key specifications for ASA C250

Platform Configuration: ASA C250 Single Chassis HA Pair

Max Raw Capacity: 1.4736 PB

Memory: 128.0000 GB

Form Factor: 2U chassis with 2 HA controllers and 24 drive slots

ONTAP Version: b_startONTAP: 9.16.1P2b_end

PCIe Expansion Slots: 4

Minimum ONTAP Version: ONTAP 9.13.1P1

=== Scaleout Maximums
|===
| Type | HA Pairs | Raw Capacity | Max Memory
| NAS |  |  | 
| SAN | 6 | 8.8 PB / 7.9 PiB | 768 GB
| HA Pair |  | 1.5 PB / 1.3 PiB | 128.0000
|===

=== IO

==== Onboard IO
|===
| Protocol | Ports
| Ethernet 25 Gbps | 4
| Ethernet 10 Gbps | 4
|===

==== Total IO
|===
| Protocol | Ports
| Ethernet 100 Gbps | 4
| Ethernet 25 Gbps | 20
| Ethernet 10 Gbps | 4
| FC 32 Gbps | 16
| NVMe/FC  32 Gbps | 16
|  | 0
|===

==== Management Ports
|===
| Protocol | Ports
| Ethernet 1 Gbps | 2
| RS-232 115 Kbps | 4
| USB 12 Mbps | 4
|===

=== Storage Networking Supported
FC;
iSCSI;
NVMe/FC ;

=== System Environment Specifications
* Typical Power: 2906 BTU/hr
* Worst-case Power: 3750 BTU/hr
* Weight: 54.3 lb<br/>24.6 kg
* Height: 2U
* Width: 19” IEC rack-compliant (17.6” 44.7 cm)
* Depth: 
* Operating Temp/Altitude/Humidity: 10°C to 35°C<br/>50°F to <br/>95°F) at<br/><= 3048m<br/><= 10000 ft) elevation;8% to 80%<br/>relative humidity, noncondensing
* Non-operating Temp/Humidity: -40°C to 70°C (-40°F to 158°F) upto 12192m (40000 ft)<br/>10% to 95%  relative humidity, noncondensing, in original container
* Acoustic Noise: Declared sound power (LwAd): 7.2;<br/>Sound pressure (LpAm) (bystander positions): 69.1 dB

=== Compliance
* Certifications EMC/EMI: AMCA,
FCC,
ICES,
KC,
Morocco,
VCCI
* Certifications safety: BIS,
CB,
CSA,
G_K_U-SoR,
IRAM,
NOM,
NRCS,
SONCAP,
TBS
* Certifications Safety/EMC/EMI: EAC,
UKRSEPRO
* Certifications Safety/EMC/EMI/RoHS: BSMI,
CE DoC,
UKCA DoC
* Standards EMC/EMI: BS-EN-55024,
BS-EN55035,
CISPR 32,
EN55022,
EN55024,
EN55032,
EN55035,
EN61000-3-2,
EN61000-3-3,
FCC Part 15 Class A,
ICES-003,
KS C 9832,
KS C 9835
* Standards Safety: ANSI/UL60950-1,
ANSI/UL62368-1,
BS-EN62368-1,
CAN/CSA C22.2 No. 60950-1,
CAN/CSA C22.2 No. 62368-1,
CNS 14336,
EN60825-1,
EN62368-1,
IEC 62368-1,
IEC60950-1,
IS 13252(part 1)

=== High Availability
Ethernet based baseboard management controller (BMC) and ONTAP management interface;
Redundant hot-swappable controllers;
Redundant hot-swappable power supplies;

