---
sidebar: sidebar
permalink: a5x/install-requirements.html
keywords: a5x, install, setup, cautions
summary: Review the equipment needed and the lifting precautions for your platform and shelves.
---
= Installation requirements - AFF A5X
:icons: font
:imagesdir: ../media/

[.lead]
Review the equipment needed and the lifting precautions for your AFF A5X storage system and storage shelves.

== Equipment needed for install
To install your storage system, you need the following equipment and tools. 

** Access to a Web browser to configure your storage system
** Electrostatic discharge (ESD) strap 
** Flashlight
** Laptop or console with a USB/serial connection
** Phillips #2 screwdriver 

== Lifting precautions 
Storage systems and shelves are heavy. Exercise caution when lifting and moving these items.

=== Storage system weight
Take the necessary precautions when moving or lifting your storage system.

The AFF A5X storage system can weigh up to 10 lbs (4.5 kg). To lift the storage system, use two people or a hydraulic lift.

image::../media/drw_a5x_weight_caution_ieops-xxxx.svg[AFF A5X lifting caution icon]

=== Shelf weight
Take the necessary precautions when moving or lifting your shelf.

An NS224 shelf can weigh up to 66.78 lbs (30.29 kg). To lift the shelf, use two people or a hydraulic lift. Keep all components in the shelf (both front and rear) to prevent unbalancing the shelf weight.

image::../media/drw_ns224_lifting_weight_ieops-1716.svg[NS224 NSM100 lifting caution]

.What's next?
After you've reviewed the hardware requirements, you link:install-prepare.html[prepare to install your AFF A5X storage system].