---
permalink: ns224/cable-asa-systems-hot-add-shelf.html
sidebar: sidebar
keywords: ns224, shelves, shelf, ns224 shelves, hot-add, ha, pair, cable, hot-add an ns224 drive shelf
summary: You cable each NS224 shelf you are hot-adding so that each shelf has two connections to each controller in the HA pair.
---
= Cable shelf to ASA systems - NS224 shelves
:icons: font
:imagesdir: ../media/

[.lead]
You cable each NS224 shelf you are hot-adding so that each shelf has two connections to each controller in the HA pair.

.Cable shelf to ASA A1K
[%collapsible]


====

You can hot-add up to three additional NS224 shelves (for a total of four shelves) to an ASA A1K HA pair.

.Before you begin

* You must have reviewed the link:requirements-hot-add-shelf.html[hot-add requirements and best practices]. 

* You must have completed the applicable procedures in link:prepare-hot-add-shelf.html[Prepare to hot-add a shelf]. 

* You must have installed the shelves, powered them on, and set the shelf IDs as described in link:prepare-hot-add-shelf.html[Install a shelf for a hot-add].


.About this task

* This procedure assumes that your HA pair has at least one existing NS224 shelf. 
* This procedure addresses the following hot-add scenarios:
** Hot-adding a second shelf to an HA pair with two RoCE-capable I/O modules in each controller. (You have installed a second I/O module and recabled the first shelf to both I/O modules or already had the first shelf cabled to two I/O modules. You will cable the second shelf to both I/O modules).
** Hot-adding a third shelf to an HA pair with three RoCE-capable I/O modules in each controller. (You have installed a third I/O module and will cable the third shelf to only the third I/O module).
** Hot-adding a third shelf to an HA pair with four RoCE-capable I/O modules in each controller. (You have installed a third and fourth I/O module and will cable the third shelf to the third and fourth I/O modules).
** Hot-adding a fourth shelf to an HA pair with four RoCE-capable I/O modules in each controller. (You have installed a fourth I/O module and recabled the third shelf to the third and fourth I/O modules or already had the third shelf cabled to the third and fourth I/O modules. You will cable the fourth shelf to both the third and fourth I/O module).

.Steps

. If the NS224 shelf you are hot-adding will be the second NS224 shelf in the HA pair, complete the following substeps. 
+
Otherwise, go to the next step.
+
.. Cable shelf NSM A port e0a to controller A slot 10 port a (e10a).
.. Cable shelf NSM A port e0b to controller B slot 11 port b (e11b).
.. Cable shelf NSM B port e0a to controller B slot 10 port a (e10a).
.. Cable shelf NSM B port e0b to controller A slot 11 port b (e11b).
+
The following illustration highlights the cabling for the second shelf in the HA pair with two RoCE-capable I/O modules in each controller:
+
image::../media/drw_ns224_vino_m_2shelves_2cards_ieops-1642.svg[Cabling for ASA A1K with two shelves and two IO modules, width=452px]
+
. If the NS224 shelf you are hot-adding will be the third NS224 shelf in the HA pair with three RoCE-capable I/O modules in each controller, complete the following substeps. 
Otherwise, go to the next step.
.. Cable shelf NSM A port e0a to controller A slot 9 port a (e9a).
.. Cable shelf NSM A port e0b to controller B slot 9 port b (e9b).
.. Cable shelf NSM B port e0a to controller B slot 9 port a (e9a).
.. Cable shelf NSM B port e0b to controller A slot 9 port b (e9b).
+
The following illustration highlights the cabling for the third shelf in the HA pair with three RoCE-capable I/O modules in each controller:
+
image::../media/drw_ns224_vino_m_3shelves_3cards_ieops-1643.svg[Cabling for ASA A1K with three shelves and three IO modules, width=452px]

. If the NS224 shelf you are hot-adding will be the third NS224 shelf in the HA pair with four RoCE-capable I/O modules in each controller, complete the following substeps. 
Otherwise, go to the next step.
.. Cable shelf NSM A port e0a to controller A slot 9 port a (e9a).
.. Cable shelf NSM A port e0b to controller B slot 8 port b (e8b).
.. Cable shelf NSM B port e0a to controller B slot 9 port a (e9a).
.. Cable shelf NSM B port e0b to controller A slot 8 port b (e8b).
+
The following illustration highlights the cabling for the third shelf in the HA pair with four RoCE-capable I/O modules in each controller:
+
image::../media/drw_ns224_vino_m_3shelves_4cards_ieops-1644.svg[Cabling for ASA A1K with three shelves and four IO modules, width=452px]

. If the NS224 shelf you are hot-adding will be the fourth NS224 shelf in the HA pair with four RoCE-capable I/O modules in each controller, complete the following substeps. 

.. Cable shelf NSM A port e0a to controller A slot 8 port a (e8a).
.. Cable shelf NSM A port e0b to controller B slot 9 port b (e9b).
.. Cable shelf NSM B port e0a to controller B slot 8 port a (e8a).
.. Cable shelf NSM B port e0b to controller A slot 9 port b (e9b).
+
The following illustration highlights the cabling for the fourth shelf in the HA pair with four RoCE-capable I/O modules in each controller:
+
image::../media/drw_ns224_vino_m_4shelves_4cards_ieops-1645.svg[Cabling for ASA A1K with four shelves and four IO modules, width=452px]

. Verify that the hot-added shelf is cabled correctly using https://mysupport.netapp.com/site/tools/tool-eula/activeiq-configadvisor[Active IQ Config Advisor^].
+
If any cabling errors are generated, follow the corrective actions provided.

.What's next?
If you disabled automatic drive assignment as part of the preparation for this procedure, you need to manually assign drive ownership and then reenable automatic drive assignment, if needed. Go to link:complete-hot-add-shelf.html[Complete the hot-add].

Otherwise, you are done with the hot-add shelf procedure.

====

.Cable shelf to ASA A70 or ASA A90
[%collapsible]


====

You can hot-add up to two NS224 shelves to an ASA A70 or ASA A90 HA pair when additional storage (to the internal shelf) is needed.

.Before you begin

* You must have reviewed the link:requirements-hot-add-shelf.html[hot-add requirements and best practices]. 

* You must have completed the applicable procedures in link:prepare-hot-add-shelf.html[Prepare-to hot-add a shelf]. 

* You must have installed the shelves, powered them on, and set the shelf IDs as described in link:prepare-hot-add-shelf.html[Install a shelf for a hot-add].


.About this task

* This procedure assumes that your HA pair has only internal storage (no external shelves) and that you are hot-adding up to two additional shelves and two RoCE-capable I/O modules in each controller.

* This procedure addresses the following hot-add scenarios:
** Hot-adding the first shelf to an HA pair with one RoCE-capable I/O module in each controller.
** Hot-adding the first shelf to an HA pair with two RoCE-capable I/O modules in each controller.
** Hot- adding the second shelf to an HA pair with two RoCE-capable I/O modules in each controller.

.Steps

. If you are hot-adding one shelf using one set of RoCE-capable ports (one RoCE-capable I/O module) in each controller module, and this is the only NS224 shelf in your HA pair, complete the following substeps.
+
Otherwise, go to the next step.
+
NOTE: This step assumes you installed the RoCE-capable I/O module in slot 11.
+
.. Cable shelf NSM A port e0a to controller A slot 11 port a (e11a).
.. Cable shelf NSM A port e0b to controller B slot 11 port b (e11b).
.. Cable shelf NSM B port e0a to controller B slot 11 port a (e11a).
.. Cable shelf NSM B port e0b to controller A slot 11 port b (e11b).
+
The following illustration shows cabling for one hot-added shelf using one RoCE-capable I/O module in each controller module: 
+
image::../media/drw_ns224_vino_i_1shelf_1card_ieops-1639.svg[Cabling for ASA A70 or A90 with one shelf and one IO module, width=452px]

. If you are hot-adding one or two shelves using two sets of RoCE-capable ports (two RoCE-capable I/O modules) in each controller module, complete the applicable substeps.
+
NOTE: This step assumes you installed the RoCE-capable I/O modules in slots 11 and 8.
+
[options="header" cols="1,3"]]
|===
| Shelves| Cabling
a|
Shelf 1
a|
.. Cable NSM A port e0a to controller A slot 11 port a (e11a).
.. Cable NSM A port e0b to controller B slot 8 port b (e8b).
.. Cable NSM B port e0a to controller B slot 11 port a (e11a).
.. Cable NSM B port e0b to controller A slot 8 port b (e8b).
.. If you are hot-adding a second shelf, complete the "`Shelf 2`" substeps; otherwise, go to step 3.

The following illustration shows cabling for one hot-added shelf
using two RoCE-capable I/O modules in each controller module: 

image::../media/drw_ns224_vino_i_1shelf_2cards_ieops-1640.svg[Cabling for ASA A70 or A90 with one shelf and two IO modules, width=452px]

a|
Shelf 2
a|
.. Cable NSM A port e0a to controller A slot 8 port a (e8a).
.. Cable NSM A port e0b to controller B slot 11 port b (e11b).
.. Cable NSM B port e0a to controller B slot 8 port a (e8a).
.. Cable NSM B port e0b to controller A slot 11 port b (e11b).
.. Go to step 3.

The following illustration shows cabling for two hot-added shelf 
using two RoCE-capable I/O modules in each controller module: 

image::../media/drw_ns224_vino_i_2shelves_2cards_ieops-1641.svg[Cabling for ASA A70 or A90 with two shelves and two IO modules, width=452px]

|===

. Verify that the hot-added shelf is cabled correctly using https://mysupport.netapp.com/site/tools/tool-eula/activeiq-configadvisor[Active IQ Config Advisor^].
+
If any cabling errors are generated, follow the corrective actions provided.

.What's next?
If you disabled automatic drive assignment as part of the preparation for this procedure, you need to manually assign drive ownership and then reenable automatic drive assignment, if needed. Go to link:complete-hot-add-shelf.html[Complete the hot-add].

Otherwise, you are done with the hot-add shelf procedure.


====


.Cable shelf to ASA A250 or ASA C250
[%collapsible]


====

include::../_include/cable-a250-c250-hot-add-shelf.adoc[]

====

.Cable shelf to ASA A400 or ASA C400
[%collapsible]

====

include::../_include/cable-a400-c400-hot-add-shelf.adoc[]

====

.Cable shelf to ASA A800 or ASA C800
[%collapsible]

====

include::../_include/cable-a800-c800-hot-add-shelf.adoc[]

====


.Cable shelf to ASA A900
[%collapsible]

====

include::../_include/cable-a900-hot-add-shelf.adoc[]

====