---
permalink: ns224/cable-asa-systems-hot-add-shelf.html
sidebar: sidebar
keywords: ns224, shelves, shelf, ns224 shelves, hot-add, ha, pair, cable, hot-add an ns224 drive shelf
summary: You cable each NS224 shelf you are hot-adding so that each shelf has two connections to each controller in the HA pair.
---
= Cable shelf to ASA systems - NS224 shelves
:icons: font
:imagesdir: ../media/

[.lead]
You cable each NS224 shelf you are hot-adding so that each shelf has two connections to each controller in the HA pair.

.About this task

Your hardware system may be compatible with both NS224 shelves with NSM100 modules and NS224 shelves with NSM100B modules. To check the compatibility and port names for your hardware and shelves, consult the https://hwu.netapp.com[NetApp Hardware Universe].

.Cable shelf to ASA A1K
[%collapsible]


====

You can hot-add up to three additional NS224 shelves (for a total of four shelves) to an ASA A1K HA pair.

include::../_include/cable-a1k-hot-add-shelf.adoc[]

====

.Cable shelf to ASA A20
[%collapsible]


====

You can hot-add a maximum of one NS224 shelf to an ASA A20 HA pair when additional storage (to the internal shelf) is needed.

include::../_include/cable-20-hot-add-shelf.adoc[]

====


.Cable shelf to ASA A30 or ASA A50
[%collapsible]


====

You can hot-add up to two NS224 shelves to an ASA A30, ASA C30, ASA A50, or ASA C60 HA pair when additional storage (to the internal shelf) is needed.

include::../_include/cable-30-50-60-hot-add-shelf.adoc[]

====


.Cable shelf to ASA A70 or ASA A90
[%collapsible]


====

You can hot-add up to two NS224 shelves to an ASA A70 or ASA A90 HA pair when additional storage (to the internal shelf) is needed.

include::../_include/cable-70-90-hot-add-shelf.adoc[]

====


.Cable shelf to ASA A250 or ASA C250
[%collapsible]


====

When additional storage is needed, you can hot-add a maximum of one NS224 shelf to an ASA A250 or ASA C250 HA pair.

include::../_include/cable-a250-c250-hot-add-shelf.adoc[]

====

.Cable shelf to ASA A400 or ASA C400
[%collapsible]

====

How you cable an NS224 shelf for a hot-add depends on whether you have an ASA A400 or ASA C400 HA pair.


include::../_include/cable-a400-c400-hot-add-shelf.adoc[]

====

.Cable shelf to ASA A800 or ASA C800
[%collapsible]

====

How you cable an NS224 shelf in an ASA A800 or ASA C800 HA pair depends on the number of shelves you are hot-adding and the number of RoCE-capable port sets (one or two) you are using on the controllers.

include::../_include/cable-a800-c800-hot-add-shelf.adoc[]

====


.Cable shelf to ASA A900
[%collapsible]

====

include::../_include/cable-a900-hot-add-shelf.adoc[]

====