---
permalink: ns224/cable-a1k-hot-add-shelf.html
sidebar: sidebar
keywords: ns224, shelves, shelf, ns224 shelves, hot-add, ha, pair, cable, hot-add an ns224 drive shelf
summary: You cable each NS224 shelf you are hot-adding so that each shelf has two connections to each controller in the HA pair.
---
= Cable a shelf to the AFF A1K HA pair - NS224 shelves
:icons: font
:imagesdir: ../media/

[.lead]
You cable each NS224 shelf you are hot-adding so that each shelf has two connections to each controller in the HA pair.

You can hot-add up to three additional NS224 shelves (for a total of four shelves) to an AFF A1K HA pair.

.Before you begin

* You must have reviewed the link:requirements-hot-add-shelf.html[hot-add requirements and best practices]. 

* You must have completed the applicable procedures in link:prepare-hot-add-shelf.html[Prepare-to hot-add a shelf]. 

* You must have installed the shelves, powered them on, and set the shelf IDs as described in link:prepare-hot-add-shelf.html[Install a shelf for a hot-add].


.About this task

* This procedure assumes that your HA pair has at least one existing NS224 shelf. 
* This procedure addresses the following hot-add scenarios:
** Hot-adding a second shelf to an HA pair with two RoCE-capable I/O modules in each controller. (You have installed a second I/O module and recabled the first shelf to both I/O modules or already had the first shelf cabled to two I/O modules. You will cable the second shelf to both I/O modules).
** Hot-adding a third shelf to an HA pair with three RoCE-capable I/O modules in each controller. (You have installed a third I/O module and will cable the third shelf to only the third I/O module).
** Hot-adding a third shelf to an HA pair with four RoCE-capable I/O modules in each controller. (You have installed a third and fourth I/O module and will cable the third shelf to the third and fourth I/O modules).
** Hot-adding a fourth shelf to an HA pair with four RoCE-capable I/O modules in each controller. (You have installed a fourth I/O module and recabled the third shelf to the third and fourth I/O modules or already had the third shelf cabled to the third and fourth I/O modules. You will cable the fourth shelf to both the third and fourth I/O module).

.Steps

. If the NS224 shelf you are hot-adding will be the second NS224 shelf in the HA pair, complete the following substeps. 
+
Otherwise, go to the next step.
+
.. Cable shelf NSM A port e0a to controller A slot 10 port a (e10a).
.. Cable shelf NSM A port e0b to controller B slot 11 port b (e11b).
.. Cable shelf NSM B port e0a to controller B slot 10 port a (e10a).
.. Cable shelf NSM B port e0b to controller A slot 11 port b (e11b).
+
The following illustration highlights the cabling for the second shelf in the HA pair with two RoCE-capable I/O modules in each controller:
+
image::../media/drw_ns224_vino_m_2shelves_2cards_ieops-1642.svg[Cabling for AFF A1K with two shelves and two IO modules, width=452px]
+
. If the NS224 shelf you are hot-adding will be the third NS224 shelf in the HA pair with three RoCE-capable I/O modules in each controller, complete the following substeps. 
Otherwise, go to the next step.
.. Cable shelf NSM A port e0a to controller A slot 9 port a (e9a).
.. Cable shelf NSM A port e0b to controller B slot 9 port b (e9b).
.. Cable shelf NSM B port e0a to controller B slot 9 port a (e9a).
.. Cable shelf NSM B port e0b to controller A slot 9 port b (e9b).
+
The following illustration highlights the cabling for the third shelf in the HA pair with three RoCE-capable I/O modules in each controller:
+
image::../media/drw_ns224_vino_m_3shelves_3cards_ieops-1643.svg[Cabling for AFF A1K with three shelves and three IO modules, width=452px]

. If the NS224 shelf you are hot-adding will be the third NS224 shelf in the HA pair with four RoCE-capable I/O modules in each controller, complete the following substeps. 
Otherwise, go to the next step.
.. Cable shelf NSM A port e0a to controller A slot 9 port a (e9a).
.. Cable shelf NSM A port e0b to controller B slot 8 port b (e8b).
.. Cable shelf NSM B port e0a to controller B slot 9 port a (e9a).
.. Cable shelf NSM B port e0b to controller A slot 8 port b (e8b).
+
The following illustration highlights the cabling for the third shelf in the HA pair with four RoCE-capable I/O modules in each controller:
+
image::../media/drw_ns224_vino_m_3shelves_4cards_ieops-1644.svg[Cabling for AFF A1K with three shelves and four IO modules, width=452px]

. If the NS224 shelf you are hot-adding will be the fourth NS224 shelf in the HA pair with four RoCE-capable I/O modules in each controller, complete the following substeps. 

.. Cable shelf NSM A port e0a to controller A slot 8 port a (e8a).
.. Cable shelf NSM A port e0b to controller B slot 9 port b (e9b).
.. Cable shelf NSM B port e0a to controller B slot 8 port a (e8a).
.. Cable shelf NSM B port e0b to controller A slot 9 port b (e9b).
+
The following illustration highlights the cabling for the fourth shelf in the HA pair with four RoCE-capable I/O modules in each controller:
+
image::../media/drw_ns224_vino_m_4shelves_4cards_ieops-1645.svg[Cabling for AFF A1K with four shelves and four IO modules, width=452px]

. Verify that the hot-added shelf is cabled correctly using https://mysupport.netapp.com/site/tools/tool-eula/activeiq-configadvisor[Active IQ Config Advisor^].
+
If any cabling errors are generated, follow the corrective actions provided.

. If you disabled automatic drive assignment as part of the preparation for this procedure, you need to manually assign drive ownership and then reenable automatic drive assignment, if needed.
+
Otherwise, you are done with this procedure.