---
permalink: ns224/hot-add-eoa-cable-overview.html
sidebar: sidebar
keywords: ns224, shelves, shelf, ns224 shelves, hot-add, ha, pair, eoa systems, end-of-availability, cable
summary: Cable your NS224 shelf to your end-of-availability system so that each shelf has two connections to each controller in the HA pair.
---
= Cable shelf for hot-add - End-of-availability systems overview
:icons: font
:imagesdir: ../media/

[.lead]
Cable each NS224 shelf you are hot-adding so that each shelf has two connections to each controller in the HA pair.

.About this task

Your hardware system may be compatible with both NS224 shelves with NSM100 modules and NS224 shelves with NSM100B modules. To check the compatibility and port names for your hardware and shelves, consult the https://hwu.netapp.com[NetApp Hardware Universe^].

.End-of-availability platform cabling procedures

Select your end-of-availability platform to view platform-specific cabling instructions:

* link:hot-add-eoa-cable-a320.html[Cable shelf - AFF A320]
* link:hot-add-eoa-cable-a700.html[Cable shelf - AFF A700]
* link:hot-add-eoa-cable-fas500f.html[Cable shelf - FAS500f]

.What's next

After cabling your shelf, link:hot-add-eoa-complete.html[complete the hot-add procedure].
