---
permalink: ns224/prepare-hot-add-shelf-install-roce.html
sidebar: sidebar
keywords: ns224, shelves, shelf, ns224 shelves, hot-add, ha, pair, preparation, roce, pcie, io modules
summary: Install additional RoCE-capable PCIe cards or I/O modules when your HA pair needs more available RoCE-capable Ethernet ports for hot-adding an NS224 shelf.
---
= Install RoCE-capable PCIe cards or I/O modules for a hot-add - NS224 shelves
:icons: font
:imagesdir: ../media/

[.lead]
Install additional RoCE-capable PCIe cards or I/O modules when your HA pair needs more available RoCE-capable Ethernet ports for hot-adding an NS224 shelf.

If your platform model supports the use of RoCE-capable PCIe cards or I/O modules, your HA pair must have enough available RoCE-capable Ethernet ports to support the number of shelves you are hot-adding.

.Steps
. For each shelf you are hot-adding, verify that there are two RoCE-capable ports on each controller.
+
These ports can be on board the controllers, on RoCE-capable PCIe cards, a combination of both, or on RoCE-capable I/O modules, as supported by your platform model.
+
. If your HA pair does not have enough available RoCE-capable ports, install the additional PCIe cards or I/O modules into the correct controller slots, as supported by your platform model.
+
.. Identify the correct controller slots for your platform model. See https://hwu.netapp.com[NetApp Hardware Universe^].
+
.. See your platform model's documentation for PCIe card or I/O module installation instructions.

.What's next

After installing any required RoCE-capable PCIe cards or I/O modules, link:prepare-hot-add-shelf-configure-roce-ports.html[configure RoCE-capable ports for storage use].
