---
permalink: ns224/prepare-hot-add-shelf.html
sidebar: sidebar
keywords: ns224, shelves, shelf, ns224 shelves, hot-add, ha, pair, requirement, preparation, applicable, complete, drive, hot-add an ns224 drive shelf
summary: You can hot-add an NS224 drive shelf after your HA pair meets certain requirements, and after the preparation tasks applicable to your HA pair are completed.
---
= Prepare for a hot-add - NS224 shelves
:icons: font
:imagesdir: ../media/

[.lead]
Complete the preparation tasks applicable to your HA pair before hot-adding an NS224 shelf.

== Install RoCE-capable PCIe cards or I/O modules
If your platform model supports the use of RoCE-capable PCIe cards or I/O modules, your HA pair must have enough available RoCE-capable Ethernet ports to support the number of shelves you are hot-adding. 

.Before you begin
Make sure you identify the correct controller slots for your platform model. See https://hwu.netapp.com[NetApp Hardware Universe^]. 

.Steps
. For each shelf you are hot-adding, verify that there are two RoCE-capable ports on each controller. 
+
These ports can be on board the controllers, on RoCE-capable PCIe cards, a combination of both, or on RoCE-capable I/O modules, as supported by your platform model.
+
. If your HA pair does not have enough available RoCE-capable ports, install the additional PCIe cards or I/O modules into the correct controller slots, as supported by your platform model.  
+
See your platform model's documentation for PCIe card or I/O module installation instructions.

== Configure ports for storage use

If your HA pair has non-dedicated RoCE-capable Ethernet ports that you are using to hot-add an NS224 shelf, you must configure the ports for storage use (not networking use).

.Before you begin
* Make sure you have reviewed the link:requirements-hot-add-shelf.html[hot-add requirements]. 

* Make sure you installed any additional RoCE-capable PCIe cards or I/O modules in each controller.

.About this task

* For some platform models, when a RoCE-capable PCIe card or I/O module is installed in a supported slot on a controller, the ports automatically default to storage use (instead of networking); however, it is recommended that you complete the following procedure to verify the RoCE-capable ports are configured for storage use.

* If you determine that the non-dedicated RoCE-capable ports in your HA pair are not configured for storage use, it is a nondisruptive procedure to configure them. 
+
Depending on the version of ONTAP your HA pair is running you may need to reboot the controllers:
+
 ** If your HA pair is running a version of ONTAP 9.6, you need to reboot the controllers, one at a time.
+
** If your HA pair is running ONTAP 9.7 or later, you do not need to reboot the controllers, unless one or both controllers are in maintenance mode. This procedure assumes that neither controller is in maintenance mode.
+
** To change ports from storage use to networking use, enter the command, `storage port modify -node _node_name_ -port _port_name_ -mode network`.

.Steps

. Log in to the cluster using SSH or the serial console port.
. Enter the following command to verify if the non-dedicated ports in the HA pair are configured for storage use:
+
`storage port show`
+
* If your HA pair is running ONTAP 9.8 or later, the non-dedicated ports display `storage` in the `Mode` column.
+
* If your HA pair is running ONTAP 9.7 or 9.6, the non-dedicated ports, which display `false` in the `Is Dedicated?` column, also display `enabled` in the `State` column.
+
[NOTE]
====
When non-dedicated ports are not configured for storage use, the command output displays the following:

* If your HA pair is running ONTAP 9.8 or later, the non-dedicated ports display `network` in the `Mode` column.

* If your HA pair is running ONTAP 9.7 or 9.6, the non-dedicated ports, which display `false` in the `Is Dedicated?`` column, also display `disabled` in the `State` column.
====

. If the non-dedicated ports are configured for storage use, you are done with this procedure.
+
Otherwise, you need to configure the ports by completing steps 4 through 7.
+
. Configure the non-dedicated ports for storage use, on one of the controller modules:
+
You must repeat the applicable command for each port you are configuring.
+
[options="header" cols="1,3"]
|===
| If your HA pair is running...| Use this command...
a|
ONTAP 9.8 or later
a|
`storage port modify -node _node_name_ -port _port_name_ -mode storage`
a|
ONTAP 9.7 or 9.6
a|
`storage port enable -node _node_name_ -port _port_name_`
|===

. If your HA pair is running ONTAP 9.6, reboot the controller module so that the port changes take effect: `system node reboot -node _node_name_ -reason _reason_for_the_reboot_`.
+
Otherwise, go to the next step.
+
NOTE: The reboot can take up to 15 minutes.

. Repeat the steps for the second controller module:
+
[options="header" cols="1,3"]
|===
| If your HA pair is running...| Then...
a|
ONTAP 9.7 or later
a|

 .. Repeat step 4.
 .. Go to step 7.

a|
ONTAP 9.6
a|

 .. Repeat steps 4 and 5.
+
NOTE: The first controller must have already completed its reboot.

 .. Go to step 7.

+
|===

. Verify that the non-dedicated ports on both controller modules are configured for storage use: `storage port show`
+
You can enter the command on either controller module.
+
If your HA pair is running ONTAP 9.8 or later, the non-dedicated ports display `storage` in the `Mode` column.
+
If your HA pair is running ONTAP 9.7 or 9.6, the non-dedicated ports, which display `false` in the `Is Dedicated?` column, also display `enabled` in the `State` column.

== Recable port connections

Before hot-adding additional shelves, depending on your platform model, you might need to recable an existing shelf (after you have installed the additional RoCE-capable PCIe cards or I/O modules) across two sets of ports in different slots for resiliency against slot failure.

.Before you begin

* Make sure you have reviewed the link:requirements-hot-add-shelf.html[hot-add requirements]. 

* Make sure you installed any additional RoCE-capable PCIe cards or I/O modules in each controller.

* Make sure that the non-dedicated ports on the RoCE-capable PCIe cards or I/O modules you installed are configured for storage use.

.About this task

* Recabling port connections is a nondisruptive procedure when your shelf has multipath-HA connectivity.

* You move one cable at a time to always maintain connectivity to the shelf during this procedure.
+
NOTE: Moving a cable does not require any wait time between unplugging the cable from one port and plugging it into another port.

* If needed, refer to the cabling illustrations in [Cable ], which shows an existing single shelf and the recabled shelf, in a two-shelf configuration.


.Steps

. Recable the existing shelf's connections across two sets of RoCE-capable ports in different slots, as applicable to your platform model.
+
// start tabbed area

[role="tabbed-block"]
====

.AFF A1K
--
The substeps assume the existing shelf is cabled to a RoCE-capable I/O 
module in either slot 11 (two shelf configuration) or slot 9 (four shelf configuration) on each controller.

NOTE: If you have an AFF A1K HA pair and you are hot-adding a third shelf and installing a third or fourth RoCE-capable I/O module in each controller, the third shelf is cabled to only the third or fourth I/O modules. You do not need to recable any existing shelves. 

Do one of the following:

* If hot-adding a second shelf, recable the first shelf across both RoCE-capable I/O modules:

.. On controller A, move the cable from slot 11 port b (e11b) to
slot 10 port b (e10b).
.. Repeat the same cable move on controller B.

* If hot-adding a fourth shelf, recable the third shelf across the R0CE-capable I/O modules in slot 9 on each controller:

.. On controller A, move the cable from slot 9 port b (e9b) to
slot 8 port b (e8b).
.. Repeat the same cable move on controller B.


--


.AFF A70 or AFF A90
--
The substeps assume the existing shelf is cabled to a RoCE-capable I/O 
module in slot 11 on each controller.

If you are hot-adding a second shelf, recable the first shelf across both RoCE-capable I/O modules:

.. On controller A, move the cable from slot 11 port b (e11b) to
slot 8 port b (e8b).
.. Repeat the same cable move on controller B.

--

.AFF A800 or AFF C800
--
The substeps assume the existing shelf is cabled to RoCE-capable PCIe cards in slot 5 on each controller.

If you are hot-adding a second shelf, recable the first shelf across both sets of RoCE-capable ports on each controller:

.. On controller A, move the cable from slot 5 port b (e5b) to slot 3 port b (e3b).
.. Repeat the same cable move on controller B.

--

.AFF A700
--
The substeps assume the existing shelf is cabled to RoCE-capable I/O modules in slot 3 on each controller.

If you are hot-adding a second shelf, recable the first shelf across both sets of RoCE-capable ports on each controller:

.. On controller A, move the cable from slot 3 port b (e3b) to slot 7 port b (e7b).
.. Repeat the same cable move on controller B.

--

.AFF A400 or AFF C400
--
If you are hot-adding a second shelf, recable the first shelf across both sets of RoCE-capable ports on each controller.

Depending on your platform model, do one of the following:

* On the AFF A400:
+
.. On controller A, move the cable from port e0d to slot 5 Port b (e5b).
.. Repeat the same cable move on controller B.

* On the AFF C400:
+
.. On controller A, move the cable from slot 4 port a (e4a) to slot 5 port b (e5b).
.. Repeat the same cable move on controller B.

--

====
// end tabbed area
+

. Verify that the recabled shelf is cabled correctly using https://mysupport.netapp.com/site/tools/tool-eula/activeiq-configadvisor[Active IQ Config Advisor^].
+
If any cabling errors are generated, follow the corrective actions provided.

== Disable automatic drive assignment

If you are manually assigning drive ownership for the NS224 drive shelf you are hot-adding, then you need to disable automatic drive assignment if it is enabled.

If you are unsure whether you should manually assign drive ownership, or want to understand the automatic assignment of drive ownership policies for your storage system, see https://docs.netapp.com/us-en/ontap/disks-aggregates/disk-autoassignment-policy-concept.html[About automatic assignment of disk ownership^].

.Before you begin

Make sure you have reviewed the link:requirements-hot-add-shelf.html[hot-add requirements]. 

.Steps

. Verify whether automatic drive assignment is enabled: `storage disk option show`
+
You can enter the command on either node.
+
If automatic drive assignment is enabled, the output shows `on` in the `Auto Assign` column (for each node).

. If automatic drive assignment is enabled, disable it: `storage disk option modify -node _node_name_ -autoassign off`
+
You must disable automatic drive assignment on both nodes.

.What's next?
Go to link:prepare-hot-add-shelf.html[Install a shelf for a hot-add].

