---
permalink: ns224/prepare-hot-add-shelf-recable-shelves.html
sidebar: sidebar
keywords: ns224, shelves, shelf, ns224 shelves, hot-add, ha, pair, preparation, recable
summary: Recable existing shelves across two sets of ports in different slots when required by your platform model before hot-adding additional NS224 shelves.
---
= Recable existing shelves for a hot-add - NS224 shelves
:icons: font
:imagesdir: ../media/

[.lead]
Recable existing shelves across two sets of ports in different slots when required by your platform model before hot-adding additional NS224 shelves.

Before hot-adding additional shelves, depending on your platform model, you might need to recable an existing shelf after you have installed the additional RoCE-capable PCIe cards or I/O modules.

.Before you begin

* Make sure you installed any additional RoCE-capable PCIe cards or I/O modules in each controller.

* Make sure that the non-dedicated ports on the RoCE-capable PCIe cards or I/O modules you installed are configured for storage use.

.About this task

* Recabling port connections is a nondisruptive procedure when your shelf has multipath-HA connectivity.

* You move one cable at a time to always maintain connectivity to the shelf during this procedure.
+
NOTE: Moving a cable does not require any wait time between unplugging the cable from one port and plugging it into another port.

* If needed, refer to the shelf cabling illustrations for your platform model in link:cable-overview-hot-add-shelf.html[Overview of cabling for a hot-add].

.Steps

. Recable the existing shelf's connections across two sets of RoCE-capable ports in different slots, as applicable to your platform model.

* For AFF systems:
+
[role="tabbed-block"]
====

.AFF A1K
--
Do one of the following if you are hot-adding a second shelf or a fourth shelf.

NOTE: If you have an AFF A1K HA pair and you are hot-adding a third shelf and installing a third or fourth RoCE-capable I/O module in each controller, the third shelf is cabled to only the third or third and fourth I/O modules. You do not need to recable any existing shelves.

* If you are hot-adding a second shelf, recable the first shelf across the RoCE-capable I/O modules in slot 11 and slot 10 on each controller.
+
The substeps assume the existing shelf is cabled to a RoCE-capable I/O
module in slot 11 on each controller.
+
.. On controller A, move the cable from slot 11 port b (e11b) to
slot 10 port b (e10b).
.. Repeat the same cable move on controller B.

* If you are hot-adding a fourth shelf, recable the third shelf across the RoCE-capable I/O modules in slot 9 and slot 8 on each controller.
+
The substeps assume the third shelf is cabled to a RoCE-capable I/O
module in slot 9 on each controller.
+
.. On controller A, move the cable from slot 9 port b (e9b) to
slot 8 port b (e8b).
.. Repeat the same cable move on controller B.

--

.AFF A70, AFF A90, or AFF C80
--
If you are hot-adding a second shelf, recable the first shelf across the RoCE-capable I/O modules in slot 11 and slot 8 on each controller.

The substeps assume the existing shelf is cabled to a RoCE-capable I/O
module in slot 11 on each controller.

.. On controller A, move the cable from slot 11 port b (e11b) to
slot 8 port b (e8b).
.. Repeat the same cable move on controller B.
--

.AFF A800 or AFF C800
--
If you are hot-adding a second shelf, recable the first shelf across the two sets of RoCE-capable ports in slot 5 and slot 3 on each controller.

The substeps assume the existing shelf is cabled to RoCE-capable PCIe cards in slot 5 on each controller.

.. On controller A, move the cable from slot 5 port b (e5b) to slot 3 port b (e3b).
.. Repeat the same cable move on controller B.
--

.AFF A700
--
If you are hot-adding a second shelf, recable the first shelf across the two sets of RoCE-capable ports in slot 3 and slot 7 on each controller.

The substeps assume the existing shelf is cabled to RoCE-capable I/O modules in slot 3 on each controller.

.. On controller A, move the cable from slot 3 port b (e3b) to slot 7 port b (e7b).
.. Repeat the same cable move on controller B.
--

.AFF A400 or AFF C400
--
If you are hot-adding a second shelf, depending on your platform model, do one of the following:

* On the AFF A400:
+
Recable the first shelf across the two sets of RoCE-capable ports, onboard e0c/e0d and in slot 5, on each controller.
+
The substeps assume the existing shelf is cabled to RoCE-capable onboard ports e0c/e0d on each controller.
+
.. On controller A, move the cable from port e0d to slot 5 Port b (e5b).
.. Repeat the same cable move on controller B.

* On the AFF C400:
+
Recable the first shelf across the two sets of RoCE-capable ports in slot 4 and slot 5, on each controller.
+
The substeps assume the existing shelf is cabled to RoCE-capable ports in slot 4 on each controller.
+
.. On controller A, move the cable from slot 4 port a (e4a) to slot 5 port b (e5b).
.. Repeat the same cable move on controller B.
--

.AFF A900
--
Do one of the following if you are hot-adding a second shelf or a fourth shelf.

* If you are hot-adding a second shelf, recable the first shelf across the RoCE-capable I/O modules in slot 2 and slot 10 on each controller.
+
The substeps assume the existing shelf is cabled to a RoCE-capable I/O
module in slot 2 on each controller.
+
.. On controller A, move the cable from slot 2 port b (e2b) to
slot 10 port b (e10b).
.. Repeat the same cable move on controller B.

* If you are hot-adding a fourth shelf, recable the third shelf across the RoCE-capable I/O modules in slot 1 and slot 11 on each controller.
+
The substeps assume the third shelf is cabled to a RoCE-capable I/O
module in slot 1 on each controller.
+
.. On controller A, move the cable from slot 1 port b (e1b) to
slot 11 port b (e11b).
.. Repeat the same cable move on controller B.
--

.AFF A30, AFF C30, AFF A50, or AFF C60
--
If you are hot-adding a second shelf, recable the first shelf across the RoCE-capable I/O modules in slot 3 and slot 1 on each controller.

The substeps assume the existing shelf is cabled to a RoCE-capable I/O
module in slot 3 on each controller.

.. On controller A, move the cable from slot 3 port b (e3b) to
slot 1 port b (e1b).
.. Repeat the same cable move on controller B.
--
====

* For ASA systems:
+
[role="tabbed-block"]
====

.ASA A1K
--
Do one of the following if you are hot-adding a second shelf or a fourth shelf.

NOTE: If you have an ASA A1K HA pair and you are hot-adding a third shelf and installing a third or fourth RoCE-capable I/O module in each controller, the third shelf is cabled to only the third or third and fourth I/O modules. You do not need to recable any existing shelves.

* If you are hot-adding a second shelf, recable the first shelf across the RoCE-capable I/O modules in slot 11 and slot 10 on each controller.
+
The substeps assume the existing shelf is cabled to a RoCE-capable I/O
module in slot 11 on each controller.
+
.. On controller A, move the cable from slot 11 port b (e11b) to
slot 10 port b (e10b).
.. Repeat the same cable move on controller B.

* If you are hot-adding a fourth shelf, recable the third shelf across the RoCE-capable I/O modules in slot 9 and slot 8 on each controller.
+
The substeps assume the third shelf is cabled to a RoCE-capable I/O
module in slot 9 on each controller.
+
.. On controller A, move the cable from slot 9 port b (e9b) to
slot 8 port b (e8b).
.. Repeat the same cable move on controller B.
--

.ASA A70 or ASA A90
--
If you are hot-adding a second shelf, recable the first shelf across the RoCE-capable I/O modules in slot 11 and slot 8 on each controller.

The substeps assume the existing shelf is cabled to a RoCE-capable I/O
module in slot 11 on each controller.

.. On controller A, move the cable from slot 11 port b (e11b) to
slot 8 port b (e8b).
.. Repeat the same cable move on controller B.
--

.ASA A800 or ASA C800
--
If you are hot-adding a second shelf, recable the first shelf across the two sets of RoCE-capable ports in slot 5 and slot 3 on each controller.

The substeps assume the existing shelf is cabled to RoCE-capable PCIe cards in slot 5 on each controller.

.. On controller A, move the cable from slot 5 port b (e5b) to slot 3 port b (e3b).
.. Repeat the same cable move on controller B.
--

.ASA A400 or ASA C400
--
If you are hot-adding a second shelf, depending on your platform model, do one of the following:

* On the ASA A400:
+
Recable the first shelf across the two sets of RoCE-capable ports, onboard e0c/e0d and in slot 5, on each controller.
+
The substeps assume the existing shelf is cabled to RoCE-capable onboard ports e0c/e0d on each controller.
+
.. On controller A, move the cable from port e0d to slot 5 Port b (e5b).
.. Repeat the same cable move on controller B.

* On the ASA C400:
+
Recable the first shelf across the two sets of RoCE-capable ports in slot 4 and slot 5, on each controller.
+
The substeps assume the existing shelf is cabled to RoCE-capable ports in slot 4 on each controller.
+
.. On controller A, move the cable from slot 4 port a (e4a) to slot 5 port b (e5b).
.. Repeat the same cable move on controller B.
--

.ASA A900
--
Do one of the following if you are hot-adding a second shelf or a fourth shelf.

* If you are hot-adding a second shelf, recable the first shelf across the RoCE-capable I/O modules in slot 2 and slot 10 on each controller.
+
The substeps assume the existing shelf is cabled to a RoCE-capable I/O
module in slot 2 on each controller.
+
.. On controller A, move the cable from slot 2 port b (e2b) to
slot 10 port b (e10b).
.. Repeat the same cable move on controller B.

* If you are hot-adding a fourth shelf, recable the third shelf across the RoCE-capable I/O modules in slot 1 and slot 11 on each controller.
+
The substeps assume the third shelf is cabled to a RoCE-capable I/O
module in slot 1 on each controller.
+
.. On controller A, move the cable from slot 1 port b (e1b) to
slot 11 port b (e11b).
.. Repeat the same cable move on controller B.
--

.ASA A30 or ASA A50
--
If you are hot-adding a second shelf, recable the first shelf across the RoCE-capable I/O modules in slot 3 and slot 1 on each controller.

The substeps assume the existing shelf is cabled to a RoCE-capable I/O
module in slot 3 on each controller.

.. On controller A, move the cable from slot 3 port b (e3b) to
slot 1 port b (e1b).
.. Repeat the same cable move on controller B.
--
====

[start=2]
. Verify that the recabled shelf is cabled correctly using https://mysupport.netapp.com/site/tools/tool-eula/activeiq-configadvisor[Active IQ Config Advisor^].
+
If any cabling errors are generated, follow the corrective actions provided.

.What's next

If you need to manually assign drive ownership, link:prepare-hot-add-shelf-disable-auto-drive-assign.html[disable automatic drive assignment and complete the preparation tasks].
