---
permalink: ns224/prepare-hot-add-shelf.html
sidebar: sidebar
keywords: ns224, shelves, shelf, ns224 shelves, hot-add, ha, pair, requirement, preparation, applicable, complete, drive, hot-add an ns224 drive shelf
summary: Complete the preparation tasks required before hot-adding an NS224 shelf.
---
= Prepare for a hot-add - NS224 shelves
:icons: font
:imagesdir: ../media/

[.lead]
Complete the preparation tasks applicable to your HA pair before hot-adding an NS224 shelf.

When you are done with the applicable preparation tasks, go to link:prepare-hot-add-shelf.html[Install a shelf for a hot-add].

== Install RoCE-capable PCIe cards or I/O modules
If your platform model supports the use of RoCE-capable PCIe cards or I/O modules, your HA pair must have enough available RoCE-capable Ethernet ports to support the number of shelves you are hot-adding. 

.Steps
. For each shelf you are hot-adding, verify that there are two RoCE-capable ports on each controller. 
+
These ports can be on board the controllers, on RoCE-capable PCIe cards, a combination of both, or on RoCE-capable I/O modules, as supported by your platform model.
+
. If your HA pair does not have enough available RoCE-capable ports, install the additional PCIe cards or I/O modules into the correct controller slots, as supported by your platform model. 
+ 
.. Identify the correct controller slots for your platform model. See https://hwu.netapp.com[NetApp Hardware Universe^]. 
+
.. See your platform model's documentation for PCIe card or I/O module installation instructions.

== Configure RoCE-capable ports for storage use

If your HA pair has non-dedicated RoCE-capable Ethernet ports that you are using to hot-add an NS224 shelf, you must configure the ports for storage use (not networking use).
To prepare for a hot-add, complete these tasks in order:
.Before you begin
* link:prepare-hot-add-shelf-install-roce.html[Install RoCE-capable PCIe cards or I/O modules]
* link:prepare-hot-add-shelf-configure-roce-ports.html[Configure RoCE-capable ports for storage use]
* link:prepare-hot-add-shelf-recable-shelves.html[Recable existing shelves]
* link:prepare-hot-add-shelf-disable-auto-drive-assign.html[Disable automatic drive assignment]

.What's next

After completing the applicable preparation tasks, link:install-hot-add-shelf.html[install a shelf for a hot-add].

