---
permalink: ns224/requirements-hot-add-shelf.html
sidebar: sidebar
keywords: ns224, shelves, shelf, ns224 shelves, hot-add, ha, pair, requirement
summary: To hot-add an NS224 drive shelf, your HA pair must meet certain requirements.
---
= Requirements and best practices to hot-add a shelf - NS224 shelves
:icons: font
:imagesdir: ../media/

[.lead]
Before hot-adding a shelf, be sure to review the requirements and best practices.

== Requirements
To hot-add an NS224 drive shelf, your HA pair must meet certain requirements.

* *Supported ONTAP version*: Your platform model and version of ONTAP must support the NS224 shelf and drives you are hot-adding. See https://hwu.netapp.com[NetApp Hardware Universe^]

* *Number of shelves*: Your HA pair must have less than the maximum number of shelves supported, by at least the number of shelves you plan to hot-add.
+
You cannot have exceeded the maximum number of shelves supported by your HA pair after hot-adding shelves. See https://hwu.netapp.com[NetApp Hardware Universe^].

* *Cabling*: Make sure you have the correct number and type of cables to connect the shelf. See https://hwu.netapp.com[NetApp Hardware Universe^].
+
** If you are hot-adding a shelf to an HA pair that already has an NS224 shelf, your HA pair cannot have any storage cabling error messages, and it must be cabled as multipath HA.
+
** You can run  https://mysupport.netapp.com/site/tools/tool-eula/activeiq-configadvisor[Active IQ Config Advisor^] to view any storage cabling error messages and the corrective actions you should take. 

* *RoCE-capable Ethernet ports*: Your HA pair must have enough available RoCE-capable Ethernet ports to support the number of shelves you are hot-adding. 
+
** For each shelf you are hot-adding, you need two RoCE-capable ports on each controller. These ports can be on board the controllers, on RoCE-capable PCIe cards, a combination of both, or on RoCE-capable I/O modules, as supported by your platform model.
+
** If your HA pair does not have enough available RoCE-capable ports, and your platform model supports the use of RoCE-capable PCIe cards or I/O modules, you must have installed the additional cards or I/O modules into the correct controller slots, as supported by your platform model.  
+
Make sure you identify the correct controller slots for your platform model. See https://hwu.netapp.com[NetApp Hardware Universe^]. See your platform model's documentation for PCIe card or I/O module installation instructions. See https://docs.netapp.com/us-en/ontap-systems/index.html[ONTAP Hardware Systems Documentation].
+
** Non-dedicated RoCE-capable ports must be configured for storage use (not networking use). See _Prepare non-dedicated RoCE-capable ports for a hot-add_.

* *AFF A700 HA pair*: If you have an AFF A700 HA pair and you are hot-adding the initial NS224 drive shelf (no NS224 drive shelf exists in your HA pair), you must have installed a core dump module (X9170A, NVMe 1TB SSD) in each controller to support core dumps (store core files). See link:../fas9000/caching-module-and-core-dump-module-replace.html[Replace the caching module or add/replace a core dump module -- AFF A700 and FAS9000^]

== Best practices
Familiarize yourself with the following best practices before hot-adding an NS224 drive shelf.

* If you have an ASA HA pair supporting NS224 shelves, you can use this procedure.

* *Best practice:* The best practice is to have the current version of the https://mysupport.netapp.com/site/downloads/firmware/disk-drive-firmware/download/DISKQUAL/ALL/qual_devices.zip[Disk Qualification Package^] installed before hot-adding a shelf.
+
Having the current version of the DQP installed allows your system to recognize and use newly qualified drives. This avoids system event messages about having noncurrent drive information and prevention of drive partitioning because drives are not recognized. The DQP also notifies you of noncurrent drive firmware.
+
//30 aug 2022, BURT 1491809: correct the DQP link

* *Best practice:* The best practice is to run https://mysupport.netapp.com/site/tools/tool-eula/activeiq-configadvisor[Active IQ Config Advisor^] before and after hot-adding a shelf.
+
Running Active IQ Config Advisor before hot-adding a shelf provides a snap shot of the existing shelf Ethernet (ENET) connectivity, verifies NVMe shelf module (NSM) firmware versions, and allows you to verify a shelf ID already in use in the HA pair. 
+
Running Active IQ Config Advisor after hot-adding a shelf allows you to verify shelves are cabled correctly and that shelf IDs are unique within the HA pair.
+

* *Best practice:* The best practice is to have current versions of https://mysupport.netapp.com/site/downloads/firmware/disk-shelf-firmware[NVMe shelf module (NSM) firmware^] and https://mysupport.netapp.com/site/downloads/firmware/disk-drive-firmware[drive firmware^] on your system before adding a new shelf.
+
NOTE: Do not revert firmware to a version that does not support your shelf and its components.
+
After you have cabled a hot-added shelf, ONTAP recognizes the shelf:

 ** Drive ownership is assigned if automatic drive assignment is enabled.
 ** NSM shelf firmware and drive firmware should be updated automatically, if needed.
+
NOTE: Firmware updates can take up to 30 minutes.