---
permalink: fas8300/bootmedia-replace-requirements.html
sidebar: sidebar
keywords: fas8300, fas8700, replace the boot media
summary: Before replacing the boot media in your FAS8300 or FAS8700 system, verify that you meet the necessary requirements for a successful replacement. This includes making sure you have a USB flash drive with the appropriate amount of storage and verifying that you have the correct replacement boot device.
---
= Review requirements for manual boot media recovery in your FAS8300 or FAS8700 system
:icons: font
:imagesdir: ../media/

[.lead]
Before replacing the boot media in your FAS8300 or FAS8700 system, verify that you meet the necessary requirements for a successful replacement. This includes verifying that you have the correct replacement boot media, confirming that the e0S (e0M wrench) port on the impaired controller is not faulty, and determining whether Onboard Key Manager (OKM) or External Key Manager (EKM) is enabled.

If your storage system is running ONTAP 9.17.1 or later, use the link:bootmedia-replace-workflow-bmr.html[automated boot recovery procedure]. If your system is running an earlier version of ONTAP, you must use the manual boot recovery procedure.

include::../_include/bootmedia_replace_requirements.adoc[]

.What's next?

After you've reviewed the requirements to replace the boot media, you need to link:bootmedia-encryption-preshutdown-checks.html[check encryption key support and status on the boot media].
