---
permalink: fas8300/bootmedia-shutdown.html
sidebar: sidebar
keywords: fas8300, fas8700, shut, down, take, over, impair, controller, procedure, storage, system, hardware, configuration, shut down the impaired controller
summary: You can shut down or take over the impaired controller using different procedures, depending on the storage system hardware configuration.
---
= Shut down the impaired controller - FAS8300 and FAS8700
:icons: font
:imagesdir: ../media/

[.lead]
After completing the NVE or NSE tasks, you need to complete the shutdown of the impaired controller.  Shut down or take over the impaired controller using the appropriate procedure for your configuration.

If your storage system is running ONTAP 9.17.1 or later, use the link:bootmedia-replace-workflow-bmr.html[automated boot recovery procedure]. If your system is running an earlier version of ONTAP, you must use the manual boot recovery procedure.

== Option 1: Most systems

include::../_include/shutdown_bootmedia.adoc[]

== Option 2: Controller is in a MetroCluster

After completing the NVE or NSE tasks, you need to complete the shutdown of the impaired controller.

include::../_include/shutdown_any_mcc_supported.adoc[]

== Option 3: Controller is in a two-node Metrocluster

After completing the NVE or NSE tasks, you need to complete the shutdown of the impaired controller.

include::../_include/shutdown_2n_mcc.adoc[]
