---
permalink: fas8300/chassis-replace-complete-system-restore-rma.html
sidebar: sidebar
keywords: fas8300, fas8700, shut, chassis, controller, replace, remove, swap, verify, install, power, supply, metrocluster, aggregates, replacement, process, equipment, rack, ha, state, system
summary: "You must verify the HA state of the chassis and return the failed part to NetApp, as described in the RMA instructions shipped with the kit."
---
= Complete the chassis replacement for your FAS8300 or FAS8700 system
:icons: font
:imagesdir: ../media/

[.lead]
You must verify the HA state of the chassis and return the failed part to NetApp, as described in the RMA instructions shipped with the kit.

== Step 1: Verify and set the HA state of the chassis

You must verify the HA state of the chassis, and, if necessary, update the state to match your system configuration.

.Steps
. In Maintenance mode, from either controller module, display the HA state of the local controller module and chassis: `ha-config show`
+
The HA state should be the same for all components.

. If the displayed system state for the chassis does not match your system configuration:
 .. Set the HA state for the chassis: `ha-config modify chassis _HA-state_`
+
The value for HA-state can be one of the following:

*** `ha`
*** `mcc`
*** `mcc-2n`
*** `mccip`
*** `non-ha`

 .. Confirm that the setting has changed: `ha-config show`
. If you have not already done so, recable the rest of your system.


== Step 2: Switch back aggregates in a two-node MetroCluster configuration

include::../_include/2n_mcc_switchback.adoc[]

== Step 3: Complete the replacement process

include::../_include/complete_rma.adoc[]
