---
permalink: fas8300/controller-replace-move-hardware.html
sidebar: sidebar
keywords: fas8300, fas8700, move the controller module hardware
summary: Replace the controller in your FAS8300 or FAS8700 system when a hardware failure requires it. The replacement process involves removing the impaired controller, moving the components to the replacement controller, installing the replacement controller, and rebooting it.
---
= Replace the controller - FAS8300 and FAS8700
:icons: font
:imagesdir: ../media/

[.lead]
Replace the controller in your FAS8300 or FAS8700 system after a hardware failure. Remove the failed controller. Move its components to the replacement. Install the new controller and reboot.

NOTE: The Ver2 controller module has only one caching module socket (Slot 6) in the FAS8300. FAS8700 does not have a VER2 controller module. The caching module functionality is not impacted by the socket removal.  

== Step 1: Remove the controller module

You must remove the controller module from the chassis when you replace the controller module or replace a component inside the controller module.

include::../_include/a400_controller_remove.adoc[]

== Step 2: Move the power supplies

Move the power supplies to the replacement controller module.

include::../_include/a400_controller_replace_move_psu.adoc[]

== Step 3: Move the NVDIMM battery

Move the NVDIMM battery to the replacement controller module.

include::../_include/a400_controller_replace_move_nvdimm_battery.adoc[]

== Step 4: Move the boot media

Move the boot media to the replacement controller module.

include::../_include/a400_controller_replace_move_bootmedia.adoc[]

== Step 5: Move the PCIe risers and mezzanine card

Move the PCIe risers and mezzanine card to the replacement controller module.

include::../_include/a400_controller_replace_move_pcie_risers.adoc[]

== Step 6: Move the cache module
Move the cache module to the replacement controller module.

include::../_include/fas8300_controller_replace_move_cache_module.adoc[]


== Step 7: Move the DIMMs

Move the DIMMs to the replacement controller module.

include::../_include/a400_controller_replace_move_dimms.adoc[]

== Step 8: Install the controller module

Reinstall the controller module and reboot it.

include::../_include/a400_controller_install_controller_replace.adoc[]

.What's next?
After you've replaced the impaired FAS8300 or FAS8700 controller, you need to link:controller-replace-system-config-restore-and-verify.html[restore the system configuration].