---
permalink: a700s/bootmedia-replace-overview.html
sidebar: sidebar
keywords: aff a700s, aff, a700s, primary, boot, media, store, ontap, image, system, restore, primary, media, secondary, usb, flash, drive, replace, replace the boot media, manual, manual boot recovery
summary: "Learn about boot media replacement on an AFF A700s system and understand the recovery methods. The AFF A700s system supports only manual boot media recovery procedures. Automated boot media recovery is not supported."
---
= Overview of boot media replacement - AFF A700s
:icons: font
:imagesdir: ../media/

[.lead]
Learn about boot media replacement on an AFF A700s system and understand the recovery methods. The primary boot media stores the ONTAP boot image that the system uses during startup. You can restore the primary boot media image using the ONTAP image from the secondary boot media or, if necessary, from a USB flash drive formatted to FAT32.

The AFF A700s system supports only manual boot media recovery procedures. Automated boot media recovery is not supported.

If your secondary boot media has failed or is missing the image.tgz file, you must restore the primary boot media using a USB flash drive. The drive must be formatted to FAT32 and must have the appropriate amount of storage to hold the image_xxx.tgz file.

* The replacement process restores the var file system from the secondary boot media or USB flash drive to the primary boot media.
* You must replace the failed component with a replacement FRU component you received from your provider.
* It is important that you apply the commands in these steps on the correct controller:
 ** The _impaired_ controller is the controller on which you are performing maintenance.
 ** The _healthy_ controller is the HA partner of the impaired controller.

If you need to replace the secondary boot media while the primary boot media is installed and healthy, contact NetApp Support and mention the https://kb.netapp.com/on-prem/ontap/OHW/OHW-KBs/How_to_replace_the_secondary_boot_device_of_an_a700s[How to replace the secondary boot device of an AFF A700s^] KB article.