---
permalink: a700s/chassis-replace-overview.html
sidebar: sidebar
keywords: aff a700s, replace the chassis
summary: "You replace an impaired chassis the new chassis of the same model as the impaired chassis."
---
= Review requirements before replacing an AFF A700s chassis
:icons: font
:imagesdir: ../media/

[.lead]
Before replacing the chassis in your AFF A700s system, review the requirements for a successful replacement. The chassis replacement procedure moves the controller modules and SSD drives from the impaired chassis to the replacement chassis and is disruptive.

All other components in the system must be functioning properly; if not, you must contact technical support.

* You can use this procedure with all versions of ONTAP supported by your system.
* This procedure is written with the assumption that you are moving the SSDs and controller modules to the new chassis, and that the replacement chassis is a new component from NetApp.
* This procedure is disruptive. For a two-node cluster, you will have a complete service outage and a partial outage in a multi-node cluster.
