---
permalink: a700s/maintain-overview.html
sidebar: sidebar
keywords: a700s maintenance, maintenance, repairing a700s, repairing a700s, replace a700s components, replace a700s components
summary: Maintain the AFF A700s hardware
---
= Learn about maintaining an AFF A700s storage system
:icons: font
:imagesdir: ../media/

[.lead]
For the AFF A700s storage system, you can perform maintenance procedures on the following components.

== Boot media

The boot media stores a primary and secondary set of boot image files that the system uses when it boots. 

== Chassis

The chassis is the physical enclosure housing all the controller components such as the controller/CPU unit, power supply, and I/O.

== Controller

A controller consists of a board, firmware, and software. It controls the drives and implements the ONTAP functions.

== DIMM

You must replace a DIMM (dual in-line memory module) when a memory mismatch is present, or you have a failed DIMM.

== Drive

A drive is a device that provides the physical storage media for data.

== Fan

The fan cools the controller.

== NVRAM battery

A battery is included with the controller and provides the backup power if the AC power fails.

== NVRAM module

The NVRAM module (non-volatile random-access memory) preserves cached data if the power fails.

== PCIe card

A PCIe (peripheral component interconnect express) card is an expansion card that plugs into the PCIe slot on the motherboard. 

== Power supply

A power supply provides a redundant power source in a controller shelf.

== Real-time clock battery

A real time clock battery preserves system date and time information if the power is off. 