---
sidebar: sidebar
permalink: asa-r2/install-setup-requirements.html
keywords: asa r2, install, setup, cautions
summary: Get started with install and setup of the ASA r2 storage system and deploy it as a node in your ONTAP environment.
---
= Requirements and lifting precautions for ASA r2
:icons: font
:imagesdir: ../media/

[.lead]
Get started with the install and setup workflow for the ASA r2 storage system and deploy it as a node in your ONTAP environment. 

== Equipement needed for install
Before installing your storage system, confirm you have all of the additional equipment and tools that you need.

** Phillips #2 screwdriver 
** Flashlight
** ESD strap 
** A paperclip or narrow tipped ball point pen for setting NS224 shelf IDs
** Laptop or console with a USB/serial connection
** Access to a Web browser to configure your storage system

== Lifting precautions 
You should be aware of the safety concerns associated with the weight of the platform and shelves.

=== ASA r2 systems
A fully loaded A1K platform can weigh up to 62.83 lbs (28.5 kg) and requires two people to lift or use a hydraulic lift.

image::../media/drw_a1k_weight_caution_ieops-1698.svg[AFF A1K lifting caution icon]

=== Shelves
You should be aware of the safety concerns associated with the weight of the shelf.

A fully loaded shelf can weigh up to 66.78 lbs (30.29 kg) and requires two people to lift or use a hydraulic lift. Avoid removing shelf components (from the front or rear of the shelf) to reduce the shelf weight, because shelf weight will become unbalanced.

image::../media/drw_ns224_lifting_weight_ieops-1716.svg[NS224 lifting caution]


