---
permalink: fas/specifications.html
sidebar: sidebar
keywords: FAS2820 specifications, FAS2820 specs, NetApp FAS2820, FAS2820 hardware
summary: Key specifications for the FAS2820 storage system
---
= Key specifications for FAS2820
:icons: font
:imagesdir: ../media/

[.lead]
The following are select specifications for the FAS2820. Visit https://hwu.netapp.com[NetApp Hardware Universe^] (HWU) for a complete list of FAS2820 specifications. This page is reflective of a single high availability pair. 

=== Key specifications for FAS2820

Platform Configuration: FAS2820 Single Chassis HA Pair

Max Raw Capacity: 3.1680 PB

Memory: 128.0000 GB

Form Factor: 2U chassis with 2 HA controllers and 12 drive slots

ONTAP Version: b_startONTAP: 9.16.1P2b_end

PCIe Expansion Slots: 4

Minimum ONTAP Version: ONTAP 9.13.1RC1

=== Scaleout Maximums
|===
| Type | HA Pairs | Raw Capacity | Max Memory
| NAS | 12 | 38.0 PB / 33.8 PiB | 1536 GB
| SAN | 6 | 19.0 PB / 16.9 PiB | 768 GB
| HA Pair |  | 3.2 PB / 2.8 PiB | 128.0000
|===

=== IO

==== Onboard IO
|===
| Protocol | Ports
| Ethernet 25 Gbps | 4
| SAS 12 Gbps | 4
|===

==== Total IO
|===
| Protocol | Ports
| Ethernet 25 Gbps | 12
| Ethernet 10 Gbps | 8
| FC 32 Gbps | 8
| NVMe/FC  32 Gbps | 8
|  | 0
| SAS 12 Gbps | 4
|===

==== Management Ports
|===
| Protocol | Ports
| Ethernet 1 Gbps | 2
| RS-232 115 Kbps | 4
| USB 600 Mbps | 2
|===

=== Storage Networking Supported
CIFS;
FC;
FCoE;
iSCSI;
NFS v3;
NFS v4.0;
NFS v4.1;
NVMe/TCP;
S3;
S3 with NAS;
SMB 2.0;
SMB 2.1;
SMB 2.x;
SMB 3.0;
SMB 3.1;
SMB 3.1.1;

=== System Environment Specifications
* Typical Power: 1815 BTU/hr
* Worst-case Power: 2339 BTU/hr
* Weight: 57.2 lb<br/>25.9 kg
* Height: 2U
* Width: 19” IEC rack-compliant (17.6” 44.7 cm)
* Depth: 20.0”<br/>(25.1” with cable management bracket)
* Operating Temp/Altitude/Humidity: 10°C to 35°C<br/>50°F to <br/>95°F) at<br/><= 3048m<br/><= 10000 ft) elevation;8% to 80%<br/>relative humidity, noncondensing
* Non-operating Temp/Humidity: -40°C to 70°C (-40°F to 158°F) upto 12192m (40000 ft)<br/>10% to 95%  relative humidity, noncondensing, in original container
* Acoustic Noise: Declared sound power (LwAd): 7.8;<br/>Sound pressure (LpAm) (bystander positions): 68.4 dB

=== Compliance
* Certifications EMC/EMI: AMCA,
FCC,
ICES,
KC,
Morocco,
VCCI
* Certifications safety: BIS,
CB,
CSA,
G_K_U-SoR,
IRAM,
NOM,
NRCS,
SONCAP,
TBS
* Certifications Safety/EMC/EMI: EAC,
UKRSEPRO
* Certifications Safety/EMC/EMI/RoHS: BSMI,
CE DoC,
UKCA DoC
* Standards EMC/EMI: BS-EN-55024,
BS-EN55035,
CISPR 32,
EN55022,
EN55024,
EN55032,
EN55035,
EN61000-3-2,
EN61000-3-3,
FCC Part 15 Class A,
ICES-003,
KS C 9832,
KS C 9835
* Standards Safety: ANSI/UL60950-1,
ANSI/UL62368-1,
BS-EN62368-1,
CAN/CSA C22.2 No. 60950-1,
CAN/CSA C22.2 No. 62368-1,
CNS 14336,
EN60825-1,
EN62368-1,
IEC 62368-1,
IEC60950-1,
IS 13252(part 1)

=== High Availability
Ethernet based baseboard management controller (BMC) and ONTAP management interface;
Redundant hot-swappable controllers;
Redundant hot-swappable power supplies;
SAS in-band management over SAS connections for external shelves;
